### ISSUE TITLE
Should EF Core Store hit database with every request?

### ISSUE THREAD

**Issue by ericsports** [Finbuckle/Finbuckle.MultiTenant#118]
I understand why the database would be hit every request initially, but am I missing an option where the store is cached somewhere perhaps so that it's not hitting the database with every http request?

**Comment by AndrewTriesToCode** [comment]
Hi @ericsports 
You aren't missing anything. The EFCore Store is pretty basic--but in practice I haven't seen a performance problem. I usually use it with Sql Azure which does some caching at the db level. A store using Redis or something could easily be created by implementing IMultiTenantStore but I there is nothing like that in the repo.
