### ISSUE TITLE
Docs issues

### ISSUE THREAD

**Issue by ghost** [Finbuckle/Finbuckle.MultiTenant#120]
The link to https://www.finbuckle.com/MultiTenant/Docs/EFCore#configuring-with-asp.net-core on the left-side nav doesn't work because jQuery sees the period as a class name identifier so it's looking for` id="configuring-with-asp" class="net-core"`. 
  
The _Data Isolation with Entity Framework Core_ and _Data Isolation with ASP.NET Core Identity_ sections refer to `TenantContext` as a context constructor parameter but the context constructors expect `TenantInfo` now.

**Comment by AndrewTriesToCode** [comment]
@webwizgordon 
Thanks I just updated the website. No code changes in this repo--the site is a separate repo.

**Comment by ghost** [comment]
No problem. Is there a better spot to report issues with the site? I saw the docs folder here and it seems to match the site so I figured they came from here.

BTW It looks like the data isolation pages are still out of date with `TenantContext`.

**Comment by AndrewTriesToCode** [comment]
This is the best place to report docs issues-- the content is actually the markdown files in this repo and can be updated via PR, but the actual website is separate-- it dynamically generates the  document navigation based on the markdown in this repo.
