### ISSUE TITLE
Accessing entities from other tenants

### ISSUE THREAD

**Issue by ericsports** [Finbuckle/Finbuckle.MultiTenant#130]
I have a need where I want to be able to access entities (including users, roles) from another tenant, that is one that is being set up to administer users and other items for other tenants.  I very well could be doing this in the wrong approach, but was just wondering if there were a way for this sort of functionality?

Any help is much appreciated!

**Comment by AndrewTriesToCode** [comment]
Hi @ericsports 

Are you using normal LINQ queries to try to access the entities that belong to other tenants?

If so this should be easy. Internally Finbuckle.MultiTenant sets a global query filter. This can easily be bypassed for a query as shown in this link:
https://docs.microsoft.com/en-us/ef/core/querying/filters#disabling-filters

Let me know how it goes.

**Comment by ericsports** [comment]
That does the trick, thanks!
