### ISSUE TITLE
Questions about basic setup

### ISSUE THREAD

**Issue by pkavan** [Finbuckle/Finbuckle.MultiTenant#132]
Thanks for creating this. For an earlier project I did on NET Core 1.x I used SaaSKit, but it doesn't seem to work for 2.x and I don't have the time to figure out why. 

I used your samples to get the basics up on the new 2.x project I am starting. I can replicate the basic stuff in my new project -- getting the TenantInfo in a controller function and passing it to a page. works well.

However, I was wondering if you had a more extensive sample showing how to inject a tenant into, for example, a _Layout page so I can style it per tenant. Or how to pass it into a controller at creation. 

I'll admit middleware is a little bit of a weak spot for me, but I am willing to dig into it with some help. I have a feeling this is a where I am not seeing the next steps.

Again thanks. I love how clean this implementation is.

**Comment by AndrewTriesToCode** [comment]
Hi @pkavan Thanks for the kind words and I'm glad you have found the library helpful. SaasKit is nice, but the ASP.NET Core 2 release really changed how things work and SaasKit hasn't been updated yet.

Your layout per tenant question is interesting-- I've tried to keep per-tenant logic in the Options patterns, but from what I can tell layout and view customization is a good example of where you have to build the logic right into the page itself.

I haven't tested this (I will soon, maybe find a better way), but I think if you put a layout name in your tenant configuration so that `TenantInfo.Items["myLayout"]` return is you can use the view imports page to select a different layout:

```
@{
    // Something like this but maybe more robust to handle a KeyNotFoundExecption
    Layout = Context.GetMultiTenantContext()?.TenantInfo.Items["myLayout"] ?? "_defaultLayout";
}
```

**Comment by AndrewTriesToCode** [comment]
On rereading your question, I'll add that in any view you can access the `TenantInfo` via the HttpContext (available to views as "Context"): 
```Context.GetMultiTenantContext().TenantInfo```.

Also you can inject `MultiTenantContextAccessor` to get the MultiTenantContext (similar to `HttpContextAccessor`):
```
// In view or controller assume MultiTenantContextAccessor is
// injected as "_multiTenantContextAccessor"
var tenantInfo = _multiTenantContextAccessor.MultiTenantContext?.TenantInfo;
```

If you run into any problems please let me know.

**Comment by pkavan** [comment]
Thanks for the prompt reply. I will give that a shot. Your  second response was really what I was getting after -- so thanks for re-reading :)

I asked about the _Layout Page specifically because I use a bootstrap nav with a couple of tenant specific settings and wanted to make sure I could do something similar to what I was doing with SaaSKit, which was....essentially

`@inject tenant`

...where tenant would be an instantiation of my 'tenant' class for the current tenant. 

If all that makes sense.

**Comment by pkavan** [comment]
@achandlerwhite I had a chance to look at my new project again. Thanks for the advice. That did the trick. I am now trying to figure out how to get my ApplicationDbContext to switch to the appropriate connection string.

**Comment by AndrewTriesToCode** [comment]
Hi @pkavan,

If you are using DI to get a DbContext derived from `MultiTenantDbContext` then it will use DI to get the current TenantInfo and automatically use the `ConnectionString` property set for that tenant.

Take a look at the [Data Isolation Sample](https://github.com/Finbuckle/Finbuckle.MultiTenant/tree/master/samples/DataIsolationSample). In that sample there are 3 tenants configured. Two share a connection string and one has it's own connection string.

**Comment by pkavan** [comment]
@achandlerwhite Thanks. I looked at that. I can't seem to get how to set up my `AppDbContext` with the `TenantInfo` though. My setup looks like

```
        public void ConfigureServices(IServiceCollection services)
        {
            //Add Context Accessor
            services.AddHttpContextAccessor();

            // Add multitenancy
            services.AddMultiTenant()
                .WithInMemoryStore(Configuration.GetSection("BorrowerBase:MultiTenant:InMemoryStore"))
                .WithHostStrategy();

            services.AddDbContext<ApplicationDbContext>(options =>
                options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));

            services.AddIdentity<ApplicationUser, IdentityRole>(options =>
            {
                //Password Options
                options.Password.RequiredLength = 6;
                options.Password.RequireNonAlphanumeric = false;
                options.Password.RequireLowercase = false;
                options.Password.RequireUppercase = false;
                options.Password.RequireDigit = false;

                // Lockout Options
                options.Lockout.DefaultLockoutTimeSpan = TimeSpan.FromMinutes(3);
                options.Lockout.MaxFailedAccessAttempts = 7;
                options.Lockout.AllowedForNewUsers = true;
            })
                            .AddEntityFrameworkStores<ApplicationDbContext>()
                            .AddDefaultTokenProviders();

            // Add application services.
            services.AddTransient<IEmailSender, EmailSender>();
            services.AddMvc();


        }
```

Like I said, this part of the setup is my weakest area. I figured out how to change the connection string inside of a controller if I needed, but I have to have it setup earlier because my database has all the Identity stuff in there too and the first page I hit is the login page and I need the _signinManager there. 

I'lll keep playing around. Thanks for all your help

**Comment by AndrewTriesToCode** [comment]
Can you post the definition of your `ApplicationDbContext` class? If it derives from `MultiTenantDbContext` it will get the connection string from the tenant.

Also you should not specify the connection string in the startup because it will depend on the tenant during runtime. If you derive from `MultiTenantDbContext` as shown below then you can use the current tenant connection string in the context's `OnConfiguring` method. `OnConfiguring` is called at least once per request, so it will make sure the connection string for the *current* tenant is used.
```
// don't set option here
services.AddDbContext<ApplicationDbContext>(options =>
  options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));

// Instead derive from MultiTenantDbContext and override the OnConfiguring as shown here:
public class ApplicationDbContext : MultiTenantDbContext
{
        public ApplicationDbContext(TenantInfo tenantInfo) : base(tenantInfo)
        {
        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            // ConnectionString below will already be set to equal the tenant's connection string.
            optionsBuilder.UseSqlite(ConnectionString); // or UseSqlServer... or any other Use...
            base.OnConfiguring(optionsBuilder);
        }
...
}
```

**Comment by pkavan** [comment]
Thanks.

I modified configure services so its.

```
public void ConfigureServices(IServiceCollection services)
{
	//Add Context Accessor
	services.AddHttpContextAccessor();

	// Add multitenancy
	services.AddMultiTenant()
		.WithInMemoryStore(Configuration.GetSection("BorrowerBase:MultiTenant:InMemoryStore"))
		.WithHostStrategy();

	services.AddDbContext<ApplicationDbContext>();

	services.AddIdentity<ApplicationUser, IdentityRole>(options =>
	{
		//Password Options
		options.Password.RequiredLength = 6;
		options.Password.RequireNonAlphanumeric = false;
		options.Password.RequireLowercase = false;
		options.Password.RequireUppercase = false;
		options.Password.RequireDigit = false;

		// Lockout Options
		options.Lockout.DefaultLockoutTimeSpan = TimeSpan.FromMinutes(3);
		options.Lockout.MaxFailedAccessAttempts = 7;
		options.Lockout.AllowedForNewUsers = true;
	})
					.AddEntityFrameworkStores<ApplicationDbContext>()
					.AddDefaultTokenProviders();

	// Add application services.
	services.AddTransient<IEmailSender, EmailSender>();
	services.AddMvc();
}
```

My `ApplicationDbContext ` is


```
    public class ApplicationDbContext : IdentityDbContext<ApplicationUser>
    {
        public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options)
            : base(options)
        {
        }

        public DbSet<Certificate> Certificates { get; set; }
        public DbSet<LoanProduct> LoanProducts { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseInMemoryDatabase("EFCoreStoreSampleDb");
            base.OnConfiguring(optionsBuilder);
        }



        protected override void OnModelCreating(ModelBuilder builder)
        {
            base.OnModelCreating(builder);
            // Customize the ASP.NET Identity model and override the defaults if needed.
            // For example, you can rename the ASP.NET Identity table names and more.
            // Add your customizations after calling base.OnModelCreating(builder);
        }
    }

```

So, the problem I have here is that I can't change my context that way, because I use it for my Identity stuff. Does that make sense?

**Comment by AndrewTriesToCode** [comment]
@pkavan 

I can see 2 options:

1) Change `ApplicationDbContext` to inherit from `MultiTenantIdentityDbContext` (which itself derives from `IdentityDbContext`, but adds multitenant support such as the `ConnectionString` for the current tenant I talked about).

2) Use DI to inject `TenantInfo` into your db context (just add it as a constructor parameters and ASP.NET 
 Core should inject it). From that you can use the `TenantInfo.ConnectionString` property in your `OnConfiguring`. This might be better if you don't need the more advanced features `MultiTenantIdentityDbContext` provides such as multiple tenants sharing a database.

**Comment by pkavan** [comment]
@achandlerwhite I tried scheme two and determined that order in Startup.c matters. I had this:

```
        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            ...

            app.UseStaticFiles();

            app.UseAuthentication();

  -->     app.UseMultiTenant();

            app.UseMvc(routes =>
            {
                routes.MapRoute(
                    name: "default",
                    template: "{controller=Home}/{action=Index}/{id?}");
            });
        }
```
The app would start okay and pass tenant info into my dB context. However, once I signed in, it would hit it a few more times. The first pass after login would have tenant info, but the second would be null. 

After looking at it, I did this:

```
        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            ...

  -->     app.UseMultiTenant();

            app.UseStaticFiles();

            app.UseAuthentication();

            app.UseMvc(routes =>
            {
                routes.MapRoute(
                    name: "default",
                    template: "{controller=Home}/{action=Index}/{id?}");
            });
        }
```

...moving UseMultiTenant() to the top of the stack. 


This did the trick. 

Thanks,

**Comment by AndrewTriesToCode** [comment]
Yep, it definitely needs to be before `UseAuthentication`. I think its stated in the docs but I will check. You might still want `UseStaticFiles` before multi tenant though so that things like css and image files come through without any potential interference.

**Comment by balindersingh** [comment]
> @achandlerwhite I tried scheme two and determined that order in Startup.c matters. I had this:
> 
> ```
>         public void Configure(IApplicationBuilder app, IHostingEnvironment env)
>         {
>             ...
> 
>             app.UseStaticFiles();
> 
>             app.UseAuthentication();
> 
>   -->     app.UseMultiTenant();
> 
>             app.UseMvc(routes =>
>             {
>                 routes.MapRoute(
>                     name: "default",
>                     template: "{controller=Home}/{action=Index}/{id?}");
>             });
>         }
> ```
> 
> The app would start okay and pass tenant info into my dB context. However, once I signed in, it would hit it a few more times. The first pass after login would have tenant info, but the second would be null.
> 
> After looking at it, I did this:
> 
> ```
>         public void Configure(IApplicationBuilder app, IHostingEnvironment env)
>         {
>             ...
> 
>   -->     app.UseMultiTenant();
> 
>             app.UseStaticFiles();
> 
>             app.UseAuthentication();
> 
>             app.UseMvc(routes =>
>             {
>                 routes.MapRoute(
>                     name: "default",
>                     template: "{controller=Home}/{action=Index}/{id?}");
>             });
>         }
> ```
> 
> ...moving UseMultiTenant() to the top of the stack.
> 
> This did the trick.
> 
> Thanks,

I am trying the same thing to  DI to inject TenantInfo but not sure  how to add it in OnConfiguring

**Comment by AndrewTriesToCode** [comment]
@balindersingh can you open a new issue and post some details about what you are trying to do and what the problem appears to be?
