### ISSUE TITLE
Azure Webjobs

### ISSUE THREAD

**Issue by alexmaie** [Finbuckle/Finbuckle.MultiTenant#138]
Hey, 

Can we use this library outside of asp core? As an example,we could put a message on a queue and have an  azure webjob process the message. The message has a tenant id and the webjob would save the changes to the appropriate database

Thanks
Alex

**Comment by AndrewTriesToCode** [comment]
Hi @alexmaie 
Yes, you can just reference the Finbuckle.MultiTenant.EntityFrameworkCore Nuget package then when you spin up a dbcontext that derives from `MultiTenantDbContext` make sure to provide the constructor a TenantInfo object. In ASP.NET Core DI handles this for you, but it can be done manually too.

**Comment by alexmaie** [comment]
Hey, thanks for the quick reply.

I assume that I could also use the other base project (not asp core) since
I can't use ef core.

**Comment by AndrewTriesToCode** [comment]
Hi @alexmaie 
Sure, the Finbuckle.MultiTenant.Core package contains things like the basic strategy, stores, and interfaces. I'm not sure how useful it will be without ASP.NET Core in the picture.
