### ISSUE TITLE
Per-tenant options not set for a class

### ISSUE THREAD

**Issue by vlatkozmejkoski** [Finbuckle/Finbuckle.MultiTenant#139]
Hello,

I've been implementing a custom MultiTenantStore, since i am using a nosql database to store tenants. Now that part works as it seems, since i get the TenantInfo when i get the MultiTenantContext. Now the part where i setup per-tenant options for a class, , called TenantOptions, and has one property "ConnectionString", which i use to inject into my MongoContext to connect to the tenant-specific database, is not working apparently.
What i am doing is: 
`services.AddMultiTenant() //strategy ... //store .. //.WithPerTenantOptions<TenantOptions>((to, ti) => {to.ConnectionString = ti.ConnectionString})`

Apparently whenever the TenantOptions instance is called by the MongoContext, the ConnectionString is `null`. 
I'm not sure if i am using the `WithPerTenantOptions<TOptions>()` method correctly.
Please do point me what i am doing wrong. Many thanks!

**Comment by AndrewTriesToCode** [comment]
Hi @vlatkozmejkoski Can you post a sample of what your `TenantOptions` class looks like? Also is `TenantOptions` registered for DI as a singleton, scoped, or transient?

In theory, in your mongo db setup area you will inject `IOptions<TenantOptions>`, `IOptionsSnaption<TenantOptions>`, or `IOptionsMonitor<TenantOptions>` from which you get the `TenantOptions` instance and it should pick up the tenant info.

If you are only using `TenantOptions` to get the connection string you can skip a lot of this... just inject `TenantInfo` into your mongo db setup area and use the connection string on `TenantInfo` directly.

**Comment by vlatkozmejkoski** [comment]
Hi @achandlerwhite. Thank you for the reply.
After i posted this i followed microsoft docs on options pattern and end up doing what you suggested.
But your other suggestion seems to be much better, injecting TenantInfo into mongo setup.

Thank you a lot.

**Comment by vlatkozmejkoski** [comment]
Hi @achandlerwhite again. I've encountered another problem regarding WithPerTenantOptions.
I am implementing tenant-specific authorization policies, where i am using WithPerTenantOptions<TenantRequirement>() and set the class' property to the current tenant id. 
I'm using this TenantRequirement instance inside ConfigureServices, so i'm trying to get the TenantRequirement instance from the serviceProvider.GetService<T>().
Now this instance is used inside an AuthorizationHandler implementation, where i can make use of the instance's property, but the instance does not contain the TenantId set from WithPerTenantOptions, rather it is a Guid.Empty.
I am getting the instance from the serviceProvider as:
`serviceProvider.GetService<IOptions<TenantClaimRequirement>>().Value`
I am not sure if whether this is a problem with WithPerTenantOptions, or I'm getting the instance from the container in the wrong way.

**Comment by AndrewTriesToCode** [comment]
@vlatkozmejkoski 

Hi, I saw your update here  but also that you reclosed it. In theory it should work just fine, but I have seen a few places where this library didn't interact perfectly with ASP.NET Core... so let me know if I should continue to look into it.

Thanks!

**Comment by vlatkozmejkoski** [comment]
Well basically, to fix this, I again, directly injected `TenantInfo` into the `CustomAuthorizationHandler`, because I couldn't find a way where the TenantClaimRequirement class would be instantiated per-tenant. Now the requirement class is kinda useless in the handler, but oh well :)

**Comment by AndrewTriesToCode** [comment]
Thanks for letting me know. I will take a look at how the library interacts with authorization policies and related requirements.
