### ISSUE TITLE
Finbuckle.MultiTenant going forward

### ISSUE THREAD

**Issue by AndrewTriesToCode** [Finbuckle/Finbuckle.MultiTenant#148]
Hello!

With the recent release of Finbuckle.MultiTenant 3.1.0 I am going to start shifting toward ASP.NET Core 3.0  support.  This means:

- Finbuckle.MultiTenant 4.0.0 + will require ASP.NET Core 3 (eventually 3.1 since it is an LTS release)
- Any future fixes for ASP.Net Core 2.1 will remain in the Finbuckle 3.1.x versions for Finbuckle.

I hope to take advantage of this to make a few improvements:
- Restructure to remove dependency on EF Core if you don't want it
- Support more general "host" structure for .NET Core, so that it isn't just for web applications
- Use the new routing in ASP.NET Core 3 to improve RouteStrategy 

Also in thinking ahead I am considering a managed / premium version of Finbuckle.MultiTenant with a SAAS tenant manager/store and official support. Please let me know if this would be of interest to you. (My email is in my profile).

Finally, I'm very interested in hearing about how you are using the library. Would you be OK if I listed your company/project on the website?

Thanks!
Andrew

**Comment by WalternativE** [comment]
Hi Andrew!

First of all I want to thank you for your great work ❤ I really like your unintrusive and effective approach. Having your library as normal ASP.NET Core middleware makes it really easy to use without me having to structure my whole app around a third party dependency. It makes me quite independent as well - I wrote a F# vanilla ASP.NET Core 2.2 app prototype with it and it worked out of the box. As far as I can see it should also easily work with Giraffe and Saturn as both frameworks sit on top of ASP.NET Core. It also proved to be very extensible (my multi tenant store is implemented using AzureStorage tables while the in-memory testing setup uses a trivial throwaway implementation).

Cool to see you working on a ASP.NET Core 3.0 version. Really looking forward to taking advantage of the new Endpoint system (for a dozen reasons).

If you want to have more info on how we use Finbuckle just write me an email at gregor.beyerle@innerspace.eu 😊

Kind regards
Gregor

**Comment by juicycleff** [comment]
Hi, I had to leave the ABP framework for this because it gives me more structure, Albeit, could this Library work easily with MongoDB, I've lost touch with DN CORE and only just decided to use it again and I'm loving it, but an example of a non entity framework orm will be nice. Again awesome work

**Comment by AndrewTriesToCode** [comment]
Hi all. Just to follow up I recently released Finbuckle.MultiTenant 4.0.0 which supports .NET Core 3 and well as 2.2 and 2.1 i.e. all Microsoft supported versions. I found that multitargetting worked well so 2.2 and 2.1 apps using the library will also benefit from future enhancements.

Thanks!
Andrew

**Comment by AndrewTriesToCode** [comment]
@juicycleff   Hi I'm sorry I never responded to you. I don't have much MongoDB experience myself, but I'll look into this.
