### ISSUE TITLE
IdentityServer4 support

### ISSUE THREAD

**Issue by AndrewTriesToCode** [Finbuckle/Finbuckle.MultiTenant#155]
This has been requested many times and I plan to tackle it soon. I will need to support the config and operational stores used by IdentityServer4 and also the Identity variants that it uses for ASP.NET Core Identity.

**Comment by sberube** [comment]
Hi @AndrewTriesToCode, do you have some kind of plan? Maybe I can give you a hand with this! Thanks!

**Comment by AndrewTriesToCode** [comment]
hi @sberube Sorry I haven't responded yet -- I will write out some thoughts here later today. One thing to start with is to Identity all the different multitenant use cases with IS4. Some are obvious, but I suspect there are several less obvious ones.

**Comment by natelaff** [comment]
I think this will come in the form of different IEndpointRouter implementations. I use IdentityServer4 with this method using tenant name in the base path. There are some other minor changes, but it would seem that from a Finbuckle perspective, having a Finbuckle.MultiTenant.IdentityServer package that basically has different IEndpointRouters (base path, host).

I ran into complications with IS4 and multitenancy using the recommended approach or acr_values. I use ASP.NET Core Identity there with EF Core. Using acr_values was fine, up until the /authorize endpoint was hit, at which point there was no context any longer and I didn't know which database to connect to, so I really had to keep the tenant name in the address so I always had access to it.

Happy to try and help on this, but curious to hear what your thoughts on this are first :)

**Comment by AndrewTriesToCode** [comment]
Covered in other discussion.
