### ISSUE TITLE
MultiTenantOptionsCache is internal type

### ISSUE THREAD

**Issue by chernihiv** [Finbuckle/Finbuckle.MultiTenant#156]
[Options Caching](https://github.com/Finbuckle/Finbuckle.MultiTenant/blob/fbcbde19b7e2029236f9fb16ab8c254dd9b791df/docs/Options.md#options-caching) section describes how casting to `MultiTenantOptionsManager<TOptions>` exposes new methods to reset cache, however, `MultiTenantOptionsManager<TOptions>` is internal and not accessible.

> In some situations cached options may need to be cleared so that the options can be regenerated.
> When using per-tenant options via IOptions<TOptions> and IOptionsSnapshot<TOptions> the injected instance is of type MultiTenantOptionsManager<TOptions>. Casting to this type exposes the Reset() method which clears any internal caching for the current tenant and cause the options to be regenerated when next accessed via Value or Get(string name).
> When using per-tenant options with IOptionsMonitor<TOptions> each injected instance uses a shared persistent cache. This cache can be retrieved by injecting or resolving an instance of IOptionsMonitorCache<TOptions> which has a Clear() method that will clear the cache for the current tenant. Casting the IOptionsMonitorCache<TOptions> instance to MultiTenantOptionsCache<TOptions> exposes the Clear(string tenantId) and ClearAll() methods. Clear(string tenantId) clears cached options for a specific tenant (or the regular non per-tenant options if the parameter is empty or null). ClearAll() clears all cached options (including regular non per-tenant options).

[MultiTenantOptionsCache.cs](https://github.com/Finbuckle/Finbuckle.MultiTenant/blob/master/src/Finbuckle.MultiTenant.AspNetCore/Internal/MultiTenantOptionsCache.cs)

**Comment by AndrewTriesToCode** [comment]
@chernihiv Thanks for pointing this out. I will submit a PR later today to fix this. It passed all my unit tests... but didn't catch this!

**Comment by chernihiv** [comment]
Yeah, I saw tests 😃.
Let me know if I could help you with PR.

**Comment by AndrewTriesToCode** [comment]
@chernihiv I just merged the PR in. Feel free to submit any fixes for problem you find.
