### ISSUE TITLE
Finbuckle.MultiTenant doesn't work well with Authorize attribute

### ISSUE THREAD

**Issue by izundo-viennv** [Finbuckle/Finbuckle.MultiTenant#160]
Any way to process authorization for HomeController in SharedLogin project. Because for my purpose I want to protect HomeController for each tenant, but not root site.

**Comment by AndrewTriesToCode** [comment]
hi @izundo-viennv 

Can you give me a little more info on where you are with this and maybe post your `ConfigureServices` and `Configure` methods?

Usually for me the root site is an action on HomeController, but in theory there shouldn't be any problem if you have a different root site.

**Comment by AndrewTriesToCode** [comment]
hi @izundo-viennv 

I just wanted to follow up here. Did you ever find a way to make this work?
