### ISSUE TITLE
Duplicate call of GetIdentifierAsync in Strategy Wrapper

### ISSUE THREAD

**Issue by danjus10** [Finbuckle/Finbuckle.MultiTenant#163]
![image](https://user-images.githubusercontent.com/37114016/62783409-466dee80-bab4-11e9-8ce9-379c5691747f.png)

Remove line 57.  identifier is already set .

**Comment by danjus10** [comment]
I tried to push a PR to fix but not sure why its blocked.  anyways - Thanks for the awesome lib.  v nice !

**Comment by AndrewTriesToCode** [comment]
hi @danjus10 I'm not sure why it wouldn't allow you to submit a PR-- I need to check on that.

Good catch on this bug!

**Comment by danjus10** [comment]
Thanks for the quick response 👍   

Where is the best place to ask question about the libraries?  I'm trying to decide if it supports multiple tenant strategies.  e.g WithDelegateStrategy fallsback to WithRouteStrategy if no tenant, found is that possible?

**Comment by AndrewTriesToCode** [comment]
This issues area is the best place for these questions. I'm planning on that feature in the next release, but currently only a single strategy is used (except if you use fallback too).

**Comment by danjus10** [comment]
> This issues area is the best place for these questions. I'm planning on that feature in the next release, but currently only a single strategy is used (except if you use fallback too).

Ok cool. I'll keep an eye out.

**Comment by AndrewTriesToCode** [comment]
Hi @danjus10 can you please try to submit a PR for this and let me know? I just released a new version but I didn't include this bug fix yet. Thanks!

**Comment by danjus10** [comment]
No dice.   i'm logged in for sure.   Maybe check  the repo permissions. ?

[cid:f4fb5968-fd2d-4f3f-bf79-77cec36bc0fd]
________________________________

**Comment by AndrewTriesToCode** [comment]
Hm, that's not good. I don't currently see that you have a fork of the project-- you had one when you tried to submit though right? I checked the settings but didn't see anything obvious. My understanding is that anyone with read access to a public repo can submit a PR from their own fork.

Just to narrow things down, can you tell me at which step in the[ github docs for submitting a pull request](https://help.github.com/en/articles/creating-a-pull-request-from-a-fork) that you can't get any further?

**Comment by danjus10** [comment]
Oh I see!   I was trying to do a branch & PR directly in your repo rather than a fork etc

Thanks for your patience [new to github contribution] ✌

Dan
________________________________

**Comment by AndrewTriesToCode** [comment]
Excellent. No worries it is confusing--I totally messed up someone else's PR earlier today.
