### ISSUE TITLE
Finbuckle with Blazor  ServerSide Support 

### ISSUE THREAD

**Issue by Sheko007** [Finbuckle/Finbuckle.MultiTenant#169]

**Comment by AndrewTriesToCode** [comment]
I'll look into this--I've been meaning to learn more about Blazer Serverside.

**Comment by unencode** [comment]
@Sheko007 - Take a look at [Blazor and Razor Pages Support #188](https://github.com/Finbuckle/Finbuckle.MultiTenant/issues/188) for a working example.

Good luck!

**Comment by Sheko007** [comment]
Thanks Very much

**Comment by davidcateduclarity** [comment]
Hi there... Is there an updated example for a Blazor App??  Im able to do the Static strategy... But Im stuck altering any other strategy, most likely due to the routing.
Any guidance is greatly appreciated.

**Comment by AndrewTriesToCode** [comment]
hi @davidcateduclarity 

Not at the moment. When you are doing Blazor-routing (and not regular ASP.NET routing) does the tenant change between routes? I'm trying to better understand Blazor use cases.

Thanks!
