### ISSUE TITLE
Unable to retain TenantInfo 

### ISSUE THREAD

**Issue by stardocs-digital** [Finbuckle/Finbuckle.MultiTenant#172]
Hello,

Thank you so much for creating this! I'm trying to implement it now and so far saving my tenantinfo has been so simple!. 

However, I'm encountering an issue where I can't seem to retain my tenantinfo in the httpcontext? 
I can set it in the controller but when it comes to the view, tenantinfo is null.

I posted a question here and was wondering if im doing something wrong?

https://stackoverflow.com/questions/57966709/net-core-multi-tenant-localhost-is-null-after-setting

**Comment by AndrewTriesToCode** [comment]
Hi, I just responded to the question over on StackOverflow. Your approach to using the library was a little different than how I designed it--it should be more work in the middleware and less setting the tenant yourself. Take a look and let me know if you have any questions.

**Comment by stardocs-digital** [comment]
Thank you! I just had one followup question.
