### ISSUE TITLE
Blazor and  Razor Pages Support

### ISSUE THREAD

**Issue by unencode** [Finbuckle/Finbuckle.MultiTenant#188]
Just wanted to contribute my experience getting Funbuckle.MultiTenant to work with Blazor and Razor Pages on .NET Core 3.0. So far it seems to be working. Perhaps these instructions will help others.

In this example, we're using EFCore for storing the tenants database and a single shared database for tenants' data. You can also change the tenant-specific connection string to put one or more tenants into their own databases.

It's straight forward:

1. Create a Blazor server-side app as you normally would. In Startup.ConfigureServices, add services as follows (using your strategy and store options) and make sure to add services.AddHttpContextAccessor().

```

public void ConfigureServices(IServiceCollection services)
        {
            services.AddSingleton<IConfiguration>(Configuration);

            //Tenants Store
            services.AddDbContext<TenantDbContext>(options =>
                options.UseSqlServer(Configuration.GetConnectionString("TenantDbConnection")));

            //Per-Tenant Data Store (Identity is added below)
            services.AddDbContext<ApplicationDbContext>();

            services.AddIdentity<MultiTenantIdentityUser, MultiTenantIdentityRole>()
                .AddEntityFrameworkStores<ApplicationDbContext>()
                .AddDefaultTokenProviders();

            services.AddMultiTenant()
               .WithHostStrategy("__tenant__.*") //https://www.finbuckle.com/MultiTenant/Docs/Strategies#static-strategy
                .WithEFCoreStore<TenantDbContext, AppTenantInfo>();

            services.AddRazorPages();
            services.AddServerSideBlazor();
            
            //Allows accessing HttpContext in Blazor
            services.AddHttpContextAccessor();
 
            services.AddSingleton<IEmailSender, EmailSender>();
        }
```

And Startup.Configure:
```


     public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {

            //2019-10-05 For Finbuckle Multitenant
            //Should be at the top of stack as this injects tenant info into httpContext
            app.UseMultiTenant();

            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
                app.UseDatabaseErrorPage();
            }
            else
            {
                app.UseExceptionHandler("/Home/Error");
                // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
                app.UseHsts();
            }

            app.UseHttpsRedirection();
            app.UseStaticFiles();

            app.UseRouting();
            app.UseAuthentication();
            app.UseAuthorization();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapBlazorHub();
                endpoints.MapControllers();

                //2019-10-05 For Finbuckle Multitenant
                endpoints.MapControllerRoute("default", "{__tenant__=}/{controller=Home}/{action=Index}");

                endpoints.MapFallbackToPage("/_Host");
            });
        }
```

ApplicationDbContext:

 ```
   public class ApplicationDbContext : MultiTenantIdentityDbContext<MultiTenantIdentityUser>
    {
        public ApplicationDbContext(TenantInfo tenantInfo, DbContextOptions<ApplicationDbContext> options)
           : base(tenantInfo, options)
        {
        }
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {

            optionsBuilder.UseSqlServer(ConnectionString);
            base.OnConfiguring(optionsBuilder);
        }
    }
}
```

TenantDbContext:

```
public class TenantDbContext : EFCoreStoreDbContext<AppTenantInfo>
    {
        public IConfiguration Configuration { get; }
        public TenantDbContext( DbContextOptions<TenantDbContext> options, IConfiguration configuration) : base( options)
        {
            Configuration = configuration;
       
        }
    }
}
```

Now on any Blazor Page (or Razor component) you can simply inject IHttpContextAccessor to get access to the Finbuckle extension methods. Here's an example:

```
@page "/"
@using Microsoft.AspNetCore.Http
@using Finbuckle.MultiTenant
@inject IHttpContextAccessor httpContextAccessor

@{
    //Try get TenantInfo from HttpConext.
    GetTenantInfo(); 

    @if (tenantInfo != null)
    {
        <h2>Tenant Info</h2>
        <ul>
            <li>Identifier: @tenantInfo.Identifier</li>
            <li>Id: @tenantInfo.Id</li>
            <li>Name: @tenantInfo.Name</li>
        </ul>
    }
}

@code
{
    TenantInfo tenantInfo;

    bool GetTenantInfo()
    {
        if (httpContextAccessor.HttpContext.GetMultiTenantContext().TenantInfo != null)
        {
            tenantInfo = httpContextAccessor.HttpContext.GetMultiTenantContext().TenantInfo;
            return true;
        }
        else
        {
            return false;
        }
    }
}
```

After this the MutliTenant extensions are available in both Blazor (and Razor Pages).

Hope this helps someone else too. It may not be perfect yet. If you'd like me to help update the docs or do further testing for Blazor (or whatever) I'd be happy to!

**Comment by AndrewTriesToCode** [comment]
@unencode 
Awesome, thanks for your contribution. I have yet to get into Blazor and I am realizing that I need to do so!

**Comment by unencode** [comment]
Yea, Blazor is really great! Razor components + SPA (even server side) is so awesome to work with.

I'm really glad it works with this project.

**Comment by mynkow** [comment]
@unencode were you able to override razor components per tenant?

**Comment by unencode** [comment]
@mynkow  if I understand correctly, yes you can override per tenant in a razor component.

It would be a matter of accessing it in OnInitialized for that component or similar:

> protected override void OnInitialized()
>     {
>         ...  tenantInfo = httpContextAccessor.HttpContext.GetMultiTenantContext().TenantInfo;
            return true;
>     }

Is that what you mean? I'm not 100% from the question.

**Comment by kamalraturi** [comment]
Hi,
I am trying to apply it on Razor Pages project. But In startup.cs file how we should replace this (in DataIsolationSample project):
```
app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllerRoute("default", "{__tenant__=}/{controller=Home}/{action=Index}");
            });
```

In Razor pages startup file we have 
```
app.UseEndpoints(endpoints =>
            {
                endpoints.MapRazorPages();
            });
```
My objective is to use Finbuckle.Multitenant for host strategy with different stores (sqlserver):
`services.AddMultiTenant().WithHostStrategy("*.__tenant__.?").WithConfigurationStore();
`

**Comment by AndrewTriesToCode** [comment]
Hi @mynkow 

if you are using the host strategy then you don't need to worry about the the route -- that is only needed if you are using the routing strategy.

**Comment by win32nipuh** [comment]
@unencode Can you please give a link to this working app? 

Because of many undefined entities, for example: what is the AppTenantInfo ? where and how it is defined?

**Comment by AndrewTriesToCode** [comment]
So I'm trying to learn Blazor to start thinking about the best way to support it. In a regular web app each request is a natural scope boundary to apply the tenant logic, and certain things are cached such as per-tenant options across requests to improve performance.

In Blazor I struggle to see such a natural scope boundary. I don't (yet) see a "pipeline" where it makes sense to inject logic around multitenancy, except at the initialization of the Blazor components.

Once a server-side Blazor app (or top level component) has been rendered in the browser, would there ever be a case to need to switch tenant at that point? Would it be reasonable to require a server page refresh to switch tenant?

As I understand it anything in DI as scoped when a Blazor component is server-rendered is effectively a singleton within Blazor. I also gather that its not a good idea to rely on `HttpContext` in Blazor. With that in mind I think most of the existing strategy/stores would work on the initial request, `IMultiTenantContext<TenantInfo>` will then be registered as a scoped service in DI, and then Blazor can inject the interface wherever it is needed. I'm not sure about `WithPerTenantOptions` but it's worth testing to see if the options Blazor injects get the modified values.

**Comment by davidcateduclarity** [comment]
Thank you for this!!!

**Comment by sebastianbartmann** [comment]
Hey! For my project I currently need to decide on the frontend technology. I'd like to use blazor, but it seems finbuckle isn't ready for that yet. Looking at razor pages it seems it isn't either (since the close relationship to blazor).

In the hopes that finbuckle will, at one point this year, work well with blazor what do you suggest using for now?

I don't feel like setting up an angular (or any other frontend JS framework) is smart since moving to blazor from JS seems much work. 
( I'm using the routing strategy. )

Thanks!

**Comment by AndrewTriesToCode** [comment]
hi @gugarutz 

I encourage you to try it out and post any specific issues you run up against.

Razor Pages should work just as well as MVC apps -- the only caveat is that for pages you bring in from a library (e.g. Identity) they obviously won't have the tenant route param initially. If you look at the Identity samples in the repo you'll see I get around this using a convention to add the route into the Identity Pages -- this would work for other Razor Pages library/apps as well. Also note that I used something called the "AmbientRouteUrlGenerator" in that example to make it so the tenant route param in a request is implicitly included in new URL/link generation.

For Blazor, it works OK when hosted in a regular pipeline, ie server side Blazor or wasm Blazor served from ASP.NET core site. Keep in mind how dependency injection scopes differ in Blazor so the tenant lifetime becomes singleton- rather than scope- based. I haven't tried much with a pure wasm Blazor app.

Use case question for you: do you think the tenant would change much in a Blazor app after the initial load or would it be "steady" once things are running in the browser?
