### ISSUE TITLE
Question: default fallback tenant identifier

### ISSUE THREAD

**Issue by vdecristofaro** [Finbuckle/Finbuckle.MultiTenant#19]
Which is the best way to implement a default fallback identifier with host subdomain strategy?

Suppose I registered `*.domain.com` in your dns. I have two tenants; tenant 1 and tenant2. I would like to redirect the user to the `www.domain.com` url if the tenant resolver does not find any tenant registered.

Sorry for the english. Thanks!

**Comment by AndrewTriesToCode** [comment]
Hi, I will consider this for a future enhancement.

If you want a fallback url then I suggest dropping in some logic right after the MultiTenant middleware similar to below. This checks if tenantcontext is null and if you aren't already a "www" request, and then if so redirects to the www version.

```
app.UseMultiTenant();

app.Use(async (context, next) =>
{
    if (context.GetTenantContext() == null &&
       !context.Request.Host.Host.ToLower().StartsWith("www"))
    {
        context.Response.Redirect("http://domain.com");
    }
 
   await next.Invoke();
});

// other middleware below
```

**Comment by AndrewTriesToCode** [comment]
Added #25 to capture this request.
