### ISSUE TITLE
Code-Documentation mismatch

### ISSUE THREAD

**Issue by williambowsher** [Finbuckle/Finbuckle.MultiTenant#192]
I am trying to use the MultitenantDbContext and the documented constructor that only takes a connectionString, but there is no such constructor.

Is there anyway of creating a DesignTime Db Context so that I can process my Migrations?

**Comment by AndrewTriesToCode** [comment]
Hi thanks for pointing out the docs need to be updated. 

I recommend creating a dummy tenant info like in this sample:

https://github.com/Finbuckle/Finbuckle.MultiTenant/blob/master/samples/ASP.NET%20Core%203/IdentityDataIsolationSample/Data/DesignTimeFactory.cs

**Comment by williambowsher** [comment]
It's ok I have worked around the issue and have it all functioning now.

Thanks for responding, you can close the ticket.

**Comment by williambowsher** [comment]
Thanks for the help, but I have implemented a slightly different solution as I have a separate tenant management application.

Thanks for all the hard work with Finbuckle, keep it up.

Regards
