### ISSUE TITLE
DbContext does not have a constructor with connection string

### ISSUE THREAD

**Issue by williambowsher** [Finbuckle/Finbuckle.MultiTenant#195]
In the documentation it says:
There is also a base constructor which takes a connection string parameter instead of a TenantInfo. Use this for design time context creation for use with migrations or other tools.

But there is only a constructor with TenantInfo, how can I create a DbContext to use with EF Migrations?

**Comment by williambowsher** [comment]
Its ok I don't need the connectionString constructor I have found away around it.

If you make the OnConfiguring method look like this
`
if (!optionsBuilder.IsConfigured)
{
               optionsBuilder.UseSqlServer(ConnectionString);
}
`

Then you can create a DbContext like so 
`
var dbOptions = new DbContextOptionsBuilder<ComplianceContext>();
dbOptions.UseSqlServer(connectionString);
return new ComplianceContext(null, dbOptions.Options);
`

**Comment by AndrewTriesToCode** [comment]
Hi, yeah I have a pending update to that documentation. I recommend using a design time factory for migrations as the EF Core documentation describes. Then to create the dB context a simple dummy tenant can be used. 

Also I have pending updates that don’t require inheriting from MultiTenantDbContext to give you more flexibility.

**Comment by kamalraturi** [comment]
> Hi, yeah I have a pending update to that documentation. I recommend using a design time factory for migrations as the EF Core documentation describes. Then to create the dB context a simple dummy tenant can be used.
> 
> Also I have pending updates that don’t require inheriting from MultiTenantDbContext to give you more flexibility.

Hi @achandlerwhite , thanks for this great MultiTenent solution.  I tried use this without inmemory (having sql-server as stores) but documentation is not available yet. I pushed my repo to github. Can you help me on the sample project asp.net core 3.0 "EFCoreStoreSample"? Here is the repo: https://github.com/kamalraturi/Finbuckle.MultiTenant

**Comment by williambowsher** [comment]
Thanks for the update, I have got it all working now so it's all good. When
I get back to my pc I will see if .y workaround is of use to you.

Regards

**Comment by r0lan2** [comment]
> Its ok I don't need the connectionString constructor I have found away around it.
> 
> If you make the OnConfiguring method look like this
> `if (!optionsBuilder.IsConfigured) { optionsBuilder.UseSqlServer(ConnectionString); }`
> 
> Then you can create a DbContext like so
> `var dbOptions = new DbContextOptionsBuilder<ComplianceContext>(); dbOptions.UseSqlServer(connectionString); return new ComplianceContext(null, dbOptions.Options);`

Hi @williambowsher  do you have some sample runing using sql as store? I don't know if my app or the library is responsible to create the table related with the catalog..

**Comment by williambowsher** [comment]
I will take a look and post you some code 

Kind Regards

William Bowsher

**Comment by r0lan2** [comment]
> I will take a look and post you some code Kind Regards William Bowsher
> […](#)
> On 17 Feb 2021, at 17:45, Rolando ***@***.***> wrote: ﻿ Its ok I don't need the connectionString constructor I have found away around it. If you make the OnConfiguring method look like this if (!optionsBuilder.IsConfigured) { optionsBuilder.UseSqlServer(ConnectionString); } Then you can create a DbContext like so var dbOptions = new DbContextOptionsBuilder<ComplianceContext>(); dbOptions.UseSqlServer(connectionString); return new ComplianceContext(null, dbOptions.Options); Hi @williambowsher do you have some sample runing using sql as store? I don't know if my app or the library is responsible to create the table related with the catalog.. — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

Sorry I deleted my question just after you added your comments... I am trying looking into your repo and check if still have questions :)
