### ISSUE TITLE
Per-tenant CORS

### ISSUE THREAD

**Issue by GordonBlahut** [Finbuckle/Finbuckle.MultiTenant#196]
I'm trying to use per-tenant CORS policy but it doesn't seem to work.

I'm not sure if I'm setting it up wrong or if ASP.NET Core just doesn't setup the CORS middleware in a compatible way but I'm wondering if anyone else has had any success with this.

```csharp
public IServiceProvider ConfigureServices(IServiceCollection services)
{
    services.AddCors(options => {});

    // ... other stuff

    services.AddMultiTenant()
        .WithHostStrategy("__tenant__")
        .WithFallbackStrategy("localhost")
        .WithInMemoryStore(Configuration.GetSection("MultiTenant"))
        .WithPerTenantOptions<Microsoft.AspNetCore.Cors.Infrastructure.CorsOptions>((options, tenantContext) =>
        {
            options.AddPolicy("ApiCorsPolicy", builder => builder
                .WithOrigins(IdentityServerConfig.GetClients(tenantContext)
                    .SelectMany(c => c.AllowedCorsOrigins)
                    .Where(o => o != null)
                    .ToArray())
                .AllowAnyHeader()
                .AllowAnyMethod());
        });
}
```
```csharp
public void Configure(IApplicationBuilder app, IHostingEnvironment env)
{
    app.UseMultiTenant();
    app.UseCors("ApiCorsPolicy");
    // other stuff
}
```
Setting a breakpoint inside `WithPerTenantOptions`, I can see that it never even gets hit.

**Comment by AndrewTriesToCode** [comment]
Any luck @GordonBlahut ?

Sometimes Microsoft coaches options internally which can make getting the desired abhor across tenants difficult, but it is doable. I’ll try to take a look this week.

**Comment by achandlerwhite** [comment]
Any luck @GordonBlahut ?

Sometimes Microsoft coaches options internally which can make getting the desired abhor across tenants difficult, but it is doable. I’ll try to take a look this week.

**Comment by achandlerwhite** [comment]
Any luck @GordonBlahut ?

Sometimes Microsoft coaches options internally which can make getting the desired abhor across tenants difficult, but it is doable. I’ll try to take a look this week.

**Comment by GordonBlahut** [comment]
@achandlerwhite No luck yet. Since it never hits `WithPerTenantOptions` I suspect they aren't even using an `IOptions`-based approach in the cords middleware but I haven't had a chance to really dig through the source.

**Comment by AndrewTriesToCode** [comment]
@GordonBlahut you may have figured it out already, but the options are pulled in the [CorsService](https://github.com/aspnet/AspNetCore/blob/master/src/Middleware/CORS/src/Infrastructure/CorsService.cs) class, which internally caches them. A simple hack would be reregister the service as transient rather than a singleton I think. The options are cached anyway so I'm not sure why they did so in this class. They also did it in AuthenticationSchemeProvider, which I had to work around.

**Comment by aswin-ingenuous** [comment]
For those who are on the same boat, the `CorsPolicyBuilder` now supports a delegate to determine if the origin is allowed or not: [SetIsOriginAllowed](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.cors.infrastructure.corspolicybuilder.setisoriginallowed?view=aspnetcore-8.0).

```
public void Configure(IApplicationBuilder app, IMultiTenantContextAccessor<TenantInfo> ctx)
{
    app.UseCors(config => config
      .AllowAnyHeader()
      .AllowAnyMethod()
      .SetIsOriginAllowed((origin) =>
      {
        var tenant = ctx.MultiTenantContext.TenantInfo;
        var originsAllowed = // get the allowed origins for the tenant
        return originsAllowed.Contains(origin);
      })
    );
}
```
