### ISSUE TITLE
Usage with IdentityServer4

### ISSUE THREAD

**Issue by williambowsher** [Finbuckle/Finbuckle.MultiTenant#197]
Firstly thank you for all your work on Finbuckle, makes my life a lot easier.

Now to my question:
I have integrated my application with IdentityServer 4 and when a user is authenticated they are assigned a claim for the tenant they should be using, is there anyway of restricting the user to the tenant?

**Comment by AndrewTriesToCode** [comment]
Hi, I can give you a more detailed response later today, but this is an area I’m actively looking into.

How are you doing the user authentication in IdentityServer? Are you using Identity or something else?

**Comment by williambowsher** [comment]
Hi Andrew,
I have now sorted all my issues, I am indeed using Identity and I have
added a small API to the IdentityServer source code so I can automate the
user sync, then I have the postback action check the claims for the tenant
claim, I'd the tenant cla does not match the tenant returned from the http
context then I remove the auth cookie and redirect to the proper tenant.

Everything else works perfectly.

Thanks for the great work.
