### ISSUE TITLE
Is there any examples for working with IdentityServer4?

### ISSUE THREAD

**Issue by chinaq** [Finbuckle/Finbuckle.MultiTenant#198]
Is there any examples for working with IdentityServer4? Thanks.

**Comment by AndrewTriesToCode** [comment]
hi @chinaq I don't have any public samples at the moment, but let me ask about your use case.

What parts of identityServer4 would you want to behave "per-tenant"?

Would you want different API or identity resources?
Different users?
Different federation settings?
Howabout the operational store of active tokens and such--would that need to be multi tenant as well?

**Comment by chinaq** [comment]
Hi @achandlerwhite,

 I'm new to multi-tenant and IdentityServer4, and not familiar with some concepts that you mentioned. What I want is to get the Identity resource which combined with the tenant info from the IdentityServer4, that would help me to controll the API authority on the server side. If there are some examples that will help me a lot to learn it faster.

Thanks.
