### ISSUE TITLE
Pending update to EFCore Store documentation.

### ISSUE THREAD

**Issue by kamalraturi** [Finbuckle/Finbuckle.MultiTenant#199]
> Hi, yeah I have a pending update to that documentation. I recommend using a design time factory for migrations as the EF Core documentation describes. Then to create the dB context a simple dummy tenant can be used.
> 
> Also I have pending updates that don’t require inheriting from MultiTenantDbContext to give you more flexibility.

Hi @achandlerwhite , thanks for this great MultiTenant solution.  I tried use this without inmemory (having sql-server as stores) but documentation (https://www.finbuckle.com/MultiTenant/Docs/Stores) is not available yet. I pushed my repo to github. Can you help me on the sample project asp.net core 3.0 "EFCoreStoreSample"? Here is the repo: https://github.com/kamalraturi/Finbuckle.MultiTenant

_Originally posted by @kamalraturi in https://github.com/Finbuckle/Finbuckle.MultiTenant/issues/195#issuecomment-561138889_

**Comment by AndrewTriesToCode** [comment]
hi @kamalraturi sorry the late reply. Sure I am taking a look and update my response.
