### ISSUE TITLE
When Finbuckle.MultiTenant 4.1.0 will be released?

### ISSUE THREAD

**Issue by mjallaq88** [Finbuckle/Finbuckle.MultiTenant#201]
I would like to know when are you planning to release a new version of the latest code 4.1.0?

**Comment by AndrewTriesToCode** [comment]
hi @mjallaq88 
I'm planning for version 5.0 within the next week. It will support .NET Core 3.1, have more multi tenant stores, and allow for more flexibility with EFCore and existing databases.

**Comment by mjallaq88** [comment]
Awesome. I'm looking forward to consuming it.  I'm using the latest code in my current project as a `git submodule` to use some of the added features.

**Comment by AndrewTriesToCode** [comment]
@mjallaq88 update: I have finished all the functionality. Just a few minor items then I will publish 5.0.

**Comment by mjallaq88** [comment]
@achandlerwhite Great news! Thank you for the update
