### ISSUE TITLE
Extension methods not available for EFCore

### ISSUE THREAD

**Issue by Warhead5555** [Finbuckle/Finbuckle.MultiTenant#216]
In the documentation section 'Adding MultiTenant functionality to an existing DbContext' for EF you are talking about extension methods when implementing the IMultiTenantDbContext interface.

[Link to documentation](https://www.finbuckle.com/MultiTenant/Docs/EFCore#adding-multitenant-functionality-to-an-existing-dbcontext)

But to my surprise it's not possibile to reach the following extension methods static classes due to their _internal_ access modifiers:

- Static class **FinbuckleModelBuilderExtensions** method **ConfigureMultiTenant** 
- Static class **IMultiTenantDbContextExtensions** method **EnforceMultiTenant** 

PS, The methode name builder.SetupMultiTenant() as stated in the documentation example should be changed to builder.ConfigureMultiTenant() 

** As a workaround i copied the code of the extension methods to my local project. But this can't be the right way in my opinion.

**Comment by AndrewTriesToCode** [comment]
@Warhead5555 

Thanks for reporting the issue! You are right and I will et up a new release with the corrections.

**Comment by Warhead5555** [comment]
Thank you for fixing this bug on such short notice. Keep up the good work.
