### ISSUE TITLE
MultiTenantContext has internal properties

### ISSUE THREAD

**Issue by UmairB** [Finbuckle/Finbuckle.MultiTenant#219]
Why was a decision made to make `MultiTenantContext` with internal properties? Finbuckle has been very good for us in asp.net core scenario but when we tried to implement our infrastructure using finbuckle in say, azure functions, we ran into the problem of not being able to provide a mechanism for creating our own `MultiTenantContext`.

Maybe make `MultiTenantContext` an abstract base class and allow different implementions to provide their own way of creating this? Or abstract the code that creates the multitenant context out of the asp.net core middleware and put it into a service in core. Which will allow anyone to create a multitenant context from anywhere.

**Comment by AndrewTriesToCode** [comment]
hi @UmairB 

There is no strong reason other than my personal preference for strong encapsulation at the time. I definitely agree with you and will plan to address this in the next release.

Thanks!

**Comment by AndrewTriesToCode** [comment]
I'll add to this that I also plan to remove the dependency on `HtpContext` storing the `MultiTtenantContext` so that things work better in scenarios like yours or also non web hosted .NET Core stuff.
