### ISSUE TITLE
Multitenant Store does not work if given constructor has dependency injections

### ISSUE THREAD

**Issue by gitriinbigd** [Finbuckle/Finbuckle.MultiTenant#221]
First, my rationale for creating a custom store is I do not want to store connection strings in plain text in the database. I'd like to have a custom store that handles obfuscating that information. From there, I may get cheeky and try other things but that's the goal. I started with a simple configuration: 
```
            collection.AddMultiTenant()
                .WithHostStrategy()
                .WithStore<MultiTenantStore>(ServiceLifetime.Scoped)
                .WithFallbackStrategy(MultiTenancyConstants.DEFAULT_IDENTIFIER);

```
I hard-coded a store because what I had wasn't working. So I have something akin to this:
```
    public class MultiTenantStore : IMultiTenantStore
    {
        private readonly IDbContextScopeFactory _scopeFactory;

        public MultiTenantStore(IDbContextScopeFactory scopeFactory)
        {
            Guard.Against.Null(scopeFactory, nameof(scopeFactory));
            _scopeFactory = scopeFactory;
        }
        public Task<TenantInfo> TryGetAsync(string id)
        {
            throw new NotImplementedException();
        }

        public Task<TenantInfo> TryGetByIdentifierAsync(string identifier)
        {
            if (identifier == MultiTenancyConstants.DEFAULT_IDENTIFIER)
            {
                return Task.FromResult(new TenantInfo(MultiTenancyConstants.DEFAULT_ID, MultiTenancyConstants.DEFAULT_IDENTIFIER, "Test", "*connectionstring*", null));
            }
            return null;
        }

        public Task<bool> TryAddAsync(TenantInfo tenantInfo)
        {
            throw new NotImplementedException();
        }

        public Task<bool> TryRemoveAsync(string id)
        {
            throw new NotImplementedException();
        }

        public Task<bool> TryUpdateAsync(TenantInfo tenantInfo)
        {
            throw new NotImplementedException();
        }
    }

```
I have my SecurtyDbContext implementing the IMultiTenantDbContext and the tenant passed is NULL. When I remove the IDbContextScopeFactory scopeFactory from the constructor, it WORKS!! I cannot wrap my head around why this would be occurring. This is .NET Core and Entity Framework 3.1.1 

Any thoughts?

**Comment by AndrewTriesToCode** [comment]
Hi @gitriinbigd 

Is `IDbContextScopeFactory` registered in the service collection for dependency injection? If so it should be able to use the constructor without problem by injecting the parameter. It's possible there is a bug with that though so let me know.

A different option: the `WithStore` method can take parameters which will then be plugged into the constructor. For example if you have an `IDbContextScopeFactory` instance you can call:
```
...WithStore<MultiTenantStore>(ServiceLifetime.Scoped, myContextScopeFactory);
```

Another option: the other `WithStore` overload that take a factory method to construct the instance. This gives the most control:
```
...WithStore<MultiTenantStore>(ServiceLifetime.Scoped, services =>
{
    return new MultiTenantStore (... constructor stuff ...);
}));

```

I hope this helps!

**Comment by gitriinbigd** [comment]
`IDbContextScopeFactory `is registered as a service and what is weird is that the store constructor is called and the `TryGet `method is called as well. 

This is where is gets very weird. 

With that in the constructor, when the `SecurityDbContext` is invoked, the `TenantInfo `parameter is **NULL**. If I shut things down, remove the argument from the constructor, restart, when the `SecurityDbContext `is invoked, the `TenantInfo `parameter is **NOT NULL**. 

It does not seem to make any sense but I can reproduce this reliably. I tend to think there is a bug but have not had the time to check out the code, step through it, etc.

**Comment by AndrewTriesToCode** [comment]
So in taking a closer look I can see this is a little more complicated. Is `SecurityDbContext` the concrete implementation of `IDbContextScopeFactory`? Do I have it right that you are trying to use a multitenant db context inside the multitenant store? We have a bit of a chicken-and-the-egg problem. I think I can explain the behavior you observe.

The `IMultiTenantDbContext` implementation expects that the `TenantInfo` property it has will be set somehow. It's probably passed in through DI in your constructor.

BUT, the DI for `TenantInfo` is ready only *after* the middleware runs. The middleware runs the strategy and store logic. So the store itself can't rely on something that relies on the `TenantInfo`.

So in your case the store would try to DI the dbcontext which tries to DI the tenantInfo, which isn't ready yet because the store has to first get it, so the store can't be created!

Does the SecurityDbContext really need to be multitenant itself?

If I am off track I apologize. I'd be happy to look at the project if you can link me to a repository showing the behavior.

**Comment by gitriinbigd** [comment]
Not exactly. The IDbContextScopeFactory generates context scopes which are used for accessing DbContexts (see https://mehdi.me/dbcontextscope-source-code-now-available-on-github/). I won’t get into that but it’s nothing to do directly with the DBContext. 

I don’t have a project I can publish but will try and pull something together. In short, the dependency injection is working - but when it does, it doesn’t set the tenant. That’s the gist. I’ll try and get a subset of the code together to demonstrate the problem. 

On the upside, your explanation makes sense and I see how that would absolutely be a problem. I just don’t think it correlates to *this* problem.

**Comment by AndrewTriesToCode** [comment]
Ok I see what you mean now. I enjoyed your article, interesting stuff as an aside.

I don't know what could be the cause. You probably are aware that `WithStore` actually decorates the provided store with a wrapper store that does validation and logging. I wonder if that is somehow causing the problem.

Can you try registering without the helper method just to eliminate the wrapper as a factor?
```
services.AddScope<IMultiTenantStore, YourStore>();
```

Also the symbol packages are on Nuget so depending on your IDE you should be able to step through the source code to see exactly what is going on.

**Comment by AndrewTriesToCode** [comment]
@gitriinbigd 

Hi just checking in. Have you been able to make this work for you?
