### ISSUE TITLE
Should I use the tenant filter for a many-to-many join entity?

### ISSUE THREAD

**Issue by devalot76** [Finbuckle/Finbuckle.MultiTenant#222]
Hi,
I apologize in advance for the possible OT, but I really don't know what else to ask.
Should I use the tenant filter even for a join entity created to implement a many-to-many ralationship?

Thank you very much.
Best regards.

**Comment by AndrewTriesToCode** [comment]
hi @devalot76!

That is a very good question. The global query filter works on the "initial" Entity of the query, which is almost never the intersection entity. I usually don't bother with making the intersection table multitenant because I prefer to keep things simple if I can.
