### ISSUE TITLE
HttpRemoteStore does not parse Items collection

### ISSUE THREAD

**Issue by clinically-au** [Finbuckle/Finbuckle.MultiTenant#233]
Hi Andrew,

Similarly to EFCoreStore (https://github.com/Finbuckle/Finbuckle.MultiTenant/issues/212), it would be great if HttpRemoteStoreClient could parse the Items collection returned to it.

Thanks
W.

**Comment by clinically-au** [comment]
I've found that simply adding the items dictionary to the anonymous type in `HttpRemoteStoreClient.TryGetByIdentifierAsync(...)` seems to work:

`var anon = new { Id = "", Identifier = "", Name = "", ConnectionString = "", Items = new Dictionary<string,object>()};`

And then:
`return new TenantInfo(result.Id, result.Identifier, result.Name, result.ConnectionString, result.Items);`

Am I missing something important about why this should not be done?

Thanks
W.

**Comment by AndrewTriesToCode** [comment]
Yep--it can almost exactly the same way as long as the server uses the compatible type variable within the JSON. I'll add this to the list.

**Comment by AndrewTriesToCode** [comment]
Doing a little cleanup -- with the move to custom ITenantInfo implementations Items is no longer used anymore.
