### ISSUE TITLE
How can I get the tenant information to support hot updates

### ISSUE THREAD

**Issue by alonsoalon** [Finbuckle/Finbuckle.MultiTenant#237]
Get the tenant information in the configuration file. How can I get the tenant information to support hot updates?The production environment is in need of thermal updates.

**Comment by AndrewTriesToCode** [comment]
@alonsoalon I apologize for the late reply.

I'm not sure I understand your question. Are you using the `ConfigurationStore' MultiTenantStore? It should automatically pick up any changes to the saved appsettings.json file just like ASP.NET Core picks up other changes in the settings file at runtime.
