### ISSUE TITLE
Web API implementation or example

### ISSUE THREAD

**Issue by cland** [Finbuckle/Finbuckle.MultiTenant#240]
Hi there,
Thanks for this great package. I am new to this and trying out a simple Multi-tenant Rest API. Can I use this package for that? I've tried to modify the "RouteStrategySample" by creating an API controller and updating the Startup.cs, UserEndPoints like so:
```
app.UseEndpoints(endpoints =>
{
    endpoints.MapControllerRoute("default", "{__tenant__=}/{controller=Home}/{action=Index}");
    endpoints.MapControllerRoute(
             name: "api",
             pattern: "{__tenant__=}/api/{controller}/{id?}"
    );
});
```

I am not 100% confident if this is the correct way to configure it. My api controller simply return and IActionResult of the TenantInfo object. Using postman, I am failing to replicate what the default MVC controller HomeController is doing. I'm returning it as an IActionResult in my API controller.

Please help on how I can configure this to work. The strategy can be any, doesn't have to be routing strategy only. My API controller looks like so:

```
    [Route("/api/[controller]")]
    [ApiController]
    public class TasksController : ControllerBase
    {
        public IActionResult Get()
        {
            var ti = HttpContext.GetMultiTenantContext()?.TenantInfo;
            if(ti == null)
            {
                return BadRequest("Missing tenant information");
            }
            return new ObjectResult(ti);
        }
    }
```

**Comment by AndrewTriesToCode** [comment]
Hi @cland 

It should work for APIs just fine. If I recall correctly the API route ignores the `UseEndpoint` configuration. I think you just need to add `__tenant__` in your `ApiController` route attribute:
```
[Route("/{__tenant__=}/api/[controller]")]
[ApiController]
public class TasksController : ControllerBase
...
```

Give that a try and let me know. You can remove the other routes stuff (unless you need them otherwise). I should probably add something about this to the documentation.

**Comment by cland** [comment]
Thanks, it's working fine now. 

Just a note to other newbies like me, the error I had received when I tried to return the TenantInfo object as is, as per my code in my post, was this:

![image](https://user-images.githubusercontent.com/4290381/77946461-9ce9a080-72c2-11ea-83fd-d85728258a80.png)

The multi-tenant setup was actually working fine, I just needed to sort out the object being returned. For this particular test I did this:

```
    [Route("/{__tenant__=}/api/[controller]")]
    [ApiController]
    public class TasksController : ControllerBase
    {
        public IActionResult Get()
        {
            var ti = HttpContext.GetMultiTenantContext()?.TenantInfo;
            if(ti == null)
            {
                return BadRequest("Missing tenant information");
            }
            var tenantInfoDTO = new
            {
                ti.Id,
                ti.Name,
                ti.Identifier,
                ti.ConnectionString
            };
            return new ObjectResult( tenantInfoDTO);
        }
    }
```

Thanks @achandlerwhite . Now need to include some JWT security...struggle continues :)
