### ISSUE TITLE
Get IOptions with a service class.

### ISSUE THREAD

**Issue by Hammurabidoug** [Finbuckle/Finbuckle.MultiTenant#243]
How do I get IOptions with a class that does not have an HttpContext like a service class?

**Comment by Hammurabidoug** [comment]
I posted a [Blazor code sample](https://github.com/Hammurabidoug/Finbuckle.MultiTenant) that mocks up what I am trying to achieve.

The example includes [this contribution](https://github.com/Finbuckle/Finbuckle.MultiTenant/issues/188), which does not work.

Service classes do not contain HttpContext, so it is always null. "[How do I access HttpContext in Server-side Blazor](https://stackoverflow.com/questions/53817373/how-do-i-access-httpcontext-in-server-side-blazor)?" on StackOverflow attempts to inject an IHttpContextAccessor, which is similar to [issue 188](https://github.com/Finbuckle/Finbuckle.MultiTenant/issues/188).

On the ASP.Net Core site "[Blazor Server HttpContextAccessor.HttpContext null when client is behind proxy](https://github.com/dotnet/aspnetcore/issues/18183)," @javiercn says "We don't recommend using HttpContextAccessor in server-side Blazor applications as the context is not always available and its availability depends on the underlying transport, which is not reliable. This is the same as for other SignalR applications."

In feat: refactor [multitenant context storage #234](https://github.com/Finbuckle/Finbuckle.MultiTenant/issues/234), @achandlerwhite says, "A better solution would be to store it in the dependency injection container. This would have the added benefit of utility for non-webhost based .NET Core hosted applications which can also use the DI container." Will this feature satisfy the requirement of a service class in server-side Blazor? If so, is there an anticipated timeline for when this feature will be complete? Is there somewhere I can see the feature in development?

**Comment by AndrewTriesToCode** [comment]
hi @Hammurabidoug 
I'm not up-to-date on Blazor-- are you able to inject the same services into services that you can into Asp.Net Core controllers?

For per-tenant-options currently this library relies internally on `HttpContextAccessor` so I think that Blazor bug will impact you. For the next release I am working to remove that dependency, but I am probably not going to put it directly into DI per my quote above, but still have it be accessible via `IMultiTenantContextAccessor`. I think this would then work within Blazor. I have a few PRs in progress, I'll try to get the one for `IMultiTenantContextAccessor` up this week.

**Comment by Hammurabidoug** [comment]
Hi @achandlerwhite 
The HttpContextAccessor is not working with Blazor as written. I created a Finbuckle.MultiTenant.Blazor library [here](https://github.com/Hammurabidoug/Finbuckle.MultiTenant/tree/master/src/Finbuckle.MultiTenant.Blazor). There's also a sample [Blazor application here](https://github.com/Hammurabidoug/Finbuckle.MultiTenant/tree/master/samples/ASP.NET%20Core%203/BlazorSample). It might not be the best implementation, but it works. I wish I could inject into the middleware a service that can return an IMultiTenantContext.

The Blazor library only supports Core 3.0 and 3.1.

The sample also includes implementation of a derived TenantInfo with a generic ConfigurationStore.

I would love to have your input on this: how I could improve it and what you could use for the next version of the Finbuckle.MultiTenant release.

Since you have the InternalsVisible in the assemblyinfo, I can't reference the NuGet package, so I'm going to have to include the build with my project.  I'd much rather reference NuGet. Perhaps it would be better to use interfaces for strategies and such rather than concrete classs in the middleware so that these InternalsVisible could be removed. Otherwise, you could open up the setters, I guess. Essentially, it's mostly an easy library to extend as it exists right now, but the HttpContext piece is tightly coupled.

**Comment by AndrewTriesToCode** [comment]
@Hammurabidoug I will have a 6.0.0-preview2 out this weekend where I am not relying on `HttpContextAccessor` I am curious to see if it will work for you in Blazor.

**Comment by Hammurabidoug** [comment]
That's really good news. I'll check it out when you post it.

**Comment by Hammurabidoug** [comment]
I pulled down your code from the release-6.0.0-dev branch. It looks good. I particularly like your addition of the ITenantInfo interface and the associated generics. You also opened up the setters on The MultiTenantContext properties.

For the middleware though, it would be nice if the storage of the context was abstracted out.  You could add an IContext parameter to the Invoke method, for instance.  The IContext would default as a wrapper around HttpContext and contain methods for adding and retrieving a IMultiTenantContext<TTenantInfo> object. If we wanted to use a different IContext than the default HttpContext wrapper, then we could use our implementation. For server-side Blazor, this could be a session dictionary.  The AddMultiTenant extension could have an optional WithContext<IContext> that would inject into the Invoke method of the middleware.

**Comment by ZedZipDev** [comment]
Hi, Doug, I am trying to use your approach to read additional config parameters in my Blazor app+Finbuckle v6.
Could you please say me, why it does not work:
I get this piece of code 
```
services.AddBlazorMultiTenant().
WithStore<ConfigurationStore<DerivedTenantInfo>>(ServiceLifetime.Singleton)
.WithHostStrategy(@"__tenant__.*")
.WithPerTenantOptions<CustomOptions, DerivedTenantInfo>(t => t.CustomOptions);  

```
and replaced with this:
```
services.AddMultiTenant<DerivedTenantInfo>()
.WithConfigurationStore()
.WithHostStrategy(tenantSettings.HostTemplate)
.WithPerTenantOptions<S3ConfigOptions>((options, tenantInfo) =>
{
tenantInfo.S3CustomOptions = options;// <-------debug point is not reached
});

```

But the S3CustomOptions  is already null and I  the debug point is not reached.
What is incorrect?

**Comment by AndrewTriesToCode** [comment]
@Hammurabidoug 
Yeah my next commit for preview2 is refactoring the middleware to use an `ITenantResolver` that will be agnostic to ASP.NET. Should work well for Blazor or hosted service situations.
