### ISSUE TITLE
Multiple DbContexts per tenant

### ISSUE THREAD

**Issue by tcorvin** [Finbuckle/Finbuckle.MultiTenant#245]
Does Finbuckle.MultiTenant support multiple connection strings per tenant?
(i.e. for an infrastructure database, an auth database, and an app database)

If not, any thoughts and how this could be accomplished "manually?"

Thanks,
Tyson

**Comment by AndrewTriesToCode** [comment]
hi @tcorvin 
The next version releasing soon will support a custom Tenant Info object so you can have any number of connection strings. Then in the configuration for the database context you would have to somehow choose the connection string you wanted to use.

In the current version you could store them in Items collection, but its just a <string, object> dictionary and not strongly typed.

**Comment by tcorvin** [comment]
Hey @achandlerwhite, perfect ... I'll use the items collection for now as we wait for next release ... thanks!
