### ISSUE TITLE
Question about seeding database

### ISSUE THREAD

**Issue by mobinseven** [Finbuckle/Finbuckle.MultiTenant#246]
Hi.
I am trying to use your well-designed library in a Blazor app, [BlazorBoilerplate](https://github.com/enkodellc/blazorboilerplate).

The problem I encountered is simple:
In the above mentioned app, a function, `databaseInitializer`, tries to seed database with default roles and built-in user accounts. This `databaseInitializer` is called in startup.configure() part of the program. Where:

1. `TenantInfo` of the `ApplicationDbContext` returns null, so obviously `SaveChanges()` will throw `MultiTenantException: MultiTenant Entity cannot be changed if TenantInfo is null.`

2. `HttpContext` is not around yet, therefore I can not use `TrySetTenantInfo`.

My question: How should I implement the seeding procedure?

More details:

- `AddMultiTenant` :

```c#
services.AddMultiTenant()
    .WithDelegateStrategy(context =>
    {
        Claim c = ((HttpContext)context).User.Claims.FirstOrDefault(c => c.Type == Constants.Claims.TenantId);
        if (c != null)
        {
            string tenantId = c.Value;
            return Task.FromResult(tenantId);
        }
        else
        {
            return Task.FromResult(Constants.Tenant.RootTenantTitle);
        }
    })
    .WithEFCoreStore<TenantStoreContext>()
    .WithFallbackStrategy(Constants.Tenant.RootTenantTitle);
``` 

- Somewhere before seeding `ApplicationDbContext`, I successfully seeded `TenantStoreContext`:
```c#
if (!await _tenantStoreContext.TenantInfo.AnyAsync(t => t.Identifier == Constants.Tenant.RootTenantTitle))
{
    _tenantStoreContext.TenantInfo.Add(new TenantInfo(Constants.Tenant.RootTenantTitle, Constants.Tenant.RootTenantTitle,
        Constants.Tenant.RootTenantTitle, null, null));
    await _tenantStoreContext.SaveChangesAsync();
}

var defaultTenantInfo = await _tenantStoreContext.TenantInfo.SingleAsync(t => t.Identifier == Constants.Tenant.RootTenantTitle);
```

**Comment by AndrewTriesToCode** [comment]
@mobinseven  sorry for the slow response

Are the default roles and user accounts the same for all tenants or are they "per-tenant"?

If they are shared across all tenants I recommend creating a dummy `TenantInfo` with the proper connection string so you can just `new MyDbContext(dummyTenant)` or similar.

If these are per-tenant then it gets a lot tricker. One approach I've seen is to create an endpoint you can hit that will do the seeding for you--that endpoint would then have the httpcontext and middleware in place for the DI to work for the db context.

**Comment by mobinseven** [comment]
@AndrewTriesToCode Thanks for your involvement.
As the first case is true for our case, I used a hack:
```c#
    public class ApplicationDbContext : MultiTenantIdentityDbContext<ApplicationUser, IdentityRole<Guid>, Guid>, IApplicationDbContext, IMultiTenantDbContext
    {
        public new TenantInfo TenantInfo { get; } = new TenantInfo(...);
        ...
    }
```
Let me know what do you think about this. Thanks.
