### ISSUE TITLE
Using Finbuckle.Multitenant with IdentityServer4

### ISSUE THREAD

**Issue by bilalhashmi** [Finbuckle/Finbuckle.MultiTenant#247]
Hi

Thanks for the great library. It is quite easy to use.

I am trying to implement a multi-tenant application. I have **ASP.NET Core MVC** application which uses a service (implemented using **IdentityServer4** and **ASP.NET Identity Framework**) for authentication.  Let suppose, I have two tenants (tenant1, tenant2). I have added **Redirect Uris** for both tenants in IdentityServer4 service. Now when I access my mvc application using tenant specific URL [https://localhost:5000/tenant1](), it redirects me to login page of identity server running on [https://localhost:5001/Account/Login?ReturnUrl...](). After successful, I get a separate cookie for that application.  Now when I try to access it using another tenant URL [https://localhost:5000/tenant2](), it redirects me towards the identity server **Authorize** end point instead of login screen. It is actually using ASP.NET Core Identity cookie called "identity" in my application. My question is how can I land user to login page for tenant2 instead of using "identity" cookie which is redirecting it towards authorize end point? Could you please or anybody else help me to solve my problem. 

### MVC Application Authentication services configuration
```
  services.AddAuthentication(options =>
            {
                options.DefaultScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                options.DefaultChallengeScheme = "oidc";
            })
            .AddCookie(CookieAuthenticationDefaults.AuthenticationScheme, options =>
            {
                options.Cookie.Name = "Auth.";
                options.Cookie.IsEssential = true;
                options.SessionStore = new MemoryCacheTicketStore();
            })
            .AddOpenIdConnect(options =>
            {
                options.SignInScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                options.Authority = identityUrl.ToString();
                options.SignedOutRedirectUri = callBackUrl.ToString();
                options.ClientId = "mvc";
                options.ResponseType = "code id_token";
                options.SaveTokens = true;
                options.GetClaimsFromUserInfoEndpoint = true;
                options.RequireHttpsMetadata = false;
                options.Scope.Add("openid");
                options.Scope.Add("profile");
                options.Events = new OpenIdConnectEvents
                {
                    OnRemoteFailure = context =>
                    {
                        context.HandleResponse();
                        context.Response.Redirect("Account/SignIn");

                        return Task.FromResult(0);
                    },
                };
            });
```

### MVC application multi-tenant services configuration using Finbuckle Library

```
services.AddMultiTenant()
                 .WithHttpRemoteStore($"{companyUrl}api/tenants/")
                 .WithBasePathStrategy()
                 .WithRemoteAuthentication()
                 .WithPerTenantOptions<CookieAuthenticationOptions>((options, tenantInfo) =>
                 {
                     options.Cookie.Name += $"{tenantInfo.Id}.Cookie";
                     options.Cookie.Path = $"/{tenantInfo.Identifier}";
                     options.LoginPath = $"{options.Cookie.Path}/Account/SignIn";
                     options.LogoutPath = $"{options.Cookie.Path}/Account/Signout";
                 })
                 .WithPerTenantOptions<OpenIdConnectOptions>((options, tenantInfo) =>
                  {
                      options.CallbackPath = $"/{tenantInfo.Identifier}/signin-oidc";
                      options.SignedOutCallbackPath = $"/{tenantInfo.Identifier}/signout-callback-oidc";

                      options.Events.OnRedirectToIdentityProvider = n =>
                      {
                          if (n.ProtocolMessage.RequestType == OpenIdConnectRequestType.Authentication)
                          {
                              var tenantId = n.HttpContext.GetMultiTenantContext()?.TenantInfo?.Id;
                              n.ProtocolMessage.AcrValues = $"tenant:{tenantId}";
                          }
                          return Task.FromResult(0);
                      };
                  });
```

### Identity Server 4 configurations

            services.AddIdentityServer(x =>
            {
                x.IssuerUri = "null";
                x.Authentication.CookieLifetime = TimeSpan.FromHours(2);
            })
            .AddSigningCredential(Certificate.Certificate.Get())
            .AddAspNetIdentity<ApplicationUser>()
            .AddConfigurationStore(options =>
            {
                options.ConfigureDbContext = builder => builder.UseSqlServer(connectionString,
                    sqlServerOptionsAction: sqlOptions =>
                    {
                        sqlOptions.MigrationsAssembly(migrationsAssembly);
                        sqlOptions.EnableRetryOnFailure(maxRetryCount: 15, maxRetryDelay: TimeSpan.FromSeconds(30), errorNumbersToAdd: null);
                    });
            })
            .AddOperationalStore(options =>
            {
                options.ConfigureDbContext = builder => builder.UseSqlServer(connectionString,
                    sqlServerOptionsAction: sqlOptions =>
                    {
                        sqlOptions.MigrationsAssembly(migrationsAssembly);
                        sqlOptions.EnableRetryOnFailure(maxRetryCount: 15, maxRetryDelay: TimeSpan.FromSeconds(30), errorNumbersToAdd: null);
                    });
            })
            .Services.AddTransient<IProfileService, ProfileService>();

            services.ConfigureApplicationCookie(options =>
            {
                options.Cookie.Name = "identity";
                options.SessionStore = new MemoryCacheTicketStore();
            });

**Comment by AndrewTriesToCode** [comment]
hi @bilalhashmi 

Good day for a tough question huh!? :)

In this case the same identity cookie is getting reused because you happen to be on the same computer when trying the two tenants (which could happen in real life). I see two options:

1) On the identity Server disable to the "remember me" functionality when the user logs in there. I think this would effectively require them to always sign on when redirected.\

2) Have Identity Server have a separate Identity cookie per tenant. Effectively you would make the Identity Server multitenant also. The multitenant value passed to IS4 via the ACR values would be used to do a `PerTenantOptions` on the identity cookie so that the cookie name is unique for each tenant. You'd need a multitenant strategy that can parse the passed ACR value to determine the tenant. Then you could also consider if you want the databases for the operational and configuration store to be per-tenant. It can get quite complicated.

Hopefully that helps-- I can try to put together a working example if that would also help.

**Comment by AndrewTriesToCode** [comment]
Folllowup queston -- does your IdentityServer4 setup have the same database of users for both of your tenants or would it have different sets of users for each tenant?

A simple but effective solution might be just to run one identity server instances per tenant.

**Comment by pworthy99** [comment]
Hi @AndrewTriesToCode 

I am currently attempting your option 2 and am struggling with getting operational and configuration store to be per-tenant. I have setup both my client and identity server to be multi tenant. I have a Tenant Configuration Database holding the tenantinfo table , then a Database per a tenant having all the ID4 tables and identity tables.

I agree it has got quite complicated. would it be possible to point me in the right direction with getting operational and configuration store to be per-tenant.

Thanks

**Comment by bilalhashmi** [comment]
Hi Andrew,

Thanks for the feedback. 

My **IdentityServer4** have different sets of users for each tenant. 

I have resolved that issue by listening the **OnValidatePrincipal** event against cookie options at **IdentityServer4** end as shown below. 

 ```
 services.ConfigureApplicationCookie(options =>
            {
                options.Cookie.Name = "identity";
                options.Events.OnValidatePrincipal = <method to execute on validating principal event>
            });
```
In the event handler, I compare user associated tenant and tenant info contained in "acr_values". In case of mismatch, I reject the principal. 

**NOTE:** I am already keeping tenant information with users without using finbuckle at IdentityServer4 end.

**Comment by jaltenbernd** [comment]
@bilalhashmi Do you have repo available where you got IdentityServer4 working with Finbuckle? I'm trying to implement the same.

**Comment by bilalhashmi** [comment]
> @bilalhashmi Do you have repo available where you got IdentityServer4 working with Finbuckle? I'm trying to implement the same.

Sorry I don't have any repo but if you have the same problem as mine then answer is also posted.
