### ISSUE TITLE
Data Isolation: DataContext ConnectionString null

### ISSUE THREAD

**Issue by joashTheCoder** [Finbuckle/Finbuckle.MultiTenant#251]
in the Documentation it says that the connectionString will be specified in the OnConfiguring like so

 protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlite(ConnectionString);
            base.OnConfiguring(optionsBuilder);
        }

and i also followed the dataIsolation sample

this is inside setupDb()

var ti = new TenantInfo("tenant-ante-d043favoiaw", null, null, "Data Source=Ante.db", null);
            using (var db = new DataContext(ti))
            {
                db.Database.EnsureDeleted();
                db.Database.EnsureCreated();
                db.Warehouses.Add(new Domain.Warehouse { Id = new Guid(), Name = "Quezon City warehouse ", Description = "random", Address = "fulladdress"});
                db.Warehouses.Add(new Domain.Warehouse { Id = new Guid(), Name = "Makati City warehouse ", Description = "random", Address = "fulladdress"});
                db.Warehouses.Add(new Domain.Warehouse { Id = new Guid(), Name = "Cebu City warehouse ", Description = "random", Address = "fulladdress"});
                db.SaveChanges();
            }

but when i try to do a migration theres a  Null reference exception that says the connection string is null in the OnConfiguring method

**Comment by AndrewTriesToCode** [comment]
@joashTheCoder 

Hi, for migration look at the code I have to trigger it in `Program.cs` in that sample. You'll see it doesn't refer to SetupDb at all.

Alternatively you could use a design time factory for the database context. The IdentityDataIsolation samples shows how to use this approach. Looks for the DesignTimeFactory.cs file.

**Comment by hhuseyinpay** [comment]
Hey @AndrewTriesToCode, first of all, thank you for developing this great library! I'm planning to use the library for my project. For now, I'm testing hoststrategy with IdentityDataIsolation. But I cannot run the dotnet ef migrations add command because it gave an error like: "System.NullReferenceException  .... Data/ApplicationDbContext.cs:line 19"

**Comment by joashTheCoder** [comment]
Hi @AndrewTriesToCode 
I added that also in my program.cs but for some reason the connection string is still null.

public static void Main(string[] args)
        {
            var host = CreateHostBuilder(args).Build();

            var env = host.Services.GetService<IWebHostEnvironment>();
            if (env.EnvironmentName == "Development")
            {
                using (var db = new DataContext(new TenantInfo(null, null, null, "Data Source=sample.db", null)))
                {
                    db.Database.MigrateAsync().Wait();
                }

                using (var db = new DataContext(new TenantInfo(null, null, null, "Data Source=test.db", null)))
                {
                    db.Database.MigrateAsync().Wait();
                }
            }
            
            host.Run();
        }

**Comment by AndrewTriesToCode** [comment]
I'll take a closer look -- do you have a repo I can clone to see the project?

Also are you doing the migration from the CLI when you get the error?

**Comment by joashTheCoder** [comment]
Hi @AndrewTriesToCode, thank you for replying.
this is my repo: https://github.com/joashTheCoder/AnteWebAPI

yes, i'm doing the migration from the CLI. this is what i type : dotnet ef migrations add InitialCreate -p Persistence/ -s API/

**Comment by AndrewTriesToCode** [comment]
hi @joashTheCoder , cool project you have going on there. I like your organization.

I see now that you want your dbcontext in a different project than your API and you also figured out the startup and project parameters to `dotnet ef`.

Here is what I suggest:
- remove the automigration code from `program.cs` in your api project -- I don't think you want to trigger migrations when you start the API and even so it won't put it into the correct project by default.
- Check out design time factories: https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/dbcontext-creation#from-a-design-time-factory
I think you will want this in your persistence project. In your factory when you "new" the data context just create a tenant info and hardcode the connection string there. Migrations will use that context.
- You will still want to use the API or application as the startup project for the `dotnet ef` command, but I don't think you will need anything special in those projects. The need for a startup project is a design limitation in EFCore.

Let me know how it goes!

**Comment by joashTheCoder** [comment]
HI @AndrewTriesToCode,
it works! thank you!

**Comment by hbermani** [comment]
Just passing by and noticed this thread.... I wonder if you considered using DevOps pipeline and dacpac files to manage database migrations across environments.

**Comment by AndrewTriesToCode** [comment]
@hbermani I haven't looked into that, thanks for the recommendation.
