### ISSUE TITLE
Finbuckle 6.0.0 prep

### ISSUE THREAD

**Issue by AndrewTriesToCode** [Finbuckle/Finbuckle.MultiTenant#253]
Hello,

I'm planning to release Finbuckle 6.0.0 soonish.

The code is in the `release-6.0.0-dev` branch.

I've uploaded Finbuckle.MultiTenant version `6.0.0-preview1` to Nuget.org so you can take a look at the changes.
**Preview 1 Notes**
- Entire library has been rewritten to support custom tenant information.
  - `AddMultiTenant`, `UseMultiTenant`, and many other types/functions now have a `TTenantInfo` generic parameter that is required. It must be a "newable" reference that implemented `ITenantInfo`.
  - `ITenantInfo` includes only Id, Identifier, Name, and ConnectionString properties. Note that the Items collection is not there.
  - A default `TenantInfo` class is provided which implements `ITenantInfo` without adding anything else. Most samples and tests use this default. This does not use a required constructor to initialize a new instance.
  - You can implement your own `ITenantInfo` to add anything you want to it.
  - Things like `EFCoreStore`, `ConfigurationStore`, and `HttpRemoteStore` should handle all the properties on your custom `ITenantInfo` if you keep it simple enough. You may potentially also use attributes to control how those stores serialize and deserialize your fields.
  - Samples are updated. AuthenticationOptionsSample uses a custom `ITenantInfo` to store the default Challenge scheme for each tenant.
  - Docs **not** yet updated.
- Simplified MultiTenantContext
  - Removed `IMultiTenantContext` so now we just have `MultiTenantContext<TTenantInfo>` which has getters and setters for all of its properties.
  - These properties no longer have a reference back to the parent `MultiTenantContext<TTenantInfo>`.

**Preview 2 notes**
- `UseMultiTenant` no longer needs `TTenantInfo` generic parameter.
- Refactor tenant resolution logic into ITenantResolver.
- Mulitple strategies and stores can be registered.
  - They are run in order registered.
  - Multiple of the same type can be registered (mainly useful for DelegateStrategy)
  - The first strategy / store combo to return a TenantInfo is used.
- Refactors the middleware to use an ITenantResolver.
- Added IMultiTenantContext<TTenantInfo>.
- netcoreapp3.0 target removed (.Net Core 3.0 is out of support by Microsoft)
- `MultiTenantDbContext` now has direct access to `TenantInfo`
- Various other changes and fixes.
  - Per-tenant options broke in preview1, should be working now.

**Preview 3 notes**
- Better Blazor support
  - `UseMultiTenant` once again requires `TTenantInfo` generic parameter (because reasons)
- Refactored `InMemoryStore` to use `InMemoryStoreOptions` which allow for simpler configuration. 
  - `WithInMemoryStore` overload takes and acting to configure the options. The options specify case sensitivity and the seeded tenants in the store.
- Added session strategy which uses a session variable to get tenant identifier.
  - Useful in conjunction with an expensive strategy to skip it on subsequent requests or to not rely on host/url structure.
- RemoteAuthentication strategy changes
  - renamed to `RemoteAuthenticationCallbackStrategy`
  - minor performance improvement
  - register as normal strategy using `WithRemoteAuthenticationCallbackStrategy` (it's a mouthful)
  - support added for OpenID Connect RP to OP forward sign out
  - theoretical support for WS-Federation authentication
  - need to update docs to explain when this should or shouldn't be used
- Removed items marked obsolete
  - `InMemoryStore` loading from config
  - some old `MultiTenantIdentityDbContext` helper classes, etc...
  - Will probably move the rest of the Stores/Strategies to this options approach.
- Removed fallback strategy
  - Alternative: register a final static strategy for same effect.

**Preview 4 notes**
- Added overload of `AddMultiTenant` which exposes a `MultiTenantOptions` instance in which you can add to a list of strings of ignored identifiers.
- Change nuget package scheme.
  - Projects should reference the specific package(s) needed
    - class library - Finbuckle.MultiTenant
    - ASP.NET Core / Blazor - Finbuckle.MultiTenant.AspNetCore
    - EFCore - Finbuckle.MultiTenant.EntityFrameworkCore
  - This will allow more flexibility as more packages are added (ie EF6 or Azure related functionality)
  - Finbuckle.MultiTenant will replace Finbuckle.MultiTenant.Core
    - Finbuckle.MultiTenant.Core will no longer be used or updated
- Maybe some per-tenant options enhancements
- ~~Maybe add custom tenant support to EFCore code~~
  - ~~currently you can just cast the `ITenantInfo` to a custom tenant info type~~
  - ~~would like to have it formalized via generic `TTenantInfo` parameters similar to the rest of the library~~
- ~~Maybe support for Azure App Configuration feature flags~~

The crossed out items didn't pan out for this release. They will still be considered for the future.

*Preview 5 Notes*:
- No longer need to pass `TenantInfo` type to `UseMultiTenant()`

- Added `WithPerTenantAuthentication()`

> The `WithPerTenantAuthentication()` method can be called after
> `AddMultiTenant<T>()` and uses conventions to configure common authentication
> options based on public properties of the `ITenantInfo` type parameter.
> 
> The following happens when `WithPerTenantAuthentication()` is called:
> - The default challenge scheme is set to the `ChallengeScheme` property
>   of the `ITenantInfo` implementation.
> - Cookie names are appended with the tenant id.
> - 'Path' for cookie authentication is set to the `CookiePath` property
>   of the `ITenantInfo` implementation.
> - 'LoginPath' for cookie authentication is set to the `CookieLoginPath` property
>   of the `ITenantInfo` implementation.
> - 'LogoutPath' for cookie authentication is set to the `CookieLogoutPath`
>   property of the `ITenantInfo` implementation.
> - 'AccessDeniedPath' for cookie authentication is set to the
>   `CookieAccessDeniedPath` property of the `ITenantInfo` implementation.
> - Seveal internal services are registered to support remote authentication such
>   as OAuth 2.0 and OpenID Connect.
> - `Authority` for OpenID connect authentication is set to the
>   `OpenIdConnectAuthority` property of the `ITenantInfo` implementation.
> - `ClientId` for OpenID connect authentication is set to the
>   `OpenIdConnectClientId` property of the `ITenantInfo` implementation.
> - `ClientSecret` for OpenID connect authentication is set to the
>   `OpenIdConnectClientSecret` property of the `ITenantInfo` implementation.
> 
> If the `ITenantInfo` implementation lacks one of the properties there is no
> impact on the respective authentication property.
> 
> By changing the default challenge per-tenant, the user can be redirected to a
> different scheme as needed. Combined with a per-tenant OpenID Connect authority,
> this can route to shared or tenant specific authentication infrastructure.
> 
> The `CookiePath`, `CookieLoginPath`, `CookieLogoutPath`, and
> `CookieAccessDeniedPath` properties can use a template format where `__tenant__`
> will be replaced with the identifier for each specific tenant. For example, a
> `CookieLoginPath` of "/\_\_tenant\_\_/Identity/Account/Login" will result in
> "/initech/Identity/Account/Login" for the Initech tenant.

- Updated related docs and samples
- Fixed a few bugs

**Comment by wojtj** [comment]
Thanks Andrew, a very elegant solution for ITenantInfo.

Do the constructors for MultiTenantDbContext need adjusting? My default constructors for my AppDbContext now look like:

`public ApplicationDbContext(ITenantInfo tenantInfo) : base((TenantInfo)tenantInfo) { }`

 `public ApplicationDbContext(ITenantInfo tenantInfo, DbContextOptions<ApplicationDbContext> options) : base((TenantInfo)tenantInfo, options) { }`

but I am now getting a runtime error:

> AggregateException: Some services are not able to be constructed (Error while validating the service descriptor 'ServiceType: MyApp.Data.ApplicationDbContext Lifetime: Scoped ImplementationType: MyApp.Data.ApplicationDbContext': No constructor for type 'MyApp.Data.ApplicationDbContext' can be instantiated using services from the service container and default values.)

My ITenantInfo implementation is copied from the new version of TenantInfo.

Any thoughts?

**Comment by clinically-au** [comment]
Thanks, Andrew. A very elegant solution for ITenantInfo

Do the constructors for MultiTenantIdentityDbContext and MultiTenantDbContext need to be adjusted to expect an ITenantInfo object rather than TenantInfo?

**Comment by AndrewTriesToCode** [comment]
@wojtj yeah I need to register ITenantInfo in DI. I’ll upload a new version today.

I've gone back and forth on whether to take the `TTenantInfo` approach into the multi tenant EFCore area of the library. I've decided to leave it as-is, e.g. dependent on `ITenantInfo` for now. Users have the option of course to inject any `ITenantInfo` implementation they want.

**Comment by AndrewTriesToCode** [comment]
@wojtj on taking a closer look I realize that most of the multi tenant encore stuff was still reliant on `ITenantInfo`. After going back and forth a few times I've decided to extend the generic `TTenantInfo` approach here as well. That will come in preview2.

**Comment by ZedZipDev** [comment]
Thanx, it is great.
What about "how to use in Blazor" example? It may be useful

**Comment by win32nipuh** [comment]
Btw, I go to branch release-6.0.0-dev and
see the 
README.md Finbuckle.MultiTenant 5.0.4
CHANGELOG.md | release: v5.0.4

**Comment by AndrewTriesToCode** [comment]
@win32nipuh Thansk for pointing that out. I plan to do preview2 this weekend and will update the readme.

@Oleg26Dev  there is a blazor sample in the other open pull request. I've asked @Hammurabidoug if he wants to adapt that sample for this PR. His PR parameterized one of the multitenant stores for a custom tenantinfo -- this PR effectively does that for the entire library.

**Comment by AndrewTriesToCode** [comment]
Preview2 update - it's taking longer than I thought. I am refactoring the middleware code and it is taking longer than I thought to do it right.

**Comment by AndrewTriesToCode** [comment]
Just uploaded preview2 to Nuget.

- Refactor tenant resolution logic into ITenantResolver.
- Mulitple strategies and stores can be registered.
  - They are run in order registered.
  - Multiple of the same type can be registered (mainly useful for DelegateStrategy)
  - The first strategy / store combo to return a TenantInfo is used.
- Refactors the middleware to use an ITenantResolver.
- Added IMultiTenantContext<TTenantInfo>.
- netcoreapp3.0 target removed (.Net Core 3.0 is out of support by Microsoft)
- `MultiTenantDbContext` now has direct access to `TenantInfo`
- Various other changes and fixes.
  - Per-tenant options broke in preview1, should be working now.

**Comment by mikeandersun** [comment]
Please consider caching the `TenantInfo`.

**Comment by AndrewTriesToCode** [comment]
hi @mikeandersun 

Can you give me some more detail on what you have in mind? In the current build the tenant info is created once per request and reused for subsequent accesses during the request. I'm also planning a few things that will also help performance:

-  a session based strategy that will offer low cost tenant resolution on further requests after an initial request uses a more expensive strategy/store
- support for the ASP.NET Core local / remote cache use by stores. This can already be done today but I could build it in to make it easier.

**Comment by AndrewTriesToCode** [comment]
Just uploaded preview3:

**Preview 3 notes**
- Better Blazor support
  - `UseMultiTenant` once again requires `TTenantInfo` generic parameter (because reasons)
- Refactored `InMemoryStore` to use `InMemoryStoreOptions` which allow for simpler configuration. 
  - `WithInMemoryStore` overload takes and acting to configure the options. The options specify case sensitivity and the seeded tenants in the store.
- Added session strategy which uses a session variable to get tenant identifier.
  - Useful in conjunction with an expensive strategy to skip it on subsequent requests or to not rely on host/url structure.
- RemoteAuthentication strategy changes
  - renamed to `RemoteAuthenticationCallbackStrategy`
  - minor performance improvement
  - register as normal strategy using `WithRemoteAuthenticationCallbackStrategy` (it's a mouthful)
  - support added for OpenID Connect RP to OP forward sign out
  - theoretical support for WS-Federation authentication
  - need to update docs to explain when this should or shouldn't be used
- Removed items marked obsolete
  - `InMemoryStore` loading from config
  - some old `MultiTenantIdentityDbContext` helper classes, etc...
  - Will probably move the rest of the Stores/Strategies to this options approach.
- Removed fallback strategy
  - Alternative: register a final static strategy for same effect.

Upcoming preview4 items:
- Documentation review (needs a lot of work)
- Change nuget package scheme.
  - Projects should reference the specific package(s) needed
    - class library - Finbuckle.MultiTenant
    - ASP.NET Core / Blazor - Finbuckle.MultiTenant.AspNetCore
    - EFCore - Finbuckle.MultiTenant.EntityFrameworkCore
  - This will allow more flexibility as more packages are added (ie EF6 or Azure related functionality)
  - Finbuckle.MultiTenant will replace Finbuckle.MultiTenant.Core
    - Finbuckle.MultiTenant.Core will no longer be used or updated
- Maybe some per-tenant options enhancements
- Maybe add custom tenant support to EFCore code
  - currently you can just cast the `ITenantInfo` to a custom tenant info type
  - would like to have it formalized via generic `TTenantInfo` parameters similar to the rest of the library
- Maybe support for Azure App Configuration feature flags

**Comment by AndrewTriesToCode** [comment]
Preview4 is up. The new packaging scheme will definitely require you to adjust your nuget references as outlined below.

**Preview 4 notes**
- Added overload of `AddMultiTenant` which exposes a `MultiTenantOptions` instance in which you can add to a list of strings of ignored identifiers.
- Change nuget package scheme.
  - Projects should reference the specific package(s) needed
    - class library - Finbuckle.MultiTenant
    - ASP.NET Core / Blazor - Finbuckle.MultiTenant.AspNetCore
    - EFCore - Finbuckle.MultiTenant.EntityFrameworkCore
  - This will allow more flexibility as more packages are added (ie EF6 or Azure related functionality)
  - Finbuckle.MultiTenant will replace Finbuckle.MultiTenant.Core
    - Finbuckle.MultiTenant.Core will no longer be used or updated
- Maybe some per-tenant options enhancements
- ~~Maybe add custom tenant support to EFCore code~~
  - ~~currently you can just cast the `ITenantInfo` to a custom tenant info type~~
  - ~~would like to have it formalized via generic `TTenantInfo` parameters similar to the rest of the library~~
- ~~Maybe support for Azure App Configuration feature flags~~

The crossed out items didn't pan out for this release. They will still be considered for the future.

**Comment by AndrewTriesToCode** [comment]
Just uploaded preview 5. I don't expect any feature changes from this point. Just fixes, samples, and doc updates. Release 6 itself will still need updated docs before official release.

*Preview 5 Notes*:
- No longer need to pass `TenantInfo` type to `UseMultiTenant()`

- Added `WithPerTenantAuthentication()`

> The `WithPerTenantAuthentication()` method can be called after
> `AddMultiTenant<T>()` and uses conventions to configure common authentication
> options based on public properties of the `ITenantInfo` type parameter.
> 
> The following happens when `WithPerTenantAuthentication()` is called:
> - The default challenge scheme is set to the `ChallengeScheme` property
>   of the `ITenantInfo` implementation.
> - Cookie names are appended with the tenant id.
> - 'Path' for cookie authentication is set to the `CookiePath` property
>   of the `ITenantInfo` implementation.
> - 'LoginPath' for cookie authentication is set to the `CookieLoginPath` property
>   of the `ITenantInfo` implementation.
> - 'LogoutPath' for cookie authentication is set to the `CookieLogoutPath`
>   property of the `ITenantInfo` implementation.
> - 'AccessDeniedPath' for cookie authentication is set to the
>   `CookieAccessDeniedPath` property of the `ITenantInfo` implementation.
> - Seveal internal services are registered to support remote authentication such
>   as OAuth 2.0 and OpenID Connect.
> - `Authority` for OpenID connect authentication is set to the
>   `OpenIdConnectAuthority` property of the `ITenantInfo` implementation.
> - `ClientId` for OpenID connect authentication is set to the
>   `OpenIdConnectClientId` property of the `ITenantInfo` implementation.
> - `ClientSecret` for OpenID connect authentication is set to the
>   `OpenIdConnectClientSecret` property of the `ITenantInfo` implementation.
> 
> If the `ITenantInfo` implementation lacks one of the properties there is no
> impact on the respective authentication property.
> 
> By changing the default challenge per-tenant, the user can be redirected to a
> different scheme as needed. Combined with a per-tenant OpenID Connect authority,
> this can route to shared or tenant specific authentication infrastructure.
> 
> The `CookiePath`, `CookieLoginPath`, `CookieLogoutPath`, and
> `CookieAccessDeniedPath` properties can use a template format where `__tenant__`
> will be replaced with the identifier for each specific tenant. For example, a
> `CookieLoginPath` of "/\_\_tenant\_\_/Identity/Account/Login" will result in
> "/initech/Identity/Account/Login" for the Initech tenant.

- Updated related docs and samples
- Fixed a few bugs

**Comment by Hawxy** [comment]
@AndrewTriesToCode FYI the EFCoreStore is currently broken due to incompatible lifetimes between `IMultiTenantStore` and `ITenantResolver`. Trying to run the `EFCoreStoreSample` exposes the relevant problem.

**Comment by AndrewTriesToCode** [comment]
@Hawxy Thanks for letting me know!

**Comment by AndrewTriesToCode** [comment]
I have fixed the issue @Hawxy mentioned above but it's not worth another preview release.

As a workaround after your call to `AddMultiTenant<T>()` and its chained builders add these two lines:

```cs
services.Replace(new ServiceDescriptor(typeof(ITenantResolver<TenantInfo>), typeof(TenantResolver<TenantInfo>), ServiceLifetime.Scoped));
services.Replace(new ServiceDescriptor(typeof(ITenantResolver), sp => sp.GetRequiredService<ITenantResolver<TenantInfo>>(), ServiceLifetime.Scoped));
```

They might require some `using` statements to pull in the right namespace and of course sub in your own class for `TenantInfo` if you aren't using the default one.
