### ISSUE TITLE
IdentityDataIsolation with Host Strategy

### ISSUE THREAD

**Issue by hhuseyinpay** [Finbuckle/Finbuckle.MultiTenant#256]
Hi, I'm trying to run the IdentityDataIsolation example with the host strategy. I made the following changes:
![Screen Shot 2020-05-04 at 15 42 55](https://user-images.githubusercontent.com/14811488/80966897-17f02a80-8e1e-11ea-8e96-965c7f8f4d8a.png)
![Screen Shot 2020-05-04 at 15 43 01](https://user-images.githubusercontent.com/14811488/80966903-1b83b180-8e1e-11ea-89ee-12f62382b928.png)
![Screen Shot 2020-05-04 at 15 43 17](https://user-images.githubusercontent.com/14811488/80966904-1c1c4800-8e1e-11ea-9ed4-0ee9ba683a43.png)

It throws the following error:
![Screen Shot 2020-05-04 at 15 44 53](https://user-images.githubusercontent.com/14811488/80966999-51289a80-8e1e-11ea-9b01-1edec90ceb0b.png)

**Comment by ZedZipDev** [comment]
What NuGet packages you have installed in the project?

**Comment by AndrewTriesToCode** [comment]
@hhuseyinpay My guess is it is related to the host matching template here:
```
.WithHostStrategy("*.__tenant__.?)
```

What is the url for the request throwing the error? Also I don't see it in your screenshot, but do you still have the default connection string value in the json for the configuration store?

```
"Finbuckle:MultiTenant:Stores:ConfigurationStore": {
    "Defaults": {
      "ConnectionString": "Data Source=Data/SharedIdentity.db"
    },
    "Tenants": [
      {
        "Id": "finbuckle",
        "Identifier": "finbuckle",
        "Name": "Finbuckle"
      },
      {
        "Id": "megacorp",
        "Identifier": "megacorp",
        "Name": "MegaCorp"
      },
      {
        "Id": "initech",
        "Identifier": "initech",
        "Name": "Initech LLC",
        "ConnectionString": "Data Source=Data/InitechIdentity.db"
      }
    ]
  }
```

**Comment by ZedZipDev** [comment]
I had the same strange exception.
Install NuGets:
Microsoft.EntityFrameworkCore
Microsoft.EntityFrameworkCore.Sqlite
and try again. After it this exception can disappear.

**Comment by hhuseyinpay** [comment]
@Oleg26Dev I tried but it did not work for me:
![Screen Shot 2020-05-07 at 12 16 43](https://user-images.githubusercontent.com/14811488/81277180-bbc71980-905c-11ea-9c95-635a7257e069.png)

@AndrewTriesToCode I'm getting the error at https://localhost:5001/Identity/Account/Register and .../Login 
Yes, I screenshotted just my edits. So other parts are the same with IdentityDataIsolation example.
![Screen Shot 2020-05-07 at 12 19 03](https://user-images.githubusercontent.com/14811488/81277344-f630b680-905c-11ea-9a73-f5cb09df84bc.png)

**Comment by hhuseyinpay** [comment]
I find the problem. When using "*.__tenant__.?" strategy URL should end with  .com etc. So I added 
 localhost.com to the hosts file and it worked.
