### ISSUE TITLE
Use EF 6?

### ISSUE THREAD

**Issue by michaelkaboro** [Finbuckle/Finbuckle.MultiTenant#259]
Would be possible to use EF 6 for the Database context?

If not currently possible, do you think adding this functionality would be complicated as I see you have used EF Core mostly throughout the definition of MultiTenantDbContext.

If it wouldn't require a big change in the library, I would wish to include this, your guidance would very much be appreciated.

**Comment by AndrewTriesToCode** [comment]
hi @michaelkaboro 

I don't think it would be that complicated--I'm not aware that I am using anything that is not in EF6. The bigger challenge is that I use MacOS so I can't easily try to do an EF6 version. I could install Windows 10 easily enough I guess. It's probably something not in the next release.

**Comment by michaelkaboro** [comment]
Ok, I will work on this and send a pull request. 

I don't think you would need to install Windows 10 though, for this, EF6 from version 6.4 is .net core compatible. Or is there something I am missing?

**Comment by AndrewTriesToCode** [comment]
@michaelkaboro  No, I didn't realize EF6 was not .Net Core compatible. I'd welcome a pull request. I wonder if we should add a new project e.g. Finbuckle.MultiTenant.EntityFramework6.

**Comment by michaelkaboro** [comment]
EF6 v6.3 onwards is compatible with .net Core. Let me work on the EF6 version and do a pull request.

**Comment by AndrewTriesToCode** [comment]
Thanks @michaelkaboro 

Do me a favor and submit the pull request against the 6.0 dev branch. Also please set it up as a new Project in the solution, similar to the EFCore one. Hopefully not many changes are needed and the tests can all be carried over!

**Comment by AndrewTriesToCode** [comment]
Doing some cleanup -- going to close this one out as we're not planning to target EF6 at this time,

**Comment by enkodellc** [comment]
@AndrewTriesToCode  Is the a time frame where you do plan on targeting EF6 / .net 6? Thanks sharing your project.

**Comment by AndrewTriesToCode** [comment]
Working on it now, planning to release the same day .NET 6 drops officially

**Comment by AndrewTriesToCode** [comment]
Just to be clear, I'm only testing out with EF Core 6, not legacy EF6
