### ISSUE TITLE
Add a SQL based IMultiTenantStore

### ISSUE THREAD

**Issue by AndrewTriesToCode** [Finbuckle/Finbuckle.MultiTenant#26]
As a basic SQL based tenant store using Entity Framework.

**Comment by Cpcrook** [comment]
Have you started poking at this yet?  I may trial an implementation later today.

**Comment by AndrewTriesToCode** [comment]
@Cpcrook I have a simple one-off implementation for a test project--I'll post it here this evening, By all means please give it a shot. Ideally it would be a flexible solution. Maybe it should be called EFCoreMultiTenantStore and would setup like `services.AddMultiTenant().WithEFCoreStore<TenantStoreDbContext>()....` or something similar. I'm not the best way to tell it which tables/entities to use to get the TenantContext though.

**Comment by AndrewTriesToCode** [comment]
@Cpcrook sorry I wasn't able to find the previous implementation of this I said I would post here.

**Comment by AndrewTriesToCode** [comment]
Implemented in PR #73
