### ISSUE TITLE
What is incorrect in WithPerTenantOptions in v6 vs v5?

### ISSUE THREAD

**Issue by ZedZipDev** [Finbuckle/Finbuckle.MultiTenant#261]
I am trying to use the  approach described in issue

"Get IOptions with a service class"
https://github.com/Finbuckle/Finbuckle.MultiTenant/issues/243

to read additional config parameters in my Blazor app+Finbuckle v6.
Could you please say me, why it does not work:
I get this piece of code

services.AddBlazorMultiTenant().
WithStore<ConfigurationStore<DerivedTenantInfo>>(ServiceLifetime.Singleton)
.WithHostStrategy(@"__tenant__.*")
.WithPerTenantOptions<CustomOptions, DerivedTenantInfo>(t => t.CustomOptions);  

and replaced with this:

services.AddMultiTenant<DerivedTenantInfo>()
.WithConfigurationStore()
.WithHostStrategy(tenantSettings.HostTemplate)
.WithPerTenantOptions<S3ConfigOptions>((options, tenantInfo) =>
{
tenantInfo.S3CustomOptions = options;// <-------debug point is not reached
});

But the S3CustomOptions is already null and I the debug point is not reached.
What is incorrect?

**Comment by AndrewTriesToCode** [comment]
@Oleg26Dev 
I'm looking into this. Thanks for reporting it.

**Comment by AndrewTriesToCode** [comment]
Do you have a GitHub project I can look at?

Generally with per tenant options you would use the tenant information to modify the options -- looks like you have it the other way around here.

**Comment by ZedZipDev** [comment]
I need to read some additional tenant specific settings like Connection string.
I have tried to build my project using approach suggested by Doug in this sample
https://github.com/Hammurabidoug/Finbuckle.MultiTenant/tree/master/samples/ASP.NET%20Core%203/BlazorSample

But he has the additional project in the Finbuckle and extension. 
Andrew, may be v6 allows to do the same but simpler? 
I mean: to create DerivedTenantInfo with additional fields, to read additional config settings like
 ```
"Finbuckle:MultiTenant:Stores:ConfigurationStore": {
    "Defaults": {
      "ConnectionString": "Datasource=sample.db",
      "CustomOptions": {
        "Value1": "Default value 1",
        "Value2": "Default value 2"
      }
    },
    "Tenants": [
      {
        "Id": "tenant-megacorp-d043favoiaw",
        "Identifier": "megacorp",
        "Name": "MegaCorp"
      },
      {
        "Id": "tenant-finbuckle-d043favoiaw",
        "Identifier": "finbuckle",
        "Name": "Finbuckle",
        "CustomOptions": {
          "Value1": "Finbuckle value 1"
        }
      },
      {
        "Id": "tenant-initech-341ojadsfa",
        "Identifier": "initech",
        "Name": "Initech LLC",
        "CustomOptions": {
          "Value2": "Initech LLC value 2"
        }
      }
    ]
 
```

**Comment by AndrewTriesToCode** [comment]
I figured out the problem and will have this fixed in preview2 out today or tomorrow.

**Comment by AndrewTriesToCode** [comment]
@Oleg26Dev I just uploaded preview2 to Nuget -- this issue should be fixed.
