### ISSUE TITLE
AWS Cognito

### ISSUE THREAD

**Issue by gurdeepsira** [Finbuckle/Finbuckle.MultiTenant#262]
Hi,
I am just exploring Finbuckle and it looks good. 

This is not an issue but more a request for help. My multi-tenant app is using AWS Cognito. What needs to be done in Finbuckle to work with this? Is it possible to see any worked examples? 

Thanks!

**Comment by AndrewTriesToCode** [comment]
hi @gurdeepsira 

I'm not to familiar with Cognito. Is there a .Net Core code sample you can point me to that will give me an idea of where this library might be helpful?
