### ISSUE TITLE
Have MultiTenantContext implement IMultiTenantContext in release-6.0.0-dev

### ISSUE THREAD

**Issue by Hammurabidoug** [Finbuckle/Finbuckle.MultiTenant#263]
I am currently referencing the project files versus NuGet for the release-6.0.0-dev because I need the MultiTenantContext<TTenantInfo> to implement an IMultiTenantContext<TTenantInfo> interface in order to support testing mocks and alternate implementations of the context. I request switching references from a concrete class to an interface.

**Comment by AndrewTriesToCode** [comment]
Hi I will plan to add that in. Out of curiosity what sort of alternative implementations do you use?

**Comment by Hammurabidoug** [comment]
I only have different (Blazor-specific) implementations of the middleware and the accessor, so, for me, an IMultiTenantContext interface would be helpful for supporting unit testing mocks.

`

        [Fact]
        public void SetWithPerTenantOptionsDerivedTenantInfo()
        {
            // Arrange
            var expectedString = Guid.NewGuid().ToString();
            var expectedUri = new Uri("http://test.com");
            var expectedGuid = Guid.NewGuid();

            var services = new ServiceCollection();
            var accessor = new Mock<IMultiTenantContextAccessor<TenantInfoFake>>();
            var contextMock = new Mock<IMultiTenantContext<TenantInfoFake>>();
            contextMock.Setup(c => c.TenantInfo).Returns(new TenantInfoFake
            {
                Options = new OptionsFake
                {
                    PublicStringGetSetProperty = expectedString,
                    PublicUriGetSetProperty = expectedUri,
                    PublicGuidGetSetProperty = expectedGuid
                }
            });
            accessor.Setup(a => a.MultiTenantContext).Returns(contextMock.Object);
            services.AddSingleton(accessor.Object);
            var builder = new FinbuckleMultiTenantBuilder<TenantInfoFake>(services);
            builder.WithPerTenantOptions<OptionsFake, TenantInfoFake>(t => t.Options);
            var sp = services.BuildServiceProvider();

            // Act
            var optionsAccessor = sp.GetRequiredService<IOptions<OptionsFake>>();
            var options = optionsAccessor.Value;

            // Assert
            Assert.Equal(expectedString, options.PublicStringGetSetProperty);
            Assert.Equal(expectedUri, options.PublicUriGetSetProperty);
            Assert.Equal(expectedGuid, options.PublicGuidGetSetProperty);
        }
`

**Comment by AndrewTriesToCode** [comment]
@Hammurabidoug I just uploaded preview2 which has `IMultiTenantContext<TTenantInfo>`
