### ISSUE TITLE
DataIsolationSample cannot be built in v6.0.0-preview2

### ISSUE THREAD

**Issue by ZedZipDev** [Finbuckle/Finbuckle.MultiTenant#266]
I have tried to build the sample DataIsolationSample 

1.   <PackageReference Include="Finbuckle.MultiTenant" Version="6.0.0-preview1" /> - OK
2.  <PackageReference Include="Finbuckle.MultiTenant" Version="6.0.0-preview2" /> Error:

> `\DataIsolationSample\Startup.cs(43,17,43,43): error CS1061: 'IApplicationBuilder' does not contain a definition for 'UseMultiTenant' and no accessible extension method 'UseMultiTenant' accepting a first argument of type 'IApplicationBuilder' could be found 

`

**Comment by AndrewTriesToCode** [comment]
Thanks @Oleg26Dev Can you please post the csproj file here?

Please try `dotnet clean`, `dotnet restore --force`, and rebuild. Still get the issue?

**Comment by ZedZipDev** [comment]
```
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="3.1.1" />
    <PackageReference Include="Finbuckle.MultiTenant" Version="6.0.0-preview2" />
  </ItemGroup>

  <ItemGroup>
    <!-- <ProjectReference Include="..\..\..\src\Finbuckle.MultiTenant\Finbuckle.MultiTenant.csproj" /> -->
  </ItemGroup>
</Project>

```

**Comment by AndrewTriesToCode** [comment]
If you comment out the package reference and uncomment the project reference does it compile?

**Comment by ZedZipDev** [comment]
sorry, my mistake, just will repeat
Now I cannot build the Multitenant from sources because by some reasons it has code used namespaces from my other test project:

```
Finbuckle.MultiTenant\src\Finbuckle.MultiTenant.EntityFrameworkCore\**MultiTenantIdentityDbContext**.cs(42,56,42,76): error CS0400: The type or namespace name '**DataIsolationBlazor2**' could not be found in the global namespace (are you missing an assembly reference?)
3>G:\MyProjects\_CrossPlatform\Multitenancy\_MT\Finbuckle.MultiTenant\src\Finbuckle.MultiTenant.EntityFrameworkCore\MultiTenantIdentityDbContext.cs(36,25,36,45): error CS0400: The type or namespace name 'DataIsolationBlazor2' could not be found in the global namespace (are you missing an assembly reference?)

```

**Comment by ZedZipDev** [comment]
Ok, it works.
I have cloned GIT repository to clear space, it works with project and using NuGet package too.
Also, as you wrote:
>dotnet clean
>dotnet restore --force
and rebuild

But again my recent question: how to get additional config parameters like ConnectionString,ConnectionString2,  S3/Minio connection parameters?
