### ISSUE TITLE
Typo in the documentation

### ISSUE THREAD

**Issue by ZedZipDev** [Finbuckle/Finbuckle.MultiTenant#268]
There 
https://www.finbuckle.com/MultiTenant/Docs/EFCore#deriving-from-multitenantdbcontext
need to remove ';' because it gives syntax error in the code

```
public class MyDbContext : DbContext, IMultiTenantDbContext
{
    ...
    public TenantInfo TenantInfo { get; }
    public TenantMismatchMode TenantMismatchMode { get; }//;//<------remove ;
    public TenantNotSetMode TenantNotSetMode { get; }//;//<------remove ;
    ...
}

```

**Comment by AndrewTriesToCode** [comment]
Thanks @Oleg26Dev 

With v6 I've got a lot of documentation updating to do. Helping me with the typos is much appreciated.

**Comment by AndrewTriesToCode** [comment]
If you want to please go ahead and submit a PR for any types you find. They should be quick and easy to merge into the dev-v6.0.0 branch

**Comment by ZedZipDev** [comment]
Ок, done, I have create a pull-request. 
Also, I have yet some other notes about typos and about some classes using.
Andrew, by the way, I have detected this trying to resolve my problem with DbContext.
Please take a look at this topic :
https://github.com/Finbuckle/Finbuckle.MultiTenant/issues/248
