### ISSUE TITLE
6.0.0-preview3 IdentityDataIsolationSample throws except

### ISSUE THREAD

**Issue by Hammurabidoug** [Finbuckle/Finbuckle.MultiTenant#278]
When attempting to build and run the IdentityDataIsolationSample using the 6.0.0-preview3 branch, the following exception is thrown: 

> "'Some services are not able to be constructed (Error while validating the service descriptor 'ServiceType: IdentityDataIsolationSample.Data.ApplicationDbContext Lifetime: Scoped ImplementationType: IdentityDataIsolationSample.Data.ApplicationDbContext': No constructor for type 'IdentityDataIsolationSample.Data.ApplicationDbContext' can be instantiated using services from the service container and default values.)"

This is causing all the other Identity classes that require injection of the ApplicationDbContext. The full Aggregate exception is:

> System.AggregateException: 'Some services are not able to be constructed (Error while validating the service descriptor 'ServiceType: IdentityDataIsolationSample.Data.ApplicationDbContext Lifetime: Scoped ImplementationType: IdentityDataIsolationSample.Data.ApplicationDbContext': No constructor for type 'IdentityDataIsolationSample.Data.ApplicationDbContext' can be instantiated using services from the service container and default values.) (Error while validating the service descriptor 'ServiceType: Microsoft.AspNetCore.Identity.IUserClaimsPrincipalFactory`1[Microsoft.AspNetCore.Identity.IdentityUser] Lifetime: Scoped ImplementationType: Microsoft.AspNetCore.Identity.UserClaimsPrincipalFactory`1[Microsoft.AspNetCore.Identity.IdentityUser]': No constructor for type 'IdentityDataIsolationSample.Data.ApplicationDbContext' can be instantiated using services from the service container and default values.) (Error while validating the service descriptor 'ServiceType: Microsoft.AspNetCore.Identity.UserManager`1[Microsoft.AspNetCore.Identity.IdentityUser] Lifetime: Scoped ImplementationType: Microsoft.AspNetCore.Identity.UserManager`1[Microsoft.AspNetCore.Identity.IdentityUser]': No constructor for type 'IdentityDataIsolationSample.Data.ApplicationDbContext' can be instantiated using services from the service container and default values.) (Error while validating the service descriptor 'ServiceType: Microsoft.AspNetCore.Identity.ISecurityStampValidator Lifetime: Scoped ImplementationType: Microsoft.AspNetCore.Identity.SecurityStampValidator`1[Microsoft.AspNetCore.Identity.IdentityUser]': No constructor for type 'IdentityDataIsolationSample.Data.ApplicationDbContext' can be instantiated using services from the service container and default values.) (Error while validating the service descriptor 'ServiceType: Microsoft.AspNetCore.Identity.ITwoFactorSecurityStampValidator Lifetime: Scoped ImplementationType: Microsoft.AspNetCore.Identity.TwoFactorSecurityStampValidator`1[Microsoft.AspNetCore.Identity.IdentityUser]': No constructor for type 'IdentityDataIsolationSample.Data.ApplicationDbContext' can be instantiated using services from the service container and default values.) (Error while validating the service descriptor 'ServiceType: Microsoft.AspNetCore.Identity.SignInManager`1[Microsoft.AspNetCore.Identity.IdentityUser] Lifetime: Scoped ImplementationType: Microsoft.AspNetCore.Identity.SignInManager`1[Microsoft.AspNetCore.Identity.IdentityUser]': No constructor for type 'IdentityDataIsolationSample.Data.ApplicationDbContext' can be instantiated using services from the service container and default values.) (Error while validating the service descriptor 'ServiceType: Microsoft.AspNetCore.Identity.IUserStore`1[Microsoft.AspNetCore.Identity.IdentityUser] Lifetime: Scoped ImplementationType: Microsoft.AspNetCore.Identity.EntityFrameworkCore.UserOnlyStore`6[Microsoft.AspNetCore.Identity.IdentityUser,IdentityDataIsolationSample.Data.ApplicationDbContext,System.String,Microsoft.AspNetCore.Identity.IdentityUserClaim`1[System.String],Microsoft.AspNetCore.Identity.IdentityUserLogin`1[System.String],Microsoft.AspNetCore.Identity.IdentityUserToken`1[System.String]]': No constructor for type 'IdentityDataIsolationSample.Data.ApplicationDbContext' can be instantiated using services from the service container and default values.)'

The exception is thrown in the Program.Main method when the IHostBuilder.Build() method is called.

**Comment by AndrewTriesToCode** [comment]
@Hammurabidoug  Thanks for posting this. I'll take a look and make sure I get it working again.

**Comment by AndrewTriesToCode** [comment]
OK I just updated that branch with the fix. I changed the layout view to tolerate a null multi tenant context and I changed the application db context to take `ITenantInfo` in the constructor rather than `TenantInfo`. Thanks again!
