### ISSUE TITLE
MultiTenant entity primary key best practices

### ISSUE THREAD

**Issue by GioviQ** [Finbuckle/Finbuckle.MultiTenant#280]
With MultiTenant attribute or with method isMultiTenant a TenantId property is added to the entity without any changes to the primary key of the enity.

In some cases the primary keys are well know strings and there would be an entity per Tenant with the same key in the same db and that's not possible.

So, do I have to make PK + TenantId a new composite key by myself? Or is there something else in Finbuckle to handle this automatically?

**Comment by AndrewTriesToCode** [comment]
@GioviQ 

Currently there isn't a way to handle it for you in the library so yeah, you have to do it yourself. I realized when I did this for the Identity entity types that a general approach would be much better. Maybe something like 'IsMultiTenant(bool adjustIndex = false)`. Thanks for the suggestion!

**Comment by AndrewTriesToCode** [comment]
In a recent PR and in the next release I added a method which will automatically at tenant ID to keys and indexes. Going to close this out. Thanks!
