### ISSUE TITLE
Avoiding null TenantInfo injection

### ISSUE THREAD

**Issue by GioviQ** [Finbuckle/Finbuckle.MultiTenant#281]
In some cases, for example when appplication starts, in ApplicationDbContext a null TenantInfo is injected causing exception at some point.

In fact every Tenant framework should have a Master Tenant without the need to define a Fallback strategy. A master tenant instance of TenantInfo should be a mandatory parameter of every tenant framework.

My proposal:

 app.UseMultiTenant(new TenantInfo() { ... }); //internally memorized as MasterTenant
 app.UseMultiTenant(); //find in the store a tenant with identifier "Master" and use this as MasterTenant

services.TryAddScoped<TenantInfo>(sp => sp.GetRequiredService<IHttpContextAccessor>().HttpContext?.GetMultiTenantContext()?.TenantInfo ?? MasterTenant);
           
fallback strategy to remove

what do you think about it?

**Comment by AndrewTriesToCode** [comment]
hi @GioviQ I'm going to mark this idea as a potential future enhancemnet. I've seen a few places where you explicitly don't want a default tenant so I'd have to think about this.

Not sure if you are using the preview versions, but in them I have removed the fallback strategy and the "replacement" is just to register the static strategy last (you can register multiple strategies and they run in order).

Also note that this is still a problem in design time db context ops like migration, I believe. I don't believe the actual pipeline is run even though migration does use the `Startup` class.

**Comment by GioviQ** [comment]
I used host strategy in https://github.com/enkodellc/blazorboilerplate/tree/development and a master tenant is mandatory, because it is the tenant where you can add other tenants and it is not binded to an hostname.

At the moment I put default in https://github.com/enkodellc/blazorboilerplate/blob/development/src/Server/BlazorBoilerplate.Storage/ApplicationDbContext.cs#L35

I am currently using the version 5, but I will try the 6.

I have an exception during a migration with:

             modelBuilder.Entity<ApplicationUser>().IsMultiTenant(); 

object not set ... UpdateUserIndex something like that

Then I used the attribute MultiTenant and the migration succeded.

**Comment by AndrewTriesToCode** [comment]
I'm glad you got the migration to work. The object not set error is a little concerning so I'm going to mark this as a bug to look into.

**Comment by AndrewTriesToCode** [comment]
Going to close this issue out. The code related to the UpdateUserIndex has been updated since this. If I get more reports of an error of course I will investigate further.
