### ISSUE TITLE
I need to 

### ISSUE THREAD

**Issue by jean-jagnow** [Finbuckle/Finbuckle.MultiTenant#287]
You can specify {__tenant __ =} in the route mapping for a spa on a route determined by
app.Map ("/{__ tenant __ =}/my-spa/", x => ...
Thus?

expected result : https://localhost:5001/tenant-1/my-spa/#

**Comment by AndrewTriesToCode** [comment]
@jean-jagnow  sorry for the late reply.

I'm not sure I understand what you are asking. What is the observed result when you try to do this? I honestly don't have a lot of personal experience using with SPAs, but I'd like to make sure I can help you.

Generally I use the tag helper and I just set the tag attribute `asp-route-__tenant__=my_tenant` and the link generation works ok.
