### ISSUE TITLE
Any timeline for v6 preview 5 or release

### ISSUE THREAD

**Issue by bobskigit** [Finbuckle/Finbuckle.MultiTenant#291]
Any ideas on when v6 will be ready, preview 4 doesn't work for me.

get error on HttpContext.GetMultiTenantContext<TenantInfo>()?.TenantInfo; says GetMultiTenantContext does not exist

**Comment by AndrewTriesToCode** [comment]
@bobskigit Hi Bob. I'm actively working on it. At this point just cleaning things up. I'll probably have another preview up this week that is very close to the final thing.

For that error, you'll need to use `GetMultiTenantContenxt<TenantInfo>()` (substitute in your custom tenant info type if you are using one. Let me know if that doesn't get your past the error.

**Comment by AndrewTriesToCode** [comment]
Update: I expect to push preview 5 out today

**Comment by bobskigit** [comment]
I tried to move to preview 5 but get the following


'HttpContext' does   not contain a definition for 'GetMultiTenantContext' and no accessible   extension method 'GetMultiTenantContext' accepting a first argument of type   'HttpContext' could be found (are you missing a using directive or an   assembly reference?)

On all controllers that use multi-tenant
--

**Comment by bobskigit** [comment]
Installed preview 5 works like a charm.

Thanks

**Comment by AndrewTriesToCode** [comment]
Excellent. UseMultiTenant working for you as well?

**Comment by bobskigit** [comment]
Yes.

Just going to apply the ITenantInfo to our tenant class to see if I can get that working as well. This is should make the implementation in our setup easier.

**Comment by AndrewTriesToCode** [comment]
Oops i meant GetMultiTentantContext not UseMultiTenant. Anyway, glad it is working for you. Let me know if you run into any other issues.
