### ISSUE TITLE
Problems after project updated to v6-preview5

### ISSUE THREAD

**Issue by win32nipuh** [Finbuckle/Finbuckle.MultiTenant#296]
My code was working using preview3 but after the update to oreview5:

using Finbuckle.MultiTenant.EntityFrameworkCore; - does not exist, ok, I have removed it

but  this cannot be compiled because MultiTenantDbContext is unknown

```
 public partial class dbContext : MultiTenantDbContext
    {
        bool bSnake = false;

        public PMdbContext(ITenantInfo tenantInfo) : base(tenantInfo)
        {
        }

```

How to fix the code (worked with preview 4)?

**Comment by AndrewTriesToCode** [comment]
Ho @win32nipuh can you post your csproj file and your context class? Or email to me if you don’t want to post it?

**Comment by win32nipuh** [comment]
Hi Andrew, ok, sent.

**Comment by AndrewTriesToCode** [comment]
@win32nipuh in the project file you sent I don't see a package reference to `Finbuckle.MultiTenant.EntityFrameworkCore`

Also you'll need to update your Microsoft EF Core references to 3.1.4-- I should not require this in the final release.

**Comment by win32nipuh** [comment]
Thanx, it fixed, now I see that there are few of Finbuckle packages.
