### ISSUE TITLE
Razor Pages anchor tag helper with route strategy

### ISSUE THREAD

**Issue by PatrickBorkowicz** [Finbuckle/Finbuckle.MultiTenant#297]
This might be a duplicate of #49. I'm unable to get razor page links working correctly under the route strategy.

Here is my Startup.cs:

	public void ConfigureServices(IServiceCollection services)
	{
		...
		services.AddHttpContextAccessor();
		...
		services.AddMultiTenant()
			.WithStore<MultiTenantStore>(ServiceLifetime.Transient)
			.WithRouteStrategy();

		services.AddControllersWithViews()
			.AddRazorRuntimeCompilation();

		services.AddRazorPages()
			.AddRazorRuntimeCompilation();
	}

	public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
	{
		...
		app.UseHttpsRedirection();
		app.UseStaticFiles();
		app.UseCookiePolicy();
		app.UseRouting();
		app.UseMultiTenant();

		app.UseEndpoints(endpoints =>
		{
			endpoints.MapControllerRoute("default", "{__tenant__=}/{controller=Home}/{action=Index}/{id?}");
			endpoints.MapRazorPages();
		});
	}

Assuming I am on a page with the URL
	`https://example.com/mytenant/Index`

And I use the anchor tag helper to generate a link to a controller action such as:
	`<a asp-action="Contact" asp-controller="Home">Contact</a>`

Then the anchor tag helper will produce a correct URL, preserving the tenant identifier in the route:
	`https://example.com/mytenant/Home/Contact`

However:
	`<a asp-page="/Search">Search</a>`
results in:
	`https://example.com/Search`
which I believe should be:
	`https://example.com/mytenant/Search`

It does work if I explicitly specify the __tenant__ parameter, such as:
`<a asp-page="/Search" asp-route-__tenant__="@Context.GetMultiTenantContext().TenantInfo.Identifier">Search</a>`

But that is not ideal. Am I missing something? Do I need to add a page route convention to achieve the desired behaviour? I plan to add Identity to this project and would like to get this sorted out first. Thanks.

**Comment by AndrewTriesToCode** [comment]
hi @PatrickBorkowicz 

Microsoft changed the behavior in ASP.NET Core 3 so that "ambient" route values are not preserved in link generation: only area, controller, and action are "automatic" in that sense.

Not to worry though, I have a work around. The Identity Data Isolation sample in the ASP.NET Core 3.1 samples folder has a class called `AmbientValueLinkGenerator` here:
[https://github.com/Finbuckle/Finbuckle.MultiTenant/blob/master/samples/ASP.NET%20Core%203/IdentityDataIsolationSample/Infrastructure/AmbientValueLinkGenerator.cs](https://github.com/Finbuckle/Finbuckle.MultiTenant/blob/master/samples/ASP.NET%20Core%203/IdentityDataIsolationSample/Infrastructure/AmbientValueLinkGenerator.cs)

Copy that file into your project and you can use it like this in `ConfigureServices`:
```cs
// This will wrap the default LinkGenerator with one that preserves certain ambient route values.
services.DecorateService<LinkGenerator, AmbientValueLinkGenerator>(new List<string> { "__tenant__" });
```

The `DecorateService` extension method is included in Finbuckle.MultiTenant and is another handy tool as well.

Give that a try and let me know how it goes.

**Comment by PatrickBorkowicz** [comment]
@AndrewTriesToCode You are a legend sir! That did the trick.

Apologies, I should have mentioned I was using .Net Core 3.1. Is there any value to my using the BasePathStrategy over RouteStrategy, assuming I only ever want the tenant identifier at the 'root' of the path? To give some context, we are redesigning an ASP.NET application that currently uses a custom subdomain/host strategy which is hard to maintain with wildcard SSL certificates bindings, etc...

Also. thank you for this exceptionally versatile library, it should be part of the SDK as multi-tenancy is a fairly common SASS model.

**Comment by AndrewTriesToCode** [comment]
@PatrickBorkowicz  I'm glad it worked and that you find the library useful. Please keep it in mind if I ever figure out how to turn on sponsorships. I'm thinking of adding this ambient link generator as part of the standard setup when using the route strategy, or maybe as an option at least.

Regarding basepath vs routing -- if your route always puts the tenant as the base path there isn't much practical difference. In some situations basepath can work better -- i.e. you need the finbuckle.multitenant middleware to run before the routing middleware, or you aren't using the routing middleware at all. It's not very common.

**Comment by PatrickBorkowicz** [comment]
I should have also mentioned that adding:
`services.DecorateService<LinkGenerator, AmbientValueLinkGenerator>(new List<string> { "__tenant__" });`
alone was not enough, as the Razor page links would be rendered with the tenant identifier as a query parameter instead of a route parameter. e.g:
`example.com/mypage?__tenant__=megacorp`

I also had to add `MultiTenantPageRouteModelConvention` to `.AddRazorPagesOptions(o => {...})` to get the desired effect, which I believe I got from one of the other samples.

**Comment by shainegordon** [comment]
@PatrickBorkowicz where did you find `MultiTenantPageRouteModelConvention`?

I think that is my missing piece to get this working on Razor Pages too

**Comment by shainegordon** [comment]
ok so I ended up using this as an example - https://github.com/Finbuckle/Finbuckle.MultiTenant/blob/master/samples/ASP.NET%20Core%203/IdentityDataIsolationSample/Startup.cs

So I created my own `IPageRouteModelConvention`

```
public class MultiTenantPageRouteModelConvention : IPageRouteModelConvention
    {
        public void Apply(PageRouteModel model)
        {
            foreach (var selector in model.Selectors)
            {
                selector.AttributeRouteModel.Template =
                    AttributeRouteModel.CombineTemplates("{__tenant__}", selector.AttributeRouteModel.Template);
            }
        }
    }
```


```
services.AddRazorPages().AddRazorPagesOptions(options =>
            {
                options.Conventions.Add(new MultiTenantPageRouteModelConvention());
            })
```

**Comment by AndrewTriesToCode** [comment]
@shainegordon You got it from the right place!
