### ISSUE TITLE
JWT Bearer with NET CORE 3.1

### ISSUE THREAD

**Issue by dlebee** [Finbuckle/Finbuckle.MultiTenant#303]
Hello I am trying to configure JwtBearerOptions with the help of WithPerTenantOptions.

the delegate never seems to be called.

Do you have a working example where there would be a different authority per tenant?

> Here is the source.

```csharp
public class Startup
    {
        private readonly IConfiguration configuration;

        public Startup(IConfiguration configuration)
        {
            this.configuration = configuration;
        }

        // This method gets called by the runtime. Use this method to add services to the container.
        // For more information on how to configure your application, visit https://go.microsoft.com/fwlink/?LinkID=398940
        public void ConfigureServices(IServiceCollection services)
        {
            services
                .AddAuthentication()
                .AddJwtBearer();

            services
                .AddMultiTenant()
                .WithDelegateStrategy(context =>
                {
                    var request = ((HttpContext)context).Request;
                    var tenantFromHeader = request.Headers["X-Tenant"].FirstOrDefault() ?? "b2c-master";
                    return Task.FromResult(tenantFromHeader);
                })
                .WithInMemoryStore()
                 .WithPerTenantOptions<AuthenticationOptions>((options, tenantInfo) =>
                 {
                     options.DefaultScheme = JwtBearerDefaults.AuthenticationScheme;
                     options.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;
                 })
                .WithPerTenantOptions<JwtBearerOptions>((options, tenantInfo) =>
                {
                    // THIS NEVER GETS CALLED ^
                    var authorityName = tenantInfo.Name;
                    var authority = $"{configuration["KeyCloak:Endpoint"]}/realms/{authorityName}";
                    options.Authority = authority;
                    options.TokenValidationParameters.ValidateAudience = false;
                });

            services.AddControllers();
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseRouting();
            app.UseMultiTenant();
            app.UseAuthentication();
            app.UseAuthorization();
            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();
            });
        }
    }
```
I wish to accomplish this 

![image](https://user-images.githubusercontent.com/36390643/88205317-93da6180-cc1a-11ea-8de5-b16d9ee92e98.png)

I could not find any samples in your github.

**Comment by AndrewTriesToCode** [comment]
hi @dlebee  

I'm taking a look and will post back shortly.

**Comment by dlebee** [comment]
> hi @dlebee
> 
> I'm taking a look and will post back shortly.

@AndrewTriesToCode  Thank you.

**Comment by AndrewTriesToCode** [comment]
@dlebee 
If doesn't say it in the docs, but I think you will need to also use `WithRemoteAuthentication`.

Give that a try and let me know. That method will register a special override for the default authentication scheme options which need to work so that it knows to load the per-tenant JWT options...

By the way if you haven't check out the pinned issue about release 6. This specific thing is changed in release 6 with respect to the default schemes via a new method `WithPerTenantAuthentication`. The JWT options part will be the same though.

**Comment by dlebee** [comment]
@AndrewTriesToCode I tried that it did not seem to work, have you give it a try?

**Comment by AndrewTriesToCode** [comment]
@dlebee  I did confirm that it worked for me-- but I simplified your example somewhat. I changed the strategy to a simple static one and used a configuration store. And what made it actually work was `WithRemoteAuthentication`

I'd recommend you try that as well to get as simple a test as possible. I didn't see how your in-memory store is populated, but the per-tenant options won't fire unless an actual tenant is found in the store.

**Comment by dlebee** [comment]
@AndrewTriesToCode I am not sure how it works the store, I though the delegate of tenant took care of resolving the tenant, is there a way to manage how tenantInfo are resolved without a store? just with a delegate and a custom logic?

If you don't mind uploading the sample somewhere it would be great.

**Comment by AndrewTriesToCode** [comment]
@dlebee 
Here's the basic explanation: the strategy's job is to find an "identifier" which in your case is a header value. It then uses the identifier to lookup the tenant in the store. In the example for the JWT options it kinda of skips over this detail--but the inmemory store needs to be populated with the tenants info. I actually would recommend the configuration store over the inmemory store so I should update the docs.

If the identifier matches a tenant in the store then per-tenant options can take effect.

**Comment by dlebee** [comment]
@AndrewTriesToCode is there a way to resolve the tenant without a store, and more through lets say Service Registration?

Like ITenantResolver.ResolveTenantAsync(tenantId)

**Comment by AndrewTriesToCode** [comment]
The middleware and the resolver both need a configured store to resolve the tenant.  This results in a `TenantInfo` object with more than just the identifier.

You could create a simple store that just returns a basis tenantIfo:

```cs
public class MyStore : IMultiTenantStore
{
  public Task<TenantInfo> GetByIdentifierAsync(string identifier)
  {
    return new TenantInfo(identifier, identifier, null, null, ...);
    // other functions with no functionality needed
  }
}
```

Then in your `ConfigureServices` method:
```cs
services.AddMultiTenant().WithStore<MyStore>().... 
```

That would be a simple store that just sort of "echoes" the identifier from the strategy.

Release 6 allows for custom `TenantInfo` classes so it would vary slightly from what is shown above.

**Comment by dlebee** [comment]
Thank you so much it works! :)

```csharp
services.AddHttpContextAccessor();
            services
                .AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
                .AddJwtBearer(JwtBearerDefaults.AuthenticationScheme, null);

            services.AddMultiTenant()
                .WithStore<StateLessStore>(ServiceLifetime.Singleton)
                .WithRemoteAuthentication()
                .WithDelegateStrategy(context => 
                {
                    var request = ((HttpContext)context).Request;
                    var tenantFromHeader = request.Headers["X-Tenant"].FirstOrDefault() ?? "b2c-master";
                    return Task.FromResult(tenantFromHeader);
                })
                .WithPerTenantOptions<JwtBearerOptions>((options, tenant) =>
                {
                    options.Authority = $"{configuration["KeyCloak:Endpoint"]}/realms/{tenant.Id}";
                    options.TokenValidationParameters.ValidateAudience = false;
                });

            services.AddControllers();
```

and

```csharp
internal class StateLessStore : IMultiTenantStore
    {
        public Task<bool> TryAddAsync(TenantInfo tenantInfo)
        {
            return Task.FromResult(true);
        }

        public Task<TenantInfo> TryGetAsync(string id)
        {
            throw new System.NotImplementedException();
        }

        public Task<TenantInfo> TryGetByIdentifierAsync(string identifier)
        {
            return Task.FromResult(new TenantInfo(identifier, identifier, identifier, null, new Dictionary<string, object> { }));
        }

        public Task<bool> TryRemoveAsync(string id)
        {
            return Task.FromResult(true);
        }

        public Task<bool> TryUpdateAsync(TenantInfo tenantInfo)
        {
            return Task.FromResult(true);
        }
    }
```

Obviously its not the final code but yeah! thank you! 

@AndrewTriesToCode

**Comment by AndrewTriesToCode** [comment]
Awesome!
