### ISSUE TITLE
TenantInfo Store from catalog db

### ISSUE THREAD

**Issue by jams4code** [Finbuckle/Finbuckle.MultiTenant#311]
Hi,

I've been using Finbuckle for one month on a project and it's really good. Thank a lot for that library.

I'm using the BasePath Strategy with a custom store that I added.

The configuration store is working well but I don't find safe to put the connection strings there and also it's not the perfect place for an application that will have DB added and removed from the list.

So, I just wanted to know if you want me to add that "WithCatalogStore" extension.

It's a Store based on the IMultitenantStore that needs a DB context where it will pull the tenant list.
I have two Db context : CatalogDbContext (contains the TenantInfo) & ApplicationDbContext.

![three-tenancy-patterns](https://user-images.githubusercontent.com/56386365/89440916-a42b2a00-d74c-11ea-92f2-733be7739020.png)

If you want me to add it and test through a pull request let me know and I'll do it.

Have a great day,
Jamal

**Comment by AndrewTriesToCode** [comment]
Hi @jams4code 

First of all, I'm glad you are finding the library helpful.

We've got the `EFCoreStore` that uses Entity Framework Core and db contexts which is used similarly. I think it might create confusion to add another db context based store which is so similar. I have a few questions though:

1. Have you seen the 6.0 preview releases? A lot changed with stores there so you might want to take a look if you haven't.
2. Do you plan to make this available in a repository or a nuget for those that might want to use it? If so I'd be happy to mention it on the webpage and the docs.

Thanks!
