### ISSUE TITLE
How to Fetch all tenants from store?

### ISSUE THREAD

**Issue by vermilion** [Finbuckle/Finbuckle.MultiTenant#313]
Hi!

Thanks for a great lib. I've been playing with it for a while and I'm confused how to get all `Tenants` from tenant store?
`IMultiTenantStore` does not have such method... 

This is clear for some stores but not for the `ConfigurationStore`. The only way is to get it from IConfiguration object but that's not very intuitive.
Any method to get it? Or can you add __GetAll__ method to this interface and implement that in all stores?

Found PR #309

**Comment by vermilion** [comment]
Found PR #309

**Comment by AndrewTriesToCode** [comment]
Hi @vermilion 
We have a pending PR that will add a method to retrieve them all. Hopefully that will help out.

-Drew
