### ISSUE TITLE
How to use multitenancy in Rest API?

### ISSUE THREAD

**Issue by win32nipuh** [Finbuckle/Finbuckle.MultiTenant#322]
I have a Blazor client->ASP>NET Web server->database. 
The multitenancy works fine, thank Andrew.

But now I need to replace all server -side methods to Rest API methods.

How to use multitenancy in case of RESTFul API? Any samples?

**Comment by AndrewTriesToCode** [comment]
hi @win32nipuh 

I don't have any samples at the moment, but it works exactly the same for the most part. You'll want to use a strategy compatible with your api design -- `HostStrategy` and `RouteStrategy` work well. If you are using tokens to authenticate the API then the `ClaimStrategy` or similar might work. Nothing special about a regular HTTP app request and an API request from this perspective.

For the multitenant store, ideally you want to use the same store for the API as the rest of your setup uses. In this case a database store using `EFCoreStore` or a custom store using Redis or something would work well.

Good luck and let me know if you hit any specific problems.

**Comment by Valks** [comment]
May or may not be useful, but I did a little prototype using azure functions:

https://github.com/Valks/Finbuckle.MultiTenant/tree/AddAzureFunctionsSupport

Didn't take much to get it working. Probably should look at adding a way to get the tenant from an attributed parameter but otherwise works almost the same.

I also adjusted the base route model to add a generic prefix (mainly to remove the /api)

Small caveat is that the way I've hooked into the middleware pipeline isn't officially supported. That said an official approach is triaged so I'd expect this to work while we wait for them to give an official solution.

**Comment by AndrewTriesToCode** [comment]
@Valks That's very interesting, thanks for sharing!

**Comment by win32nipuh** [comment]
Could you please comment: how in your opinion to add tenant to this sample? 
There is description

https://www.red-gate.com/simple-talk/dotnet/c-programming/build-a-rest-api-in-net-core/

There is the project sample
https://github.com/beautifulcoder/BuildRestApiNetCore

That is the simple sample uses swagger etc. 

If I use the host strategy, i.e. 
http://initech:5000/v1/products
http://finbuckle:5000/v1/products
I will always call the same controller methods?

```
namespace BuildRestApiNetCore.Controllers
{
  [ApiController]
  [ApiVersion("1.0")]
  [Route("v{version:apiVersion}/[controller]")]
  [Produces("application/json")]
  public class ProductsController : ControllerBase
  {
    private readonly ProductContext _context;
    private readonly ILogger<ProductsController> _logger;

    public ProductsController(ProductContext context, ILogger<ProductsController> logger)
    {
      _context = context;
      _logger = logger;

      if (_context.Products.Any()) return;

      ProductSeed.InitData(context);
    }

    [HttpGet]
    [Route("")]
    [ProducesResponseType(StatusCodes.Status200OK)]
    public ActionResult<IQueryable<Product>> GetProducts([FromQuery] string department, [FromQuery] ProductRequest request)

```

What is wrong in my descriptions? 
Sorry for the question, but I am trying to understand the RESTful way of multitenancy. Thank you

**Comment by AndrewTriesToCode** [comment]
Hi @win32nipuh 

Fundamentally it should work exactly the same for an API as for a web app, e.g. strategies and stores will be in the pipeline and work the same. Obviously swagger and nlog don't know anything about Finbuckle but if they use the Options pattern they their options can be customized per-tenant. I haven't look into these two items specifically.

The multitenant strategy can vary for an API -- you could use the host or routing one easily. For the routing one your would add the `{__tenant__}` route parameter as part of the route attribute. You could also get fancier and make a custom strategy that looks at a query parameter in the request, an Http header, or even a JWT claim token if you want to get fancy.

I don't see anything wrong with your approach -- yes with different subdomains the actual controllers will be the same, just the detected tenant will differ, and that can affect things like use of options (referring the the ASP.NET Core Options pattern), EF Core, or your own logic (if you use `HttpContext.GetMultiTenantContext` in your controller logic).

I'm happy to answer any more question just let me know. I should probably create an API sample project.
