### ISSUE TITLE
WithPerTenantAuthentication conflicts withs ClaimStrategy

### ISSUE THREAD

**Issue by AndrewTriesToCode** [Finbuckle/Finbuckle.MultiTenant#324]
In 6.0.0 `WithPerTenantAuthentication` conflicts with `ClaimStrategy` and effectively cancels any signin. This is due to `ClaimStrategy` triggering principal validation configured by `WithPerTenantAuthentication`.

On this [branch](https://github.com/Finbuckle/Finbuckle.MultiTenant/tree/fix/ClaimStrategy-PerTenantAuthentication-Compat) a fix is being prepped for release. A sample project for `ClaimStrategy` is also included.

**Comment by stonesvillage** [comment]
@AndrewTriesToCode I've not found any problems with this branch - good work!
Is there a timeline when an updated package is released?

**Comment by AndrewTriesToCode** [comment]
There will be a new release when .NET 5 is released. I am also trying to get out a preview release this week to support the .NET 5 RC release.
