### ISSUE TITLE
Should ConnectionString be part of ITenantInfo?

### ISSUE THREAD

**Issue by natelaff** [Finbuckle/Finbuckle.MultiTenant#325]
Just throwing it out there, ConnectionString to me is not natural on ITenantInfo, and belongs in an implementation. For example, if you want to just client side packages, HttpRemoteStore is looking for connection string, that's never going to exist.

Another point, in my app server side app the connection string is built outside of the scope of where this would hit, by acquiring userId and password from Azure Key Vault. So even in my API which is EF Core based, I would never use ConnectionString property.

Just a thought for when you feel like making a major breaking change ;)

**Comment by AndrewTriesToCode** [comment]
Hi @natelaff thanks for the feedback. I think you are right and I agree. I mainly kept it for the time being to not change too fast and to have an easy story for the use case where tenants do not share a database.

Thanks again!

**Comment by natelaff** [comment]
I found a use for ConnectionString when using Configuration store in debug by storing my localhost tenant in config. Still not convinced this property belongs on ITenantInfo, but it is no longer an eye sore for me and serves a purpose. If you don't feel like changing this one and closing it I wouldn't hold it against you ;)
