### ISSUE TITLE
Service locator fails when using a class derived from ITenantInfo

### ISSUE THREAD

**Issue by Valks** [Finbuckle/Finbuckle.MultiTenant#329]
I'm trying to add a CosmosDb store implementation (not using EFCore) which works fine if I use ```TenantInfo``` for the record model but if I change to another class that implements ```ITentantInfo``` it fails to locate the ```MultiTenantContextAccessor``` and from the error below it looks like it's trying to resolve ```TenantInfo``` instead of ```ITenantInfo```

```
Executed 'Devices' (Failed, Id=1d9ccd0c-c57d-41d1-8514-0ba84d3c8e89, Duration=272ms)
System.Private.CoreLib: Exception while executing function: Devices. Microsoft.Extensions.DependencyInjection.Abstractions: No service for type 'Finbuckle.MultiTenant.IMultiTenantContextAccessor`1[Finbuckle.MultiTenant.TenantInfo]' has been registered.
```

I also tried using the InMemoryStore and get the same error. Any thoughts?

**Comment by Valks** [comment]
Nevermind, it was an oversight on my part when I call ```GetMultiTenantContext<TenantInfo>```. I was looking everywhere except the actual function using the code...

**Comment by AndrewTriesToCode** [comment]
@Valks Glad you sorted it out! Let me know how the CosmosDb store works out for you. I'll probably eventually add it to the library.
