### ISSUE TITLE
EF Core global filter null reference exception

### ISSUE THREAD

**Issue by SebOpalinski** [Finbuckle/Finbuckle.MultiTenant#334]
Hi, I'm trying to setup a multi-tenant application but I'm having issues with the global TenantId query filter. I'm really stumped so any help at would be really appreciated!

All my ef core queries are throwing something like the below null reference exception. I have checked and there is definitely a MultiTenantContext set before the queries are made:

   __at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, LambdaExpression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.FirstOrDefaultAsync[TSource](IQueryable`1 source, Expression`1 predicate, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Identity.EntityFrameworkCore.UserStore`9.FindByNameAsync(String normalizedUserName, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Identity.UserManager`1.<FindByNameAsync>d__78.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.AspNetCore.Identity.SignInManager`1.<PasswordSignInAsync>d__39.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Coniecto.Areas.Identity.Pages.Account.LoginModel.<OnPostAsync>d__25.MoveNext()__

Here's my dbcontext class:
```
public class ApplicationDbContext : MultiTenantIdentityDbContext<User, ApplicationRole, Guid>

	{
		private readonly ICurrentUserService _currentUserService;
		public ApplicationDbContext(ITenantInfo tenantInfo, DbContextOptions<ApplicationDbContext> options, ICurrentUserService currentUserService)
			: base(tenantInfo, options)
		{
			_currentUserService = currentUserService;
		}

		public DbSet<AppTenantInfo> Tenants { get; set; } = null!;
		public DbSet<Project> Projects { get; set; } = null!;
		public DbSet<Epic> Epics { get; set; } = null!;

		protected override void OnModelCreating(ModelBuilder modelBuilder)
		{
			modelBuilder.HasPostgresExtension("uuid-ossp")
				.ApplyConfigurationsFromAssembly(typeof(ApplicationDbContext).Assembly);

			base.OnModelCreating(modelBuilder);
		}

		public override Task<int> SaveChangesAsync(CancellationToken cancellationToken = new CancellationToken())
		{
			foreach (var entry in ChangeTracker.Entries<IEntity>())
			{
				switch (entry.State)
				{
					case EntityState.Added:
						if (_currentUserService.IsAuthenticated)
						{
							entry.Entity.CreatedById = (Guid)_currentUserService.UserId!;
							entry.Entity.ModifiedById = (Guid)_currentUserService.UserId!;
						}

						entry.Entity.CreatedDate = DateTime.Now;
						entry.Entity.ModifiedDate = DateTime.Now;
						break;
					case EntityState.Modified:
						if (_currentUserService.IsAuthenticated)
						{
							entry.Entity.ModifiedById = (Guid)_currentUserService.UserId!;
						}

						entry.Entity.ModifiedDate = DateTime.Now;
						break;
				}
			}

			return base.SaveChangesAsync(cancellationToken);
		}
	}
```
and my startup:
```
	public class Startup
	{
		public Startup(IConfiguration configuration)
		{
			Configuration = configuration;
		}

		public IConfiguration Configuration { get; }

		public void ConfigureServices(IServiceCollection services)
		{
			services.AddMiniProfiler().AddEntityFramework();

			services.AddDbContext<ApplicationDbContext>(options =>
				options.UseNpgsql(Configuration.GetConnectionString("ApplicationDbContextConnection"))
					.UseSnakeCaseNamingConvention());

			services.AddIdentity<User, ApplicationRole>(opt => opt.User.RequireUniqueEmail = true)
				.AddEntityFrameworkStores<ApplicationDbContext>()
				.AddDefaultTokenProviders();

			services.AddAuthentication(IdentityConstants.ApplicationScheme).AddCookie();

			services.AddAuthorization(opt =>
			{
				opt.FallbackPolicy = new AuthorizationPolicyBuilder()
					.RequireAuthenticatedUser()
					.Build();
			});

			services.AddRazorPages().AddRazorRuntimeCompilation();

			services.AddMvc()
				.AddFluentValidation(cfg => { cfg.RegisterValidatorsFromAssemblyContaining<Startup>(); })
				.AddFeatureFolders()
				.AddAreaFeatureFolders()
				.AddRazorOptions(options =>
				{
					options.AreaPageViewLocationFormats.Add(new AreaFeatureFolderOptions().FeatureFolderName + @"\Shared\{0}.cshtml");
				});

			services.AddMultiTenant<AppTenantInfo>()
				.WithRouteStrategy()
				.WithStaticStrategy("Anonymous")
				.WithStore<MultiTenantStore>(ServiceLifetime.Scoped)
				.WithPerTenantAuthentication();

			services.DecorateService<LinkGenerator, AmbientValueLinkGenerator>(new List<string> { "__tenant__" });

			services.AddSingleton<IEmailSender, EmailSender>();

			services.AddAutoMapper(typeof(Startup));

			//services.Scan(scan => scan.FromCallingAssembly().AddClasses(classes => classes.AssignableTo<IValidator>()).AsImplementedInterfaces().WithTransientLifetime());
			services.Scan(scan => scan.FromCallingAssembly().AddClasses(classes => classes.AssignableTo<IService>()).AsImplementedInterfaces().WithTransientLifetime());

			services.AddScoped<ICurrentUserService, CurrentUserService>();

			services.AddHttpContextAccessor();
		}

		public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
		{
			if (env.IsDevelopment())
			{
				app.UseDeveloperExceptionPage();
				app.UseDatabaseErrorPage();
			}
			else
			{
				app.UseExceptionHandler("/Home/Error");
				// The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
				app.UseHsts();
			}
			app.UseHttpsRedirection();
			app.UseStaticFiles();

			app.UseSerilogRequestLogging();
			app.UseMiniProfiler();

			app.UseRouting();
			app.UseMultiTenant();

			app.UseAuthentication();
			app.UseAuthorization();

			app.UseEndpoints(endpoints =>
			{
				endpoints.MapControllerRoute(
					name: "default",
					pattern: "{__tenant__=}/{controller=Home}/{action=Index}/{id?}");
				endpoints.MapRazorPages();
			});
		}
	}
```

**Comment by SebOpalinski** [comment]
After some more investigation, it looks like because I was using the same DB context for my tenant store as my application, the DB context was getting created with a null ITenantInfo and then that DB context was used for the remainder of the request. 

To fix this, I had to create a separate DB context for my tenant store and manually set the tenant info once found. I think it would probably be best to recommend a seperate context in the documentation.

**Comment by AndrewTriesToCode** [comment]
@SebOpalinski 

I'm glad you figured it out -- I usually recommend your new approach for this reason.
