### ISSUE TITLE
Support Shards for Multi tenant szenario

### ISSUE THREAD

**Issue by jiwanovski87** [Finbuckle/Finbuckle.MultiTenant#336]
Hi all,
as far as we can see, Finbuckle supports the following multi tenant scenarios:
- One database for N tenants (with adding a field to each table)
- One database per tenant

I am wondering if it is planned to support also Shards? (more desription [here](https://docs.microsoft.com/en-us/azure/azure-sql/database/saas-tenancy-app-design-patterns#g-multi-tenant-app-with-sharded-multi-tenant-databases))
That means, that I can have several tenants on one database but not separating this with a field in each table. Each tenant gets his own Shard.

The problem with this version is, that the data is not splitted on database and this could result into problems with privacy (because on database level everyone can see everything from all tenants). On the other hand we cannot deliver one database to tenant because this is creating additional costs for every tenant and this could become expensive fast. 

Therefore I believe a model with Shards would have the most benefit. If you want to can have just one Shard on a database or you can have N Shards on a database... So is this planned?

Thanks

**Comment by AndrewTriesToCode** [comment]
Hi @jiwanovski87 

In that link multiple tenants share a single shard.

This can effectively be accomplished by combining your two bullet points. Have multiple databases, each one configured as a Finbuckle shared database with groups of tenants assigned to each database (or shard).

The multitenant shared database approach Finbuckle supports partially isolates data -- if you use standard EFCore methods most of the time you won't pull in a different tenant's info. The limitations are related to how the global query filter works -- it doesn't work on the `Find` method for an entity and it doesn't work past the base level of a query. If you design your application to avoid those two cases and if you users can only access the database through your application UI / API then they will never see other tenant data.

I'd be happy to discuss more--let me know what you think.

**Comment by jiwanovski87** [comment]
Hi @AndrewTriesToCode,

sorry for my late response. For now we have decided to work with databases for each tenant.
I believe using the same database for several tenants will become interesting in the future. But for this strategy it would be very interesting to seperate the data not only with the application. Also on database level this should be splitted and we should be able to decide which user can see which data. So I believe sharding will become very interesting then und it would be interesting. 

I believe it would be very cool, if there might be some scripts to enable the sharding feature on chosen and common databases to have a quicker setup. 

In addition to that: Is it planned to have some scripts available to support thinks like "Updating several tenant databases within one script" or is there already an existing feature?

As example: If we have a multi tenant with one database per tenant and we added one field. Then it would be nice to say: Update all tenants or update Tenant A and Tenant B first. If this is finisehd update also Tenant C, D and E... 

Thanks

**Comment by riccardone** [comment]
Hi,
My two penny. 

You can do sharding in an SqlServer instance partitioning tables. That means that it is a low level configuration of your store, not made up at application level where Finbuckle Multitenant is. Even your link, in fact does not illustrate sharding but separate database per tenant.
