### ISSUE TITLE
Combing strategies/stores

### ISSUE THREAD

**Issue by rebal15** [Finbuckle/Finbuckle.MultiTenant#337]
Hi all, 

I'm fairly new to this project, and so far I'm loving it! I'm wondering if it is possible to almost 'combine' different strategies/stores:

I'm looking to use something similar to the IdentityDataIsolationSample, however I want to be able to grab and update the data from a HTTP Remote store, instead of using a local SQLite database or similar. Any ideas?

Thanks!

**Comment by AndrewTriesToCode** [comment]
hi @rebal15 

Yes you can mix and match strategies and stores. The strategy's job is just to look at the request and return an identifier string. The store's job is to take an identifier string and try to return the tenant detail info if it exists. So they are totally separate and can be combined in different ways.

Also you can register multiple strategies and/or stores. the library will try each strategy until one returns and identifier then it will try each store until one returns tenant details. If none do then it moves on to the next strategy.

Let me know if you have any more questions!

**Comment by rebal15** [comment]
Thanks for the reply @AndrewTriesToCode. Just another thing - how come the Http Remote Store is read only? Am I not able to modify it to enable the program to send back requests to change the data? I'd like to be able to use Per-tenant data with Identity, using an HTTP Remote store as the data source.

**Comment by AndrewTriesToCode** [comment]
You can certainly modify it. It’s meant to be pretty basic and to work for most people. Wherever it is sending the update would have to store the changes, eg in a database so in my use case the http remote server uses the EFCoreStore and I do any updates I want directly via the database.
