### ISSUE TITLE
Why no template for OpenIdConnect options?

### ISSUE THREAD

**Issue by natelaff** [Finbuckle/Finbuckle.MultiTenant#338]
From docs:

_The CookieLoginPath, CookieLogoutPath, and CookieAccessDeniedPath properties can use a template format where __tenant__ will be replaced with the identifier for each specific tenant. For example, a CookieLoginPath of "/__tenant__/Identity/Account/Login" will result in "/initech/Identity/Account/Login" for the Initech tenant._

Was there any specific reason properties such as OpenIdConnectAuthority cannot do the same?

Being able to do something like the below would be very useful and more dynamic for dev/production configs. Currently if you don't want to add a member to the class you lose all the sugar of WithPerTenantAuthentication() just to override a simple guy like this.

```json
  "Finbuckle:MultiTenant:Stores:ConfigurationStore": {
    "Defaults": {
      "ConnectionString": "",
      "OpenIdConnectAuthority": "https://something/__tenant__"      
    }
  }
```

**Comment by natelaff** [comment]
I see where it would plop in [here](https://github.com/Finbuckle/Finbuckle.MultiTenant/blob/1b8ae36b183809318ef920e91f60e409b721e79c/src/Finbuckle.MultiTenant.AspNetCore/Extensions/MultiTenantBuilderExtensions.cs#L103)

So wondering if this was explicitly excluded from this behavior or didn't think it would be particularly useful. I would like to voice my request if the latter ;)

**Comment by natelaff** [comment]
Ah wait, this won't work the way I thought it would. I was thinking these defaults worked on a global level, not related to the Config store (meaning, I thought this would apply AFTER the tenant was resolved from the store, even a custom one). Turns out, this is specific to the ConfigurationStore only and there is no concept of global variables like I was thinking this worked.

To pull this off I'd have to modify the custom store to read from the config as well, so either way I lose something. May as well just not use WIthPerTenantAuthentication and bring all of that back in manually. No biggie!

**Comment by AndrewTriesToCode** [comment]
No technical reason it wasn't included--just focused on cookies initially. If it was then you wouldn't need to have a value for it in the tenant store at all -- you would set the template in the global `OpenIdConnectOptions` then `WithPerTenantAuthentication` could override the template token with the current tenant. It shouldn't be specific to any store. I'll add it in a future release.

**Comment by AndrewTriesToCode** [comment]
Closing out since your PR added these. Thanks!
