### ISSUE TITLE
I must be missing something obvious.

### ISSUE THREAD

**Issue by quartilesoftware** [Finbuckle/Finbuckle.MultiTenant#340]
Hi,

I am trying to get started  with Finbuckle by adding a  simple working test of Multitenanncy to an existing .Net Core 3.1 application. I’m trying to inject the Finbuckle TenantInfo into a controller using dependency injection. Whatever I do, I always see the error: 
 “InvalidOperationException: Unable to resolve service for type 'Finbuckle.MultiTenant.IMultiTenantStore`1[Finbuckle.MultiTenant.TenantInfo]' while attempting to activate 'Application.Controllers.HomeController'. “

This is how I’ve configured Finbuckle in Startup.cs:

    public void ConfigureServices(IServiceCollection services)
        {

            services.AddMultiTenant<TenantInfo>()
            .WithStaticStrategy("MyTenant");
...
and
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {

        app.UseMultiTenant(); 

            app.UseAuthentication();
            app.UseAuthorization();

            app.UseSession();
            app.UseCookiePolicy();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers(); // Map attribute-routed API controllers
                endpoints.MapDefaultControllerRoute(); // Map conventional MVC controllers using the default route
                endpoints.MapRazorPages();
            });

       

This is how the controller I'm trying to inject the TenantInfo into looks:

    public class HomeController : Controller
    {

        private readonly IConfiguration _configuration;
        private readonly IWebHostEnvironment _environment;
        private readonly TenantInfo _tenantInfo;

        public HomeController(
            IConfiguration configuration,
            IWebHostEnvironment environment,
            TenantInfo tenantInfo
        )
        {
            _configuration = configuration;
            _environment = environment;
            _tenantInfo = tenantInfo;

        }

Can anyone please point out to me what I must obviously be missing, because none of that works?

Regards,

Mike

**Comment by AndrewTriesToCode** [comment]
Hi, it looks like you forgot to register a tenant store, eg WithConfigurationStore() after add multi tenant. 

What type of store did you plan to use?

**Comment by quartilesoftware** [comment]
Hi Andrew,

Thanks for your very prompt reply.

I'd already tried following one of the ConfigurationStore samples earlier, like this:

        public void ConfigureServices(IServiceCollection services)
        {

            services.AddMultiTenant<TenantInfo>()
            .WithStaticStrategy("MyTenant")
            .WithConfigurationStore();


and with the values in appsettings.json from one of the sample projects:

  "Finbuckle:MultiTenant:Stores:ConfigurationStore": {
    "Defaults": {
      "ConnectionString": "Datasource=sample.db"
    },
    "Tenants": [
      {
        "Id": "tenant-finbuckle-d043favoiaw",
        "Identifier": "finbuckle",
        "Name": "Finbuckle"
      },
      {
        "Id": "tenant-initech-341ojadsfa",
        "Identifier": "initech",
        "Name": "Initech LLC"
      }
    ]
  },


But I get the same result.

Regards,

Mike

**Comment by AndrewTriesToCode** [comment]
Did your static tenant identifier match one of tenant identifiers in your appsettings.json  file? If you have a GitHub repo for the project I’d be happy to take a look.

**Comment by quartilesoftware** [comment]
Hi Andrew,

Thanks. Naturally, that was it! The second pair of eyes was what I needed. I had mis-typed one character in .WithStaticStrategy in the actual  name data I was using.

In passing, I'm migrating my MultiTenant applications from SaasKit and on day one of Finbuckle, it's obvious your documentation, simplicity of use, and most of all active development and support are much better. Well done and thanks.

Regards,

Mike
