### ISSUE TITLE
Using without Tenant Validation

### ISSUE THREAD

**Issue by terencevs** [Finbuckle/Finbuckle.MultiTenant#341]
I was wondering if there is a way to use without doing Tenant Validation, so basically just using the features of adding the tenant ID to the EF queries.

This is the setup I am looking at:

User -> API Gateway - > API

The API gateway will do the Tenant Validation and then passes the tenant id on to the API in JWT but then the API does another validation to check if the tenant exists. I don't want to do the two calls, just the one.

Would this be bad practice?

**Comment by AndrewTriesToCode** [comment]
Yeah you can do that just by passing a `TenantInfo` into the constructor of the db context.

Can you give me a better picture of what you are trying to do? What do you mean by tenant validation exactly? Do you not want it to resolve the tenant, but rather just use a tenant you tell it to explicitly?

**Comment by terencevs** [comment]
Hi Andrew,

My API gateway calls the HTTP remote store to get the tenant information. At this stage the validation is done to check if the tenant exists. I am using Claim Strategy with tenant id in the JWT.

If this is a success the API gateway then calls the child API (with the JWT). At this stage I have configured the child API to also use Claim Strategy and HTTP Remote Store, but I don't really want it to call the remote store again. I just want to use the functionality Finbuckle provides by automatically adding the tenantId to all my EF queries.

Thanks

**Comment by AndrewTriesToCode** [comment]
I understand what you mean now. I would suggest you create a custom dummy store that just returns a `TenantInfo` object with the tenant id set on it exactly as the claims strategy extracted it. It would look something like this:

```cs
public class DummyStore<TTenantInfo> : IMultiTenantStore<TTenantInfo> where TTenantInfo : class, ITenantInfo, new()
{
    public Task<bool> TryAddAsync(TTenantInfo tenantInfo)
    {
        throw new NotImplementedException();
    }

    public async Task<TTenantInfo> TryGetAsync(string id)
    {
        throw new NotImplementedException();
    }

    public async Task<IEnumerable<TTenantInfo>> GetAllAsync()
    {
        throw new NotImplementedException();
    }

    public async Task<TTenantInfo> TryGetByIdentifierAsync(string identifier)
    {
        var result = new TTenantInfo { Id = identifier, Identifier = identifier };

        return await Task.FromResult(result);
    }

    public Task<bool> TryRemoveAsync(string id)
    {
        throw new NotImplementedException();
    }

    public Task<bool> TryUpdateAsync(TTenantInfo tenantInfo)
    {
        throw new NotImplementedException();
    }
}
```

The only caveat here is that the tenant claim stores the tenant identifier but EFCore uses the tenant id, so you'll just want to make sure they are the same.
