### ISSUE TITLE
How do we implement additional properties for TenantInfo when using EFCoreStore?

### ISSUE THREAD

**Issue by quartilesoftware** [Finbuckle/Finbuckle.MultiTenant#342]
Hi,

I’ve got a basic working example of a separate database per tenant which uses this in Startup.cs:
 services.AddMultiTenant<TenantInfo>()
    .WithEFCoreStore<MultiTenantStoreDbContext, TenantInfo>()
    .WithHostStrategy();

Using .WithEFCoreStore,  if I want to extend the content of TenantInfo, to store and retrieve additional properties, say, “Country” for each tenant, how and where do I do that in Finbuckle?

**Comment by quartilesoftware** [comment]
Old GitHub issues and the Docs have helped me to make some progress and I now have an  almost-working implementation by doing this:

1.	Create a custom class for AppTenant details which implements ITenantInfo 
2.	Create a custom MultiTenant store for the custom AppTenant class by following the description at https://www.finbuckle.com/MultiTenant/Docs/Stores
3.	Configure Finbuckle MultitenantServices in Startup.cs to use an EFCore store with the custom class and the custom store.

In Startup.cs -> Configure, a seeding method correctly populates the database, using the required service.

The remaining problem is that whatever changes I try, the controller which needs to use the multitenant service passed to it by dependency injection  always displays the error message :  “InvalidOperationException: Unable to resolve service for type 'AppTenantForFinbuckle' while attempting to activate 'Application.Controllers.HomeController'.  “

Can anyone please tell me where to start looking to find the cause of that error?


-----------------
Here are the key extracts:
Startup.cs:

```
        public void ConfigureServices(IServiceCollection services)
        {

            services.AddMultiTenant<AppTenantForFinbuckle>()
             .WithEFCoreStore<MultiTenantStoreDbContextUsingAppTenantForFinbuckle, AppTenantForFinbuckle>()
             .WithHostStrategy();


```


Custom  AppTenant class:

```

public class AppTenantForFinbuckle : ITenantInfo
{

    public string Id { get; set; }
    public string Identifier { get; set; }
    public string Name { get; set; }
    public string ConnectionString { get; set; }

    public string Country { get; set; }

}

```

Custom MultiTenantStore:


```

public class MultiTenantStoreDbContextUsingAppTenantForFinbuckle : EFCoreStoreDbContext<AppTenantForFinbuckle>
    {

        //The context for the database of all tenants


        public MultiTenantStoreDbContextUsingAppTenantForFinbuckle(DbContextOptions<MultiTenantStoreDbContextUsingAppTenantForFinbuckle> options) : base(options)
        {
        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer("A valid connection string");
            base.OnConfiguring(optionsBuilder);
        }


        public DbSet<AppTenantForFinbuckle> AppTenantForFinbuckle { get; set; }

    }

```

Database store seeding method called in Startup.cs ->Configure->SetupStore(app.ApplicationServices) 


```
    private void SetupStore(IServiceProvider sp)
    {
        Console.WriteLine("Seeding the store...");

        var scopeServices = sp.CreateScope().ServiceProvider;
        var store = scopeServices.GetRequiredService<IMultiTenantStore<AppTenantForFinbuckle>>();

        store.TryAddAsync(new AppTenantForFinbuckle
        {
            Id = "1",
            Identifier = "red.something.localhost:53408",
            Name = "Red",
            ConnectionString = "A string",
            Country = "ABC"
        }).Wait();

        Console.WriteLine("Added the first item to the store...");

        store.TryAddAsync(new AppTenantForFinbuckle
        {
            Id = "2",
            Identifier = "blue.something.localhost:53408",
            Name = "Blue",
            ConnectionString = "Another string",
            Country = "DEF"
        }).Wait();

        Console.WriteLine("Added the second item to the store...");

    }

```

**Comment by AndrewTriesToCode** [comment]
@quartilesoftware looks like you figured most of it out, but in `MultiTenantStoreDbContextUsingAppTenantForFinbuckle` you don't need the `AppTenantForFinbuckle` property -- it will be inherited automatically so your custom db context doesn't need much except for the connection info.

**Comment by quartilesoftware** [comment]
Thanks Andrew,

I made that change but still get the same error.

```

    public class MultiTenantStoreDbContextUsingAppTenantForFinbuckle : EFCoreStoreDbContext<AppTenantForFinbuckle>
    {

        //The context for the database of all tenants

        public MultiTenantStoreDbContextUsingAppTenantForFinbuckle(DbContextOptions<MultiTenantStoreDbContextUsingAppTenantForFinbuckle> options) : base(options)
        {
            Database.EnsureCreated();
        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer("A valid connection string");
            base.OnConfiguring(optionsBuilder);
        }

    }

```

```

InvalidOperationException: Unable to resolve service for type 'AppTenantForFinbuckle' while attempting to activate 'Application.Controllers.HomeController'.

```

Can you think of anything else I could try?

**Comment by quartilesoftware** [comment]
Adding an extract from HomeController.cs for completeness:


```
    public class HomeController : Controller
    {

        //If attempting to use AppTenantForFinbuckle:
        private readonly IConfiguration _configuration;
        private readonly IWebHostEnvironment _environment;
        private readonly AppTenantForFinbuckle _tenantInfo;

        public HomeController
        (
            IConfiguration configuration,
            IWebHostEnvironment environment,
            AppTenantForFinbuckle tenantInfo
        )
        {
            _configuration = configuration;
            _environment = environment;
            _tenantInfo = tenantInfo;

        }

```

**Comment by quartilesoftware** [comment]
I’ve also just tried not using dependency injection and instead doing this:


```
var theTenantInfo = HttpContext.GetMultiTenantContext<AppTenantForFinbuckle>()?.TenantInfo;
```
Which returns null for theTenantInfo

**Comment by AndrewTriesToCode** [comment]
Hm, can you give me a link to a github repo where I can try out the app and see the error?

**Comment by AndrewTriesToCode** [comment]
Question: is this code and error happening during the seeding, before a request? If so then there is effectively no tenant. Let me know if I have that right and I can offer some suggestions.

**Comment by quartilesoftware** [comment]
Hi Andrew,

Thanks for your offer of help, but I was spending too much time trying to get Finbuckle to work with a custom EF Core store and had to move on to focus on the business application. 

I’ve written my own small tenant resolver service to plugin to Startup.cs, which handles a host header strategy, unresolved tenants, separate databases or a single database and cookies per tenant. That was all I really needed and it works with exactly the same EF Core store I couldn’t get working with Finbuckle.

Regards,

Mike

**Comment by AndrewTriesToCode** [comment]
Mike, I'm glad you found a path forward. I'll take your experience as feedback that I need to improve the documentation in this area.
