### ISSUE TITLE
What to do with null tenant in HostStrategy

### ISSUE THREAD

**Issue by natelaff** [Finbuckle/Finbuckle.MultiTenant#348]
I have an MVC UI front end. In debug I use BasePathStrategy, but when published I use HostStrategy.

I want to create a landing page when the tenant doesn't exist (or hits the app subdomain). So, I created a LandingController that overrides the route to just be empty then shows that view.

In BasePathStrategy this works fine. Excluding the tenant takes me right to the landing page. Perfect.

However, in HostStrategy, now obviously it's just taking over every tenant name, which I should have anticipated, yet, did not.

So app.mysite.com should hit the landing page because "app" does not exist as a tenant. I thought adding it to ignoredidentifiers might have the desired effect, but, negative.

So, I can probably reverse this logic and make home controller not default, and check if a tenant is resolved then redirect, but this also brought up a potential interesting feature for adding a property to MultiTenantOptions such as TenantNotFoundPath that the middleware just redirects to to make signup pages and such easily accomplished.

So, now sourcing feedback on a) what's the most fluid way to deal with null tenants and b) is the TenantNotFoundPath redirect a good idea and worth investigating?

**Comment by natelaff** [comment]
Possible dupe of #239

**Comment by AndrewTriesToCode** [comment]
hi @natelaff 
What do your routes look like? Would it be acceptable in your case to have a static "default" or "app" tenant that stands in for these situations?

**Comment by natelaff** [comment]
Here's what I'm doing in the route

```csharp
            app.UseEndpoints(endpoints =>
            {
                switch (Configuration["MultiTenantStrategy"])
                {
                    case "Path":
                        endpoints.MapControllerRoute("Sign", "{__tenant__}/{area:exists}/{controller=Kiosk}/{action=Index}");
                        endpoints.MapControllerRoute("default", "{__tenant__}/{controller=Home}/{action=Index}");
                        break;
                    default:
                        endpoints.MapControllerRoute("Sign", "{area:exists}/{controller=Kiosk}/{action=Index}");
                        endpoints.MapDefaultControllerRoute();
                        break;
                }
            });
```

I thought about the static tenant name which will handle one case. Since my Azure app service is doing *.mysite.com to allow any of these through i was thinking it could be nice to allow sign up for that one. ("this domain doesn't exist yet, but it can be yours! sign up..."

**Comment by natelaff** [comment]
@AndrewTriesToCode what do you think about a concept like this...

```csharp
    public class MultiTenantOptions
    {
        public IList<string> IgnoredIdentifiers = new List<string>();
        public MultiTenantEvents Events { get; set; } = new MultiTenantEvents();
    }

    public class MultiTenantEvents
    {
        public Func<TenantNotFoundContext, Task> OnTenantNotFound { get; set; } = context => Task.CompletedTask;
    }

    public class TenantNotFoundContext
    {
        public object Context { get; set; }
        public string Identifier { get; set; }
    }
```

Then in the TenantResolver if the identifier is located but not resolved from the store this can be fired off:

```csharp
        public async Task<IMultiTenantContext<T>> ResolveAsync(object context)
        {
            IMultiTenantContext<T> result = null;

            foreach (var strategy in Strategies)
            {
                var _strategy = new MultiTenantStrategyWrapper(strategy, loggerFactory?.CreateLogger(strategy.GetType()));
                var identifier = await _strategy.GetIdentifierAsync(context);

                if (options.CurrentValue.IgnoredIdentifiers.Contains(identifier))
                {
                    Utilities.TryLoginfo(loggerFactory?.CreateLogger(GetType()), $"Ignored identifier: {identifier}");
                    identifier = null;
                }

                if (identifier != null)
                {
                    foreach (var store in Stores)
                    {
                        var _store = new MultiTenantStoreWrapper<T>(store, loggerFactory?.CreateLogger(store.GetType()));
                        var tenantInfo = await _store.TryGetByIdentifierAsync(identifier);
                        if (tenantInfo != null)
                        {
                            result = new MultiTenantContext<T>();
                            result.StoreInfo = new StoreInfo<T> { Store = store, StoreType = store.GetType() };
                            result.StrategyInfo = new StrategyInfo { Strategy = strategy, StrategyType = strategy.GetType() };
                            result.TenantInfo = tenantInfo;

                            break;
                        }
                    }

                    if (result != null)
                        break;

// NEW: FIRE TENANT NOT FOUND EVENT
                    if (options.CurrentValue.Events?.OnTenantNotFound != null)
                        await options.CurrentValue.Events.OnTenantNotFound(new TenantNotFoundContext() { Context = context, Identifier = identifier });
                }
            }

            return result;
        }
```

This opens up this possibility

```csharp
services.AddMultiTenant<TenantInfo>(config =>
                {      
                    config.Events = new MultiTenantEvents()
                    {
                        OnTenantNotFound = async (context) =>
                        {
                            if (context.Context is HttpContext httpContext)
                            {
                                httpContext.Response.Redirect($"/home/landing?identifier={context.Identifier}");
                                await Task.FromResult(0);
                            }
                        }
                    };
                })
```

This is working well on my end, and seems to be a pretty elegant solution to resolve what happens when the tenant is not resolved.

What do you think of this concept?

**Comment by natelaff** [comment]
Added a PR #351 to address this and #349 which is related.

**Comment by natelaff** [comment]
Oops. Didn't mean to hit close. Check out the PR and let me know if you like this concept :)

**Comment by AndrewTriesToCode** [comment]
Hi, I like the events idea. Let's add onto 6.1 once I get that out tomorrow.
