### ISSUE TITLE
Resolving tenant from API key

### ISSUE THREAD

**Issue by renhammington** [Finbuckle/Finbuckle.MultiTenant#352]
Hi Andrew

Love your work! This is such an awesome project - let us know how we can help you out financially! So much work has gone into this. Anyway, I have a question about the use of API keys. It would appear that the delegate strategy is the best for this situation, although I'm not sure how to access the store from within the delegate.

All requests will contain an API key in the header. From this, if I can access the store from within the delegate, I can look up the validate the key and return the relevant tenant. How would you do this?

`
services.AddMultiTenant<Tenant>()
				.WithDelegateStrategy(async context =>
				{
					var httpContext = context as HttpContext;
					if (httpContext == null)
						return null;

					httpContext.Request.Headers.TryGetValue("ApiKey", out StringValues apiKey);
					// Find the relevant tenant by apiKey
					// Return the tenant
				})
				.WithEFCoreStore<TenantsDbContext, Tenant>();`

**Comment by AndrewTriesToCode** [comment]
Hi @renhammington 

I think the delegate strategy will work well for you. We actually have a new HeaderStrategy coming out in a release this week so you might want to try that too. Regarding the store -- all the strategy needs to do is return the identifier. the middleware will try it against each store you have registered to find a match. It's all handled for you!

Also this week I'll be turning on the Github Sponsors page this week after the .NET 5 release -- thanks so much for your support.

**Comment by renhammington** [comment]
Awesome, thanks @AndrewTriesToCode. Just signed up as your first sponsor 👍 

Can I elaborate a bit more on the problem? Here's the approach I'm thinking:

- Each tenant can have many API keys with different scopes.
- The key can only be viewed once when they are first created. They're only stored in hashed form.
- Key format is a composite structure with a `{prefix}.{suffix}` format, such as `SBDwFikN.ja+2wmoMB8OGXrIY+OTlei8gKUqlYZHgviUMXb5A2EF4q37/lNcg7tj4wxjTPVFqmHBqHs2pJEItfDYxZ2z5kA==`  (a bit like SendGrid's approach
- The prefix is stored unhashed as an index, of sorts
- Importantly, the tenant identifier is not supplied in the headers

The process would be:

- Api calls come with ApiKey in the header
- Find the TenantApiKey record by the using the prefix of the supplied ApiKey
- Hash the suffix of the supplied ApiKey and compare against the hashed key stored in the TenantApiKey record
- If they match, then it's a valid apikey, and from here we can find the tenant

How would you recommend I do this using the delegate strategy? I'm coming from .Net 4.5 so this is a steep and rapid learning curve. Even a little guidance would help! 

I guess I could append the tenant identifier to the apikey so it would be `{tenantIdentifier}.{prefix}.{suffix}` as a workaround, but I'm not sure about the implications of that. Perhaps you'll have a view?

**Comment by AndrewTriesToCode** [comment]
@renhammington thanks so much for being my first sponsor!

This is an interesting situation you have. So you need to store the prefixed mapped to the  hashed suffix and identifier somewhere and the strategy will need access to it. 

You could use a something as simple as a Dictionary<string, (string hashedSuffix, string Identifier)> where the prefix is the key to the hashedSuffix / Identifier tuple. If the hashes match return the identifier. Wrap it in a POCO and register it as a singleton in DI and the strategy can access it, check for an dictionary item with matching key, check if hashes match, then return identifier. This is simple but only works for a single server. You'd need a fancier mapping with Redis or EFCore if you have multiple servers that need to handle the API requests. On the more complex side it could even be a microservice so your api servers contact it via http on the backend?

You could also store the mapping as a part of the tenant store. If you use more than one type of tenant store in your app it could get tricky, but very doable. If you use the EFCoreStore then this is similar to using the EFCore store approach described above.

Also you'd need to think about how the mapping gets populated and maintained.

Maybe you've already figured this all out -- but let me know how it goes. I can go into a little more detail if you'd like. The jump form .NET Framework to .NET Core can be tricky but I've found ASP.NET Core to be really well designed. If you hit any issues there let me know.
