### ISSUE TITLE
How to implement TablePerType Custamization with Identity Data Isolation Per Tenant

### ISSUE THREAD

**Issue by slnkykrn** [Finbuckle/Finbuckle.MultiTenant#361]
Hello,
I want to create multiple database depends on different tenants. But when I customize identity tables like AspNetUsers with additional column a dicsriminator column opened in table itself. But I want to use tablepertype strategy for inherited types.

I'm using .Net Core 3 by the way. Do I need to migrate .net 5.0 to handle this situation or do you have any suggestions ? 
Does .Net 5.0 version support this need ? 

Thank you.

**Comment by AndrewTriesToCode** [comment]
hi @slnkykrn 

I haven't played around too much with table-per-type but per [this doc](https://docs.microsoft.com/en-us/ef/core/modeling/inheritance#table-per-type-configuration) EFCore 5.0 is required. I don't think EFCore 5.0 itself actually requires .NET 5 though.

Anyway I think Finbuckle.MultiTenant is impacted much by this. If you run into any specific issues post some code and I'll take a look.

-Andrew

**Comment by slnkykrn** [comment]
Hello thanks for the answer actually I migrate by code to .net 5.0 and just give a try. finbuckle automatically restore ef.core 5.0 package so I could handle tpt . 
But I had an issue I want to spesific modified User approach for tenants like below I have more than one user definition :

    public class Example1: IdentityUser 
    {
        public int deneme { get; set; }
    }

    public class Example2: IdentityUser 
    {
        public int someFeature{ get; set; }
    }

You see I want to use Identity core with multi users who have their own properties, I could handle the db side but I couldn't handle AddIdentity in startup side.  Does finbuckle any solution for that issue ?

And I know finbuckle has an option like [MultiTenant] but when I use this option my migration ended up with below error :
System.InvalidOperationException: The index {'NormalizedUserName'} cannot be removed from the entity type 'Example1' because it is defined on the entity type 'IdentityUser'.

Thank you
