### ISSUE TITLE
Custom ITenantInfo additional values are always null .WithConfigurationStore()

### ISSUE THREAD

**Issue by mike-rowley** [Finbuckle/Finbuckle.MultiTenant#362]
I am trying to implement the Custom ITenantInfo functionality however there seems to be no real information or samples on how this works in the docs.

I have hopefully included all the pertinent code below.  The _multiTenantContextAccessor.MultiTenantContext.TenantInfo always returns NULL for every field in PaintMobileTenantInfo except the 4 TenantInfo fields.  All fields in the appsettings.json file exist for every client.

Any suggestions on what I am missing that I need to make this work?
Thanks
M

`
        public void ConfigureServices(IServiceCollection services)
        { ...
           services.AddMultiTenant<PaintMobileTenantInfo>()
                .WithConfigurationStore()
                .WithHostStrategy("__tenant__");
       ...}

        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        { ...
            app.UseMultiTenant(); 
       ...}

    public class PaintMobileTenantInfo : ITenantInfo
    {
        public string Id { get; set; }
        public string Identifier { get; set; }
        public string Name { get; set; }
        public string ConnectionString { get; set; }
        public string ClientID { get;set; }
        public string SharedSecret { get;set; }
        public string AzureBlobStorageAccount { get;set; }
        public string AzureBlobStorageKey { get;set; }
        public string AzureBlobStorageContainer { get;set; }
        public string AzureBlobStorageRootFolder { get;set; }
        public string AzureBlobStorageUserFilesFolder { get;set; }
        public string AzureBlobStorageContainerURL { get;set; }
        public string AzureBlobStorageUserFilesPathURL { get;set; }
        public string AzureBlobStorageDocumentsURL { get;set; }
        public string AzureBlobStorageProductImagesURL { get;set; }
        public string AzureBlobStorageLogosURL { get;set; }
        public string GoogleMapsAPIKey { get;set; }
    }

    public class zoPageModel : PageModel
    {
        protected PaintMobileDBContext _dbContext;
        protected PaintMobileTenantInfo _tenantInfo;
        protected readonly IMapper _mapper;
        protected readonly IHttpContextAccessor _httpContext;

        public zoPageModel(IHttpContextAccessor httpContext, PaintMobileDBContext dbContext, IMapper mapper, IMultiTenantContextAccessor<PaintMobileTenantInfo> _multiTenantContextAccessor)
        {
            _dbContext = dbContext;
            _httpContext = httpContext;
            _mapper = mapper;
            _tenantInfo = _multiTenantContextAccessor.MultiTenantContext.TenantInfo;
            
        }
 ...}
`

**Comment by mike-rowley** [comment]
I will leave this here in hopes that it helps someone else who made the same mistake I did.

When migrating from V5 to V6, custom ITenantInfo fields in the appsettings.json file need to be moved from the "Items" sub-array and put into the base array.

This is the structure for V6
`
 "Finbuckle:MultiTenant:Stores:ConfigurationStore": {
    "Defaults": {
      "ConnectionString": ""
    },
    "Tenants": [
      {
        "Id": "123",
        "Identifier": "123.domain.com",
        "Name": "123 domain",
        "ConnectionString": "<connectionstring>",
        "SharedSecret": "<sharedsecret>",
        "ClientID": "<clientid>",
        "ChallengeScheme": "challengescheme"
}
    ]
  }
`

This is the structure for V5  (NOTE the Item Array)
`
 "Finbuckle:MultiTenant:Stores:ConfigurationStore": {
    "Defaults": {
      "ConnectionString": ""
    },
    "Tenants": [
      {
        "Id": "123",
        "Identifier": "123.domain.com",
        "Name": "123 domain",
        "Items": {
           "ConnectionString": "<connectionstring>",
           "SharedSecret": "<sharedsecret>",
           "ClientID": "<clientid>",
           "ChallengeScheme": "challengescheme"
        }
}
    ]
  }
`

**Comment by AndrewTriesToCode** [comment]
hi @mike-rowley  It looks like you figured it out. I as also going to say to make sure to use the generic version of `IMultiTenantContextAccessor<T>` to make sure you get back your custom type. I'll try to improve the docs around this.

If you don't mind me asking, why do you use `IMultiTenantContextAccessor` rather than just directly injecting or getting `TenantInfo` from DI or using `HttpContext.GetMultiTenantContext<T>()? I'm trying to always understand others' use cases.

Cheers,
Andrew

**Comment by mike-rowley** [comment]
I started off using DI and after hours chasing the NULL values, its just where I ended up after trying all 3 approaches.  I will be converting it all back to DI.

Thanks
M
