### ISSUE TITLE
Make ignored identifiers case insensitive

### ISSUE THREAD

**Issue by natelaff** [Finbuckle/Finbuckle.MultiTenant#364]
Do you have any issue if TenantResolver check for ignored identifiers is made case insensitive?

https://github.com/Finbuckle/Finbuckle.MultiTenant/blob/612889bdddce4ab9143bc2f0988145fce12afa35/src/Finbuckle.MultiTenant/TenantResolver.cs#L67

Changing to something like this...?

```
 if (options.CurrentValue.IgnoredIdentifiers.Any(s => s.Equals(identifier, System.StringComparison.OrdinalIgnoreCase)))
```

**Comment by AndrewTriesToCode** [comment]
No feel free to include in your PR
This is even easier:
```if (options.CurrentValue.IgnoredIdentifiers.Contains(identifier, StringComparer.OrdinalIgnoreCase))```

**Comment by natelaff** [comment]
Cool! I will. I think I read Any was faster? This is probably insignificant in this case (even if that is the case)
