### ISSUE TITLE
How to update other tenant (single tenant, multiple tenants) data

### ISSUE THREAD

**Issue by endrihacker** [Finbuckle/Finbuckle.MultiTenant#367]
@AndrewTriesToCode I want to thank you for the support you gave me for [this issue](https://github.com/Finbuckle/Finbuckle.MultiTenant/issues/331).

What I want to achieve now is:

1. Migrate and Seed databases for each tenant
2. Update other tenant data

For topic 1:

To migrate all databases I use the following script:

   var tenants = _tenantStore.GetAllAsync().Result;
   
    foreach(var tenant in tenants)        
    {        
        ApplicationDbContext context = new ApplicationDbContext(tenant);
        await context.Database.MigrateAsync().ConfigureAwait(false);
    }

It works but what I don't like there is that I am creating `new ApplicationDbContext `  and not using DI to get the context. Is this the right way to do it since I want to do it for every tenant?

Also it would be better to do some seed data. Before I change the app to multitenant application it looked like [this](https://github.com/endrihacker/QuickAppMultitenant/blob/main/DAL/DatabaseInitializer.cs).

How to make it aware of tenant?

For topic 2:
Since I couldn't find something from the documentation (or I wasn't looking at the right place) I just noted [this closed issue](https://github.com/Finbuckle/Finbuckle.MultiTenant/issues/347) is close to what I want.
Is this the right approach to manage other tenants data? What I want to achieve is to create a tenant management dashboard which is able to control all the tenants.

**Comment by AndrewTriesToCode** [comment]
hi @endrihacker 

1. Your approach is good. DI is a tool in your toolbox, but not the only tool. Nothing wrong with what you have done here. You might want to call `Dispose` on each db context at the end of the loop or use a `using` around the db context so it gets auto-disposed. For seeding you could also do it in a similar loop. There's not a "best" way to handle seeding as far as I've been able to tell and because you need a tenant info instance some seeding approaches won't work--I usually just loop through the tenants and seed as needed.

2. You didn't say it, but I gather you are using `Identity`? I'm working on some extension methods on `UserManager` and `RoleManager` that will help with this in the next release but the basic idea in that post does work. The extension methods will be doing essentially the same thing.

I too am working on a tenant management UI so let me know what other challenges you come up against. You are probably a little further along than I am.

**Comment by endrihacker** [comment]
hi @AndrewTriesToCode 

1. Thanks for the tip on `Dispose` or `using`. This is my first project that I am implementing multitenancy and having to handle multiple databases is a challenge for me.

2. Yes I am using `Identity` but that was not the topic. I just used that sample because that's the only only one I found that was possible to modify **other tenant's data**.

Thanks for your great effort making this library simple and easy to use! I'll try to share the issues with you.
For now it seems that I am on the right track. 
Exciting to hear about UI tenant management.  👍

**Comment by endrihacker** [comment]
Hi @AndrewTriesToCode!

I have noticed that each time I need to modify other tenant data I need to do something like this: 

        var tenantManager = _httpContextAccessor.HttpContext.GetMultiTenantContext<ExtendedTenantInfo>()?.TenantInfo;
        var originalServiceProvider = _httpContextAccessor.HttpContext.RequestServices;
        var tenantToManage = await _tenantStore.TryGetAsync(_tenant.Id);


        // set tenant we want to manage
        _httpContextAccessor.HttpContext.TrySetTenantInfo(tenantToManage, true);


        // .... do some modifications for other tenant ........

        // reset serviceprovider and tenant
        _httpContextAccessor.HttpContext.RequestServices = originalServiceProvider;
        _httpContextAccessor.HttpContext.TrySetTenantInfo(tenantManager, false);


If I need to do it like this for every controller and action of the API these brings a lot of code duplicate. 
I want to make a certain tenant to be able to manage other tenants. 
Can this process be simplified?

**Comment by AndrewTriesToCode** [comment]
That's the basic pattern. It could be simplified based on what you are doing as the manager--is it mainly database or Identity stuff?
It might just be simple to create a new db context for the specific tenant and dispose of it, similar to your migration code.

If you need per-tenant options for any DI that happens as you do modifications then you're current approach is the cleanest way. You could wrap it in a helper function that takes a lambda or delegate for the tenant modifications. Something like this:
```cs
void DoTenantStuff(Action tenantConfig, HttpContext context)
{
    var tenantManager = _httpContextAccessor.HttpContext.GetMultiTenantContext<ExtendedTenantInfo>()?.TenantInfo;
    var originalServiceProvider = _httpContextAccessor.HttpContext.RequestServices;
    var tenantToManage = await _tenantStore.TryGetAsync(_tenant.Id);


    // set tenant we want to manage
    _httpContextAccessor.HttpContext.TrySetTenantInfo(tenantToManage, true);


    // call the delegate provided.
    tenantConfig();

    // reset serviceprovider and tenant
    _httpContextAccessor.HttpContext.RequestServices = originalServiceProvider;
    _httpContextAccessor.HttpContext.TrySetTenantInfo(tenantManager, false);
}
```

Then all your controllers and stuff would call this helper function and provide the logic they want to happen for the new tenant.
