### ISSUE TITLE
Where did WithRemoteAuthentication go?

### ISSUE THREAD

**Issue by Nisden** [Finbuckle/Finbuckle.MultiTenant#369]
Hello

So I am upgrading from an 5.x version to 6.1 and WithRemoteAuthentication have been removed?

How to I enable OIDC handling, but without enabling the rest of the WithPerTenantAuthentication options?

**Comment by AndrewTriesToCode** [comment]
hi @Nisden 
As you saw it's now called internally with the idea being to simplify things. Maybe I should re-expose it. Here's a simplified excerpt from `WithPerTenantAuthentication` that should provide the functionality without anything extra. Just plug it into your `ConfigureServices` method:

```cs
             var builder = AddMultiTenant<T>()...

             builder.WithRemoteAuthenticationCallbackStrategy();
            
            // We need to "decorate" IAuthenticationService so callbacks so that
            // remote authentication can get the tenant from the authentication
            // properties in the state parameter.
            if (services.Where(s => s.ServiceType == typeof(IAuthenticationService)).Any())
                throw new MultiTenantException("WithRemoteAuthenticationCallbackStrategy() must be called after AddAuthorization() in ConfigureServices.");
            services.DecorateService<IAuthenticationService, MultiTenantAuthenticationService<TTenantInfo>>();

            // Replace IAuthenticationSchemeProvider so that the options aren't
            // cached and can be used per-tenant.
            services.Replace(ServiceDescriptor.Singleton<IAuthenticationSchemeProvider, MultiTenantAuthenticationSchemeProvider>());
```

**Comment by Nisden** [comment]
Hey Andrew

I get the idea behind moving it all to WithPerTenantAuthentication, but we already have so much other stuff happening in the Cookie events/options, OIDC Options, etc. That having this library try to manipulate it as well might cause disaster :)

I would love to see the WithRemoteAuthentication reintroduced as a lower level component.

**Comment by Nisden** [comment]
Well.... MultiTenantAuthenticationService is internal, so I am unable to copy/paste the code.

**Comment by AndrewTriesToCode** [comment]
@Nisden Thanks for the PR, I agree with the change and will eventually merge it in.

**Comment by AndrewTriesToCode** [comment]
@Nisden I just release 6.2.0 which has the changes discussed.

`WithPerTenantAuthentcation` is just a called to these:
```csharp
builder.WithPerTenantAuthenticationCore(config);
builder.WithPerTenantAuthenticationConventions();
builder.WithRemoteAuthenticationCallbackStrategy();
```

which you can call yourself and skip the conventions stuff.
