### ISSUE TITLE
Claims strategy with IdentityDbContext scopes ITenantInfo before its resolved

### ISSUE THREAD

**Issue by chadbengen** [Finbuckle/Finbuckle.MultiTenant#379]
The ClaimsStrategy makes a call to AuthenticateAsync(), and in doing so it triggers a dependency on my MultiTenantIdentityDbContext.  This dbcontext is configured per the docs and has both constructors taking a ITenantInfo param.  This in turn scopes the ITenantInfo *before* the ClaimsStrategy is completed.  As a result all future ITenantInfo dependencies are null.  Further, the MultiTenantDbContext is scoped and fails to enforce the tenant constraints.

It's fairly easy to resolve the ITenantInfo issues with the following code; however, the dbcontext remains a problem (unless it is also changed to transient, but that is not desired). 

Any suggestions?

```csharp
services.RemoveAll<ITenantInfo>();
services.RemoveAll<Tenant>();
services.AddTransient<Tenant>(sp => sp.GetRequiredService<IMultiTenantContextAccessor<Tenant>>().MultiTenantContext?.TenantInfo);
services.AddTransient<ITenantInfo>(sp => sp.GetService<Tenant>());
```

**Comment by AndrewTriesToCode** [comment]
Hi, I see what you mean -- can you post what your authentication configuration looks like? Are you using a token in the cookie and restoring the session info from the database or something like that?

**Comment by chadbengen** [comment]
This is an identity server 4 site with the mulittenantidentitydbcontext registered with it. I am not storing the cookie nor a token in session storage, but I disabled session storage anyway with no affect.   Aside from the code below, i am also implementing a same site cookie fix found here, although i do not think they impact:

https://www.thinktecture.com/en/identity/samesite/prepare-your-identityserver/
 https://github.com/IdentityServer/IdentityServer4/issues/4165#issuecomment-599987118

Here's a dump of my configuration code:

```csharp
            var authenticationBuilder = services.AddAuthentication();
            
            // Configure cookie
            services.ConfigureApplicationCookie(options =>
            {
                // Cookie settings
                options.Cookie.Name = "MyCookie";
                options.Cookie.HttpOnly = true;
                options.ExpireTimeSpan = TimeSpan.FromMinutes(5);

                options.LoginPath = "/Account/Login";
                options.AccessDeniedPath = "/Account/AccessDenied";
                options.SlidingExpiration = true;
            });

            // Register dbcontext dependencies
            services.AddScoped<ValidateTenantRequirement>();
            services.AddScoped<IValidateTenantRequirement, TenantNotRequiredForIdentityServerEndpoints>();

            // Register user identity dbcontext
            var identityConnectionString = configuration.GetConnectionString("IdentityDbConnection");
            services.AddDbContext<IdentityDbContext>(options => options.UseSqlServer(identityConnectionString));
            
            // Register user identity
            var builder = services
                .AddIdentity<UserIdentity, UserIdentityRole>(options =>
                {
                    options.User.RequireUniqueEmail = true;
                })
                //.AddEntityFrameworkStores<IdentityDbContext>()
                .AddDefaultTokenProviders()
                .AddRoleStore<DefaultMultiTenantRoleStore>()
                .AddUserStore<DefaultMultiTenantUserStore>();

            // Remove default IUserValidators
            builder.Services.RemoveAll<IUserValidator<UserIdentity>>();

            // Register IUserValidators
            // TODO: Create tests to confirm if these are necessary with finbuckle identity base
            builder
                .AddUserValidator<UserIdentity, UserRequiresTenantIdValidator<UserIdentity>>()
                .AddRoleValidator<UserIdentityRole, RoleRequiresTenantIdValidator<UserIdentityRole>>()
                .AddUserValidator<UserIdentity, MultiTenant.Identity.Validators.UserValidator<UserIdentity>>()
                .AddClaimsPrincipalFactory<MultipleUserClaimsPrincipalFactory<UserIdentity, UserIdentityRole>>();

            // Register claims principal factory
            services.AddScoped<ISingleUserClaimsPrincipalFactory<UserIdentity, UserIdentityRole>, MultiTenantUserClaimsPrincipalFactory<UserIdentity, UserIdentityRole>>();

#if !DEBUG
            builder.AddUserValidator<UserIdentity, UserRequiresTwoFactorAuthenticationValidator<UserIdentity>>();
#endif

            services.Configure<IdentityOptions>(options =>
            {
                // Password settings.
                options.Password.RequireDigit = true;
                options.Password.RequireLowercase = true;
                options.Password.RequireNonAlphanumeric = true;
                options.Password.RequireUppercase = true;
                options.Password.RequiredLength = 6;
                options.Password.RequiredUniqueChars = 1;

                // Lockout settings.
                options.Lockout.DefaultLockoutTimeSpan = TimeSpan.FromMinutes(5);
                options.Lockout.MaxFailedAccessAttempts = 5;
                options.Lockout.AllowedForNewUsers = true;

                // User settings.
                options.User.AllowedUserNameCharacters =
                    "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-._@+";
                options.User.RequireUniqueEmail = false;
            });

            services.AddTransient<UserManager>();
            services.AddTransient<SignInManager>();
```

**Comment by chadbengen** [comment]
I saw your code for resetting the resolved services, and adding the same after the call to AuthenticateAsync resolves the issue:

```csharp
httpContext.RequestServices = httpContext.RequestServices.CreateScope().ServiceProvider;
```
However, i am a little concerned about using that line.  If there is an earlier pipeline that relies on scoped objects, i fear unexpected consequences.

I am thinking that a specific claims middleware that comes after the authentication would be safer?  I'm going to put one together and see how it works.  This MW would be in addition to the existing UseMultiTenant() and would replace the ClaimsStrategy and would only resolve the tenant if not already resolved.

**Comment by AndrewTriesToCode** [comment]
@chadbengen thanks for the details

A few thoughts
- you are getting into some advanced use cases and unfortunately there aren't any easy answers
- if I remember correctly the claims strategy calls uses the default `AuthenticateScheme` which Identity may have set up to do something with a database -- this might be worth looking into it
- regarding the scope as long as you don't overwrite context.RequestServices earlier pipelines shouldn't be impacted--in theory!

It sounds like you have a good handle on the situation. If you find something that works for you please share!

**Comment by chadbengen** [comment]
@AndrewTriesToCode thanks for your response and feedback.

I think i resolved the issue (much easier than i expected) by using IMultiTenantContext<T> in my IdentityDbContext instead of directly injecting ITenantInfo.

I am using custom UserStore and RoleStore objects to help get around some of the limitations with IdentityDbContext you mention in your docs, and those, too, needed to depend on IMultiTenantContext<T> instead of ITenantInfo.

Essentially, any authentication dependencies need to rely on IMultiTenantContext instead of ITenantInfo if using the ClaimsStrategy.

**Comment by chadbengen** [comment]
@AndrewTriesToCode i am repopening this with a little more to my resolution and perhaps a discussion about whether or not it makes sense to incorporate changes in the code base or if this issue should be resolved by individual developers.

First of all, my resolution above was a little short sighted.  Although the IMultiTenantContext solves some of the issues, the dbcontext model is still cached with a null tenantinfo object and so fails to properly filter queries.  

My updated solution is to inject IHttpContextAccessor and get the MultiTenantContext object dynamically.  Using this dynamic resolution of the ITenantInfo allowed the query filter to successfully execute.  

My code below might need some cleanup, but essentially my IdentityDbContext inherits your base class and uses my modified Identity classes.  The only modification to these classes is that i added TenantId to the UserIdentity and UserIdentityRole classes.  All other classes simply inherit the default asp identity class.

The constructor injects both IHttpContextAccessor and IMultiTenantContext<Tenant>.  I used global filters for simplicy and use the HttpContext to generate the MultiTenantContext dynamically. 

This implementation of the IdentityDbContext allows the claim strategy to remain unchanged.

```csharp
    public class IdentityDbContext :
        MultiTenantIdentityDbContext<
            UserIdentity,
            UserIdentityRole,
            string,
            UserIdentityUserClaim,
            UserIdentityUserRole,
            UserIdentityUserLogin,
            UserIdentityRoleClaim,
            UserIdentityUserToken>
    {
        private readonly IHttpContextAccessor _httpContextAccessor;
        private readonly IValidateTenantRequirement _validateTenantRequirement;
        private string TenantId() => _httpContextAccessor?.HttpContext?.GetMultiTenantContext<Tenant>()?.TenantInfo?.Id;
        private bool TenantIsNotRequired() => !_validateTenantRequirement.TenantIsRequired();

        public IdentityDbContext(IHttpContextAccessor httpContextAccessor
            , IValidateTenantRequirement validateTenantRequirement
            , IMultiTenantContext<Tenant> multiTenantContext) : base(multiTenantContext?.TenantInfo)
        {
            _httpContextAccessor = httpContextAccessor;
            _validateTenantRequirement = validateTenantRequirement;
        }

        public IdentityDbContext(IHttpContextAccessor httpContextAccessor
            , IValidateTenantRequirement validateTenantRequirement
            , IMultiTenantContext<Tenant> multiTenantContext, DbContextOptions<IdentityDbContext> options) : base(multiTenantContext?.TenantInfo, options)
        {
            _httpContextAccessor = httpContextAccessor;
            _validateTenantRequirement = validateTenantRequirement;
        }
        protected override void OnModelCreating(ModelBuilder builder)
        {
            base.OnModelCreating(builder);

            builder.Entity<UserIdentityRole>().ToTable(TableConsts.IdentityRoles);
            builder.Entity<UserIdentityRoleClaim>().ToTable(TableConsts.IdentityRoleClaims);
            builder.Entity<UserIdentityUserRole>().ToTable(TableConsts.IdentityUserRoles);

            builder.Entity<UserIdentity>().ToTable(TableConsts.IdentityUsers);
            builder.Entity<UserIdentityUserLogin>().ToTable(TableConsts.IdentityUserLogins);
            builder.Entity<UserIdentityUserClaim>().ToTable(TableConsts.IdentityUserClaims);
            builder.Entity<UserIdentityUserToken>().ToTable(TableConsts.IdentityUserTokens);

            builder.Entity<UserIdentity>().HasQueryFilter(a =>
                TenantIsNotRequired() || TenantId() == a.TenantId);
            builder.Entity<UserIdentityRole>().HasQueryFilter(a =>
                TenantIsNotRequired() || TenantId() == a.TenantId);
        }
```

edit: modified code.  IValidateTenantRequirement is an object that allows tenant to be null when the request is an IdentityServer4 endpoints.

**Comment by Valks** [comment]
I'm pretty sure I ran into the same issue. In the end to resolve it I modified the ClaimsStrategy so that it checked if the user was already authenticated because it would give an exception if it tried to call AuthenticateAsync a 2nd time.

Also, so that other parts of the pipeline could access the claims principle I attached it to the httpContext.User

https://github.com/Valks/Finbuckle.MultiTenant/blob/wip/src/Finbuckle.MultiTenant.AspNetCore/Strategies/ClaimStrategy.cs

Took my inspiration for the httpContext.User from: https://github.com/AzureAD/microsoft-identity-web/blob/master/src/Microsoft.Identity.Web/AzureFunctionsAuthenticationHttpContextExtension.cs

I'm not sure if checking the Identify.IsAuthenticated property is the best way to identify if Auth has already run but it works if the httpContext.User is set.

**Comment by AndrewTriesToCode** [comment]
@chadbengen 

Hello, just following up here. I'm surprised to hear that the dbcontext cache was caching a null tenant inside it -- it should not be doing that (or caching any specific tenant) but rather it should dynamically access the `ITenantInfo` property within the context for the query.

I'm glad `HttpContextAccessor` worked for you -- you might want to consider `IMultiTenantContextAccessor<T>` or the non generic version to prevent a dependency on `HttpContext` and AspNetCore. The `HttpContext` extension methods internally use the `IMultiTenantContextAccessor<T>` anyway so you would be skipping an unneeded layer.

Let me know if you are still thinking this over.
