### ISSUE TITLE
Create Tenant after user registration (Register) ang Get Tenant after login (Login)

### ISSUE THREAD

**Issue by morindo** [Finbuckle/Finbuckle.MultiTenant#391]
I've been trying to set up Finbuckle (nice project name btw) with these scenarios in mind.

1. Users get on the home page and register (/Identity/Account/Register), if the user does not exist, create the user and new tenant with a dummy Identifier.
3. Users get on the home page and login (/Identity/Account/Login), if the user exists, get the tenant from cookie, claims?.

I don't want to use Route, Base Path or Host strategy, just retrieve the tenant from the database, cookie, session, claims...

Is this feasible with Finbuckle?

**Comment by AndrewTriesToCode** [comment]
hello @morindo 

Yes this is doable. The closest sample is the ASP.NET Core 2 `SharedLoginSample` project but it is a little old. I probably need to update it. The basics still apply though.

If you simply add a `__tenant__` claim in the Identity claims table linked to the Identity user and configure it to add that claim to the generated `ClaimsPrincipal` (actually I think the default `UserClaimsPrincipalFactory` will automatically add it) the `ClaimStrategy` should work pretty well with it. You'll still need a multi tenant store of some sort and when you create the tenant initially for a new user you would want to add it to the store.

If your goal is have a single user per tenant you could write a store that actually just returns a dummy `TenantInfo` with the tenant id and identifier from the user. Then for per-tenant options or database stuff it would still pretty much work as if it were really tenants.

Let me know if you hit any roadblocks. I'm happy to help.

**Comment by morindo** [comment]
Thank you very much @AndrewTriesToCode, it works like a charm! Cheers!

**Comment by devalot76** [comment]
Hi @morindo ,
I'm also trying to achive this scenario, can you share some code, please?
