### ISSUE TITLE
Adding indexes for TenantId on EF Core Entities.

### ISSUE THREAD

**Issue by mpriem** [Finbuckle/Finbuckle.MultiTenant#393]
We've been working on a solution using the Finbuckle 5.0.4 library and EF Core for quite some time now  and are slowly running into some SQL performance challenges. This mainly has to do with the fact that there is no index on the TenantId column for the various entity tables, so it keeps doing table scans as Finbuckle adds the TenantId query.

Is there a preferred pattern on how to solve this with Finbuckle?

My first thought was to add indexes to my dbcontext class for each of my entities and most common filters and joins. For example I regularly filter on Product SKU, so the relevant composite index would become:

`modelBuilder.Entity<Product>().IsMultiTenant().HasIndex("TenantId","SKU");`

**Comment by AndrewTriesToCode** [comment]
hi @mpriem 
I'm actually working on this for the next release, but I think the solution will be workable for you to use as straight code. Here is a version derived from it that doesn't require the other changes in that branch:

```cs
        public static void AdjustIndex(EntityTypeBuilder builder, IMutableIndex index)
        {
            // Set the new unique index with TenantId preserving name and database name
            IndexBuilder indexBuilder = null;
#if NET
            builder.Metadata.RemoveIndex(index);
            if (index.Name != null)
                indexBuilder = builder
                               .HasIndex(index.Properties.Select(p => p.Name).Append("TenantId").ToArray(), index.Name)
                               .HasDatabaseName(index.GetDatabaseName());
            else
                indexBuilder = builder.HasIndex(index.Properties.Select(p => p.Name).Append("TenantId").ToArray())
                                      .HasDatabaseName(index.GetDatabaseName());
#elif NETSTANDARD2_1
            builder.Metadata.RemoveIndex(index.Properties);
            indexBuilder = builder.HasIndex(index.Properties.Select(p => p.Name).Append("TenantId").ToArray())
                                  .HasName(index.GetName());
#elif NETSTANDARD2_0
            builder.Metadata.RemoveIndex(index.Properties);
            indexBuilder = builder.HasIndex(index.Properties.Select(p => p.Name).Append("TenantId").ToArray())
                                  .HasName(index.Relational().Name);
#endif

            if (index.IsUnique)
                indexBuilder.IsUnique();

            return this;
        }
```

This would be used from `OnModelCreating` like so:
```cs
// get an index
origIndex = builder.Entity<Blog>().Metadata.GetIndexes().First();

// add TenantId to the index
AdjustIndex(builder.Entity<Blog>(), origIndex);
```

You could modify it pretty easily to adjust all the indexes on an entity type by looping through them all. Let me know if you run into any issues.
