### ISSUE TITLE
[question] how to inject TenantInfo instance in DataContext

### ISSUE THREAD

**Issue by r0lan2** [Finbuckle/Finbuckle.MultiTenant#395]
Acording documentation ITenantInfo can be injected in order to get the correct connectionstring.- 

`             

             public class MyAppDbContext : DbContext
            {
                private TTenantInfo TenantInfo { get; set; }
             
            public MyAppDbContext(MyTenantInfo tenantInfo)
           {
               // DI will pass in the tenant info for the current request.
               // ITenantInfo is also injectable.
               TenantInfo = tenantInfo;
           } 
        
           protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
           {
               // Use the connection string to connect to the per-tenant database.
               optionsBuilder.UseSqlServer(TenantInfo.ConnectionString);
           }
           ...
        }

`

I've created similar code but when I try use my MyAppDbContext the TenantInfo is null.-

           public void ConfigureServices(IServiceCollection services)
        {
            services.AddControllersWithViews();

            services.AddMultiTenant<TenantInfo>()
                .WithEFCoreStore<MultiTenantStoreDbContext, TenantInfo>()
                .WithBasePathStrategy();

            services.AddScoped<MyAppDbContext >();
        }

**Comment by AndrewTriesToCode** [comment]
@r0lan2 Can you show me your startup class? For tenant info to be injected the middleware must be setup to use multi tenant strategies and stores to determine the tenant for the request.

**Comment by r0lan2** [comment]
> @r0lan2 Can you show me your startup class? For tenant info to be injected the middleware must be setup to use multi tenant strategies and stores to determine the tenant for the request.

Yes, I edited the questions above :)

**Comment by AndrewTriesToCode** [comment]
In your app pipeline setup do you call `app.UseMultiTenant()` to actually use the middleware? And just to make sure, does the EFCore store have tenants inside it so the middleware will find a match for the base path?

**Comment by r0lan2** [comment]
@AndrewTriesToCode  , I am using app.UseMultitenant().. but I think something is missing.. maybe declaration of other service?
about the second question: Yes catalog database is working fine... the problem is when I try use the second datacontext in the homecontroller.cs

`
 public HomeController(FarmerDataContext context)
        {
            _context = context;
        }
`


the code is here:


https://github.com/r0lan2/MultitenantPoC/blob/main/BasePathStrategySample/Startup.cs

**Comment by r0lan2** [comment]
I did some changes into startup.cs but still with errors..
some times Constructor receive as null and other with a reference..
![image](https://user-images.githubusercontent.com/777801/108517863-b1ea6c00-72a6-11eb-813a-d7f3262376de.png)

![image](https://user-images.githubusercontent.com/777801/108518019-e1997400-72a6-11eb-9afd-292ff4ff87fd.png)


Note:  I am looking into your example here: https://github.com/AndrewTriesToCode/FinbuckleSqlServerToDo
But I don't see much differences..

**Comment by r0lan2** [comment]
@AndrewTriesToCode  me again :) 
I am looking into your examples located here: https://github.com/Finbuckle/Finbuckle.MultiTenant/blob/main/samples/ASP.NET%20Core%203/BasePathStrategySample/Controllers/HomeController.cs

And if you add the contructor to HomeController,  the first injections of TenantInfo will be null

` private TenantInfo _tenantInfo;
        public HomeController(TenantInfo tenantInfo)
        {
            _tenantInfo = tenantInfo;
        }
`
( With the code above I tried to do some llitle changes in order to isolate the issue and don't add more code related with my other tenant datacontext  :) )

**Comment by r0lan2** [comment]
Another option in order to move around this issue related with the injection in the contructor of controller is initalize the datacontext in the action method (works  but it's not the best)

`  public IActionResult Index()
        {
           
            var ti = HttpContext.GetMultiTenantContext<TenantInfo>()?.TenantInfo;
            if (ti == null)
                return View(new TransactionViewModel()
                {
                    TenantInfo = null,
                    Transactions = new List<Transaction>()
                });
            
            using (var context = new FarmerDataContext(ti))
            {
                var transactions = context.Transactions.ToList();
                return View(new TransactionViewModel()
                {
                    TenantInfo = ti,
                    Transactions = transactions
                });
            }
        }`

**Comment by AndrewTriesToCode** [comment]
hi @r0lan2 sorry for the delay. Thanks for all the detail I'm taking a look.

**Comment by AndrewTriesToCode** [comment]
When you get a null can you check the debug output or logs and see what the request is? I suspect that something is triggering a request without a basepath. Maybe Visual Studio is automatically requesting the path "/" without a tenant?
Just as a test I suggest you register a static tenant strategy after the basepath with a default or dummy tenant just so that if no tenant is found there will at least be something.

**Comment by TropinAlexey** [comment]
I had similar problem.
TenantInfo could not be injected if corresponding tenant not found in configuration storage. So, in my case I did a `_tenantInfo == null` check to route context to default database. I think it would be nice, if something like that could be in documentation
`protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            base.OnConfiguring(optionsBuilder);

            if (_tenantInfo == null) optionsBuilder.UseSqlServer(ConfigurationExtension.DefaultConnectionString);
            else optionsBuilder.UseSqlServer(_tenantInfo.ConnectionString);
        }`

Also, there is typo in documentation with wrong type `private TTenantInfo TenantInfo { get; set; }` in documentation that reproduced in this question #https://github.com/Finbuckle/Finbuckle.MultiTenant/issues/395#issue-810686595

**Comment by TropinAlexey** [comment]
@AndrewTriesToCode Hi!
Can you tell, on which case `Defaults: ConnectionString` from appsettings is used? I assume when any of tenants can't be resolved, but is it exact?

**Comment by TropinAlexey** [comment]
@AndrewTriesToCode Hi!
Can you tell, in which case `Defaults: ConnectionString` from appsettings is used? I assume when any of tenants can't be resolved, but is it exact behavior?

**Comment by AndrewTriesToCode** [comment]
@TropinAlexey 
It is used only as part of the configuration store and if you don't put that same setting in the json for a specific tenant the default will be used.

Cheers!
