### ISSUE TITLE
Identity/Account/Login not found

### ISSUE THREAD

**Issue by DavidDury** [Finbuckle/Finbuckle.MultiTenant#396]
Hi,

I got one of your samples: FinbuckleSqlServerToDo and made some changes to it:

- database per tenant
- subdomain/Host strategy  t1.localhost, t2.localhost, t3.localhost
- per tenant options, cookies, authentication, etc

It runs fine, I created the databases, subdomain resolved correctly, however when I go to t1.localhost for example and try to go to https://t1.localhost:5001/Identity/Account/Login or https://t1.localhost:5001/Identity/Account/Register I get 404 not found.

Any idea what is wrong in my setup?

Here is my startup.cs

`using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Finbuckle.MultiTenant;
using FinbuckleSqlServerToDo.Data;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.HttpsPolicy;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc.ApplicationModels;
using Microsoft.AspNetCore.Routing;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;

namespace FinbuckleSqlServerToDo
{
    public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddDbContext<TenantDbContext>(options =>
            {
                options.UseSqlServer(Configuration.GetConnectionString("TenantConnectionString"));
            });

            services.AddIdentity<IdentityUser, IdentityRole>(options => options.SignIn.RequireConfirmedAccount = false)
               .AddEntityFrameworkStores<TenantDbContext>()
               .AddSignInManager<SignInManager<IdentityUser>>()
               .AddUserManager<AspNetUserManager<IdentityUser>>()
               .AddRoleManager<RoleManager<IdentityRole>>()
               .AddDefaultTokenProviders();

            services.AddControllersWithViews();
            services.AddRazorPages();

            services.AddAuthentication(options =>
            {
                options.DefaultScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                options.DefaultChallengeScheme = CookieAuthenticationDefaults.AuthenticationScheme;
            })
             .AddCookie(options =>
             {
                 options.Cookie.SameSite = SameSiteMode.Strict;
                 options.Cookie.SecurePolicy = CookieSecurePolicy.Always;
             });
            services.AddAuthorization();

            // Register the tenant store db context.
            services.AddDbContext<ConfigDbContext>(options =>
            {
                options.UseSqlServer(Configuration.GetConnectionString("ConfigConnectionString"));
            });

            services.AddMultiTenant<TenantInfo>()
                    .WithEFCoreStore<ConfigDbContext, TenantInfo>()
                    .WithHostStrategy("__tenant__.localhost")
                    .WithPerTenantAuthentication()
                     .WithPerTenantOptions<CookieAuthenticationOptions>((options, tenantInfo) =>
                     {

                         options.Cookie.Name = $"{tenantInfo.Identifier}.auth.cookie";
                         options.Cookie.Domain = $"{tenantInfo.Identifier}.{Configuration.GetValue<string>("WebsiteMainDomain")}";
                         options.ExpireTimeSpan = TimeSpan.FromMinutes(5);
                         options.EventsType = typeof(CustomCookieAuthenticationEvents);
                         options.LoginPath = "/Identity/Account/Login";
                         options.AccessDeniedPath = "/Identity/Account/AccessDenied";
                         options.SlidingExpiration = true;
                     }).WithPerTenantOptions<IdentityOptions>((options, tenantInfo) =>
                     {
                         options.Password.RequireDigit = true;
                         options.Password.RequireLowercase = true;
                         options.Password.RequireNonAlphanumeric = true;
                         options.Password.RequireUppercase = true;
                         options.Password.RequiredLength = 6;
                         options.Password.RequiredUniqueChars = 1;

                         options.Lockout.DefaultLockoutTimeSpan = TimeSpan.FromMinutes(5);
                         options.Lockout.MaxFailedAccessAttempts = 5;
                         options.Lockout.AllowedForNewUsers = true;

                         options.User.RequireUniqueEmail = true;

                     }).WithPerTenantOptions<JwtBearerOptions>((options, tenantInfo) =>
                     {
                         options.Authority = $"{tenantInfo.Identifier}.auth.jwt.authority";
                     }); ;

            services.AddTransient(s => s.GetService<IHttpContextAccessor>().HttpContext.User);

            services.AddScoped<CustomCookieAuthenticationEvents>();
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            else
            {
                app.UseExceptionHandler("/Home/Error");
                // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
                app.UseHsts();
            }
            app.UseHttpsRedirection();
            app.UseStaticFiles();

            app.UseRouting();

            // Add Finbuckle.MultiTenant to the app pipeline.
            // Note the tenant route parameter configured below.
            app.UseMultiTenant();

            app.UseAuthentication();
            app.UseAuthorization();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllerRoute(
                    name: "default",
                    pattern: "{controller=Home}/{action=Index}/{id?}");

                endpoints.MapRazorPages();
            });
        }
    }

    public class CustomCookieAuthenticationEvents : CookieAuthenticationEvents
    {
        private readonly IHttpContextAccessor _httpContextAccessor;

        public CustomCookieAuthenticationEvents(IHttpContextAccessor httpContextAccessor)
        {
            _httpContextAccessor = httpContextAccessor;
        }

        public override Task ValidatePrincipal(CookieValidatePrincipalContext context)
        {
            return base.ValidatePrincipal(context);
        }

        public override Task RedirectToAccessDenied(RedirectContext<CookieAuthenticationOptions> context)
        {
            return base.RedirectToAccessDenied(context);
        }

        public override Task RedirectToLogin(RedirectContext<CookieAuthenticationOptions> context)
        {
            return base.RedirectToLogin(context);
        }

        public override Task RedirectToLogout(RedirectContext<CookieAuthenticationOptions> context)
        {
            return base.RedirectToLogout(context);
        }

        public override Task RedirectToReturnUrl(RedirectContext<CookieAuthenticationOptions> context)
        {
            return base.RedirectToReturnUrl(context);
        }

        public override Task SignedIn(CookieSignedInContext context)
        {
            return base.SignedIn(context);
        }

        public override Task SigningIn(CookieSigningInContext context)
        {
            return base.SigningIn(context);
        }

        public override Task SigningOut(CookieSigningOutContext context)
        {
            foreach (var cookieKey in _httpContextAccessor.HttpContext.Request.Cookies.Keys.Where(w => w.EndsWith(".auth.cookie")))
            {
                _httpContextAccessor.HttpContext.Response.Cookies.Delete(cookieKey);
            }

            return base.SigningOut(context);
        }
    }
}
`

**Comment by AndrewTriesToCode** [comment]
@DavidDury Hi would it be possible for you to provide a link to a repo so I can clone and look into this?

Some things I'd try initially to narrow down the problem:
- try a static strategy to see if problem still occurs
- do any identity pages load?
- can you set the logging to debugging level and see what the routing logic is doing?
