### ISSUE TITLE
[Question] Migration from 5.0.4 to v6 & QueryFilters

### ISSUE THREAD

**Issue by hbermani** [Finbuckle/Finbuckle.MultiTenant#397]
Hello,

I just want to start by thanking everyone who contributed to this amazing library, it has been so useful. I have a couple of questions I wanted to ask as it has been a while since I visited the repo:

1- Is there any guide to upgrading from v5.0.4 to the latest release, any breaking changes to anticipate.
2- I was reading about global query filters in EF Core documentation and found this statement from Microsoft "It is currently not possible to define multiple query filters on the same entity - only the last one will be applied. However, you can define a single filter with multiple conditions using the logical AND operator (&& in C#)." . Am I safe in assuming MultitenantDbContext doesn't implement EF Core query filter logic so I shouldn't be worried about this .  I had a look at the source code for MultitenantDbContext in the latest release and I don't seem to spot it in the onModelCreating override.

Thank you

Haider

**Comment by AndrewTriesToCode** [comment]
Hello, glad you like the library.

1. The biggest breaking change is the move to custom tenant info types. This removes the `Items` generic container from `TenantInfo` but you can also add whatever you want to an `ITenantInfo` implementation to add properties and such. It shouldn't be too much of a challenge to get that working especially if you don't use `Items`. The main changes are that you have to declare the type when you set it up like so: `AddMultiTenant<MyTenantInfo()` The sample projects should be pretty straightforward to follow.
2. Finbuckle.MultiTenant does in fact use a query filter, but it is smart enough to preserve any existing query filter as well. If you were to add a global query filter after the base class `OnModelCreating` it would be lost.

Cheers

**Comment by hbermani** [comment]
> Hello, glad you like the library.
> 
> 1. The biggest breaking change is the move to custom tenant info types. This removes the `Items` generic container from `TenantInfo` but you can also add whatever you want to an `ITenantInfo` implementation to add properties and such. It shouldn't be too much of a challenge to get that working especially if you don't use `Items`. The main changes are that you have to declare the type when you set it up like so: `AddMultiTenant<MyTenantInfo()` The sample projects should be pretty straightforward to follow.
> 2. Finbuckle.MultiTenant does in fact use a query filter, but it is smart enough to preserve any existing query filter as well. If you were to add a global query filter after the base class `OnModelCreating` it would be lost.
> 
> Cheers

Thank you for the reply Andrew. I'll have a look at upgrading my solution to the latest version, seems straight forward enough! (Famous last words lol).

As for the second point and query filters , you are bang on point, I just tested it and can confirm the behaviour.  I also had a look at the docs here https://www.finbuckle.com/MultiTenant/Docs/EFCore#existing-query-filters and it might help including the example of the base class. In my case I use class annotation to indicate Multitenant.  But most certainly any filters positioned after   base.OnModelCreating(modelBuilder); are resulting in multitenancy filter not working and them taking priority.  An easy mistake to make with big consequences if unnoticed. 

I'll close this noe :).
