### ISSUE TITLE
Can I use this library in production environment in my project?

### ISSUE THREAD

**Issue by mikeandersun** [Finbuckle/Finbuckle.MultiTenant#4]
I would like to switch from [SaasKit ](https://github.com/saaskit/saaskit)to this project. But I don't have time to evaluate it. 
Is there any live project that use this library?

**Comment by AndrewTriesToCode** [comment]
Hi, short answer is yes you can use it—but I’m not aware of it’s use in any other projects except my own. I just put out V 1.0 so there some more items coming such as better logging. I am out of the country on vacation but I can give you a better response tomorrow or Sunday.

**Comment by AndrewTriesToCode** [comment]
@mikeandersun 

Sorry for the delay. The project is production ready, but there are a few things to consider.

- The default `IMultiTenantStore` implementation is a simple in memory concurrent dictionary. It can read from the appsettings.json file or programmatically be configured using the Add/Remove methods, but you will probably want to implement your own that can connect to your database. If you do this you will want to register your implementation with dependency injection.

- Make sure to check out the samples projects to see how the different `IMultiTenantStrategy` implementation work. I recommend the host or route based strategies.

- I don't have the documentation for using with ASP.NET Core Identity ready yet--but it works with the basic Identity approach using string as the User key.

Thanks for you interest and let me know if you have any questions!
