### ISSUE TITLE
Reset cache

### ISSUE THREAD

**Issue by sookyee** [Finbuckle/Finbuckle.MultiTenant#401]
Hi,
In my database design, I have a users table storing the users name and email and this table is filtered based on tenant id. Each user can only see data that is assigned to the same tenant id. I have another table which maps these tenant id's to an identifier. This identifier is used to authenticate the user upon login. The login function gets the email of the user, matches the email in the users table, gets the tenant id, & matches this tenant id to the identifiers table. However, when I update the tenant id of a specific  user in the users table to point to a different tenant id, and I close the browser to log back in, my function is still grabbing the old identifier? However, in the database it shows that the tenant id column is updated to the new tenant id. 

I'm wondering if asp.net core or the finbuckle framework caches the tenant id somewhere and if its possible to clear this cache?

**Comment by AndrewTriesToCode** [comment]
hi @sookyee 

The Finbuckle EF Core support specifically tries to avoid caching for this reason, but it's possible that it could be happening somewhere. Can you post what your db context and your startup class look like and I can take a look for you?

**Comment by Nisden** [comment]
Depending on what "log back in" means, it could just be the authentication ticket that still contains the old claims. 
If so you need to update the Security Stamp, when you change TenantId.

**Comment by AndrewTriesToCode** [comment]
@Nisden makes a good point. If you are storing the tenant as part of the auth ticket in the cookie it probably isn’t rereading from the database. Look into extending the security validation or modifying the stamp on the db side when tenant is updated. 

Also tenant id is intended to never change whereas tenant identifier is designed to be changed. It sounds like you are doing something a little different. Are you trying to have multiple identifiers for a single tenant id?

**Comment by sookyee** [comment]
Hi sorry for the late reply. Yes @Nisden  was right the application was reading from the old auth ticket. Thanks everyone for the help!
