### ISSUE TITLE
Possible bug with latest version having Tenant Events

### ISSUE THREAD

**Issue by mkgn** [Finbuckle/Finbuckle.MultiTenant#405]
My tenants are in json file and each tenant has a dedicated database. Even though tenants are in json, I have a Tenant table in every database having one record for the tenant with extended properties.

So, when resolving tenants I do something like below

    options.Events = new MultiTenantEvents(){
        OnTenantResolved = async (context) =>
        {
             //Query my cache to see whether this tenant is available in cache
             //if tenant is not in cache, load the tenant with additional details from database
             //update context.TenantInfo

             context.TenantInfo = tenantFromDBwithAdditionalProperties;

             //some more stuff
        }
    }

Then in another place in code I access the tenant using;

    currentTenant = httpContextAccessor.HttpContext.GetMultiTenantContext<AppTenant>().TenantInfo;

However in this case it doesn't give me the tenant that I set in the TenantResolved event. At this point the custom tenant entity (AppTenant) has fields from tenants.json file only. However in OnTenantResolved event, I get the additional data from DB and set it to context.TenantInfo

Am I doing something wrong here?

**Comment by natelaff** [comment]
You cannot set the context.TenantInfo, that's a return object to give you the context of which tenant was found and how. Assigning something back there would have no effect.

**Comment by natelaff** [comment]
@AndrewTriesToCode i suppose I should have made that a read-only prop ;)

**Comment by natelaff** [comment]
You could add another store before your config store that looks at something like DistributedCache which has the full tenant object. So in this event check if the store is your configuration store, if so, add to the primary store. All future lookups would pull it from there, including your full extended properties. Andrew may have a better way to do it, that's how I'd probably tackle this though.

**Comment by AndrewTriesToCode** [comment]
@mkgn 

@natelaff  beat me to it -- I would recommend adding a store before the expensive store such as `DistributedCacheStore` or your own custom store just like nate stated

**Comment by AndrewTriesToCode** [comment]
@natelaff if you want to submit a PR to make it readonly feel free other wise I'll get to it. PRs are on hold for just a moment while I work on onboarding to the .NET Foundation

**Comment by natelaff** [comment]
@AndrewTriesToCode if you're freezing PRs for the moment I may just have you tweak it. It will be a small enough change for you to modify when you're in a better position.

**Comment by mkgn** [comment]
Oh I see, that property suppose to be a GET only :) Well, as you suggested apart from adding another store why can't we just override some stuff in Tenant details at this point? Does it mess up some thing down the line in your code? If we can do it, it'll be like overriding certain things in the already resolved tenant. Injecting additional details will be much more easier don't you think?

**Comment by natelaff** [comment]
Theoretically TenantResolver could be modified to wait for a return on this event and use that instance of the tenant. But from a best practice stand point I would strongly discourage it for performance issues that would likely popup. Seems like an unnecessarily expensive operation.

**Comment by mkgn** [comment]
I guess you are right. If allowed you never know what people might do at this point. A heavy operation will really kill the performance. As for my problem, I got it sorted with the standard store for the moment. I guess that property has to be a GET :)
