### ISSUE TITLE
[Edited] Issue was with .WithEFCoreStore But has been solved. Two DbContext were created insted of one and solved.

### ISSUE THREAD

**Issue by NikeshNiraula** [Finbuckle/Finbuckle.MultiTenant#407]

**Comment by NikeshNiraula** [comment]
But can we use only one dbcontext and work with it??

**Comment by AndrewTriesToCode** [comment]
@NikeshNiraula 
Hi It looks like you figured it out? Do you mind if I close the issue?

**Comment by NikeshNiraula** [comment]
@AndrewTriesToCode 
Sure. But is there any way to work with  .WithEFCoreStore with a single dbcontext??

**Comment by AndrewTriesToCode** [comment]
Yes, you can put it all into a single context that derives from `EFCoreStoreDbContext<T>` where T is your tenant info type. It also must implement `IMultiTenantDbContext` and have a few key things added as described [here](https://www.finbuckle.com/MultiTenant/Docs/EFCore#adding-multitenant-functionality-to-an-existing-dbcontext).

Then just make sure you **don't** mark the EFCore store entity `TenantInfo` as multitenant. You can add more entities and make them multitenant if you want.
