### ISSUE TITLE
Per tenant options from different databases and default tenant

### ISSUE THREAD

**Issue by TropinAlexey** [Finbuckle/Finbuckle.MultiTenant#408]
Hi @AndrewTriesToCode 
I have read all of documentation, stackoverflow and issues but had stuck on quite simple things.

I'm trying to configure multitenancy where there is default database that configured in `Finbuckle:MultiTenant:Stores:ConfigurationStore:Defaults:ConnectionString` `appconfig.json` section and has been added manually to tenants collection by code below to other tenants from `Tenants` section. What I want to do is use `Default` tenant if there is no resolved tenant for current request. Also, I'm configuring per tenant options, which are read from each database from table `LookupSettings` on start and stored in extended tenant info class:

```
public void Configure(IApplicationBuilder app, IWebHostEnvironment env, IConfiguration configuration)
        {
         ...
         app.UseMultiTenant();
         ...
         SetupTenantOptions(app.ApplicationServices);
         ...
         }

       private void SetupTenantOptions(IServiceProvider sp)
        {
            var scopeServices = sp.CreateScope().ServiceProvider;
            var tenants = scopeServices.GetRequiredService<IMultiTenantStore<TenantInfoExtended>>().GetAllAsync().Result.ToList();

            //add default tenant
            tenants.Add(new TenantInfoExtended
            {
                Id = "0", 
                Name = "Default", 
                Identifier = "Default", 
                ConnectionString = ConfigurationExtension.DefaultConnectionString
            });

            foreach (var tenant in tenants)
            {
                using (var db = new LookupSettingsDbContext(tenant))
                {
                   tenant.TenantOptions = db.LookupSettings.ToDictionary(k => k.Key, v => v.Value);
                }
            }
        }
    }
```

Corresponding to your guide, I have configured DI containers:

```
public void ConfigureServices(IServiceCollection services)
        {
        ...
        services.AddScoped<ITenantInfoExtended, TenantInfoExtended>();
        services.AddMultiTenant<TenantInfoExtended>()
                .WithHostStrategy()
                .WithConfigurationStore()
                .WithPerTenantOptions<PerTenantOptions>((options, tenantInfo) =>
                {
                    options.DefaultLanguageCode = tenantInfo.TenantOptions[Constants.TenantOptions.DefaultLanguageCode];
                    options.CountryCode = tenantInfo.TenantOptions[Constants.TenantOptions.CountryCode];
                    ...
                });
```

And TenantInfoExtended class looks like this:

``` public class TenantInfoExtended : ITenantInfoExtended
    {
        public string Id { get; set; }
        public string Identifier { get; set; }
        public string Name { get; set; }
        public string ConnectionString { get; set; }

        public Dictionary<string, string> TenantOptions { get; set; }
    }
```
After all I'm trying to do couple things:
1. In DbContext and my services to get instance of my default tenant if any other hasn't been resolved. I have workaround for dbContext like:
```     
       private readonly ITenantInfoExtended _tenantInfo;

        public ApplicationDbContext(ITenantInfoExtended tenantInfo) : base(tenantInfo)
        {
            _tenantInfo = tenantInfo ??= new TenantInfoExtended {ConnectionString = ConfigurationExtension.DefaultConnectionString};
           //ConfigurationExtension.DefaultConnectionString is getting it from appsettings.json Finbuckle:MultiTenant:Stores:ConfigurationStore:Defaults:ConnectionString section
        }
```
but in services, i'd like to get default tenant with it's options manually from tenant collection, something like:

`_tenantInfo = tenantInfo ?? scopeServices.GetRequiredService<IMultiTenantStore<TenantInfoExtended>>().GetAllAsync().Where(dt=> dt.Name == "Default");`

Is there is a way which I'm not able to find? 

2. Similar, I want to use default tenant options in any of my services. How can I achieve this in case any of my tenants are not resolved and I want to get them from default tenant options?

Thank you in advance and respects

**Comment by AndrewTriesToCode** [comment]
@TropinAlexey 
I recommend that you create a tenant named "default" and in your `AddMultiTenant<T>().... put a `WithStaticStrategy("default")`. So if the other strategies fail it will use the default one in that case.

So that's different than the default settings in the `app settings.json` file-- those defaults apply to tenants but they don't define a default tenant themselves. Good question! I should updated the docs.

**Comment by TropinAlexey** [comment]
Nice! Thanks for the clue Andrew, I'll leave this issue opened for a while to try your solution

**Comment by TropinAlexey** [comment]
works nice, thanks!
