### ISSUE TITLE
Finbuckle.MultiTenant joins the .NET Foundation 🎉

### ISSUE THREAD

**Issue by AndrewTriesToCode** [Finbuckle/Finbuckle.MultiTenant#414]
**Hello! 👋** 

I'm proud to annouce that Finbuckle.MultiTenant has officially been accepted into the [.NET Foundation](https://dotnetfoundation.org)! 🎉 
With the foundation's support this project will be poised to go to the next level!

With this major milestone I'd like to give a huge thank you to my first three sponsors:
@renhammington 
@cpcrook
@project-bi

Your support is amazing, and I really do appreciate it. ❤️
Sponsorships aren't you thing but you'd like to show support? Let me know! I'll take all the support I can get!

To everyone else: thank you for the contributions, questions, bug reports, and ideas! 👍

Here are some things I'm working on to help improve the project:
- more and faster pace of enhancements via CI/CD improvements
- private NuGet feed for sponsors with continuous releases as PRs are merged
- regularly scheduled public releases on NuGet.org (likely every 4 months)
- updated website and blog posts covering common questions and topics in depth
- and more open source tools for your developer's toobox

Thanks again and happy coding! 😎

**Comment by AndrewTriesToCode** [comment]
Titles are hard 😄

**Comment by Cpcrook** [comment]
Thanks for your work on this project, Andrew, really.  Hoping to dedicate some more time contributing code in the future.

**Comment by hbermani** [comment]
This is fantastic, well deserved @AndrewTriesToCode

**Comment by AndrewTriesToCode** [comment]
A big thank you to our newest sponsor, @hasansan07

Every little bit helps!
