### ISSUE TITLE
MultiTenantIdentityDbContext Implementation 

### ISSUE THREAD

**Issue by dhavalkateliya** [Finbuckle/Finbuckle.MultiTenant#416]
Hi,
I am trying to implement MultiTenantIdentityDbContext with WithEFCoreStore but i am not able to register the service.

**CustomTenantInfo** 
```
public class CustomTenantInfo : TenantInfo
    {
        public string CreatedBy { get; set; }
        public DateTime CreatedOn { get; set; }
        public string LastModifiedBy { get; set; }
        public DateTime? LastModifiedOn { get; set; }
        public bool IsDeleted { get; set; }
    }
```

**MyDBContext class**
```
public class MyDBContext : MultiTenantIdentityDbContext<MyDBContext , IdentityRole, string>
    {
        private readonly ICurrentUserService _currentUserService;
        private readonly IDateTimeService _dateTimeService;
        public MyDBContext(DbContextOptions<MyDBContext > options, ICurrentUserService currentUserService, IDateTimeService dateTimeService,CustomTenantInfo tenant_)
                    : base(tenant_, options)
        {
            _currentUserService = currentUserService;
            _dateTimeService = dateTimeService;
        }
}
```

**Startup**
` services.AddMultiTenant<CustomTenantInfo>().WithEFCoreStore<MyDBContext,CustomTenantInfo>().WithSessionStrategy();`

I am not able to register in service with above line of code.
please suggest where i am going wrong.

**Comment by AndrewTriesToCode** [comment]
@dhavalkateliya I apologize this question slipped through the cracks. Did you ever get it to work?

**Comment by AndrewTriesToCode** [comment]
Just following up here-- I noticed that you are trying to use a multitenant db context for your multitenant store. This is normally not needed and an advanced scenario. Generally the multitenant store is just a regular db context which holds info on all the tenants -- it is not per-tenant itself.

Then separately you have other dbcontext(s) that serve your app's functionality and they can be based on `MultiTenantDbContext` or the Identity variant. Does that make sense?

**Comment by dhavalkateliya** [comment]
Thanks @AndrewTriesToCode for clarification.
