### ISSUE TITLE
[Authorize] Atribute return error 404 because It is not returning /__tenant__/Identity/Account/Login

### ISSUE THREAD

**Issue by Corcoleison** [Finbuckle/Finbuckle.MultiTenant#417]
Hello:

First of all, thank you for all the work you do, now the question. I want to put a controller in Home and when you are not loggin into the application it returns you to the login page. This is very simple in a normal application but working with tenant I don't know how to solve it. It is supposed that the only thing you may need is [Authorize] atribute but It is not returning me the good url. Maybe I have to create a new attribute but I don't know how. I'm working with ASP.NET Core. Thanks

**Comment by natelaff** [comment]
I think this is because of the way Identity UI scaffolds things out. It dumps everything in that Identity folder and kind of creates issues when you're doing anything outside of that. I think you have to scaffold identity and change that login path because they hardcode that area path.

https://stackoverflow.com/questions/50682108/change-routing-in-asp-net-core-identity-ui

**Comment by Corcoleison** [comment]
> I think this is because of the way Identity UI scaffolds things out. It dumps everything in that Identity folder and kind of creates issues when you're doing anything outside of that. I think you have to scaffold identity and change that login path because they hardcode that area path.
> 
> https://stackoverflow.com/questions/50682108/change-routing-in-asp-net-core-identity-ui

Yes, It has to do with the Identity scaffolding thing, however, as I work with the HostStrategy in my final version, there it is working fine. Thank you for your answer. The ones that works with RouteStrategy or similar may have to change something or make an [Authorize] custom attribute that redirects to login or to a page error using the tenant route.

I mark the issue as close as I don't need the solution exactly for my project.

Thank you for your answer.
