### ISSUE TITLE
Error: Section name provided to the Configuration Store is invalid

### ISSUE THREAD

**Issue by TropinAlexey** [Finbuckle/Finbuckle.MultiTenant#419]
Hi, @AndrewTriesToCode .
I'm writing integration test with xUnit for my project and faced this error from title. The error appears only when I'm running test  and it is on line:

```var tenants = scopeServices.GetRequiredService<IMultiTenantStore<TenantInfoExtended>>().GetAllAsync().Result.ToList();```

When I'm running application it's ok. What could it be?

The test looks pretty like this:

```
        [Theory, InlineData("GET")]
        public async Task AppointmentGetZoomLinkAsync(string method)
        {
            var request = new HttpRequestMessage(new HttpMethod(method), "api2/appointments/createzoom/11977");
            var response = await _client.SendAsync(request);
            Assert.Equal(HttpStatusCode.OK, response.StatusCode);
        } 
```

**Comment by AndrewTriesToCode** [comment]
Can you show your test setup code? It looks like you are using the configuration multitenant store and you have to handle that differently for using tests. You could either use a different store or see how I use the configuration store in tests [here](https://github.com/Finbuckle/Finbuckle.MultiTenant/blob/4c422b3965ff326f3232cfeb7091d44dbe1db006/test/Finbuckle.MultiTenant.Test/Stores/ConfigurationStoreShould.cs#L61-L68https://github.com/Finbuckle/Finbuckle.MultiTenant/blob/4c422b3965ff326f3232cfeb7091d44dbe1db006/test/Finbuckle.MultiTenant.Test/Stores/ConfigurationStoreShould.cs#L61-L68):

https://github.com/Finbuckle/Finbuckle.MultiTenant/blob/4c422b3965ff326f3232cfeb7091d44dbe1db006/test/Finbuckle.MultiTenant.Test/Stores/ConfigurationStoreShould.cs#L61-L68

Note that you'll need a json file for the test to load similar to a normal appSettings.json file with tenant info inside it.

**Comment by TropinAlexey** [comment]
Thank you, Andrew
