### ISSUE TITLE
How to list all the tenants you have in appsettings.json

### ISSUE THREAD

**Issue by Corcoleison** [Finbuckle/Finbuckle.MultiTenant#420]
Hello:

Could I ask for a bit of help? I'm using for the moment the configurationStores approach and adding the tenant info into appsettings.json. I want to get all the tenants in a variable or something so that I can do a dropdown list of the tenants already available.

Thanks.

**Comment by Nisden** [comment]
You should be able to use IConfiguration to get a list of all keys.

https://stackoverflow.com/a/47060065/1020941

**Comment by AndrewTriesToCode** [comment]
@Corcoleison there is a method on the `IMultiTenantStore<T>` called `GetAllAsync` which you can await to get an `IEnumerable<T>` where `T` is your tenant info type. This will let you `foreach` through each tenant in the config file. You can get the `IMultiTenantStore<T>` straight out of the DI system in most cases.
