### ISSUE TITLE
Distributed Cache Store example

### ISSUE THREAD

**Issue by ingleo44** [Finbuckle/Finbuckle.MultiTenant#422]
Hi I am trying to implement a redis store but I can not find an example of how to do that using finbuckle multitenant, do you have any example available?

**Comment by AndrewTriesToCode** [comment]
Hi @ingleo44 
The best option is to look at the provided stores and see how they implement `IMultiTenantStore<T>`. There is aleady a store that uses the distributed cache and if you are using Redis via the distributed cache interface you are almost there. It shouldn't be too difficult -- it's just a few methods. If you have any specific questions on `IMultTenantStore<T>` I'm happy to help.

Here are links to the existing stores:
https://github.com/Finbuckle/Finbuckle.MultiTenant/tree/main/src/Finbuckle.MultiTenant/Stores
