### ISSUE TITLE
Not able to run Migartion

### ISSUE THREAD

**Issue by shreya-groot** [Finbuckle/Finbuckle.MultiTenant#424]
using Finbuckle.MultiTenant;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text;

namespace Data
{
    // Tenants will only see their own blog posts.
    [MultiTenant]
    public class BlogPost
    {
        [Key]
        public int MyProperty { get; set; }
    }

    // Roles will be the same for all tenants.
    public class Roles
    {
        [Key]
        public int MyProperty { get; set; }
    }
    public class MyAppDbContext: MultiTenantIdentityDbContext
    {
        private ITenantInfo TenantInfo { get; set; }
        //public MyAppDbContext() { }
        public MyAppDbContext(ITenantInfo tenantInfo) : base(tenantInfo) { }

        public MyAppDbContext(ITenantInfo tenantInfo, DbContextOptions<MyAppDbContext> options) :
            base(tenantInfo, options)
        { }

        public DbSet<BlogPost> BlogPost { get; set; }
        public DbSet<Roles> Roles { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            // Use the connection string to connect to the per-tenant database.
            optionsBuilder.UseSqlServer("Data Source=CODING-PLAYGROU\\SQLEXPRESS;Initial Catalog=Testing;User ID=CODING-PLAYGROU\\Shreya;Integrated Security=true");
            base.OnConfiguring(optionsBuilder);
        }
    }
}

This is my StartUp.cs file

using Data;
using Finbuckle.MultiTenant;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.HttpsPolicy;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication1
{
    public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddDbContext<MyAppDbContext>();
            //services.AddIdentityCore<IdentityUser>

            //        .AddEntityFrameworkStores<MyAppDbContext>();

            //services.AddIdentityCore<IdentityUser>()
            //        .AddEntityFrameworkStores<MyAppDbContext>();
            //            services.AddDbContext<MyAppDbContext>(options =>
            //options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));
            services.AddMultiTenant<TenantInfo>();
                //.WithSessionStrategy(Const.TenantKey);
          //.WithPerTenantAuthentication();
            services.AddControllersWithViews();
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            else
            {
                app.UseExceptionHandler("/Home/Error");
                // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
                app.UseHsts();
            }
            app.UseHttpsRedirection();
            app.UseStaticFiles();

            app.UseRouting();
            app.UseMultiTenant();
            app.UseAuthorization();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllerRoute(
                    name: "default",
                    pattern: "{controller=Home}/{action=Index}/{id?}");
            });
        }

    }
}
![Screenshot (15)](https://user-images.githubusercontent.com/76510195/116840070-34ba6c00-abf2-11eb-832c-44f86fa18a65.png)

**Comment by shreya-groot** [comment]
Please help me with this

**Comment by Nisden** [comment]
What database are you trying to do this against? Looking at your code you don't have any EF Provider specified, as the UseSqlServer is out-commented.
