### ISSUE TITLE
How to get multitenancy to work in a Blazor server-side app?

### ISSUE THREAD

**Issue by cryo75** [Finbuckle/Finbuckle.MultiTenant#425]
I have a server-side app deployed in IIS under it's own website, for example `myproduct.contoso.com/MyApp` This is all working fine.

Now I want to add multitenancy using BasePathStrategy and HostStrategy. So I set up the `appsettings.json` for multiple tenants. I also added the following to the `Startup.cs`:

```csharp
    services.AddMultiTenant<MyTenantInfo>()
        .WithConfigurationStore()
        .WithHostStrategy()
        .WithBasePathStrategy();
```

and

```csharp
    app.UseMultiTenant();
    app.UseAuthentication();
    app.UseAuthorization();
    app.UseEndpoints(endpoints =>
    {
        endpoints.MapControllerRoute("default", "{first_segment=}/{controller=Home}/{action=Index}");
        endpoints.MapRazorPages();
        endpoints.MapBlazorHub();
        endpoints.MapFallbackToPage("/_Host");
    });
```

As the `_Host.cshtml` is hit first when accessing the app, I added the following:

```csharp
    public PortalTenant Tenant { get; set; }

    public void OnGet()
    {
        Tenant = httpContextAccessor.HttpContext.GetMultiTenantContext<MyTenantInfo>()?.TenantInfo;
    }
```

And as I want to access the tenant info in my razor components, I passed the `Tenant` property to `App.razor`:

```csharp
    <CascadingAuthenticationState>
        <CascadingValue Value="@Tenant">
                    <Router AppAssembly="@typeof(Program).Assembly">
                        <Found Context="routeData">
                            <AuthorizeRouteView RouteData="@routeData" DefaultLayout="@typeof(MainLayout)">
                                <NotAuthorized>
                                    Not Authorized
                                </NotAuthorized>
                                <Authorizing>
                                    Wait...
                                </Authorizing>
                            </AuthorizeRouteView>
                        </Found>
                        <NotFound>
                            <LayoutView Layout="@typeof(MainLayout)">
                                <p>Nothing here.</p>
                            </LayoutView>
                        </NotFound>
                    </Router>
        </CascadingValue>
    </CascadingAuthenticationState>
```

So I deployed the app again and trying to access it using a tenant, eg. `https://myproduct.contoso.com/tenant1/MyApp`. So in this case BasePathStrategy should be used.

However, I get a 404.

What am I doing wrong? Do I need to setup `web.config` or any other settings in IIS?

If BasePathStrategy doesn't work for Blazor apps, I can use just HostStrategy (if it works for Blazor).

**Comment by AndrewTriesToCode** [comment]
Hi, Blazor can be tricky but in theory it should still work. I don't think you need to capture the tenant and pass it to component -- instead you should be able to inject the `TenantInfo` via DI or use `IMultiTenantContextAccessor<T>` or `HttpContext.GetMultiTenantContext`.

Normally the tenant related DI has a scoped lifetime but in Blazor I believe it reverts to a Singleton lifetime so after the first request the tenant is set via the `UseMultiTenant` step and not changed on further Blazor-routed pages for the same session.

I'm not a Blazor expert though so let me know if you observe otherwise.
