### ISSUE TITLE
Can I mock _httpContextAccessor.HttpContext.GetMultiTenantContext<TenantInfo> ()?.TenantInfo.

### ISSUE THREAD

**Issue by ingleo44** [Finbuckle/Finbuckle.MultiTenant#427]
Is there a way how to mock this method for unit testing?

**Comment by rdeharo** [comment]
I'm interested in this question. 
I think this is the way for debug multitenant applications in Visual Studio when the url is localhost:xxxx. 
Or do you know any other way for debug Finbuckle applications in Visual Studio debugger?

**Comment by Nisden** [comment]
Mocking GetMultiTenantContext is rather painful, as it invokes HttpContext.RequestServices.

If you want to be able to Mock TenantInfo in your controllers you would be better off having `IMultiTenantContextAccessor<TenantInfo>` as an constructor injection.

**Comment by AndrewTriesToCode** [comment]
@Nisden is right -- just use `IMultiTenantContextAccessor<TenantInfo>` directly rather than the `GetMultiTenantContext` which is just a simple wrapper for it anyway. Let me know if you run into any issues with this.

**Comment by ingleo44** [comment]
Thanks to all for your help

**Comment by shainegordon** [comment]
If anyone is interested, this is how I ended up doing a quick fix on our integration tests after adding multi-tenant support to our application

```
var multiTenantContextAccessorDescriptor = services.First(d =>
    d.ServiceType == typeof(IMultiTenantContextAccessor<ApplicationTenantInfo>));

services.Remove(multiTenantContextAccessorDescriptor);

// Register testing version
services.AddScoped<IMultiTenantContextAccessor<ApplicationTenantInfo>>(_ =>
{
    var multiTenantContextAccessor = Mock.Of<ITestingMultiTenantContextAccessor>();
    var multiTenantContext = new MultiTenantContext<ApplicationTenantInfo>
    {
        TenantInfo = new ApplicationTenantInfo
        {
            Id = "FAKE_TENANT",
            ConnectionString = _configuration.GetConnectionString(ConnectionStringName)!,
        },
    };
    multiTenantContextAccessor.MultiTenantContext = multiTenantContext;
    return multiTenantContextAccessor;
});

///

public interface ITestingMultiTenantContextAccessor : IMultiTenantContextAccessor<ApplicationTenantInfo>
{
    new IMultiTenantContext<ApplicationTenantInfo> MultiTenantContext { get; set; }
}

```

**Comment by AndrewTriesToCode** [comment]
That’s a good approach.

In v9 there is an internal implementation called `StaticMultuTenantContextAccessor` which I will make public in the 9.1 release that works well for this need. I created it for the MultiTenant db context create factory function and realize now that it should be public not internal. 
```
internal class StaticMultiTenantContextAccessor<TTenantInfo>(TTenantInfo? tenantInfo)
    : IMultiTenantContextAccessor<TTenantInfo>
    where TTenantInfo : class, ITenantInfo, new()
{
    IMultiTenantContext IMultiTenantContextAccessor.MultiTenantContext => MultiTenantContext;

    public IMultiTenantContext<TTenantInfo> MultiTenantContext { get; } =
        new MultiTenantContext<TTenantInfo> { TenantInfo = tenantInfo };
}
```
