### ISSUE TITLE
Which is the best way to debug Finbuckle applications in Visual Studio?

### ISSUE THREAD

**Issue by rdeharo** [Finbuckle/Finbuckle.MultiTenant#429]
I have a finbuckle application where I use resolution of tenant by url, so I don't know what is the strategy to debug applications in Visual Studio on local machine when url is always localhost:xxxx.

**Comment by Nisden** [comment]
Hi @rdeharo, what resolution strategy are you using?

If your using `.WithHostStrategy()` you can add aliases for localhost in your hosts file.
  1. Open Notepad as administrator
  2. Open the file `C:\Windows\System32\drivers\etc\hosts`
  3. Add a line `127.0.0.1 mydomainalias.tld`

(You can repeat the last step as many times as needed)

**Comment by AndrewTriesToCode** [comment]
Thanks @Nisden, I agree the hosts file is a good option. There are some fancy dns services out there that use tricks to ty to simulate this but I always run into problems with them.
