### ISSUE TITLE
AppIdentityDbContext Scoped Error

### ISSUE THREAD

**Issue by goforebroke** [Finbuckle/Finbuckle.MultiTenant#430]
I get an error when trying to add my AppIdentityDbContext service to the container.

```
System.AggregateException
  HResult=0x80131500
  Message=Some services are not able to be constructed (Error while validating the service descriptor 'ServiceType: Infrastructure.Identity.AppIdentityDbContext Lifetime: Scoped ImplementationType: Infrastructure.Identity.AppIdentityDbContext': No constructor for type 'Infrastructure.Identity.AppIdentityDbContext' can be instantiated using services from the service container and default values.)
  Source=Microsoft.Extensions.DependencyInjection
  StackTrace:
   at Microsoft.Extensions.DependencyInjection.ServiceProvider..ctor(IEnumerable`1 serviceDescriptors, IServiceProviderEngine engine, ServiceProviderOptions options)
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionContainerBuilderExtensions.BuildServiceProvider(IServiceCollection services, ServiceProviderOptions options)
   at Microsoft.Extensions.DependencyInjection.DefaultServiceProviderFactory.CreateServiceProvider(IServiceCollection containerBuilder)
   at Microsoft.Extensions.Hosting.Internal.ServiceFactoryAdapter`1.CreateServiceProvider(Object containerBuilder)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at Web.Program.Main(String[] args) in E:\repos\TenantProject\Web\Program.cs:line 16
```

Below is the code in that startup class in my Web project. I am able to add my AppDbContext to the container, which is inheriting from ` EFCoreStoreDbContext<TenantInfo>`, but I cant add my Identity data context.

```
public void ConfigureServices(IServiceCollection services)
{
  services.AddDbContext<AppIdentityDbContext>(x => x.UseSqlite(_config.GetConnectionString("IdentityConnection")));

  services.AddDbContext<AppDbContext>(x => x.UseSqlite(_config.GetConnectionString("DefaultConnection")));

  services.AddControllersWithViews();
}
```

Here is my code in my infrastructure project.

```
public class AppIdentityDbContext : MultiTenantIdentityDbContext<AppUser>
{
        public AppIdentityDbContext(ITenantInfo tenantInfo) : base(tenantInfo)
        {
        }

        public AppIdentityDbContext(ITenantInfo tenantInfo, DbContextOptions<AppIdentityDbContext> options) : base(tenantInfo, options)
        {

        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            base.OnConfiguring(optionsBuilder);
        }
}
```
I am using Finbuckle.MultiTenant.AspNetCore Version=6.2.0

Any help would be appreciated.

**Comment by goforebroke** [comment]
Looks like I fixed the issue adding the line of code below...

```
            services.AddMultiTenant<SampleTenantInfo>()
            .WithRouteStrategy()
            .WithConfigurationStore()
            .WithPerTenantAuthentication();
```
I had to continue reading the documentation...

[AddMultiTenant](https://www.finbuckle.com/MultiTenant/Docs/ConfigurationAndUsage#addmultitenant)

**Comment by goforebroke** [comment]
@AndrewTriesToCode ,

After going through the rest of the documentation I was able to setup [Per-Tenant Authentication](https://www.finbuckle.com/MultiTenant/Docs/Authentication), [Per-Tenant Data with EFCore](https://www.finbuckle.com/MultiTenant/Docs/EFCore#top), and[ Per-Tenant Data with Identity](https://www.finbuckle.com/MultiTenant/Docs/Identity) together. Does Finbuckle provide functionality that would allow a user to belong to one more than one tenant? In my database, the AspNetUsers table has the foreign key from the TenantInfo table ( 1 to many relationship between tenant table and user table). I hope to allow users to belong to more than one tenant. Is this possible?

**Comment by AndrewTriesToCode** [comment]
Hello,
many-to-many between users and tenants is doable, but there aren't any examples to follow -- I've found that these use cases are somewhat more advanced and vary significantly in requirements.

If you add an intersection table between AspNetUsers and TenantInfo you can make it work, but then you need a strategy that can determine which of the user's tenants is the "current" tenant. Also in this case Identity isn't really "per-tenant" or isolated as in the sample projects. I've had it work where a user could select their tenant and a it would set a session variable which the session tenant strategy then uses to determine the tenant. 

Another caveat of this is that your login page must not be tenant specific. The steps would look something like this:

1. User logs in and a part of their user data is the tenants they belong to. A default tenant for them is set via session variable before the successful login redirect.
2. Session tenant strategy is used thereafter to determine the current tenant per request.
3. User can select from a dropdown ui of their tenants if they want to switch. The controller for this simply updates the session variable and on subsequent requests the new tenant will be current.

This leaves out a lot of detail but that's the general idea.

**Comment by goforebroke** [comment]
@AndrewTriesToCode 

Thank you for your response, the information will help me as I proceed.  Do you anticipate adding an example of a many to many between users and tenants?

**Comment by AndrewTriesToCode** [comment]
I'd like to add  a sample like that or a blog post about it but it's not the top priority for now. Thank you!
