### ISSUE TITLE
how to change grant type for per tenant authentication?

### ISSUE THREAD

**Issue by iriapb** [Finbuckle/Finbuckle.MultiTenant#431]
Hi, 

I have downloaded your example for this, (per tenant authentication) and I managed to get it working somehow with 2 custom tenants, after some changes to their identity provider (both were test identity provider).

The question is that I need to set up the grant type per tenant to do authentication and I don't see how, I know that if I change it in the identity server, it works, but the idea is to be able to change it per tenant. 

I am using .NET core 3.1 and your example, how do i do that, please?

**Comment by AndrewTriesToCode** [comment]
Hi, the grant type is set in the `OpenIdConnectOptions` via the `ResponseType` property:
https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.authentication.openidconnect.openidconnectoptions.responsetype?view=aspnetcore-5.0

If you want to change it per-tenant you can use something like this:
```cs
services.AddMultiTenant<T>()...
         WithPerTenantOptions<OpenIdConnectOptions>((options, tenantInfo) => {
           options.ResponseType = tenantInfo.OpenIdConnectResponseType;
         };
```

This assumes your tenant info type has a property for which grant type you would want to use.

Does that make sense?

**Comment by iriapb** [comment]
thanks but it doesn't make much sense to me, as I thought that .UseMultiTenant could only be used in the Configure method and not in the ConfigurationServices

**Comment by AndrewTriesToCode** [comment]
You are right! I updated that response. I recommend you check out the per-tenant options section of the docs:
https://www.finbuckle.com/MultiTenant/Docs/Options#top

This assumes you are familiar with the ASP.NET Core options pattern. The docs should be able to get you started in addition to what I have above, but let me know if you can’t get it working. I can point you in the per-tenant authentication sample where such a change would go.

**Comment by iriapb** [comment]
This is my startup class:

public class Startup

    {

        public Startup(IConfiguration configuration)

        {

            Configuration = configuration;

        }

 

        public IConfiguration Configuration { get; }

 

        public void ConfigureServices(IServiceCollection services)

        {

            services.AddControllersWithViews();
                             

            services.AddMultiTenant<SampleTenantInfo>()

                .WithConfigurationStore()

                .WithRouteStrategy()

                .WithPerTenantAuthentication()

                .WithPerTenantOptions<OpenIdConnectOptions>((options, tenantInfo) => {

                    //options.ResponseType = tenantInfo.ResponseType;

                    options.Authority = tenantInfo.OpenIdConnectAuthority;

                    options.ClientId = tenantInfo.OpenIdConnectClientId;

                    options.ClientSecret = tenantInfo.OpenIdConnectClientSecret;

                    options.ResponseType = "code";

                });

            services.AddAuthentication(CookieAuthenticationDefaults.AuthenticationScheme)

        .AddCookie()

        .AddOpenIdConnect(options =>

        {

            options.Prompt = "login consent"; // For sample purposes.

                    });

             

        }

 

        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)

        {

            if (env.EnvironmentName == "Development")

            {

                app.UseDeveloperExceptionPage();

            }

 

            app.UseStaticFiles();

            app.UseRouting();

            app.UseMultiTenant();

            app.UseAuthentication();

            app.UseAuthorization();

 

            app.UseEndpoints(endpoints =>

            {

                endpoints.MapControllerRoute("default", "{__tenant__=}/{controller=Home}/{action=Index}");

            });

        }

    }

and the problem that I've got now is that after adding .WithPerTenantOptions(...); the tenants are not loaded, being that the only change, so I guess that I am missing something else

**Comment by iriapb** [comment]
kind of sorted, I get pass that, so the problem was that the code was including already options for OpenIdConnect, in 

`.AddOpenIdConnect(options =>`

    {

        options.Prompt = "login consent"; // For sample purposes.

                });
    }

so removing the options here allows me to pick ResponseType from the tenant info, problem is that it does not take the default options that come with .WithTenantAuthentication so I have to set up everything in the options field.

My new error is the following
OpenIdConnectProtocolException: Message contains error: 'invalid_client', error_description: 'The client secret supplied for a confidential client is invalid.', error_uri: 'error_uri is null'.

Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.RedeemAuthorizationCodeAsync(OpenIdConnectMessage tokenEndpointRequest)

the thing is that I am quite surprised because the same client secret works when I remove .WithPerTenantOptions<OpenIdConnectOptions>(options, tenantInfo...)

Any help, please?

**Comment by AndrewTriesToCode** [comment]
@iriapb I apologize for the delayed response

If you place a breakpoint in the `WithPerTenantOptions` code block where you assigning the client id and secret, does the `TenantInfo` object there have the correct values? Based on what you described it sounds like a at the point where the OpenIDConnect redirect is happening there is no known tenant.
