### ISSUE TITLE
tenant.json and tenant.Development.json

### ISSUE THREAD

**Issue by mkgn** [Finbuckle/Finbuckle.MultiTenant#433]
I am using {environment}.json files to load my different config files as below code

            var config = new ConfigurationBuilder()
                .AddJsonFile("appsettings.json",optional: false, reloadOnChange: true)
                .AddJsonFile($"appsettings.{environment}.json", optional: true, reloadOnChange: true)
                .AddJsonFile("serilog.json", false, true)
                .AddJsonFile($"serilog.{environment}.json", optional: false, reloadOnChange: true)
                .AddJsonFile("tenants.json", false, true)
                .AddJsonFile($"tenants.{environment}.json", optional: false, reloadOnChange: true)
                .Build();

Now I assumed that it should pick tenants.Development.json should be the one to get data loaded as it works for appSettings.json. So to test, I just had an empty tenants.json file { } and moved all tenant details to tenants.Development.json file.

Then I query the store to get the list of tenants and it throws an exception saying:

>>: 'Section name provided to the Configuration Store is invalid.' meaning it still tries to read the configuration from tenants.json and not tenants.Development.json.

I think this should be standard or may be I am doing something wrong here?

**Comment by AndrewTriesToCode** [comment]
hi @mkgn sorry for the slow response. Yeah it looks like it should work based on what you are doing.

Are you still having this issue? In theory the `ConfigurationStore` doesn't care about json files or anything at all -- anything that can load ASP.NET Core configuration can provide the needed values. Can you post the json of your tenants file?

**Comment by mkgn** [comment]
For the moment I changed my focus on to custom store (for which I raised another question to you) :) But i will look at this again in few days. May be we can close this and I will reopen if the case is still there ?
