### ISSUE TITLE
JWTBearer with MultiTenantAuthentication doesnt work

### ISSUE THREAD

**Issue by montella1507** [Finbuckle/Finbuckle.MultiTenant#434]
Hi,

i have tried tons of ways how to make JWT bearer with dynamic audience working..

Did all here:
https://www.finbuckle.com/MultiTenant/Docs/Authentication#using-withpertenantauthentication

I have tried all...
Auto mapping from appsettings..

```
 public class Realm : ITenantInfo
    {
        public string Id { get; set; }
        public string Identifier { get; set; }
        public string Name { get; set; }
        public string OpenIdConnectAuthority  { get; set; }
        public string Audience { get; set; }
        public string ChallengeScheme { get; set; }
        public string ConnectionString { get; set; }
    }
```

as well as manual - but it has NEVER BEEN CALLED:
```
          services.AddMultiTenant<Realm>()
                .WithStrategy(ServiceLifetime.Singleton, sp => new RealmIssuerStrategy())
                .WithStore(ServiceLifetime.Singleton,
                    sp => new ConfigurationRealmStore(sp.GetService(typeof(IConfiguration)) as IConfiguration))
                .WithPerTenantAuthentication()
                .WithPerTenantOptions<JwtBearerOptions>((o, tenantInfo) =>
                {
                    
                    o.Authority = "NEVER CALLED";
                });
```

It works when i set Authority and Audience "statically" via AddJwtBearer().
```
.AddJwtBearer(
                    options =>
                    {
                        options.Audience = Configuration["Jwt:Audience"];
                      options.Authority= Configuration["Jwt:Authority"];
                        
                    }
                );
```

but when i set only Authority (or NOTHING like someone did here:
https://github.com/Finbuckle/Finbuckle.MultiTenant/issues/303)

i have hot only 401 Unauthorized and 

```
 .WithPerTenantOptions<JwtBearerOptions>((o, tenantInfo) =>
                {
                    
                    o.Authority = "NEVER CALLED";
                });
```

is NEVER called.

**Comment by montella1507** [comment]
Missl

**Comment by AndrewTriesToCode** [comment]
@montella1507 
I want to follow-up did you get it working? I'd be happy to take a closer look for you.

**Comment by montella1507** [comment]
Hello.. yes.. it was... littlebit missleading.. I had wrong implementation of IMultiTenantStrategy (bug there). And because there is propably lazy-initiation of tenants in your beautiful project, 

 .WithPerTenantOptions<JwtBearerOptions>((o, tenantInfo) =>{})
 
 was never called, because my MultiTenantStrategy resolved always "null".


IMultiTenantStrategy -> NULL (as tenant) -> 401

Thats why i though there is a problem in your source code (because  .WithPerTenantOptions has been never called) 

BTW it resolved null, because User was null (was trying to resolve Tenant from JWT token - ISSUER claim.).  But a solution was easy (i parsed  JWT token manually in IMultiTenantStrategy and read issue claim)

**Comment by AndrewTriesToCode** [comment]
Ah ok, glad you got it sorted out. Good feedback, I should add more logging to help debugging these types of situations.

**Comment by montella1507** [comment]
i think it would be nice to add information, that "tenant store" or ".WithPerTenantOptions((o, tenantInfo) =>{})" is called lazily. So it is not called when (for example) MutilTenantStategy resolves null etc.
