### ISSUE TITLE
Change data from appsettings.json "Tenants" to a database

### ISSUE THREAD

**Issue by solopromiguel** [Finbuckle/Finbuckle.MultiTenant#435]
[DataIsolation]
Currently it brings the data of the "Tenants" from the appsettings.json, it is possible to bring them from a different database or have a default database that has the data of the Tenant

```
 "Tenants": [
      {
        "Id": "megacorp",
        "Identifier": "megacorp",
        "Name": "MegaCorp"
      },
      {
        "Id": "finbuckle",
        "Identifier": "finbuckle",
        "Name": "Finbuckle"
      },
      {
        "Id": "initech",
        "Identifier": "initech",
        "Name": "Initech LLC",
        "ConnectionString": "Data Source=Data/Initech_ToDoList.db"
      }
    ]
```

**Comment by AndrewTriesToCode** [comment]
Yes -- check out the `EFCoreStore` multitenant store (in the docs and samples) which can uses any database that EFCore has a provider for. It's also not too difficult to create your own store by implementing `IMultiTenantStore<T>` if you need something more custom.

**Comment by solopromiguel** [comment]
> Yes -- check out the `EFCoreStore` multitenant store (in the docs and samples) which can uses any database that EFCore has a provider for. It's also not too difficult to create your own store by implementing `IMultiTenantStore<T>` if you need something more custom.

Thanks for the answer, I have read the documentation more thoroughly and I have managed to implement it.
