### ISSUE TITLE
custom store provider using a Factory to return the custom store

### ISSUE THREAD

**Issue by mkgn** [Finbuckle/Finbuckle.MultiTenant#436]
I am trying to develop a custom store that will read below configuration and provide it to finbuckle (WithStore.....)

  "TenantReader": {
    "TenantConfigFile": "tenants.json",
    "Type": "CA.Core.StoreProvider", //Fully qualified type name of default provider
    "AzureConnectionString": "asdfads",
  },

Based on above there is a tenantstore provider that'll either provide a standard configuration store or azurestore (file/blob etc..)
Now i want to inject the store at the startup via the provider. I am not sure how to do that.

                services.AddMultiTenant<AppTenant>(options =>
                    MultiTenancyConfigurationExtentions.SetMultiTenantConfigurations(options, services,Configuration))
                .WithHostStrategy()
                .WithStore<MultiTenantCustomStore<AppTenant>>(ServiceLifetime.Singleton)
                .WithPerTenantAuthentication();

How should I tell .WithStore<MultiTenantCustomStore<AppTenant>>(ServiceLifetime.Singleton) to use my storefactory so it'll return the store based on my config file?

**Comment by AndrewTriesToCode** [comment]
@mkgn that's a tough one and I'm not sure I can give you a good answer. Can you post what you have so far of your custom store?

A few questions: 
1. is the `tenants.json` file being loaded into the app's configuration during the host creation (similar to how it loads `appsettings.json` by default)?
2. Is the Azure connection string for an Azure blob also containing a json file or for a database or something else?

**Comment by mkgn** [comment]
Hi, 

Yes, I mean I have basically got a copy of your existing ConfigurationFileStore and implemented my own because I needed some custom methods. So it works perfectly fine.

But now, there *will* be a  need in future to go on Azure webapp route which will need me to centralize the tenant.json (so if app scales still other instances can reach for the tenant.json file). So for that I am going to create another store(just using Azure files... not blob storage). So tenants.json will still be the same. Only the read/write will be changed to use Azure storage apis

What I want help with however is that to avoid hardcoding which store to use in the Startup.cs as we currently have;

WithConfigurationSTore() or WithStore<MyCustomStore>

Rather i was looking to keep the store fully qualified assembly(XYZ.Stores.AzureStore) in appSettings.json and then load the required store (configfilestore or azurefilestore) based on that.

It seems you have some advanced configurations made possible via .WithStore(sp=> ....) So I can do something like;

    .WithStore(sp => {
        //read what config provider to use from appSettings.config
       //make an instance and return to Finbuckle. ... 
    })

**Comment by AndrewTriesToCode** [comment]
Hi, sorry for the late reply. Have you made any progress on this?

I think the use of .NET host `Configuration` might be complicating matters somewhat and you might be better off with a custom store that simply grabs a json file from a url or from Azure storage and checks the json via `Newtonsoft.Json` or `System.Text.Json` for the tenant. The out-of-the-box `Configuration` *is* based on json but it brings a lot of baggage and other complexity with it that doesn't seem to add much value for you here.
