### ISSUE TITLE
Add MultiTenant support for generic IdentityDbContext<TUser, TRole, TKey, TUserLogin, TUserRole, TUserClaim, TRoleClaim, TUserToken> 

### ISSUE THREAD

**Issue by Cpcrook** [Finbuckle/Finbuckle.MultiTenant#44]
Per: https://github.com/entrypointsoft/AspNet.Identity.EntityFramework6/blob/master/src/AspNet.Identity.EntityFramework6/IdentityDbContext.cs

An implementation supporting the more explicit generic class would be useful.

I've got a branch going for this locally that I'm playing with at the moment.

~~Edit: FYI, doesn't look like I have the ability to push branches up with the access token provided.  I'll leave anything pertaining to an issue in the branch form: feature/{issue#}-{description} and submit PRs in the dev.~~

Forked.  PR submitted (after failing to sign initial commit)

**Comment by AndrewTriesToCode** [comment]
Thanks @Cpcrook this looks great. I think Identity has a bunch of intermediate classes in between the basic <TUser> and the fully generic one you submitted--I might add to your pull request to supply those intermediate forms as well.

**Comment by AndrewTriesToCode** [comment]
Listing out all the IdentityDbContext class variants for consideration:

- [x] IdentityDbContext
- [x] IdentityDbContext<TUser>
- [x] IdentityDbContetx<TUser, TRole, TKey>
- [x] IdentityDbContext<TUser,TRole,TKey,TUserClaim,TUserRole,TUserLogin,TRoleClaim,TUserToken>

Based on this I think all the MultiTenant functionality could be located in the class based on the last version lists above and the first 3 (refactor the already existing one) would just inherit from that MultiTenantIdentityDbContext.

Question: Should we assume the nonspecific generic types in the simpler versions should be treated as if they had the MultiTenant attribute? I think we could do this by deriving attributed versions of the standard Identity classes such as IdentityRole<TKey> with e.g. MultiTenantIdentityRole<TKey> which has the MultiTenantAttribute, but no other changes from its base version.

Alternatively we could just har code to recognize the build in types and treat them as such.

Either way, if someone had a an entity class here that they didn't want to be treated as MultiTenant for some reason they could use the long form class and plug in their own non-attributed type.

Update: Added the other class variants to the pull request. Need to do more testing before merging it.

**Comment by AndrewTriesToCode** [comment]
Completed with merging of PR #45. Thanks @Cpcrook !
