### ISSUE TITLE
Handling multi-tenancy when using Rebus for messaging

### ISSUE THREAD

**Issue by dietermijle** [Finbuckle/Finbuckle.MultiTenant#441]
Hi,

we are using [Rebus](https://github.com/rebus-org/Rebus) as a service bus for supporting [Messaging](https://microservices.io/patterns/communication-style/messaging.html) in our microservices.
Rebus supports hooking into their pipeline, thus making it possible to include multi-tenancy.
With below code, I'm able to setup the MultiTenantContext when handling an incoming Rebus message.

```
public async Task Process(IncomingStepContext context, Func<Task> next)
{
    var message = context.Load<Message>();

    var tenantContext = await _tenantResolver.ResolveAsync(context);
    if (tenantContext != null)
    {
        _tenantContextAccessor.MultiTenantContext = tenantContext;
    }

    await next();
}
```

Since Rebus also supports [Workers and parallelism](https://github.com/rebus-org/Rebus/wiki/Workers-and-parallelism), I would like to know if the above will work as is or if some custom magic will be required?
If I need some more magic, could you point me in the right direction here? What's the best solution to make this work?

Thanks in advance!

**Comment by AndrewTriesToCode** [comment]
hi @dietermijle 
This is an interesting question. I'll have to dig in a little but to better understand but in theory it should work just fine if DI is scoped per "message" in Rebus. Also, the `MultiTenantContext` is stored in an `AsyncLocal<T>` which should prevent different message processing in the same thread from stepping on each others' toes. I'll respond again later after I learn more.

**Comment by AndrewTriesToCode** [comment]
After digging in a little deeper I think this is a safe approach. Your direct use of the tenant resolver really simplifies things. As long as the tenant resolver is created at the right scope and the strategies/stores are injected appropriately you should be good to go. I'd probably try to have a single DI scope per message handled.

Let mek now how it's working out for you.

**Comment by dietermijle** [comment]
@AndrewTriesToCode we're moving forward with this now and first tests indicate that the tenancy is handled correctly.
For me its fine to close this one!
