### ISSUE TITLE
Can't access the store at runtime

### ISSUE THREAD

**Issue by endrihacker** [Finbuckle/Finbuckle.MultiTenant#442]
Hello @AndrewTriesToCode!

I have been using this library for a while and it is doing fine. I have currently configured EFCore Store and I am resolving tenants from there. However, since I have some increasing connections (because of the fact that tenants are resolved through the database), I thought I can add another store to make it skip for checking the database, since this will even increase the performance.
I tried `WithConfigurationStore` and it is working fine, but since the large number of tenants, `appsettings.json` gets  about 1Mb the application delays not a reasonable amount of time to start.

What I will try to add a custom store later, but I want something fast and I gave a try to `WithInMemoryStore`. What I want to achieve is to load the tenants from EFcoreStore and put them in MemoryStore (which is registered before than EFCoreStore in configuration at Startup).

Can I use both stores or not? I think I can but in the docs it seems to be a little bit contradictory:
[Here](https://www.finbuckle.com/MultiTenant/Docs/ConfigurationAndUsage#withstore-variants) says that I can't (if I understands it correctly):  

> Only the last store configured will be used.

Will be used for what?

[Here](https://www.finbuckle.com/MultiTenant/Docs/Stores#using-multiple-stores) says that I can:

> Multiple stores can be used...

I want to [access the store at runtime](https://www.finbuckle.com/MultiTenant/Docs/Stores#accessing-the-store-at-runtime) by type, but this code is giving me an error:

        var store = serviceProvider.GetService<IEnumerable<IMultiTenantStore<TenantInfo>>>
                                .Where(s => s.ImplementationType == typeof(InMemoryStore))
                                .SingleOrDefault();

> 'IMultiTenantStore<ExtendedTenantInfo>' does not contain a definition for 'ImplementationType' and no accessible extension method 'ImplementationType' accepting a first argument of type 'IMultiTenantStore<ExtendedTenantInfo>' could be found (are you missing a using directive or an assembly reference?)

I tried both with Finbuckle 6.1.0 and 6.2.0. Do I need to import something?
Does what I want to do makes sense?

**Comment by AndrewTriesToCode** [comment]
Hi, it is definitely possible and I need to update that part of the docs. 

What I recommend is that you use the distributed cache store (if can just be the in memory distributed cache of you don’t need Redis or anything fancy) followed by the efcore store. It’s not documented except in a PR but there is an event system for when a tenant is located in the store, you would want to hook into that and add the tenant to the cache store (with some expiration time) if it was resolved from the database.

Does that make sense? I am on my phone now but can give you more detail if needed. 

For your error above you will need to say `.Where( s=> s.GetType() == typeof(InMemoryStore))` I believe. The `ImplementationType` stuff is used when looking through services in the `ServiceCollection` during configuration whereas you are looking through the `ServiceProvider` most likely at runtime.

Also would you mind emailing me (my address is listed in my profile) so I can ask for some more feedback about the library offline?

**Comment by endrihacker** [comment]
Hi Andrew!
You are talking about PR [#359](https://github.com/Finbuckle/Finbuckle.MultiTenant/pull/359). This seems exactly to be what I wanted to achieve. Instead I was trying to add them all in the first application run, which is not that smart. I'll give it a try.

I just wanted Redis because app could be deployed in multiple instances in the near future. However I see you mentioned "memory distributed cache"... Does this work if application get deployed to multiple servers?

You'll have an email by now in your inbox :)

Thank you!

**Comment by endrihacker** [comment]
Hi,

im trying to use event `OnTenantResolved`, but can't find out how to get the store (InMemoryStore) to add the tenant that is just resolved.

In startup I have the following code

	services.AddMultiTenant<ExtendedTenantInfo>(config =>
	{
		config.Events = new MultiTenantEvents()
	        {
			OnTenantResolved = async (context) =>
	                {
				ITenantInfo tenant = context.TenantInfo;
				
				// 1. How to get an instance object of inMemoryStore?
				// 2. How to know from which store tenant is resolved?
				// because I don't need to add tenant to InMemoryStore again if it is already there

				//inMemoryStore.TryAddAsync(tenant);
				await Task.FromResult(0);
			}
		};
	})
	.WithInMemoryStore()
	.WithEFCoreStore<MultiTenantStoreDbContext, ExtendedTenantInfo>()				
	.WithDelegateStrategy(async context =>
	{
		string tenantId = ((Microsoft.AspNetCore.Http.HttpContext)context).User?.FindFirst("__tenant__")?.Value;
		return await Task.FromResult(tenantId);
	})
	.WithHeaderStrategy("tenant")

Those two questions I have are
  1. How to get an instance object of inMemoryStore?
  2. How to know from which store tenant is resolved?

**Comment by AndrewTriesToCode** [comment]
Sorry for the slow reply. The `TenantResolvedContext` passed into the event has a property `Context` which in ASP.NET Core is an instance of `HttpContext` so you can get the store with something like this:

```cs
config.Events = new MultiTenantEvents()
        {
		OnTenantResolved = async (context) =>
                {
			var tenant = context.TenantInfo;
			var sp = ((IHttpContext)context.Context).RequestServices;
                        var inMemStore = await sp.GetService<IEnumerable<IMultiTenantStore<MyTenantInfo>>>().Where(s => s.GetType() == InMemoryStore<MyTenantInfo>).FirstOrDefaultAsync();

			await Task.FromResult(0);
		}
	};
```

PS thanks for the email on your use of the library!
