### ISSUE TITLE
Simple per-tenant logic class instantiation

### ISSUE THREAD

**Issue by neil-thompson-sapphire** [Finbuckle/Finbuckle.MultiTenant#443]
I'm trying this

```
public class MyTenantInfo : TenantInfo
{
    readonly ITenantRules _tenantRules;

    public MyTenantInfo()
    {
        if (Id == TenantIds.A) _tenantRules = new ATenantRules();
        if (Id == TenantIds.B) _tenantRules = new BTenantRules();
    }
```

but at this point in the pipeline Id == null.

What's the correct way of achieving this (loading a class specific to the tenant into the TenantInfo)? - or am I going about this completely wrong!

Thanks

**Comment by AndrewTriesToCode** [comment]
hello,

in the tenant info constructor Id will always be null so what youa re trying to do here won't work. The library was designed to work best with the [Options pattern](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options?view=aspnetcore-5.0) which is not limited to ASP.NET Core but can be used in any .NET application.

The idea is that you write you app logic to take advantage of options, then in Finbuckle you can use [Per-tenant options](https://www.finbuckle.com/MultiTenant/Docs/Options) to customize the how the options are presented to your application via dependency injection based on the tenant.

There's a sample in the repo as well which will show how it works. Give it a shot and let me know if you run into any issues.
