### ISSUE TITLE
Resolving tenant based on Origin or Referrer headers

### ISSUE THREAD

**Issue by ihorbond** [Finbuckle/Finbuckle.MultiTenant#448]
Hey thanks for this excellent package, it saved me a lot of time!
I tried using it with host strategy but as you note in the docs, it makes local development hard (actually kinda impossible with our vue2 client app cause of the proxy package issue) so we figured what if we used either Origin or Referrer header instead ? Neither can be set programmatically (https://developer.mozilla.org/en-US/docs/Glossary/Forbidden_header_name) so that should be safe ? Would love to hear your thoughts on this and if you think it would be beneficial to add it as a strategy, thanks

Edit: just realized origin wont be set for same domain GET requests :/

**Comment by AndrewTriesToCode** [comment]
Hello, I think it could definitely work and no red flags come to mind. You could also use the host strategy and programmatically set the host header on your client request (I know curl [can do this](https://daniel.haxx.se/blog/2018/04/05/curl-another-host/)) for testing purposes.

Probably simpler to use origin or referrer for development environment and host for production.
