### ISSUE TITLE
MultiTenantOptionsManager is internal 

### ISSUE THREAD

**Issue by Albert-the-jit** [Finbuckle/Finbuckle.MultiTenant#450]
hi 
i was reading the docs for clear the IOptionsCache and see 

> When using per-tenant options via IOptions<TOptions> and IOptionsSnapshot<TOptions> the injected instance is of type MultiTenantOptionsManager<TOptions>. Casting to this type exposes the Reset() method which clears any internal caching for the current tenant and cause the options to be regenerated when next accessed via Value or Get(string name).

but when try Cast to `MultiTenantOptionsManager` I couldn't because of `internal ` type of this class [MultiTenantOptionsManager](https://github.com/Finbuckle/Finbuckle.MultiTenant/blob/851195020203683bb81bfcb9a6bb2581d914a2a0/src/Finbuckle.MultiTenant/Options/MultiTenantOptionsManager.cs#L26)
i find [Issue ](https://github.com/Finbuckle/Finbuckle.MultiTenant/issues/156)for this from 2019 and in 2019 PR was merged For this but somehow `MultiTenantOptionsManager` is still `internal`  and `Reset()` method is unreachable

**Comment by AndrewTriesToCode** [comment]
hi! thanks for reporting this issue. I will change it back to public this weekend and get it into the next release.

**Comment by Albert-the-jit** [comment]
thanks
