### ISSUE TITLE
Options Auto Cache Reset

### ISSUE THREAD

**Issue by Albert-the-jit** [Finbuckle/Finbuckle.MultiTenant#451]
hi 
i was write middleware for Auto Invalidation  of Options Cache and i see CONTRIBUTING.md

> Contributions are always welcome.

and

> For more complex changes or new features please file an issue before you open a pull request so we can discuss and plan accordingly.

i think its might be usefull

so i add this [repo](https://github.com/Azaferany/Finbuckle.MultiTenant.AspNetCore.OptionsCacheReset)
thanks

**Comment by AndrewTriesToCode** [comment]
hi @Azaferany this looks interesting. Go ahead and submit a pull request if you would like to, or if you prefer I can look at your fork and potentially add them myself. Thanks!

**Comment by Albert-the-jit** [comment]
thanks
I will send a PR

**Comment by Albert-the-jit** [comment]
hi @AndrewTriesToCode i was send PR for this in https://github.com/Finbuckle/Finbuckle.MultiTenant/pull/453

**Comment by AndrewTriesToCode** [comment]
hi, thanks for the PR I haven't had time to take a look yet
