### ISSUE TITLE
Finbuckle.MultiTenant 6.3.0 Released

### ISSUE THREAD

**Issue by AndrewTriesToCode** [Finbuckle/Finbuckle.MultiTenant#455]
Hello, version 6.3.0 is now available on NuGet.

First, a big **THANK YOU!!!** to my sponsors @cpcrook, @renhammington, @project-bi, and @hasansan07!

If you want to support this project please check out the sponsor button above. Every little bit helps.

This release is mostly bug fixes to clean things up before .NET 6 is released. Thanks to @lahma, @mphill, and @Nivalux for their help with some of the items below.

**6.3.0**
* Removed support for .NET Core 2.1 which ended Microsoft support in August 2020.
* Retargeted specifically to .netcoreapp3.1 and .net5.0 across all packages.
* Added `AdjustKey`, `AdjustIndex`, `AdjustAlIndexes`, `AdjustUniqueIndexes` methods to be chained off `IsMultiTenant` in EFCore functionality. They add the implicit `TenantId` to the respective key/indexes.
* Reverted generic version of `IsMultiTenant` back to non-generic version for more flexibility.
* Improved tenant resolution logging functionality and performance. Thanks to **@lahma**!
* Fixed a bug with `InMemoryStore` implementation of `TryUpdate`. Thanks to **@mphill**!
* Fixed a bug where `ConfigurationStore` would throw an exception if there was no default section in the config.
* Fixed a bug where ASP.NET Core Identity security stamp validation would force user logout and raise exceptions. Thanks to **@Nivalux** for finding the root cause of this bug.
* Fixed a bug where `MultiTenantOptionsManager<TOptions>` was internal instead of public.
* Fixed problematic references in sample projects.
* Updated and improved documentation.
* Updated and improved tests.
* Added various project files for .NET Foundation on-boarding.

**Comment by npongracic** [comment]
Hi Andrew, 
Why did you remove .NET Standard 2.1 support? It's not the same as netcoreapp2.1 and it's not going out of style.
I wanted to upgrade to the new version in my .NET Standard 2.1 project but i got the not supported error.

Thank you and kind regards,
Nebojša

**Comment by AndrewTriesToCode** [comment]
hi @npongracic I mainly did it to be consistent across all packages. I wouldn't be against the main `Finbuckle.MultiTenant` package targeting `netstandard` though would that work for your case? I could do a patch release or at the latest when .NET 6 is out I will have another release.

**Comment by npongracic** [comment]
Hi Andrew,
Thank you, that would be great, it's no hurry but just thought i should let
you know. I'm using the Finbuckle.MultiTenant.EntityFrameworkCore package
and it has the issue (even though it's EF Core it should work in .NET
standard libs).
It's not really a problem for me, i could change the project to a .NET core
project but it's kind of strange that something that has worked in version
6.2 has such a breaking change that it doesn't work in version 6.3 and it
took me a while to figure out the issue.

Thank you for your hard work and kind regards,
Nebojša

**Comment by AndrewTriesToCode** [comment]
@npongracic I reverted back to `netstandard2.1` with the 6.3.1 update.

**Comment by npongracic** [comment]
Hi Andrew,
Thank you, it is working great. :)

Kind regards,
Nebojša

**Comment by snax4a** [comment]
@AndrewTriesToCode 
I am configuring entities in separated classes implementing IEntityTypeConfiguration<TEntity>

```c#
public class GroupConfig : IEntityTypeConfiguration<Group>
{
    public void Configure(EntityTypeBuilder<Group> builder)
    {
        var key = builder.Metadata.GetKeys().First();
        builder.IsMultiTenant().AdjustKey(key, builder).AdjustIndexes(); // builder parameter has wrong type
        builder.Property(g => g.Name).HasMaxLength(32);
        builder.HasIndex(g => new { g.Name, g.CreatedBy });
    }
}
```

I would like to use AdjustKey in this configuration but this method expects `EntityFrameworkCore.ModelBuilder` instead of `EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder`

Do you have any suggestion how can I get ModelBuilder here?
