### ISSUE TITLE
Question : Read UI razor files depending on tenant 

### ISSUE THREAD

**Issue by remi0411** [Finbuckle/Finbuckle.MultiTenant#457]
Hello,

I tried to found but didn't found: It is possible to use a relative path to read razor files (ex Identity/Home/Index.html) per tenant ?

**Example:** 
On Tenant1, the engine could try to read file in that order : 
/Tenant1/Identity/Account/Index.html
/Identity/Account/Index.html (if previous doesn't exists)

If these files are copied into release folder, we could add tenant and specific UIs easily 
Thank you

**Comment by AndrewTriesToCode** [comment]
Hello,

There is no specific support for different view files but it is probably possible. Take a look at the [View Discovery](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/overview?view=aspnetcore-5.0#how-controllers-specify-views) by Microsoft. From this you could use the tenant name in path you pass to the `return View("...")` line or get fancy with an `IViewLocationExpander` implementation.

Let me know if you are able to get this working well. Thanks!

**Comment by remi0411** [comment]
Nice, thank you
OK with these gist : https://github.com/cloudscribe/cloudscribe/blob/master/src/cloudscribe.Core.Web/Design/SiteViewLocationExpander.cs

**Comment by AndrewTriesToCode** [comment]
hi sorry I didn't get back to you earlier -- I think that gist looks like it would work well -- did you have success with it?
