### ISSUE TITLE
WithEFCoreStore not working with PerTenantAuthentication

### ISSUE THREAD

**Issue by davidcateduclarity** [Finbuckle/Finbuckle.MultiTenant#458]
I am trying to implement PerTenantAuthenitcation in addition to a EFCoreStore method for resolving tenant.  Here is my services call.

`services.AddMultiTenant<MyTenantInfo>()
                    .WithRouteStrategy()
                    .WithEFCoreStore<MultiTenantStoreDbContext>()
                    .WithPerTenantAuthentication();`

I have tried this multiple times but I can't seem to get it to work.  I keep receiving the following error:

_CS1061FinbuckleMultiTenantBuilder<MyTenantInfo> does not contain a definition for 'WithEFCoreStore' and no accessible extension method 'WithEFCoreStore' accepting a first argument of type 'FinbuckleMultiTenantBuilder<MyTenantInfo>' could be found (are you missing a using directive of assembly reference?)_

Here is my MyTenantInfo class

`using Finbuckle.MultiTenant;

namespace FinbuckleIdentityDataIsoluation.Entities
{
    public class MyTenantInfo : ITenantInfo
    {
        public string Id { get; set; }
        public string Identifier { get; set; }
        public string Name { get; set; }
        public string ConnectionString { get; set; }
        public string CookiePath { get; set; }
        public string CookieLoginPath { get; set; }
        public string CookieLogoutPath { get; set; }
        public string CookieAccessDeniedPath { get; set; }
    }
}`

Any ideas on what is the issue?

**Comment by AndrewTriesToCode** [comment]
Hi, thanks for reporting this. I thought I had the same issue at first but realized it was a mistake on my part. I'm pretty sure that `WithPerTenantAuthentication` isn't part of the issue here, but I could be wrong.

The EFCoreStore sample pretty much does exactly what you are doing -- does that give you the same error? Do you have the `Finbuckle.MultiTenant.EntityFrameworkCore` package referenced in your application?

**Comment by AndrewTriesToCode** [comment]
Took a closer look and I think you need to change `WithEFCoreStore<MultiTenantStoreDbContext>()` to `WithEFCoreStore<MultiTenantStoreDbContext, MyTenantInfo>()`

**Comment by davidcateduclarity** [comment]
Yep, I was looking at other examples and just saw that  *slaps forehead*

Thank you for your time.

--Dave
