### ISSUE TITLE
String with Accent not supported

### ISSUE THREAD

**Issue by paburgos** [Finbuckle/Finbuckle.MultiTenant#459]
Hi,

When I define an entry in the config file like:

"Name" :  "Panadería"

It will not detect the encoding and the ITenantInfo concrete class will display a different character.

**Comment by AndrewTriesToCode** [comment]
hi, I am not able to reproduce this. I used the base path sample project and changed the name of the first tenant in the config file to `Panadería` and it displayed correctly. Can you post a sample project that shows the issue?
