### ISSUE TITLE
Remove All tenants from InMemoryStore

### ISSUE THREAD

**Issue by endrihacker** [Finbuckle/Finbuckle.MultiTenant#460]
Hi!

Is it possible to remove all the tenants at once from InMemoryStore? If yes how could I do it because I just see methods to remove them one by one `inMemStore.TryRemoveAsync("identifier")`.

Thanks!

**Comment by AndrewTriesToCode** [comment]
hi, I think the best option is to call `GetAllAsync` on the store and loop through it calling `TryRemoveAsync`. Would that work for you?

**Comment by endrihacker** [comment]
Hi!

Sorry for late reply... that's what I did but I just wanted to know if there was something simpler.
