### ISSUE TITLE
Multiple spa with multitenant

### ISSUE THREAD

**Issue by solopromiguel** [Finbuckle/Finbuckle.MultiTenant#461]
I am looking to redirect to an admin spa when tenant is null, otherwise redirect to user spa

```
app.Map("/admin",
   adminApp =>
   {
     adminApp.UseSpa(spa =>
     {
       spa.Options.SourcePath = "angular/admin";
       spa.Options.DefaultPageStaticFileOptions = new StaticFileOptions
       {
           FileProvider = new PhysicalFileProvider(Path.Combine(Directory.GetCurrentDirectory(), "angular", "admin"))
       };

       if (env.IsDevelopment())
         spa.UseProxyToSpaDevelopmentServer("http://localhost:4200");
      });
    });

  app.Map("/user",
    userApp =>
    {
      userApp.UseSpa(spa =>
      {
        spa.Options.SourcePath = "angular/user";
        spa.Options.DefaultPageStaticFileOptions = new StaticFileOptions
        {
            FileProvider = new PhysicalFileProvider(Path.Combine(Directory.GetCurrentDirectory(), "angular", "user"))
        };

        if (env.IsDevelopment())
          spa.UseProxyToSpaDevelopmentServer("http://localhost:4201");
      });
  });  

```

In the code used by routes, I try to do it through the tenantInfo, is it possible to do it or would there be a better way?
Thanks

**Comment by AndrewTriesToCode** [comment]
hi, I'm not too familiar with Angular but I noticed you have `spa.Options` there. Have you looked into using per-tenant options? You could have  default tenant called `_admin` or similar and register the static tenant strategy last. This will cause the tenant to default to `_admin` if no other tenant was found:
```cs
services.UseMultiTenant<MyTenantInfo>()...WithStaticStrategy("_admin") // static strategy registered after any other strategy used
    .WithPerTenantOptions<SpaOptions>((options, tenantInfo) =>
    {
        if(tenantInfo.name == "_admin")
        { 
           spa.Options.SourcePath = "angular/admin";
           spa.Options.DefaultPageStaticFileOptions = new StaticFileOptions
           {
           FileProvider = new PhysicalFileProvider(Path.Combine(Directory.GetCurrentDirectory(), "angular", "admin"))
           };
         }
    });
```

I'm not sure how the spa options are used but this way the admin one would be set if no other tenant was found, otherwise it would use your regular spa options. I think this way you wouldn't have to use `map` but instead a route value to determine the tenant or some other strategy.

**Comment by solopromiguel** [comment]
> hi, I'm not too familiar with Angular but I noticed you have `spa.Options` there. Have you looked into using per-tenant options? You could have default tenant called `_admin` or similar and register the static tenant strategy last. This will cause the tenant to default to `_admin` if no other tenant was found:
> 
> ```cs
> services.UseMultiTenant<MyTenantInfo>()...WithStaticStrategy("_admin") // static strategy registered after any other strategy used
>     .WithPerTenantOptions<SpaOptions>((options, tenantInfo) =>
>     {
>         if(tenantInfo.name == "_admin")
>         { 
>            spa.Options.SourcePath = "angular/admin";
>            spa.Options.DefaultPageStaticFileOptions = new StaticFileOptions
>            {
>            FileProvider = new PhysicalFileProvider(Path.Combine(Directory.GetCurrentDirectory(), "angular", "admin"))
>            };
>          }
>     });
> ```
> 
> I'm not sure how the spa options are used but this way the admin one would be set if no other tenant was found, otherwise it would use your regular spa options. I think this way you wouldn't have to use `map` but instead a route value to determine the tenant or some other strategy.

Thanks for your answer, I was trying with "WithPerTenantOptions" and SpaOptions, but it has not worked for me, it does not enter the WithPerTenant

**Comment by AndrewTriesToCode** [comment]
Hm, hard for me to be much help with my lack of knowledge on the SPA stuff -- do you have a projet on github I can fork to take a look at the issue closer?

**Comment by solopromiguel** [comment]
> Hm, hard for me to be much help with my lack of knowledge on the SPA stuff -- do you have a projet on github I can fork to take a look at the issue closer?

I have uploaded an example project, I hope you can review it please thanks  

[finbuckle-multiple-spa-issue-sample](https://github.com/solopromiguel/finbuckle-multiple-spa-issue-sample)

**Comment by AndrewTriesToCode** [comment]
Thanks for the repo. It seems this approach for SPA has been deprecated but I think you can still get this to work.
I think the best option will be to se `MapWhen` like this:
```cs
app.MapWhen(httpContext => httpContext.GetMultiTenantContext<TenantInfo>()?.TenantInfo == null,
   adminApp =>
   {
     adminApp.UseSpa(spa =>
     {
       spa.Options.SourcePath = "angular/admin";
       spa.Options.DefaultPageStaticFileOptions = new StaticFileOptions
       {
           FileProvider = new PhysicalFileProvider(Path.Combine(Directory.GetCurrentDirectory(), "angular", "admin"))
       };

       if (env.IsDevelopment())
         spa.UseProxyToSpaDevelopmentServer("http://localhost:4200");
      });
    });

app.MapWhen(httpContext => httpContext.GetMultiTenantContext<TenantInfo>()?.TenantInfo != null,
    userApp =>
    {
      userApp.UseSpa(spa =>
      {
        spa.Options.SourcePath = "angular/user";
        spa.Options.DefaultPageStaticFileOptions = new StaticFileOptions
        {
            FileProvider = new PhysicalFileProvider(Path.Combine(Directory.GetCurrentDirectory(), "angular", "user"))
        };

        if (env.IsDevelopment())
          spa.UseProxyToSpaDevelopmentServer("http://localhost:4201");
      });
  }); 
```

Good luck and let me now how it works out.
