### ISSUE TITLE
Show data for certain tenant AND data where TenantId is null

### ISSUE THREAD

**Issue by Erw1n** [Finbuckle/Finbuckle.MultiTenant#467]
You have a multitenant entity, and you have data in there  for tenant1, tenant2 and records where tenantId is null. 
Lets say you are logged in for tenant1, would it then be possible to show records where tenantId is equal to tenant1 and where tenantId is null?

**Comment by AndrewTriesToCode** [comment]
Yes, you can use EFCore's [`IgnoreQueryFilters()`](https://docs.microsoft.com/en-us/ef/core/querying/filters#disabling-filters) method and write your own where clause like this:
```cs
myDbContext.MyEntity.IgnoreQueryFilters().Where(e => e.Property("TenantId") == "tenant1" || e.Property("TenantId" == null)...
```

Does that make sense?

**Comment by Erw1n** [comment]
Yes thank you. I managed to implement it like this.
