### ISSUE TITLE
The requested service 'Finbuckle.MultiTenant.IMultiTenantContextAccessor` has not been registered

### ISSUE THREAD

**Issue by Vetsoftone** [Finbuckle/Finbuckle.MultiTenant#472]
We tried to access the Tenantinfo with

`HttpContext.GetMultiTenantContext<TenantInfo>();`

but unfortunatelly we receive the error thet IMultiTenantContext has not been registered.

The requested service 'Finbuckle.MultiTenant.IMultiTenantContextAccessor`1[[Finbuckle.MultiTenant.TenantInfo, Finbuckle.MultiTenant, Version=6.3.1.0, Culture=neutral, PublicKeyToken=null]]' has not been registered. To avoid this exception, either register a component to provide the service, check for service registration using IsRegistered(), or use the ResolveOptional() method to resolve an optional dependency.

If we use DI we get the TenantInfo. What is necessary to register to use the MultiTenantContext?

In Startup we do the following steps:

```
services.AddMultiTenant<VsoTenantInfo>()
                .WithInMemoryStore(options =>
                {
                    //options.IsCaseSensitive = true;
                    
                    options.Tenants.Add(new VsoTenantInfo {
                    ConnectionString= "Server = localhost; Database = Tenant1; Trusted_Connection = True; MultipleActiveResultSets = true",
                    Id="1",
                    Identifier="Tenant1",
                    Name="Tenant1"
                    });
                    
                })
                .WithRouteStrategy()
                .WithPerTenantAuthentication();
```

           ```
             app.UseMultiTenant();
            app.UseEndpoints(endpoints =>
            {                
                endpoints.MapRazorPages();
                endpoints.MapControllers();
                endpoints.Map("api/{__tenant__}/{**slug}", HandleApiFallback);
                
                endpoints.MapFallbackToFile("index.html");
            });
```

**Comment by AndrewTriesToCode** [comment]
Hi saw you closed the issue-- did you solve the problem?

**Comment by Vetsoftone** [comment]
It was my mistake. I added tenants with the type of VsoTenantInfo and tried to get the the TenantInfo with the type of TenantInfo.
