### ISSUE TITLE
Per-tenant options validation

### ISSUE THREAD

**Issue by Hammurabidoug** [Finbuckle/Finbuckle.MultiTenant#474]
In the .Net IOptionsFactory implementation [here](https://github.com/dotnet/runtime/blob/main/src/libraries/Microsoft.Extensions.Options/src/OptionsFactory.cs), you'll see that there is a constructor for injecting `IEnumerable<IValidateOptions<TOptions>>`. These are used in the Create method to validate the options.
```

 if (_validations.Length > 0)
            {
                var failures = new List<string>();
                foreach (IValidateOptions<TOptions> validate in _validations)
                {
                    ValidateOptionsResult result = validate.Validate(name, options);
                    if (result is not null && result.Failed)
                    {
                        failures.AddRange(result.Failures);
                    }
                }
                if (failures.Count > 0)
                {
                    throw new OptionsValidationException(name, typeof(TOptions), failures);
                }
            }

```
This block of code is missing from the MultiTenantOptionsFactory.Create method.

To include multi-tenant options validation, would it be better to create a custom multi-tenant options factory or perform options validation in some other manner? Or should the code above be included in the current MultiTenantOptionsFactory.Create method? The problem with creating a custom factory is that the ITenantConfigureOptions interface is not public.

**Comment by AndrewTriesToCode** [comment]
Thanks, should be a straight forward addition. I'll likely include in the next release.

**Comment by Hammurabidoug** [comment]
Do you know when you plan on a next release?

**Comment by AndrewTriesToCode** [comment]
> Do you know when you plan on a next release?

Probably this weekend. The only thing here is if unit tests are needed which add some complexity.
