### ISSUE TITLE
Upcoming Changes to Finbuckle.MultiTenant Releases

### ISSUE THREAD

**Issue by AndrewTriesToCode** [Finbuckle/Finbuckle.MultiTenant#476]
Hello! I have a few things to share about `Finbuckle.MultiTenant` going forward.

First, thank you to my handful of sponsors and contributors! Your support makes all the difference, and I truly appreciate it. Sponsorship options are $5/month or pick-your-own-number-one-time-lump.

Since .NET 5 was released in 2020 I have been unhappy with the pace of Finbuckle.MultiTenant progress. Why so slow? Many reasons, but a large contributor was the amount of  manual ceremony around publishing a quality release.

I recently took the time to automate most of the release items, and it feels like a whole new ballgame! Suddenly the project is fun again!

Going forward, releases will be much more frequent. I am a believer of taking the emotion out of version numbers so I'm adhering to continuous semantic releases. Get ready for some _uncomfortable_ and _awkward_ version numbers. 6.42.8. 12.3.19. Whaat? Whatever gets merged in following conventional commit rules!

But there's a catch! 😉

**Starting _after_ the `Finbuckle.MultiTenant` release for .NET 6 support:**

0. Latest Code will always be public and open source.
1. NuGet.org public packages will be updated twice per year (or in the event of a major issue, e.g. a critical security fix). One release after the latest .NET release, and one mid-cycle.
2. Monthly sponsors, PR contributors, and customers will have immediate access to all releases via a private NuGet feed. Accessing the feed will be as seamless as possible with minimal fuss. Stay tuned for more information if you are in this category!

This is designed to accomplish several goals:

0. Provide more frequent features and fixes.
1. Encourage sponsorships.
2. Encourage PR contributions.
3. Improve overall project health and sustainability.

Thanks again and please let me know what you think.

**Comment by markgould** [comment]
Glad to hear it's fun for you again! I haven't been keeping up on the project lately, and didn't realize you've now added sponsorships. Happy to sponsor this great project!

**Comment by AndrewTriesToCode** [comment]
Thanks @markgould I really appreciate it!

**Comment by Nisden** [comment]
Sounds like a good plan :)

**Comment by AndrewTriesToCode** [comment]
Just an update -- this is still in progress, but I'm still cutting public releases in the mean time.
