### ISSUE TITLE
Cannot Set TenantInfo Manually 

### ISSUE THREAD

**Issue by 3ilal** [Finbuckle/Finbuckle.MultiTenant#477]
I hope all is good

I am using Finbuckle 6.3.1 For Multitenancy  with .NET 5.0

I am using multiple authentication schemes in my Project (Cookies and JWT).

For Cookies Based Authentication the Tenant is being Resolved Host but for JWT I have to resolved it by claim. I have used claim strategy but it is not resolving the tenant from claim(don't know why maybe because of different authentication scheme). I have created a requirement handler which checks for the Claim and try to get the tenant and set it using TrySetTenantInfo but as soon as the request hit controller the tenant info is NULL however it is being set in the Requirement Handler.

Here is my code

`if (context.User?.Identity?.IsAuthenticated ?? false)
            {
                if (!context.User.HasClaim(x => x.Type == MultiTenantClaims.Tenant))
                {
                    context.Fail();
                    return;
                }
                
                if(context.Resource is HttpContext httpContext)
                {

                    var tenantIdentifier = context.User.FindFirstValue(MultiTenantClaims.Tenant);
                    if (!string.IsNullOrEmpty(tenantIdentifier))
                    {

                        var tenantMetaData = await tenantStore?.TryGetAsync(tenantIdentifier);
                            if (!string.IsNullOrEmpty(tenantMetaData?.ConnectionString))
                            {
                                if (httpContext.TrySetTenantInfo(tenantMetaData,true))
                                {
                                    context.Succeed(requirement);
                                    return;
                                }
                            }                        
                    }
                }               
            }`

I think this my be because of AsyncLocal being used to store TenantContext.

**Comment by AndrewTriesToCode** [comment]
Hi, It's because the `ClaimStrategy` used the default authenticate scheme but as of 6.4.0 you can tell it which scheme to use like this:
```cs
...WithClaimStrategy(claimName, JwtBearerAuthenticationDefaults.AuthenticationScheme);
```
where `claimName` is the name of the claim you want to check for the tenant identifier and the next param is the scheme, which should be similar to what I have above to get the default jwt auth scheme name.

Let me know if that works for you. If not I'll look close at `TrySetTenantInfo`

**Comment by 3ilal** [comment]
> Hi, It's because the `ClaimStrategy` used the default authenticate scheme but as of 6.4.0 you can tell it which scheme to use like this:
> 
> ```cs
> ...WithClaimStrategy(claimName, JwtBearerAuthenticationDefaults.AuthenticationScheme);
> ```
> 
> where `claimName` is the name of the claim you want to check for the tenant identifier and the next param is the scheme, which should be similar to what I have above to get the default jwt auth scheme name.
> 
> Let me know if that works for you. If not I'll look close at `TrySetTenantInfo`

Yes it Works.
Thank you
