### ISSUE TITLE
Disabling/enabling authentication for specific tenants

### ISSUE THREAD

**Issue by Hazzamanic** [Finbuckle/Finbuckle.MultiTenant#480]
I'm just evaluating this library for a project and I wondered if it was possible to disable authentication on a per tenant basis? I know it uses the options pattern and I couldn't immediately see a way to accomplish this. The scenario is basically that we will have some tenants requiring okta integration and some sticking with the standard forms authentication, and some having both. Nightmare. Do you think this would be possible?

Love the library, fantastic work, have found almost everything so clean and intuitive!

**Comment by AndrewTriesToCode** [comment]
Hi,  I apologize for the slow response.

I recommend you take a look at the `WithPerTenantAuthentication` sample -- it has two tenants that use OpenId Connect (with different Auth0 "servers") and one that uses cookie authentication. This is done by using `WithPerTenantOptions` on the `AuthenticationOptions` which lets you set the default challenge scheme different for each tenant.

You also have access to all authentication schemes at any point so if you prefer to not use the Options pattern you can just put a property for the tenant scheme on the `TenantInfo` object and in your code call `return Challenge(tenantInfo.scheme)` or similar.

Let me know how it goes or if you run into specific issues I can help with.

> Love the library, fantastic work, have found almost everything so clean and intuitive!

Thanks!
