### ISSUE TITLE
Return 403/404 if no tenant resolved for multi-tenant route?

### ISSUE THREAD

**Issue by Bouke** [Finbuckle/Finbuckle.MultiTenant#484]
I'm using the RouteStrategy with a parameter named `tenant`:

```cs
services.AddMultiTenant<TenantContext>()
        .WithRouteStrategy("tenant")
```

I'd like to invoke some delegate to return a custom response if a route is invoked with the `tenant` parameter ("multi-tenant route") and no tenant was resolved. What is the canonical way of implementing this? 

I can imagine a custom middleware that checks if the current endpoint has a `tenant` parameter and check if the tenant is not set:

```cs
app.UseMultiTenant();
app.Use(async (context, next) =>
        {
            if (context.GetEndpoint() is RouteEndpoint endpoint &&
                context.GetMultiTenantContext<TenantContext>() is null &&
                endpoint.RoutePattern.Parameters.FirstOrDefault()?.Name == "tenant")
            {
                context.Response.StatusCode = (int)HttpStatusCode.Forbidden;
                return;
            }

            await next();
        });
```

**Comment by AndrewTriesToCode** [comment]
Hi, your middleware idea seems like a reasonable approach.

I was going to recommend you use a default or dummy tenant and register the static strategy for that tenant after `WithRouteStrategy`. If it doesn't find  a tenant from the route it will use the static tenant as the default. In your controller simply checking if the tenant is the default tenant will tell you no tenant matched. The only problem I see here is other routes could still match so you'd still have to check the route data.

I say go with what you've got and let me know how it goes.

**Comment by Bouke** [comment]
This seems to be working fine so far, thank you for the feedback.

**Comment by AndrewTriesToCode** [comment]
Also just an fyi I’m planning to build this capability into the multi tenant middleware directly so stay tuned
