### ISSUE TITLE
Question: Get Connection String while setting up services

### ISSUE THREAD

**Issue by luisguermark** [Finbuckle/Finbuckle.MultiTenant#486]
I am setting up health monitoring - and need to set up the connection string to the database depending on the tenant.
So.... how do I get the constr in the ConfigureServices method?

TIA

**Comment by AndrewTriesToCode** [comment]
Hi, what type of health monitoring are you setting up? Generally in `ConfigureServices` there is not yet a tenant. Are you using a shared database or separate databases per tenant?

**Comment by luisguermark** [comment]
Im going with [AspNetCore.Diagnostics.HealthChecks ](https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks#HealthCheckUI). I have both cases, A couple of tenants sharing a database, and some more tenants with their own DB. 

Yep, I found there is no tenat in configureservices, and building the host doesnt give me one either.

Also, TY for the great work with Finbuckle.

**Comment by luisguermark** [comment]
I solved it writing custom Health Check that an httpcontext from DI.
