### ISSUE TITLE
Improve library with nullable reference types

### ISSUE THREAD

**Issue by fossbrandon** [Finbuckle/Finbuckle.MultiTenant#487]
Nullable reference types (NRTs) were introduced in C# 8 to help developers understand their usage of `null` values throughout their code to avoid unexpected exceptions on edge cases or explicitly mark values as nullable if they are intended to be. More information can be found in the [official Microsoft docs](https://docs.microsoft.com/en-us/dotnet/csharp/nullable-references).

I feel like security critical libraries like this one could really benefit from implementing this feature for the following reasons:

1. It would improve the library code itself by ensuring all possible null cases are accounted for (Ex: Adding null checks or making variables nullable).
    - This is important because even if the current code is null safe without this feature now, future code may introduce edge cases that aren't caught. This feature could help prevent that from happening.
2. Consumers of the library who also have the feature enabled will get the nullable signatures from this library to keep their code safer as well.
    - More info: [Microsoft dev blog](https://devblogs.microsoft.com/dotnet/embracing-nullable-reference-types/#what-happens-when-you-call-libraries-that-have-the-feature-enabled)

I would be very happy to attempt integrating this feature into the code if you support the idea.

**Comment by AndrewTriesToCode** [comment]
hi, I agree this would be great. I have to admit I haven't looked into this much myself and it seems like a lot of work but for a good cause. If you want to Take a stab at it I certainly would appreciate it. Maybe one assembly at a time?

**Comment by fossbrandon** [comment]
I believe the work would touch a lot of files but consist of relatively simple changes such as adding null checks, declaring a variable as nullable, etc. I like the idea of doing one assembly at a time. I'll give it a go and see what you think.

**Comment by fossbrandon** [comment]
Hi there, I just started to work on this again and had a few clarifying questions.

1. Should I submit PRs into your main branch or a temporary development branch?
2. Should I enable NRTs in all the sample projects and make fixes as I make changes to the libraries? Or should it be a separate PR after all the libraries are updated?
3. Lastly, I've been able to keep the existing functionality in the `Finbuckle.MultiTenant` project so far, but I'm now trying to find the best way to handle the `ServiceCollectionExtensions.cs` file.
    - The following code complains because services may return null due to `MultiTenantContext` and `TenantInfo` being nullable.
    ![image](https://user-images.githubusercontent.com/46940941/144898726-7eafe929-d723-49fa-8151-9542a06c3902.png)
        - I can either keep the existing functionality and use the null-suppression operator to remove warnings (but still leave in the potential for a null return/errors).
        ![image](https://user-images.githubusercontent.com/46940941/144899415-88f64b61-5f34-4836-b926-3bc0769ba9bb.png)
        - Or, I can add extra logic to account for the possible null reference and throw an error to a consumer.
        ![image](https://user-images.githubusercontent.com/46940941/144899882-7a3fd861-efe0-4ae6-a36e-410bf48d6256.png)
    - Let me know if you like either of these options, or if you recommend something else. Thanks!

**Comment by AndrewTriesToCode** [comment]
Hi @fossbrandon and thanks again for tackling this

> Should I submit PRs into your main branch or a temporary development branch?

I think `main` is fine. What is the footprint of the changes? I'd imagine they are spread all over the place right?

> Should I enable NRTs in all the sample projects and make fixes as I make changes to the libraries? Or should it be a separate PR after all the libraries are updated?

I say going forward for .NET 6 samples we use it but not worry about the older ones. Many are due to be ported up to .NET 6 over the next year.

> The following code complains because services may return null due to MultiTenantContext and TenantInfo being nullable.

This is where my ignorance on NRTs comes in -- would it make sense that the service being registered are `IMultiTenantContaxt<T>?`, `T?`, and `ITenantInfo?` so that they could resolve to null?

**Comment by fossbrandon** [comment]
I'm happy to help! I think this will improve the library in the long run.

> I think `main` is fine. What is the footprint of the changes? I'd imagine they are spread all over the place right?

Unfortunately, just about every file is touched, but the changes themselves should be simple to review. And since we want to go one library/corresponding test project at a time, it shouldn't be too bad.

> I say going forward for .NET 6 samples we use it but not worry about the older ones. Many are due to be ported up to .NET 6 over the next year.
> 

This sounds good to me. I'll still use them to make sure none of these changes break anything, but I won't enable NRTs or update any code.

> This is where my ignorance on NRTs comes in -- would it make sense that the service being registered are `IMultiTenantContaxt<T>?`, `T?`, and `ITenantInfo?` so that they could resolve to null?

That's what I wanted to do initially, but `T` has the `class` constraint on it that says `T` must be a non-nullable reference type. The more I think about it, I feel like I should use the null-forgiveness operators on this to keep the existing functionality and later improvements of the library can add extra safeguards. But I'm also happy to add those safeguards in now if you like my idea from above or have a different one.

**Comment by AndrewTriesToCode** [comment]
Thanks and I agree let’s go with the null warning suppression operator approach.

**Comment by fossbrandon** [comment]
@AndrewTriesToCode Should this be reopened until the NRT work on the other 2 libraries is also merged? Or, should I create separate issues for that work?

**Comment by AndrewTriesToCode** [comment]
I'll reopen, thanks!

**Comment by AndrewTriesToCode** [comment]
@fossbrandon shall I reopen for the final segment? I understand if you aren't able to take the time to do the last part, just let me know.

**Comment by fossbrandon** [comment]
Yup! Thanks for reopening and sorry for the delay on this last one. I'm mostly done with it but life got pretty busy. I should have a PR within the next week though.

**Comment by fossbrandon** [comment]
Happy to see it!
