### ISSUE TITLE
Url.Action

### ISSUE THREAD

**Issue by goforebroke** [Finbuckle/Finbuckle.MultiTenant#492]
Not an issue with finbuckle, but rather I am unsure how to use Url.Action to redirect a user to a login page or email confirmation page  within an Area and Tenant after registering/creating a new tenant.

Users can create a new tenant through a tenant registration page. 
The page supports creating new user along with a new tenant or an existing user will create a new tenant.

If its a new user and new tenant, an email is sent to the user with a link to the email confirmation page. After confirming their email address the user can login.

If its an existing user creating a new tenant, the email will contain a link to their login page.

code snippet below...

```
  public async Task<IActionResult> PaymentSuccess()
  {
            var cart = await _currentCart.GetCartAsync();

            var accessor = _httpContextAccessor.HttpContext.RequestServices.CreateScope().ServiceProvider.GetRequiredService<IMultiTenantContextAccessor>();
            var multiTenantContext = new MultiTenantContext<DaedalSoftTenantInfo>();
            multiTenantContext.TenantInfo = await _finbuckleService.GetTenantById(cart.CheckOutOrganization.TenantId);
            accessor.MultiTenantContext = multiTenantContext;

            using (var context = new AppDbContext(multiTenantContext.TenantInfo,
            _httpContextAccessor.HttpContext.RequestServices
            .CreateScope()
            .ServiceProvider.GetRequiredService<DbContextOptions<AppDbContext>>()))
            {
                var identityService = _httpContextAccessor.HttpContext.RequestServices.CreateScope().ServiceProvider.GetRequiredService<IIdentityService>();

                var user = await identityService.FindUserByEmailAddress(cart.CheckOutAccount.EmailAddress);
                string confirmationLink;

                if (user != null)
                    confirmationLink = Url.Action() --- URL ACTION FOR EXISTING USER TO LOGIN PAGE;
                else
                {
                    user = new AppUser()
                    {
                        Email = cart.CheckOutAccount.EmailAddress,
                        UserName = Guid.NewGuid().ToString(),
                        LastName = cart.CheckOutAccount.FirstName,
                        FirstName = cart.CheckOutAccount.LastName,
                        MustChangePassword = true,
                        EmailConfirmed = false,
                        SecurityStamp = Guid.NewGuid().ToString()
                    };

                    var token = identityService.GetEmailConfirmationToken(user);

                    confirmationLink = Url.Action(); --- URL ACTION TO EMAIL CONFORMATION
                }

                await identityService.RegisterAdminAsync(user);
                await identityService.AddSuperAdminAsync(_globalSettings.SuperAdmin);

                await _emailSender.SendEmailAsync(user.Email, multiTenantContext.TenantInfo.Identifier +  " Registration", confirmationLink);
            }

            // Delete the cart from redis
            await _currentCart.DeleteCartAsync();
            
            return View();
}
```

In my application, I have an area defined as "Portal"

Web > Areas > Portal

Each tenant will have an area in the portal ... "Portal/TenantIdentifier"

```
endpoints.MapControllerRoute(
 name: "MyTenantArea",
 pattern: "{area:exists}/{__tenant__=}/{controller=Home}/{action=Index}/{id?}");
```

Within the portal I have an AccountController

The account controller has Login and ConfirmEmail methods defined.

At this point I am not sure how to use Url.Action to create/send link to my login page for existing user and new tenant

`https://mysite/Portal/TenantIdentifier/Account/Login`

or how to create/send a link to my email confirmation page for new users and new tenant

`https://mysite/Portal/TenantIdentifier/Account/ConfirmEmail`

Any help would be greatly appreciated

**Comment by AndrewTriesToCode** [comment]
Hi Jorge, I'll get to this later tonight. I don't use Url.Action much but I'll see what I can find out.

**Comment by goforebroke** [comment]
Thx Andew

Jaime

**Comment by AndrewTriesToCode** [comment]
Jaime! Not Jorge sorry! I’m going to Top Golf this week and thought of your project! Hope all is well.

**Comment by AndrewTriesToCode** [comment]
Hello again, sorry for the delay. I wish I had responded sooner because I think this is covered by the custom `AmbientValueLinkGenerator` in the `IdentityDataIsolationSample` project. In the infrastructure folder you'll see a link generator class an in the startup class you can see where I decorate the default ambient value link generator with my own which adds the tenant route param.

I plan to include this in a future release as an option when using route parameter and have it handled for you.

Let me know if it works for you!
