### ISSUE TITLE
Old identifier in the URL after the Identifier change in runtime

### ISSUE THREAD

**Issue by sasaman91** [Finbuckle/Finbuckle.MultiTenant#496]
I have two Apps (1 multitenant and 1 for managing tenants)

When I change connection string all work great. When I change Identifier from example "tenant1" to "tenant2" I can't login because all redirections are with "tenant1" in the URL.
I must restart the application in order to work. I assume that is somehow pulling tenant identifier from a cookie or something like that.

These are the Tenant Option:

`services.AddMultiTenant<Tenant>()`
          `          .WithEFCoreStore<TenantsDbContext, Tenant>()`
                  `  .WithRouteStrategy()`
                  `  .WithPerTenantOptions<CookieAuthenticationOptions>((options, tenantInfo) =>`
                    `{`
                        `   options.Cookie.Path = $"/{tenantInfo.Identifier}";`
                        `options.Cookie.Name = $"{tenantInfo.Id}_auth";`
                       ` options.Cookie.HttpOnly = true;`
                       ` options.ExpireTimeSpan = TimeSpan.FromMinutes(60);`
                       ` options.LoginPath = $"/{tenantInfo.Identifier}/Identity/Account/Login";`
                        `options.LogoutPath = $"/{tenantInfo.Identifier}/Identity/Account/Logout";`
                       ` options.AccessDeniedPath = $"/{tenantInfo.Identifier}/access-denied";`
                        `options.ReturnUrlParameter = CookieAuthenticationDefaults.ReturnUrlParameter;`
                      `  options.SlidingExpiration = true;`
                  `  })`
                   ` .WithPerTenantAuthentication();  `

**Comment by AndrewTriesToCode** [comment]
Hi! I have a few questions so that I can help better:

> When I change connection string all work great.

What connection string are you referring to? the request url? I don't see connection string in your code sample.

> When I change Identifier from example "tenant1" to "tenant2" I can't login because all redirections are with "tenant1" in the URL.

Assuming you mean changing the url. Are you saying that if you do that it will send you to the previous tenant's login page?
