### ISSUE TITLE
Hierarchical tenants

### ISSUE THREAD

**Issue by andriy-vynnychuk-orderin** [Finbuckle/Finbuckle.MultiTenant#497]
Hi Finbuckle team. your library is very useful for us and we use it in our software.

Some time ago we take request to implement master-tenant - tenant which has access to more than one tenant information and can operate with data inside them. Is it possible to implement with your library or we should write our own logic to support this?

**Comment by AndrewTriesToCode** [comment]
Hi! 

> your library is very useful for us

Thank you! That is the goal!

As for tenant hierarchy, It's not something I've prioritized at the moment. If you are interested in sponsoring it for open-source or in engaging in a consultant/contracting arrangement to build in-house let me know via the contact form on www.finbuckle.com

 I recommend you proceed with building out what works for you. If you wanted to submit a PR that would be even better! But either way I hope that I can reach out to you later and learn from your experience!

**Comment by andriy-vynnychuk-orderin** [comment]
Thank you, very much. I will back to you with result of our implementation.
