### ISSUE TITLE
[Newtonsoft.Json] only required for 3 lignes of code

### ISSUE THREAD

**Issue by bobbyangers** [Finbuckle/Finbuckle.MultiTenant#504]
Hi,
In recent projects, we've migrated to use `System.Text.Json` instead of `Newtonsoft.Json`.

Can we remove the need for this extra third party library ?

**Comment by AndrewTriesToCode** [comment]
You read my mind! Thanks.

**Comment by bobbyangers** [comment]
@AndrewTriesToCode, how is that ?

**Comment by AndrewTriesToCode** [comment]
@bobbyangers perfect. With supply chain attacks theses days have zero external dependencies adds a lot of value to this project. Thanks again!

**Comment by AndrewTriesToCode** [comment]
This was merged in! Thanks!
