### ISSUE TITLE
[Clarification/Issue] Using multitenant options in .AddOpenIdConnect() or other authentication methods in .NET 

### ISSUE THREAD

**Issue by Drakkonite** [Finbuckle/Finbuckle.MultiTenant#506]
Hi,

First and foremost, thank you for the work you did on the package, it has brightened many dark secrets of the framework for me, especially in terms of multitenancy.

I'm facing a dilemma or even an issue where you can define the IOptions<> of the Oidc provider, but as you know, it also requires mapping to a specific schema like AddOpenIdConnect(schema, IOptions<>). Where the options are very well documented, how can I utilize the package to provide per-tenant options to AddOpenIdConnect() also with the schema name ?

Any help would be appreciated.
Regards,
Dkkn

**Comment by AndrewTriesToCode** [comment]
Hi, I'm glad you like the project. Currently `WithPerTenantOptions` applies to all options of a type, regardless of their "name". I plan to add support for named options very soon.
