### ISSUE TITLE
ITenantInfo asbtraction and Clean Framework

### ISSUE THREAD

**Issue by HybridSolutions** [Finbuckle/Finbuckle.MultiTenant#507]
Hi,

in the Clean Framework architecture entities should remain in the Domain layer. The issue here is MultiTenant uses `ITenantInfo` to define a custom `TenantInfo` entity that will be used by the application. Any chance of having a custom Tenant entity with the same properties as defined by the `ITenantInfo` interface, and eventually new ones, and specify that MultiTenant should use that custom entity instead in the infrastructure layer? 
I believe this might be related to the question at [https://github.com/Finbuckle/Finbuckle.MultiTenant/issues/465](https://github.com/Finbuckle/Finbuckle.MultiTenant/issues/465) but wanted to have some feedback on this.
Thank you!

**Comment by AndrewTriesToCode** [comment]
Hello!
Yes this should be doable. The `Finbuckle.MultiTenant` library itself is designed to be "kernel" compatible in that it has no external dependencies. You can and should implement your own `ITenantInfo` -- the default `TenantInfo` implementation is really just a basic default implementation.

The `Finbuckle.MultiTenant.AspNetCore` and `Finbuckle.MultiTenant.EntityFrameworkCore` functionality are designed to work with any new fields you add on your `ITenantInfo` implementation. For example the `HtttpRemoteStore` or `EFCoreStore` will use standard json property mapping and EFCore property binding. You can even add annotations on your `ITenantInfo` implementation to help if needed.

Let me know if you have more questions or any specific situations you'd like to discuss further.
