### ISSUE TITLE
Blazor Server Host Strategy Error when I use a different tenant

### ISSUE THREAD

**Issue by OrionRiftStudios** [Finbuckle/Finbuckle.MultiTenant#511]
Hello.
I am using using host strategy and static strategy. 
Everything is working good when I use the default tenant

When I  change to other tenant  example
localhost:5001<== default
mytenant.localhost:5001==< second tenant

I am getting an error with the DbContext because suddenly the TenantInfo is null.
After some research  the TenantInfo is not null in the first call but in the second call the tenant is null. I need the info of the tenant in the DbContext to extract the ConnectionString.

This error is happening in the login screen of my app( I cleaned the cache before)

here is the configuration 

```
public static IServiceCollection AddIdentity(this IServiceCollection services, IConfiguration configuration)
        {
            services.AddDbContext<ApplicationDbContext>();
            services.AddDbContext<MultiTenantStoreDbContext>(options =>
            {
                options.UseSqlServer(configuration[Constants.IdentityDbConnectionString]);
            });
            services.AddIdentity<ApplicationUser, IdentityRole>(config =>
            {
                config.User.RequireUniqueEmail = true;
                config.Lockout.MaxFailedAccessAttempts = 6;
                config.Lockout.DefaultLockoutTimeSpan = System.TimeSpan.FromMinutes(30);
            })
              .AddEntityFrameworkStores<ApplicationDbContext>()
              .AddUserManager<CustomUserManager>()
              .AddRoleManager<RoleManager<IdentityRole>>()
              .AddDefaultTokenProviders();
            services.AddScoped<AuthenticationStateProvider, RevalidatingIdentityAuthenticationStateProvider<ApplicationUser>>();
            services.AddDatabaseDeveloperPageExceptionFilter();

            services.AddMultiTenant<MawtsTenantInfo>()
                .WithEFCoreStore<MultiTenantStoreDbContext, MawtsTenantInfo>()
                .WithHostStrategy()
                .WithStaticStrategy("default")
                .WithPerTenantAuthentication();

            return services;
        }​

```
as I said before the configuration is working fine with StaticStrategy with HostStrategy I can see the login screen with the info of the tenant  but after some calls to the db the tenant info is null.

Maybe I am missing something here.

I am using Blazor Server NET 6.0
EF Core with the latest version

Thank you for your help!

**Comment by AndrewTriesToCode** [comment]
Hi @OrionRiftStudios  -
Just to help simplify things -- if you remove `WithPerTenantAuthentication` do you still see this behavior?

**Comment by AndrewTriesToCode** [comment]
I did a quick check with a default Blazor Server app and added host strategy and it worked as expected. I suspect the problem here might be with the `DbContext` can you post that part of your code?

**Comment by OrionRiftStudios** [comment]
thank you! I am going to paste the dbcontext later today. I really appreciate your help!

**Comment by OrionRiftStudios** [comment]
Looks like I found the problem. I am trying to use multitenant with autofac 
https://autofac.readthedocs.io/en/latest/advanced/multitenant.html
I need to inject different DI depending of the tenant

I tested the app without autofac and it is working fine the hot strategy.
After I implemented autofac multitenant support I am getting that error.
do you know a better way to inject or replace some services depending of the tenant?  because I cannot find the right solution for this scenario. 

Thank you

**Comment by OrionRiftStudios** [comment]
I think it is better if I open other issue about autofac or DI injection per tenant. because the implementation of the host strategy is working fine.

**Comment by AndrewTriesToCode** [comment]
Makes sense. I'll close this out.
