### ISSUE TITLE
Dependency Injection per Tenant How to?[Blazor Server]

### ISSUE THREAD

**Issue by OrionRiftStudios** [Finbuckle/Finbuckle.MultiTenant#512]
Hello I have a requirement where I need to replace/inject some services depending of the tenantId or tenant Identifier

I am trying to use multitenant with autofac
https://autofac.readthedocs.io/en/latest/advanced/multitenant.html

I tested the app without autofac and it is working fine the hot strategy.(I am using host strategy)

After I implemented autofac multitenant support the following errors:

The tenant Id is always null(using the finbuckle)  
My workaround was getting the tenant manually using Request.Host

the app looks like is working at least the first screen.
after that when I try to navigate to other screens  the TenantInfo is null.

do you know a better way to inject or replace some services depending of the tenant? because I cannot find the right solution for this scenario.

Thank you

**Comment by AndrewTriesToCode** [comment]
hello again!

Let me state upfront that I purposefully didn't design for multitenant DI and instead opted for to focus on multitenant options. But I totally understand you have this as a requirement.

I'm not an expert with autofac, but I know they have a `ITenantIdentificationStrategy` interface. I would think (perhaps naively) that in this interface you could simply inject from the application-wide DI the singleton instance of `IMultiTenantContextAccessor<T>` and use that to return the current tenant to autofac. That interface is a singleton in Finbuckle.MultiTenant and the autofac docs seem to indicate this should work [here](https://autofac.readthedocs.io/en/latest/advanced/multitenant.html#tenant-id-strategy-tips).

Is that something you've tried?

**Comment by OrionRiftStudios** [comment]
Thank you for your reply I used IMultiTenantContextAccessor<T> with my implementation of ITenantIdentificationStrategy  the problem is the TenantInfo is always null.

I followed the tutorials of autofac the implementation is clear the problem is ITenantIdentificationStrategy  I guess is something related with the middleware  of  Finbuckle   is  using HttpContext.RequestServices I guess this should be replaced in someway with the container for the specific tenant. 

I am following plugin pattern loading assemblies at runtime.
I need to load specific assemblies or plugins for each tenant and load their dependencies and services.

example:

plugins folder.

plugins/tenant1
plugins/tenant2
plugins/tenant3

depending of the  identifier or the tenant I need to load the plugins and services. 

using WPF using frameworks like MEF this is possible. 
Blazor Server is offering similar approach I am trying to do the same as WPF 

Thank you for your help

**Comment by OrionRiftStudios** [comment]
I tested the ITenantIdentificationStrategy  registering the strategy as singleton the tenant info is still null using IMultiTenantContextAccessor<T>

**Comment by AndrewTriesToCode** [comment]
Ah ok I think maybe a less sophisticated approach might be in order. There is an event you can set on `MultiTenantOptions` on `AddMultiTenant<T>` that will be fired when the tenant is detected. From there you can set a static or singleton variable with the current tenant or set something in such a way that the `ITenantIdentificationStrategy` can read it. This only works for anything autofac needs to inject AFTER the `UseMultiTenant` middleware is  called.

Another approach you could use is to code the `ITenantIdentificationStrategy` yourself to look at the host and then let Finbuckle do it's own separate resolution -- if you keep it simple and are careful they should always match. You could even make it so Finbuckle relies on the strategy of the `ITenantIdentificationStrategy`.

In fact you could write a strategy they implements both `ITenantIdentificationStrategy` and `IMultiTenantStrategy` and use the same logic for both via a helper method on the class.

**Comment by OrionRiftStudios** [comment]
thank you  so much let me try your suggestions.

**Comment by AndrewTriesToCode** [comment]
Sure, one more thing in Finbuckle with `IMultiTenantStrategy` you will use `WithStrategy<MyStrategy>` to register it. There is an overload which will let you register it with the lifetime that you need--probably singleton so it doesn't constantly get recreated for each use of DI.

**Comment by OrionRiftStudios** [comment]
Hello! after of creating my custom strategy using IMultiTenantStrategy  and ITenantIdentificationStrategy  I could fix the issue with the TenantInfo Id.

But the IContainer from Autofac is not injected properly because UseMultitenant Middleware is the default IServiceProvider  I think this implementation should be extended allowing to override the IServiceProvider for each request with this feature we can inject the IServiceProvider we need in this case from Autofac. if you know a better solution please let me know Thank you.

**Comment by AndrewTriesToCode** [comment]
@OrionRiftStudios I apologize for letting this issue go unanswered. I don't have a better solution for you and currently per-tenant DI is not something on the roadmap and it sounds like you know more about it than I do. Did you ever find a decent solution for your use case?

**Comment by OrionRiftStudios** [comment]
Yes. I fixed it . I replaced the middleware with a custom IServiceProvider
