### ISSUE TITLE
doStrategy should return a nullable string

### ISSUE THREAD

**Issue by fretje** [Finbuckle/Finbuckle.MultiTenant#521]
I think the `Func<object, Task<string>> doStrategy` here:

https://github.com/Finbuckle/Finbuckle.MultiTenant/blob/9ddb7f05e6c067af4bb7a86a898a1c61cde05f5e/src/Finbuckle.MultiTenant/Extensions/FinbuckleMultiTenantBuilderExtensions.cs#L135

should actually be a `Func<object, Task<string?>> doStrategy`, as we're supposed to return null here when this strategy doesn't find anything?

returning null in the callback now emits a warning:
`Warning	CS8619	Nullability of reference types in value of type 'Task<string?>' doesn't match target type 'Task<string>'.	`

**Comment by AndrewTriesToCode** [comment]
Thanks for reporting. I agree and will put out a patch release later today.

**Comment by AndrewTriesToCode** [comment]
Just released 6.6.1 to address this, thanks!
