### ISSUE TITLE
Per Tenant options values are lost from TenantInfo while using EFCoreStore 

### ISSUE THREAD

**Issue by TropinAlexey** [Finbuckle/Finbuckle.MultiTenant#522]
Hi, @AndrewTriesToCode .
I have multitenancy configuration with static store and with per tenant options which are situated in each tenant's database "settings" table.
I have a custom reader, which gets all tenants from `appsettings` via service scope and using their connection strings, it reads their options from each tenant "settings" db table as Dictionary<string, string> and  stores them into my extended TenantInfo class.
My reader's fragment:
```
...
var tenants = (scopeServices.GetRequiredService<IMultiTenantStore<TenantInfoExtended>>().GetAllAsync().Result).ToList();
foreach (var tenant in tenants)
{
   using var ddb = new LookupSettingsDbContext(tenant);
   tenant.TenantOptions = ddb.Settings.ToDictionary(k => k.Name, v => v.Title); <<< Having values here
}
...
```
Works fine.

Now I have a task to store tenants info in some Master database and leave per tenant settings where they are now. For this purpose I have added `.WithEFCoreStore<MasterInstanceDbContext, TenantInfoExtended>()` and it's do the job. Despite the options are read by my custom reader as usual and I see all values in debugger, in moment of my options setup the data in `tenantInfo.TenantOptions` dictionary are null.

```
.WithPerTenantOptions<PerTenantOptions>((options, tenantInfo) =>
   {
      options.DefaultLanguageCode = tenantInfo.TenantOptions.TryGetValue("DefaultLanguageCode", out var value) ? value : "ua"; << Here is tenantInfo.TenantOptions is null
      options.CountryCode = tenantInfo.TenantOptions.TryGetValue("CountryCode", out value) ? value : "uk";
...
    }
```
Do you have any tips or some workarounds for my situation? Thank you in advance

**Comment by TropinAlexey** [comment]
Forgot to mention: also I changed strategy from `Host` to `Header`. Maybe the problem is in fact that header strategy uses `HttpContext` for operations with TenantInfo?

**Comment by AndrewTriesToCode** [comment]
hi @TropinAlexey 

If I understand correctly you basically have tenant info in 2 places: the master DB and in the appsettings.json (just for some per-tenant settings).

I think the issue is that the tenantInfo that is sent to `WithPerTenantOptions` is pulled fresh from the database so it will only have what options you have set for the tenant in the database -- the items you set earlier were seperate `TenantInfo` instances in memory from the ones used during the middleware.

A few thoughts:
1. Add the settings to the EFCore tenant store -- this isn't ideal though as you don't want them all loaded as part of the TenantInfo for each http request. But this will make them availble in `WithPerTenantOptions` on the tenant info instance passed in.
2. In `WithPerTenantOptions` place the code to reference the correct section in appsettings.json for that tenant. This is only run once per options creation which isn't every request unless you are using `ISnapshotOptions`.
3. A third option which I have used is to place extra tenant information in your dbcontext but as a separate entity from your main tenant store and then just have a 1-1 relationship between them.Then the `TenantInfo` returned via the middleware is lightweight, but you can easily access the extra tenant settings via EFCore.

Hope this helps and let me know!

**Comment by TropinAlexey** [comment]
Hi, Andrew. Thank you for your answer.

"If I understand correctly you basically have tenant info in 2 places: the master DB and in the appsettings.json (just for some per-tenant settings)."
No, per-tenant settings are stored in each tenant database individually and I'm reading them via separate dbContext as you can see in code example above.

The 3rd option, that you proposed, is the one that I'm trying to do with different ways, but failed so far. Please, take a look at this middleware fragment, where I'm trying to "enrich" `TenantInfo` with options or set them up in httpContext. But this `TenantOptions` data is absent, as services getting `TenantInfoExtended` from DI and I can't get this data from httpContext (can't find this info in documentation). What am I missing?

```
 public async Task Invoke(HttpContext context, TenantInfoExtended currentRequestTenant)
        {
            using var scope = _serviceProvider.CreateScope();
            var tenantList = scope.ServiceProvider.GetRequiredService<IMultiTenantStore<TenantInfoExtended>>().GetAllAsync().Result.Where(t => !t.ConnectionString.IsNullOrEmpty()).ToList();
            var currentTenant = tenantList.FirstOrDefault(t => t.Identifier == currentRequestTenant.Identifier);
            if (currentTenant != null)
            {
                await using var ddb = new LookupSettingsDbContext(currentRequestTenant);
                var currentTenantOptions = ddb.PerTenantSettings.ToDictionary(k => k.Name, v => v.Title);
                currentTenant.TenantOptions = _mapper.Map<PerTenantOptions>(currentTenantOptions);

                if (context.TrySetTenantInfo<TenantInfoExtended>(currentTenant, resetServiceProviderScope: true))
                {
                    _logger.LogInformation($"[REQ-DATA] Request with ID={context.TraceIdentifier} has picked up tenant: \"{currentRequestTenant.Identifier}\" from middleware");
                    await _next(context);
                }
                _logger.LogError($"[MIDDLEWARE] Request with ID={context.TraceIdentifier} for tenant: \"{currentRequestTenant.Identifier}\" didn't set tenant to this Http context");
            }
            _logger.LogError($"[MIDDLEWARE] Request with ID={context.TraceIdentifier} has not found tenant: \"{currentRequestTenant.Identifier}\"");
            //debug
            throw new KeyNotFoundException($"[MIDDLEWARE] Request with ID={context.TraceIdentifier} has not found tenant: \"{currentRequestTenant.Identifier}\"");
        }
```

**Comment by TropinAlexey** [comment]
I just figured out, that I can store per-tenant info in custom http headers, but is there a simpler way? This middleware will add overhead to read storage on every request and I must cache it, which is not really proper way to use your library

Also, today I'll try the 2nd option that you proposed, thank you for clarification

**Comment by AndrewTriesToCode** [comment]
Hi @TropinAlexey if you can post me a link to a repo where I can try it out I can take some time to look closer.

> No, per-tenant settings are stored in each tenant database individually and I'm reading them via separate dbContext as you can see in code example above.

Ok, I think get what you are attempting. I think I can simplify things a bit -- when you run the `UseMultiTenant` middleware it correctly sets the initial `TenantInfoExtended` right? Except that is missing the `TenantOptions` property which in this middleware you are trying to populate. As you noted this is a lot of database calls and extra overhead.

I added some comments to your code snippet:
```cs
 public async Task Invoke(HttpContext context, TenantInfoExtended currentRequestTenant)
        {
            using var scope = _serviceProvider.CreateScope();
            var tenantList = scope.ServiceProvider.GetRequiredService<IMultiTenantStore<TenantInfoExtended>>().GetAllAsync().Result.Where(t => !t.ConnectionString.IsNullOrEmpty()).ToList();
            var currentTenant = tenantList.FirstOrDefault(t => t.Identifier == currentRequestTenant.Identifier);
            if (currentTenant != null)
            {
                // I don't think you need anything above here in this method -- the DI provided currentRequestTenant should
               // already be set if the UseMultiTenant middlware ran before this one
                await using var ddb = new LookupSettingsDbContext(currentRequestTenant); // I assume this will use the connection string for the tenant
                var currentTenantOptions = ddb.PerTenantSettings.ToDictionary(k => k.Name, v => v.Title);
                // instead of setting currentTenant.TenantOptions I think you should set currentRequestTenant.TenantOptions
                // in other words, add them to the actual current tenant instance the middlware found
                currentTenant.TenantOptions = _mapper.Map<PerTenantOptions>(currentTenantOptions);

                // Then none this is needed -- don't need to reset the tenant instance since you just populated the 
                // TenantOptions on the existing insance -- await _next() still needed of course
                if (context.TrySetTenantInfo<TenantInfoExtended>(currentTenant, resetServiceProviderScope: true))
                {
                    _logger.LogInformation($"[REQ-DATA] Request with ID={context.TraceIdentifier} has picked up tenant: \"{currentRequestTenant.Identifier}\" from middleware");
                    await _next(context);
                }
                _logger.LogError($"[MIDDLEWARE] Request with ID={context.TraceIdentifier} for tenant: \"{currentRequestTenant.Identifier}\" didn't set tenant to this Http context");
            }
            _logger.LogError($"[MIDDLEWARE] Request with ID={context.TraceIdentifier} has not found tenant: \"{currentRequestTenant.Identifier}\"");
            //debug
            throw new KeyNotFoundException($"[MIDDLEWARE] Request with ID={context.TraceIdentifier} has not found tenant: \"{currentRequestTenant.Identifier}\"");
        }
```

That being said you unless `ddb.PerTenantSettings` does some caching this will be slow for every request. I recommend you move this logic to within `WithPerTenantOptions` as that will only pull the info when it is needed to actually create the options -- ASP.NET Core then caches the options so it's efficient.

**Comment by TropinAlexey** [comment]
Works like a charm, thank you very much for your comments in my code. Seems so obvius...
