### ISSUE TITLE
Enable discussions for this repo?

### ISSUE THREAD

**Issue by VictorioBerra** [Finbuckle/Finbuckle.MultiTenant#526]
I have some general questions and I was wondering if we could enable the GitHub discussions feature so I could ask them and get help from the community?

**Comment by AndrewTriesToCode** [comment]
Hi, Sure I will enable that a little later today.

**Comment by AndrewTriesToCode** [comment]
Ok, discussion are in place. Thanks!

**Comment by VictorioBerra** [comment]
@AndrewTriesToCode thanks! I don't seem to see a way to create a post. Is there a misconfigured permission?
