### ISSUE TITLE
How to add defaults when using WithHttpRemoteStore

### ISSUE THREAD

**Issue by paburgos** [Finbuckle/Finbuckle.MultiTenant#527]
Hi,

I am wondering if there is a way to programmatically add defaults when using WithHttpRemoteStore? Or should I add the defaults in each config at the Http remote store?

Thanks!

**Comment by AndrewTriesToCode** [comment]
Hi @paburgos 
Can you give me a concrete example of what you'd like to do here? What kind of defaults are wanting to add?

**Comment by AndrewTriesToCode** [comment]
fyi there was a bug with the json deserializer settings that is fixed in the 6.7.1 release
