### ISSUE TITLE
No access to create discussion.

### ISSUE THREAD

**Issue by VictorioBerra** [Finbuckle/Finbuckle.MultiTenant#529]
When I go to discussions, there is no button to add one.

**Comment by AndrewTriesToCode** [comment]
@VictorioBerra sorry about that. Does the discussion page look similar to my screenshot below? No green "New Discussion" button on the right?

![Screen Shot 2022-02-22 at 6 17 57 PM](https://user-images.githubusercontent.com/4422897/155246918-5d8b08f4-2d47-4bd6-bf3f-0235ff282298.png)

**Comment by VictorioBerra** [comment]
That is correct. Mobile view:

![Screenshot_20220222-204210](https://user-images.githubusercontent.com/2934507/155253441-0a0107b6-87e5-4080-9b9e-d787b5864257.jpg)

**Comment by AndrewTriesToCode** [comment]
ok I found a very obscured setting in the Organization settings -- can you start a new discussion now?

**Comment by VictorioBerra** [comment]
Works now! What was the settings?

![Screenshot_20220222-212040](https://user-images.githubusercontent.com/2934507/155256657-f47f7ebe-999e-4922-824c-dbfc46d96825.jpg)

**Comment by AndrewTriesToCode** [comment]
Under the Org settings / Member Priviliges section:
![image](https://user-images.githubusercontent.com/4422897/155257166-1825b995-b3b0-4743-919c-bffa012d15f2.png)
