### ISSUE TITLE
Problem with link generation

### ISSUE THREAD

**Issue by VictorioBerra** [Finbuckle/Finbuckle.MultiTenant#530]
Steps to reproduce:

- Clone Finbuckle.MultiTenant
- Edit IdentityDataIsolationSample/Shared/_Layout
- Add a navbar link: `<a asp-page="/HelloWorld" class="nav-item nav-link">Sample</a>`
- Add an empty razor page: IdentityDataIsolationSample/Pages/Index.cshtml

Outside of a tenant, things work fine:

![image](https://user-images.githubusercontent.com/2934507/155245759-1b49f654-f398-4a61-8fa7-04281a0e548e.png)

However, select a tenant, and notice this:

![image](https://user-images.githubusercontent.com/2934507/155245818-e767e3dd-4545-4ecb-bc9a-e7099412025a.png)

The URL becomes: `https://localhost:5001/HelloWorld?__tenant__=initech`

I notice to fix it, I can add: `asp-route-__tenant__=""`

Is this expected?

**Comment by AndrewTriesToCode** [comment]
hi @VictorioBerra

This is because of the ambient value link generator that example uses to "automatically" preserve the current tenant for link generation and is needed for the links in Identity to work. If you look at the startup closely you'll see where I modified the route template the Identity pages use so that `__tenant__` is included in the route. You can use the same for your pages like this:
```cs
options.Conventions.AddFolderRouteModelConvention("/", model =>
{
    foreach (var selector in model.Selectors)
    {
        selector.AttributeRouteModel.Template =
            AttributeRouteModel.CombineTemplates("{__tenant__}", selector.AttributeRouteModel.Template);
    }
});
```

Then the links will work as expected. Note however that links won't generate correctly if there is no tenant though so you have to be careful there. At this point I use BasePath strategy more than route and I use the option to adjust the ASP.NET PathBase so the application basically never has to deal with tenant part of the path at all--when I update this sample for .NET 6 I plan to make this change.

**Comment by VictorioBerra** [comment]
@AndrewTriesToCode Thank you, this helps. I had the above code in place, but for specific folders. I did not have "/", I had things like "/Dashboard". So maybe that was my issue.

I do in-fact have a situation where I have a /Privacy, and a /Terms page, which require no tenant, and unauthorized users can get there and read those documents.

I would like to see the BasePath strategy and .NET 6, to be honest, the only reason I am using Route strategy is because the PerTenantAuthentication docs used it, and I assumed it used it for a special reason.

**Comment by AndrewTriesToCode** [comment]
Ok I'll prioritize updating the Identity data isolation sample to .NET 6 using base path.

**Comment by VictorioBerra** [comment]
> At this point I use BasePath strategy more than route and I use the option to adjust the ASP.NET PathBase so the application basically never has to deal with tenant part of the path at all

@AndrewTriesToCode Do you have any public facing (no tenant) pages? If so, how does that work?

**Comment by VictorioBerra** [comment]
@AndrewTriesToCode Also, with the base path example, could you include RazorPages, and show examples of routing to pages, folders, with both tenant and no tenant, and when inside of a tenant, routing to a non-tenant page (ie /about).

I think that might expose any edge cases with the routing. Its not uncommon for more and more people to be using Razor Pages, and it seems like `AddFolderRouteModelConvention()` is necessary even with basepathstrat.

**Comment by VictorioBerra** [comment]
Sorry to blow this issue up, but ive been playing with this for a while now. the BasePathStrategySample.csproj does not work as-is with Razor Pages.

- Open the sample, add: `services.AddRazorPages();` and `endpoints.MapRazorPages();`.
- Add `/Pages/HelloWorld/Index.cshtml`
- Launch and try and visit https://localhost:5001/initech/HelloWorld/Index, you will get a 404

Razor pages seems to be taking the BasePath into account for routing? https://localhost:5001/HelloWorld/Index works.

**Comment by AndrewTriesToCode** [comment]
On 'WithBasePath' there is an option to adjust the asp.net core internal base path--give that a try if you aren't currently.

**Comment by VictorioBerra** [comment]
@AndrewTriesToCode Same problem when using `options.RebaseAspNetCorePathBase = true`, but im getting closer:

The following as we discussed earlier, fixes the 404, I thought maybe I didn't need it with `RebaseAspNetCorePathBase`.

```csharp
services.AddRazorPages()
  .AddRazorPagesOptions(options =>
  {
      foreach (var folder in new[] { "/HelloWorld" })
      {
          options.Conventions
              .AddFolderRouteModelConvention(folder, model =>
              {
                  foreach (var selector in model.Selectors)
                  {
                      selector.AttributeRouteModel.Template =
                          AttributeRouteModel.CombineTemplates("{first_segment}", selector.AttributeRouteModel.Template);
                  }
              });
      }
  });
```

One last problem remains, when inside a tenant and folder (IE `initech/HelloWorld/Index`), static resources try to load from then tenant:

- Add a wwwroot folder, add a site.css, add a sample style: `body { background-color: pink; }`
- In your _Layout.cshtml, add: `<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />`

Notice that you get a 404, and notice that it is trying to load: `ttps://localhost:5001/initech/css/site.css?v=nw7f3fL2lOhftVKkR8jXUcTVmApxSJ8RXoQU4rabqIs`.

The templates do not have any wwwroot folder or local static resources, so it probably didn't get spotted.

**Comment by VictorioBerra** [comment]
So, if we turn RebaseAspNetCorePathBase on, we get less link generation problems, but we introduce problems with ~/ as they preserve the base path.

**Comment by AndrewTriesToCode** [comment]
I'll get the sample uploaded tomorrow. With BasePathStrategy no need to adjust the RazorPages conventions and also you should not have '__tenant__' as part of your routes anywhere.

For static assets move UseStaticFiles to the other side of UseMultiTenant... I can't recall at the moment if it should be before or after.

**Comment by AndrewTriesToCode** [comment]
And thanks for your feedback by the way it is helpful.

**Comment by VictorioBerra** [comment]
Moving `UseMultiTenant` to before UseStatic and before UseRouting seems to have fixed most issues.

I assume we will update https://www.finbuckle.com/MultiTenant/Docs/v6.6.1/ConfigurationAndUsage to clarify that?

**Comment by VictorioBerra** [comment]
@AndrewTriesToCode Another thing lol and let me know if this should be its own issue:

 the AddOpenIdConnect handler is including the pathbase in the redirect: https://localhost:5000/acme/signin-oidc

And, because of the PathBase, all the cookies are being set on /acme path now.

**Comment by AndrewTriesToCode** [comment]
Thanks again for the feedback. I will update the documentation and I think the oidc issue is one that warrants prioritizing so I will thing about how to tackle that. I think I can adjust the callback URL i the openid connect events. Still working on the updated sample.

**Comment by AndrewTriesToCode** [comment]
I got a basic BasePathStrategy sample added but I think you are probably beyond anything it shows. Next up will be an Identity one. Also I clarified some of the behavior you noted in the Docs for this strategy. With respect to static files if you make the urls for them absolute or rooted urls they will still work without having to reorder the middleware. Maybe not ideal but another knob to tweak to get the desired behavior.

**Comment by VictorioBerra** [comment]
Thanks for the follow up, I'll review these shortly and see what I can find. I think right now I only have one or two edge cases.

**Comment by VictorioBerra** [comment]
@AndrewTriesToCode I pulled down the net6 sample. So one of the edge cases here is if you pick a tenant, hover over the Privacy link, you will see it routes to tenant/Privacy, this still works though and loads the page. I wish there was some override to tell all `Page()` and `RedirectToPage()` and `asp-page` things to ignore the base path, just as an option.

As for `~/` VS `.UseStaticFiles()` I am not sure what the better path is here. It would depend on if you host in an IIS webapp probably. An IIS web app requires `~/` all over the code because the app is hosted at mysite.com/myapp.

As for cookies, do you think its OK cookies are now at /tenant path, and wont be sent for non-tenant paths? A bonus is no need for:

```csharp
.WithPerTenantOptions<CookieAuthenticationOptions>((o, tenantInfo) =>
{
    o.Cookie.Name = "SignInCookie - " + tenantInfo.Id;
});
```

I can't think of any issues this could cause for now.

**Comment by AndrewTriesToCode** [comment]
First of all thanks for the donation -- it really helps!

Yeah I've thought about this a little bit too and there are always trade offs like you mentioned before. One thing to try is to mess with the &lt;a&gt; tag helper to try to make it tenant aware and tell if if you want a tenant link or not. Or just stick to the route strategy.

I'll admit that I mostly use the host strategy which sidesteps the link issue but is difficult to develop for.

I also think there is a lot of potential in the session strategy but you have to have some way to determine the initial tenant to set the session variable -- maybe a user claim or something. So many option and ultimately all of them have edge cases because at its core I'm just manipulating what I can in .NET without any official support.

**Comment by VictorioBerra** [comment]
I know how hard it is to maintain a popular open source project. Sounds great, I think we have explored this enough to go ahead and close it.
