### ISSUE TITLE
Shared Tenant

### ISSUE THREAD

**Issue by jmsolutionsgroup** [Finbuckle/Finbuckle.MultiTenant#537]
What is the best way to handle the situation when a user belongs to multiple tenants.   I am using Entity Framework Core in a Shared Database.  If I have 5 tenants (A,B,C,D,E) and I have users that should only have access to the information in tenant A,B, and C, how should I handle this?   Also If I want to query an EF Context for all information  in a table for the tenants A,B, and C, but not D and E how are the global filters impacted?

 I could create self referenced column on the Tenant table to indicate hierarchy, or create a many to many table to show tenant relationships, but I'm not sure what the best way to modify the filters and store users.   

Thanks

**Comment by AndrewTriesToCode** [comment]
Hello!

> What is the best way to handle the situation when a user belongs to multiple tenants

Depends on the complexity but the most flexible is to model an actual many-to-many relationship between user and tenant. In this case the Identity database is usually not "per-tenant" isolated itself.

> I have users that should only have access to the information in tenant A,B, and C, how should I handle this?

One option is to allow to user to switch between active tenant which will allow access to the information for one tenant at a time. How this will work is specific to your situation--what type of multitenant strategy are you using? Another option is to disregard the global QueryFilter Finbuckle adds and set your own after the call to `IsMultiTenant` in the database model creating that includes one or more tenants you want to have results returned for. It can get tricky.

> how are the global filters impacted?
If you set a global filter before `IsMultiTenant` then it will be combined via AND logic. If you set your own after `IsMultiTenant1 it will replace Finbuckle's logic.

I think the first question to ask is "can the user see one tenant at a time" or do they have to see it all mixed together. If one at a time, how to let the user switch between tenants -- again depends on how you are detecting the tenant.

**Comment by jmsolutionsgroup** [comment]
@AndrewTriesToCode, Thank you for the response.  I think my plan is to utilize a claim strategy because I add a multiple tenant claims during the login process I can add a tenant claim for A,B, and C for a user.  

> > how are the global filters impacted?
> > If you set a global filter before `IsMultiTenant` then it will be combined via AND logic. If you set your own after `IsMultiTenant1 it will replace Finbuckle's logic.

Is there an example of combining with the global filter?

> I think the first question to ask is "can the user see one tenant at a time" or do they have to see it all mixed together. If one at a time, how to let the user switch between tenants -- again depends on how you are detecting the tenant.

I believe our users would be able to see mixed tenant information at the same time.  We have some dashboards for those who oversee multiple tenants, so we would need to combine the data.   

Is sounds like I can utilize the MultiTenant attribute to store information but the filtering will need to be custom.  Does this sound correct?   Any other suggestions or comments are welcome, but I think I have a starting point.

**Comment by VictorioBerra** [comment]
@uchetfield its in the [docs here](https://www.finbuckle.com/MultiTenant/Docs/v6.6.1/EFCore), ctrl+f for "Existing Query Filters"

**Comment by AndrewTriesToCode** [comment]
ClaimStrategy sounds good, but be advised that `WithPerTenantAuthentication` will have problems with it -- I need to improve this use case.

`WithPerTenantAuthentication` looks at the single tenant when the user logged in and will prevent future authentication for any other tenant even if they have multiple.

I'd be curious to see what you end up with -- let me know!

With the cobined global query filters there isn't much too it. If you have a filter like:
```cs
builder.Entity<MyClass>().HasQueryFilter(e => e.Name == "Ted");
builder.Entity<MyClass>().IsMultiTenant(); // Or base method or `ConfigureMultiTenant()` when using [MultiTenant] attribute.

// Now the global query filter is similar to: e => e.Name == "Ted" && e.TenantId == currentTenantId

//Now swap them:
builder.Entity<MyClass>().IsMultiTenant(); // Or base method or `ConfigureMultiTenant()` when using [MultiTenant] attribute.
builder.Entity<MyClass>().HasQueryFilter(e => e.Name == "Ted");

// Now the global query filter is just e => e.Name == "Ted", essentially you overwrote it.
```
Does that make sense?
