### ISSUE TITLE
custom Strategy Example

### ISSUE THREAD

**Issue by iang0ld** [Finbuckle/Finbuckle.MultiTenant#541]
Does anyone have a full example a custom strategy implementation?
Also is there a way of preventing a controller from using finbuckle?

**Comment by VictorioBerra** [comment]
@iang0ld You may want to use DelegateStrategy, this lets you provide a custom function that can do literally whatever you want. Docs here: https://www.finbuckle.com/MultiTenant/Docs/v6.6.1/Strategies

If you want a true custom strategy, you should implement `IMultiTenantStrategy` and make one yourself.

Check out the source for [Static](https://github.com/Finbuckle/Finbuckle.MultiTenant/blob/main/src/Finbuckle.MultiTenant/Strategies/StaticStrategy.cs), and [Delegate](https://github.com/Finbuckle/Finbuckle.MultiTenant/blob/main/src/Finbuckle.MultiTenant/Strategies/DelegateStrategy.cs) here.

**Comment by iang0ld** [comment]
> @iang0ld You may want to use DelegateStrategy, this lets you provide a custom function that can do literally whatever you want. Docs here: https://www.finbuckle.com/MultiTenant/Docs/v6.6.1/Strategies
> 
> If you want a true custom strategy, you should implement `IMultiTenantStrategy` and make one yourself.
> 
> Check out the source for [Static](https://github.com/Finbuckle/Finbuckle.MultiTenant/blob/main/src/Finbuckle.MultiTenant/Strategies/StaticStrategy.cs), and [Delegate](https://github.com/Finbuckle/Finbuckle.MultiTenant/blob/main/src/Finbuckle.MultiTenant/Strategies/DelegateStrategy.cs) here.

Looks like delegate is exactly what I am looking for.  If you return null or empty string does that mean the next strategy in used.
For example will this use the deligate strategy and then the ClaimStategy?

services.AddMultiTenant<TenantInfo>()
        .WithDelegateStrategy(...)
        .WithClaimStrategy();

**Comment by AndrewTriesToCode** [comment]
> If you return null or empty string does that mean the next strategy is used

Yes!

@VictorioBerra thanks for helping out with responses

**Comment by iang0ld** [comment]
Perfect. Thanks.
