### ISSUE TITLE
HttpRemoteStoreSample not passing back tenant data

### ISSUE THREAD

**Issue by phil118** [Finbuckle/Finbuckle.MultiTenant#543]
Hi, Im just spiking something out and wasn't having much luck with HttpRemoteStore in my code so decided to pull the samples down, and i'm getting the same issue in the samples. 

It will find the tenant from remote store no problem but between a successful TryGetByIdentifierAsync log and printing out tenant info in view the HttpContext.GetMultiTenantContext<TenantInfo> model contains no data? 

To note it's working perfectly fine using ConfigurationStore.

Is this a bug or something i'm doing wrong?

Thanks

**Comment by AndrewTriesToCode** [comment]
hi, I'll take a look at the sample today to see what's wrong with it -- I will probably bring it up to .NET 6 as well.

**Comment by amfuller81** [comment]
I was moments away from bringing up this same exact issue. I tried getting this working for a project and after much frustration pulled down the samples to see what I may be missing and experienced the same issue.

**Comment by AndrewTriesToCode** [comment]
I suspect it may have to do with the move away from Newtonsoft.JSON to System.Text.JSON

**Comment by AndrewTriesToCode** [comment]
Yeah it was the store not deserializing the json from the server with the same serializer settings. I just updated it and the samples (still not net6.0 though) and should be working now. Thanks for reporting this!

I've made a note to try to capture this in automated testing in the future.
