### ISSUE TITLE
Help with EFCoreStore

### ISSUE THREAD

**Issue by b1tzer0** [Finbuckle/Finbuckle.MultiTenant#547]
I am new to this, so far, I think it is great.  But I need some help getting past these initial steps.

in my Program.cs file
```
builder.Services.AddMultiTenant<TenantInfo>()
    .WithClaimStrategy("http://mySample/OrgId")
    //.WithConfigurationStore();
    .WithEFCoreStore<TenantDbContext, TenantInfo>();
```

Then later I have the following:
```
var app = builder.Build();

// Apply migrations if needed
var store = app.Services.GetRequiredService<IMultiTenantStore<TenantInfo>>();
foreach (var tenant in await store.GetAllAsync())
{
    await using var db = new ApplicationDbContext(tenant);
    await db.Database.MigrateAsync();
}

```

When I get to the following line:
`var store = app.Services.GetRequiredService<IMultiTenantStore<TenantInfo>>();`

I get the following error:
An exception of type 'System.InvalidOperationException' occurred in Microsoft.Extensions.DependencyInjection.dll but was not handled in user code
Cannot resolve scoped service 'Finbuckle.MultiTenant.IMultiTenantStore`1[Finbuckle.MultiTenant.TenantInfo]' from root provider.

The TenantDbContext looks like the following:
```
    public class TenantDbContext : EFCoreStoreDbContext<TenantInfo>
    {
        readonly IConfiguration config;

        public TenantDbContext(IConfiguration config, DbContextOptions<TenantDbContext> options)
            : base(options)
        {
            this.config = config;
        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer(config.GetConnectionString("CatalogConfig"));
            base.OnConfiguring(optionsBuilder);
        }
    }
```

When utilizing the WithConfigurationStore, the migrations work with no problems.

Secondary question:  If the TenantDbContext database does not exist, does it get created automatically?  Or do I need to do migrations with it first?

Thanks in advance

**Comment by b1tzer0** [comment]
Extra Info: 
This is .net6
Using Blazor WASM

I have tried the following changes:
TenantDbContext.cs
```
public class TenantDbContext : EFCoreStoreDbContext<TenantInfo>
    {
        public TenantDbContext(DbContextOptions options) : base(options)
        {
        }
    }
```

Program.cs
```
builder.Services.AddDbContext<TenantDbContext>(options =>
{
    options.UseSqlServer(
        builder.Configuration.GetConnectionString("CatalogConnection"));
});

builder.Services.AddMultiTenant<TenantInfo>()
    .WithClaimStrategy("http://mySample/OrgId")
    .WithConfigurationStore() // Use this for the default configuration.
    .WithEFCoreStore<TenantDbContext, TenantInfo>();
```

Still getting the same error as above.

**Comment by AndrewTriesToCode** [comment]
Hi @b1tzer0 

You are running into [scope validation](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/web-host?view=aspnetcore-6.0#scope-validation). Since most db contexts are registered as a scoped service the service provider is strict about resolving a service unless you are in a scope. In ASP.NET Core / Blazor they create the scope for you prior to your controllers/components being called. In just the program.cs file though you have to do it yourself:

```cs
var app = builder.Build();

// Apply migrations if needed
using (var scope = app.Services.CreateScope())
{
    var store = scope.ServiceProvider.GetRequiredService<IMultiTenantStore<TenantInfo>>();
    foreach (var tenant in await store.GetAllAsync())
    {
        await using var db = new ApplicationDbContext(tenant);
        await db.Database.MigrateAsync();
    }
}
```

Hope this helps!

> If the TenantDbContext database does not exist, does it get created automatically? Or do I need to do migrations with it first?

It depends on the underlying database if you take no special action, but with you calling `MigrateAsync` on each one it will create it if needed. You could also use `EnsureCreated` but this will not apply migrations to an existing database.

**Comment by b1tzer0** [comment]
I was actually trying that solution as you replied, thank you so much for a rapid response.
