### ISSUE TITLE
Split/Merge Use Case

### ISSUE THREAD

**Issue by b1tzer0** [Finbuckle/Finbuckle.MultiTenant#549]
Has anyone ever discussed the possibility of having a split/merge feature?

This has happened a couple of times on our legacy platform where multiple databases would need to be split out or merged together.

Some examples that come time mind:

- Split: A company is on a shared database, but later decides they want their own database.  What would be the process of migrating that company data over to the new system? 
- Split/Merge: A company originally had multiple connections but wants to consolidate. 

I am guessing both approaches would be similar but wanted to check to see if any thought had been put in about automating the functionality.

**Comment by VictorioBerra** [comment]
@b1tzer0 Finbuckle already supports a hybrid model for per-tenant data, see the bottom of these docs: https://www.finbuckle.com/MultiTenant/Docs/v6.6.1/EFCore

I would imagine you would have to manually handle moving your data to a separate DB, or moving the separate DB data into the shared tenant DB.

How could Finbuckle solve that problem for you?

**Comment by AndrewTriesToCode** [comment]
I have thought about this but to be honest it's a little out of scope since there's a lot of factors that are specific to the situation and the database provider. If you can think of a good wide-ranging approach I would certainly consider it. I also may include something like this as a feature in a premium offering in the future -- but I'd still probably make the source available.

**Comment by b1tzer0** [comment]
What I am thinking of is similar to the Elastic DB Tools that was originally provided by Microsoft.  
I was originally planning on using those tools (since it is still recommended way of doing multi-tenant via Microsoft Docs) but found the project was no longer being maintained.  That is when I continued my search and found this project.

https://github.com/Azure/elastic-db-tools

The elastic tools were originally designed for Database Sharding, but the concept is almost identical to what you built.  Yours has a few features they do not, and they have a few features you do not.

Maybe the elastic db tools can generate some ideas on how it might be accomplished.

**Comment by AndrewTriesToCode** [comment]
I agree. Just thinking out loud, I think the most common case is a database moving from shared to its own database. It seems pretty straight forward for small amounts of data, but what if it is hours worth of transfers? Does the entire app need to go down for that? These are tough questions I don't have good answers for except "it depends".

**Comment by b1tzer0** [comment]
In my specific use case, it would just be the one tenant that has to go down, not the entire app; of course, it would cause a slow down for anyone using the shared database.

One possible way, again; this is my use case, I don't know about others.
Being able to tell the difference between configuration tables and transactional tables.

Migrating config in some instances could be much faster (I guess that really depends though on the number of config tables).
This would allow the tenant to be up and running faster, while still migrating transactional data in the background in smaller bits.

Either way, I think that whatever needs to happen that it should be a background process or a secondary application.  If I recall the elastic tools had a management console app that was external to the running app.  

Like someone else said, it might just be something I need to write as the situations occur.

**Comment by VictorioBerra** [comment]
@b1tzer0 It almost sounds easier to me to just have every tenant on their own DB and not ever need to add all of this highly complex splitting and merging stuff. At most you will need a process to create new tenant DBs, or apply migrations against existing ones.
