### ISSUE TITLE
Hangfire Dashbords and TryGetByIdentifierAsync: Unable to find Tenant with identifier """" with HangfireCustomBasicAuthenticationFilter

### ISSUE THREAD

**Issue by gianpaoloi** [Finbuckle/Finbuckle.MultiTenant#550]
Hi everydody,
I get the information messages :
[Debug] GetIdentifierAsync: Found identifier: """" 
[Debug] TryGetByIdentifierAsync: Unable to find Tenant with identifier """" 

when I'm using the Hangfire dashbord with HangfireCustomBasicAuthenticationFilter.

 I have corretly setted the JobParameter by IClientFilter when I'm creating a job.

How can I create a "tenant" autentication in Hangfire Dashboards?

Thanks

**Comment by AndrewTriesToCode** [comment]
hi @gianpaoloi I'm not particularly familiar with Hangfire -- can you tell me which Finbuckle tenant strategy you are using to detect the tenant? For some reason is is only picking up empty double quotes -- do you expect it to have identified a tenant?

**Comment by gianpaoloi** [comment]
Hi @AndrewTriesToCode  actually I'm using ClaimStrategy and HeaderStrategy. 

I'm creating a backoffice andministration page for background jobs.
Right now this page doesn't require a tenant but is very annoing to have the log with a lot of "No identifier found" :(. 

Thanks

**Comment by AndrewTriesToCode** [comment]
Hi, I know what you mean. One thing you can do is create a default tenant to avoid that issue and some other headaches. You would want to register the StaticStrategy after your other strategies so the static will be the default/fallback.

Alternatively you could adapt the middleware to ignore certain routes. I probably need to think of a way to add that to the library.

**Comment by gianpaoloi** [comment]
Tahnks for reply,
I choose to use the DelegateStrategy strategy checking if the request path have the dashboards Route and return a "default" tenant.
but the console log i still have a lot of 
![image](https://user-images.githubusercontent.com/99672700/161725217-334426f5-ff35-4e6b-824b-650d514afce5.png)

How Can I resolve this behavior?

**Comment by AndrewTriesToCode** [comment]
So there are two things:

1. On `AddMultiTenant<T>(options => ...)` you can set a list of strings which will be ignored for tenant consideration -- perfect for this type of use case.

2. Or you can filter out logging all together as described [here](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-6.0#configure-logging). You'll just add `Finbuckle.MultiTenant` to your log configuration and set the level to Information or higher and you won't see these.

**Comment by gianpaoloi** [comment]
@AndrewTriesToCode  Thanks for you helpful reply! ;)
