### ISSUE TITLE
Relationship between MultiTenantDbContext and EFCoreStoreDbContext

### ISSUE THREAD

**Issue by kbaley** [Finbuckle/Finbuckle.MultiTenant#558]
I'm working through [this guidance](https://www.finbuckle.com/MultiTenant/Docs/v6.7.2/EFCore#deriving-from-multitenantdbcontext) with a shared database. I modified my DB context to inherit from MultiTenantDbContext and I marked one of my entities as IsMultiTenant in the fluent API in OnModelCreating. Then I ran `dotnet ef migrations add MyMigration`. It add the TenantID field to my entity as expected but I also expected it to create a TenantInfo table in the database as well which it didn't. Looking through the code, I _think_ it's because MultiTenantDbContext doesn't include a DbSet&lt;TenantInfo&gt; whereas [EFCoreStoreDbContext does](https://github.com/Finbuckle/Finbuckle.MultiTenant/blob/main/src/Finbuckle.MultiTenant.EntityFrameworkCore/Stores/EFCoreStore/EFCoreStoreDbContext.cs#L16). 

Is EFCoreStoreDbContext meant solely for managing tenant data while MultiTenantDbContext is for the rest of my business data?

**Comment by AndrewTriesToCode** [comment]
So sorry for the slow reply.

> Is EFCoreStoreDbContext meant solely for managing tenant data while MultiTenantDbContext is for the rest of my business data?

Yes this is correct. EFCoreStore database itself wouldn't be MultiTenant -- at least not normally. In other words each tenant doesn't have its own per-tenant list of tenants. Rather the overall app has a single list of tenants.

**Comment by kbaley** [comment]
Thanks for the clarification
