### ISSUE TITLE
TenantInfo is null in OnConfiguring

### ISSUE THREAD

**Issue by BihunRoman** [Finbuckle/Finbuckle.MultiTenant#559]
Hi,

I am using HostStrategy and ConfigurationStore. I get an error
System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.)
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at DataAccess.Context.MyContext.OnConfiguring(DbContextOptionsBuilder optionsBuilder) 

I used to have this error on adding the migration but after creating SharedDesignTimeFactory as it was proposed I have the same error on the startup.

Any ideas why TenantInfo is null? 

My context is derived from MultiTenantIdentityDbContext<User> as I want to use Identity.

I have constractors: 

 public MyContext(ITenantInfo tenantInfo, DbContextOptions<MyContext> options) : base(tenantInfo, options)
        {
        }

public MyContext(ITenantInfo tenantInfo) : base(tenantInfo)
        {
        }

My OnConfiguring method:

protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer(TenantInfo.ConnectionString);
            base.OnConfiguring(optionsBuilder);
        }

**Comment by AndrewTriesToCode** [comment]
Hi did you figure this out? At migration time no tenant exists so there is a section in the docs on how to use a `DesignTimeFactory` to enable migrations. Let me know if you need any help. Sorry for the slow reply.
