### ISSUE TITLE
AMQP Context support

### ISSUE THREAD

**Issue by onurkanbakirci** [Finbuckle/Finbuckle.MultiTenant#562]
Is there a built-in support for get tenant identifier from RabbitMQ message? In http requests, we get tenant identifier from `HttpContext` instance and then we set `TenantInfo` by using this tenant identifier. But what if we use amqp protocol for server to server communication? In this situation how can we set `TenantInfo`?

**Comment by AndrewTriesToCode** [comment]
Hi, there is no specific support of this but you can implement `IMultiTenantStrategy` pretty easily and it take a general object parameter for context which doesn't have to be `HttpContext`. You could pass in a message and parse our the identifier from there.

I'm not familiar with amp does it use a pipeline similar to regular ASP.NET Core?

**Comment by onurkanbakirci** [comment]
For my experience, amqp doesn't have similar pipeline like http request. So, amqp message not enter the custom `IMultiTenantStrategy` method. I also try to set tenant by using `TrySetTenantInfo` method but it's not work because of absence of `HttpContext` in amqp messages. By the way,  i need to set the `TenantInfo` from my custom amqp message handler function without having `HttpContext`. Are there any solution for that?

**Comment by scharada** [comment]
i think i've seen this ... i believe MassTransit allows you to do what you want using message headers regardless of the protocol ... you should check it out.

**Comment by onurkanbakirci** [comment]
Adding 
````
 var accessor = _serviceProvider.GetService<IMultiTenantContextAccessor>();
 var multiTenantContext = new MultiTenantContext<TenantInfo>();
 multiTenantContext.TenantInfo = tenantInfo;
 accessor.MultiTenantContext = multiTenantContext;
````
before service injections, finbuckle works as expected. 
After adding above script, i can inject services which belongs to dbcontext by using 
````
var paymentTypeService = _serviceProvider.GetService<IPaymentTypeService>()!;
````
