### ISSUE TITLE
System.NullReferenceException: Object reference not set to an instance of an object when I try to Seed data

### ISSUE THREAD

**Issue by BihunRoman** [Finbuckle/Finbuckle.MultiTenant#564]
How can I seed multi-tenant identity objects (e.g. Users, Roles) from the middleware not to have NullReferenceException? 
I checked this https://github.com/Finbuckle/Finbuckle.MultiTenant/issues/312 but it didn't help. 
Here is my IdentityDataInitializer.cs:
`public static class IdentityDataInitializer
    {
        public static void SeedData(UserManager<User> userManager, RoleManager<Role> roleManager,
            MyContext context, IServiceProvider serviceProvider, TenantConfigs tenantConfigs)
        {
            foreach (var tenantConfig in tenantConfigs.Tenants)
            {
                var tenant = new TenantInfo
                {
                    Id = tenantConfig.Id,
                    Identifier = tenantConfig.Identifier,
                    Name = tenantConfig.Name,
                    ConnectionString = tenantConfig.ConnectionString
                };

                var accessor = serviceProvider.GetRequiredService<IMultiTenantContextAccessor>();
                var multiTenantContext = new MultiTenantContext<TenantInfo>
                {
                    TenantInfo = tenant
                };
                accessor.MultiTenantContext = multiTenantContext;

                SeedRoles(roleManager, tenant);
                SeedUsers(userManager, tenant);
                SeedTerminologies(context, tenant);
            }
        }

        public static void SeedUsers(UserManager<User> userManager, TenantInfo tenant)
        {
            if (!userManager.Users.Any())
            {
                User user = new User

                {
                    UserName = "Admin",
                    Email = "admin@admin.com",
                    FirstName = "First",
                    LastName = "Admin",
                    EmailConfirmed = true
                };

                IdentityResult result = userManager.CreateAsync(user, "hidden1").Result;

                if (result.Succeeded)
                {
                    userManager.AddToRoleAsync(user, RoleTypes.Administrator.ToString()).Wait();
                }
            }
        }

        public static void SeedRoles(RoleManager<Role> roleManager, TenantInfo tenant)
        {
            if (!roleManager.RoleExistsAsync(RoleTypes.Administrator.ToString()).Result) //this throws an exeption
            {
                var role = new Role
                {
                    Name = RoleTypes.Administrator.ToString()
                };
                _ = roleManager.CreateAsync(role).Result;
            }

            if (!roleManager.RoleExistsAsync(RoleTypes.Manager.ToString()).Result)
            {
                var role = new Role
                {
                    Name = RoleTypes.Manager.ToString()
                };
                _ = roleManager.CreateAsync(role).Result;
            }

            if (!roleManager.RoleExistsAsync(RoleTypes.Viewer.ToString()).Result)
            {
                var role = new Role
                {
                    Name = RoleTypes.Viewer.ToString()
                };
                _ = roleManager.CreateAsync(role).Result;
            }
        }
}`
Could you please help to identify why it throws the exeption?

**Comment by AndrewTriesToCode** [comment]
Hi it's most likely because DI isn't fully setup when seeding is called.

Here is a seed example from a client's project:

```
    public static void EnsureSeedData(WebApplication app)
    {
        // Setup and migrate tenant store database.
        using var scope = app.Services.CreateScope();
        var platformOptions = scope.ServiceProvider.GetRequiredService<IOptionsMonitor<PlatformOptions>>().CurrentValue;
        var tenantStoreDbContext = scope.ServiceProvider.GetRequiredService<MultiTenantStoreDbContext>();
        tenantStoreDbContext.Database.Migrate();

        // Seed initial primary tenant.
        var multiTenantStore = scope.ServiceProvider.GetRequiredService<IMultiTenantStore<TenantInfo>>();
        var primaryTenant = platformOptions.PrimaryTenant;

        var tenant1 = new TenantInfo()
        {
            Id = primaryTenant,
            Identifier = primaryTenant,
            Name = primaryTenant,
        };
        try
        {
            multiTenantStore.TryAddAsync(tenant1).Wait();
        }
        catch
        {
        }

        // Migrate Identity database
        var mtca = scope.ServiceProvider.GetRequiredService<IMultiTenantContextAccessor<TenantInfo>>();
        var originalMtc = mtca.MultiTenantContext;
        mtca.MultiTenantContext = new MultiTenantContext< TenantInfo >() { TenantInfo = tenant1 };
        using var identityDbContext = scope.ServiceProvider.GetRequiredService<IdentityDbContext>();
        identityDbContext.Database.Migrate();
        var roleManager = scope.ServiceProvider.GetRequiredService<RoleManager<Role>>();
        // Create GlobalAdmin role
        if (!roleManager.RoleExistsAsync("GlobalAdmin").Result)
        {
            var role = new Role() { Name = "GlobalAdmin" };
            roleManager.CreateAsync(role).Wait();
            roleManager.AddClaimAsync(role, new Claim("Permission", "GlobalAdmin")).Wait();
        }
        // Create default admin account
        var userManager = scope.ServiceProvider.GetRequiredService<UserManager<User>>();
        var adminUsername = platformOptions.DefaultAdminUsername;
        var adminPassword = platformOptions.DefaultAdminPassword;
        if (userManager.FindByNameAsync(adminUsername).Result == null)
        {
            var adminUser = new User();
            adminUser.UserName = adminUsername;
            adminUser.Email = adminUsername;
            adminUser.EmailConfirmed = true;
            var identityResult = userManager.CreateAsync(adminUser, adminPassword).Result;
            identityResult = userManager.AddToRoleAsync(adminUser, "GlobalAdmin").Result;
        }
        
        mtca.MultiTenantContext = originalMtc;
    }
```

This method is called in `Configure` right before `App.Run`:
```
SeedData.EnsureSeedData(app);
app.Run();
```

I hope this helps let me know if you have any specific questions.

**Comment by BihunRoman** [comment]
Thanks @AndrewTriesToCode ,

I will try this but I have a few questions on this:
1) What is the PlatformOptions class? 
2) You wrote: "This method is called in `Configure `right before `App.Run`". Do you mean this method is called in `Main `method of `Program`?

**Comment by BihunRoman** [comment]
Now NullRefferenceException is thrown from a different place.

```
using var identityDbContext = scope.ServiceProvider.GetRequiredService<IdentityDbContext>();
identityDbContext.Database.Migrate();
var roleManager = scope.ServiceProvider.GetRequiredService<RoleManager<Role>>();
// Create GlobalAdmin role
if (!roleManager.RoleExistsAsync("GlobalAdmin").Result)    //<-Error
```
And even identityDbContext.Roles.Any() throws it.
So yes, this is some DI issue that I haven't figured out yet. 

Also, I cannot select tables from SQL Mngmt studio, I see the error 
![image](https://user-images.githubusercontent.com/51881695/180238097-b50a512e-b527-455e-8d7c-f9d5265480a5.png)
