### ISSUE TITLE
Nested Tenants ?

### ISSUE THREAD

**Issue by scharada** [Finbuckle/Finbuckle.MultiTenant#565]
hi there. i've seen a comment somehow related to this. tenant grouping but with a more complex requirement.

here is the scenario. think of a Company C that owns several subsidiaries s1, s2, s3 ... where each sells a line of products. 
each subsidiary has its own operation and manages its own activities separately from the others, therefore can be setup as tenants.
the parent company however, must be able to access all subsidiaries data (roles and rights applu here too.)
think of a dashboard at corporate level watching activities of all subsidiaries alltogether or select one or more to 

can there be a way to set a tenant B as a child of Tenant A which would give tenant A access to its children tenants data ?

thanks.

**Comment by AndrewTriesToCode** [comment]
Hi, unfortunately there is no general support for this at the moment. I've though about it and not come to a clean way to implement it just yet. Might be that you have your own derived version of `MultiTenantDbContext` and modify the `OnModelCreating` method (global query filter that is set there for tenant) as needed for your particular use case.

**Comment by scharada** [comment]
thank you.
