### ISSUE TITLE
6.7.3 "Removing reliance on uncaught exception" causing issue

### ISSUE THREAD

**Issue by bwayway** [Finbuckle/Finbuckle.MultiTenant#575]
We've come across an issue in the most recent release made in PR [#563](https://github.com/Finbuckle/Finbuckle.MultiTenant/pull/563):
```csharp
                if (dynamicTenantInfo != null)
                {
                    options.Authority = HasPropertyWithValidValue(dynamicTenantInfo, nameof(dynamicTenantInfo.OpenIdConnectAuthority)) ? ((string)dynamicTenantInfo.OpenIdConnectAuthority).Replace(Constants.TenantToken, tc.Identifier) : string.Empty;
                    options.ClientId = HasPropertyWithValidValue(dynamicTenantInfo, nameof(dynamicTenantInfo.OpenIdConnectClientId)) ? ((string)dynamicTenantInfo.OpenIdConnectClientId).Replace(Constants.TenantToken, tc.Identifier) : string.Empty;
                    options.ClientSecret = HasPropertyWithValidValue(dynamicTenantInfo, nameof(dynamicTenantInfo.OpenIdConnectClientSecret)) ? ((string)dynamicTenantInfo.OpenIdConnectClientSecret).Replace(Constants.TenantToken, tc.Identifier) : string.Empty;
                }
            });
```

We are using Duende Identity Server, and with our project, our ITenantInfo object does not have the Authority, ClientId, and ClientSecret populated. Therefore we are getting empty values returned from HasPropertyWithValidValue. Instead, we would like to have the original value returned, rather than an empty string.

Do you see any issue if we add this change? @SharePointRadi

**Comment by AndrewTriesToCode** [comment]
I think this is reasonable. Just to clarify, if there is no tenant value then instead of empty use the default non-tenant specific option value?

**Comment by SharePointRadi** [comment]
That sounds like a reasonable ask. The default, non-tenant specific settings should be retrievable, if provided. I think that is what is meant by "original value", right?

**Comment by bwayway** [comment]
@AndrewTriesToCode @SharePointRadi Yes sorry I should have been more specific. The non-tenant specific options value.

**Comment by AndrewTriesToCode** [comment]
Just refactored this to avoid this issue, including unit tests and doc updates to make everything more robust.
