### ISSUE TITLE
Can't see hints

### ISSUE THREAD

**Issue by onurkanbakirci** [Finbuckle/Finbuckle.MultiTenant#582]
When i use `Finbuckle` in my own projects, i have figured out that there is no hint when i hover or highlight to functions or properties of `Finbuckle` project. I have looked source code of project and i have seen that there are comments for classes, functions and props. etc. So, why i can't see these comments when i hover to functions etc.  in VStudio?

Example:

<img width="690" alt="Screen Shot 2022-08-28 at 17 37 43" src="https://user-images.githubusercontent.com/50163185/187079611-115e2aa5-52dc-4f38-8b60-00cda3e846a0.png">

But i can see comments in source codes:

<img width="780" alt="Screen Shot 2022-08-28 at 17 45 26" src="https://user-images.githubusercontent.com/50163185/187079943-577bebad-e347-486f-89f6-7d9c5b143871.png">

**Comment by AndrewTriesToCode** [comment]
Hm that's a good question. Is this Visual Studio, VS Code, or something different? If you open up one of the sample projects do you see the hints?

**Comment by AndrewTriesToCode** [comment]
Well I had a setting wrong and I think it should be fixed with 6.8.1 release tonight. Thanks for letting me know!
