### ISSUE TITLE
TrySetTenantInfo problem

### ISSUE THREAD

**Issue by onurkanbakirci** [Finbuckle/Finbuckle.MultiTenant#587]
In my app, i need to change `tenantInfo` at runtime by using `TrySetTenantInfo` method. When i use following code, 
```
_httpContextAccessor.HttpContext.TrySetTenantInfo(new Tenant(), true);
 var userManager = _serviceProvider.GetService<UserManager<AppUser>>()!;
_httpContextAccessor.HttpContext.TrySetTenantInfo(new Tenant { Id = "asdasdasdasd" }, true);
```
i expect that `userManager` class' `TenantInfo` (inside of object `userManager -> Stores -> Context -> TenantInfo`) will be updated. However, when i check it, it was not updated. When i also check `HttpContext`'s `tenantInfo` was updated correctly or not by using 

```
HttpContext.GetMultiTenantContext<TenantInfo>().TenantInfo;
```

command, i can see that it's correct. So, i think that `resetServiceProviderScope` parameter is not work as expected even though i set it as true. I expect `userManager` instance's `tenantInfo` is also updated after setting `tenantInfo` by using `TrySetTenantInfo` extension method.

**Comment by AndrewTriesToCode** [comment]
hi @onurkanbakirci I see what you are saying. Based on that example code I think the problem is that `_serviceProvider` is still a reference to the original `HttpContext` DI scope. After the call to `TrySetTenantInfo` the service provider on `HttpContext` is reset so you'll want to get the service provider from `HttpContext` again:
```cs
_httpContextAccessor.HttpContext.TrySetTenantInfo(new Tenant(), true);
_serviceProvider = HttpContext.RequestService;
 var userManager = _serviceProvider.GetService<UserManager<AppUser>>()!;
``

Does that make sense? Give it a try and let me know.

**Comment by onurkanbakirci** [comment]
Yes, that's the solution. But it should be;
````

_serviceProvider = HttpContext.RequestServices;
````
Thank's for your time.
