### ISSUE TITLE
MultiTenantContext null after Blazor Server hot reload

### ISSUE THREAD

**Issue by Bouke** [Finbuckle/Finbuckle.MultiTenant#599]
When developing `dotnet watch` (aka hot reload) is a great performance boost. However it doesn't work with this package: `MultiTenantContextAccessor<T>._asyncLocalContext` will be `null` after a hot reload.

My analysis thus far after prodding it for a few hours. `AsyncLocal` apparently doesn't flow when a hot reload is performed. The middleware that initially sets the value isn't triggering, as there's no new HTTP request coming in.

 I _think_ replacing `AsyncLocal` with a scoped DI container might work, however I cannot get scoped dependency from a singleton `IMultiTenantContextAccessor`. This seems by design and "something" should own a DI scope. I would like the `CircuitHost` to provide me with scoped container, but I haven't found a way to make that happen.

<details>
<summary>Minimal example</summary>

Generate a Blazor Server app. Then install this package. Modify the following files:

Index.razor:
```cshtml
@page "/"
@using Finbuckle.MultiTenant
@inject IMultiTenantContextAccessor<TenantInfo> TenantContextAccessor
<h1>Hello, @TenantInfo?.Name!</h1>
@code {
    TenantInfo? TenantInfo => TenantContextAccessor.MultiTenantContext?.TenantInfo;
}
```

Program.cs:
```cs
using Finbuckle.MultiTenant;

var builder = WebApplication.CreateBuilder(args);

builder.Services.AddRazorPages();
builder.Services.AddServerSideBlazor();
builder.Services.AddHttpContextAccessor();

builder.Services.AddMultiTenant<TenantInfo>()
    .WithHostStrategy("__tenant__")
    .WithInMemoryStore(options =>
    {
        options.Tenants.Add(new TenantInfo { Id = "A", Identifier = "localhost", Name = "A", } );
    });

var app = builder.Build();

if (!app.Environment.IsDevelopment())
{
    app.UseExceptionHandler("/Error");
    app.UseHsts();
}

app.UseHttpsRedirection();

app.UseStaticFiles();

app.UseMultiTenant();
app.UseRouting();

app.MapBlazorHub();
app.MapFallbackToPage("/_Host");

app.Run();
```

Run the application using `dotnet watch`. It should display "Hello, A!" ("A" being the name of the tenant). Now modify `Index.razor` (e.g. add a newline). Hot reload will apply changes. Now the text will read "Hello, !".

</details>

**Comment by Bouke** [comment]
Instead of trying to fix this through DI registrations, I've fixed (worked around) the issue by flowing from `AsyncLocal` to a DI container and back. This works as when Blazor is booted the tenant is stored in `AsyncLocal`, which will then be copied over to the DI scoped container. When a hot reload is performed on the app, the tenant is copied from the DI scoped container back to `AsyncLocal`.

Note that we could also do something similar with cascading parameters, but then the current tenant would still not be visible to other parts of the code.

TenantResolver.razor
```cshtml
@using Finbuckle.MultiTenant
@inject TenantContainer<TenantInfo> Container;
@inject IMultiTenantContextAccessor<TenantInfo> Accessor;

@ChildContent

@code {

    [Parameter]
    public RenderFragment ChildContent { get; set; } = null!;

    protected override void OnInitialized()
    {
        Container.MultiTenantContext ??= Accessor.MultiTenantContext;
    }

    protected override void OnParametersSet()
    {
        Accessor.MultiTenantContext ??= Container.MultiTenantContext;
    }

}
```

Program.cs
```cs
builder.Services.AddScoped<TenantContainer<TenantInfo>>();

public class TenantContainer<T> : IMultiTenantContextAccessor<T> where T : class, ITenantInfo, new()
{
    public IMultiTenantContext<T>? MultiTenantContext { get; set; }
}
```

**Comment by AndrewTriesToCode** [comment]
Hi, for other reasons I'm considering going with a scoped instance underlying `IMultitenantAccessor` so thanks for helping me justify it. In the meantime I'm glad you have a workaround. I'm going to go ahead and close this but feel free to reopen.

Thanks!

**Comment by Bouke** [comment]
Beware that an instance scoped to the http request doesn’t flow to the blazor circuit’s scope.
