### ISSUE TITLE
How to use PostgreSQL database as a MultitenantStore?

### ISSUE THREAD

**Issue by ZedZipDev** [Finbuckle/Finbuckle.MultiTenant#620]
Is it possible to keep TenantInfo data in a custom database without using EF?

**Comment by AndrewTriesToCode** [comment]
Hi again, it certainly is but you will have to implement `IMultiTenantStore<T>` yourself. It's not a complicated interface so you should be able to use it easily. You can also use EF Core with a Postgres database which works pretty well. The library for that is [Npsql](https://www.npgsql.org/efcore/).
