### ISSUE TITLE
Should ITenantInfo have connection string removed?

### ISSUE THREAD

**Issue by PeterKneale** [Finbuckle/Finbuckle.MultiTenant#624]
- I feel like given there is support for a custom implementation of the `ITenantInfo` this property should be removed / deprecated and users of the library can implement it upon their own class should they require it.

Rationale: 
- There may be no tenant specific connection strings involved (shared schema pattern with row level security etc)
- There can be multiple connection strings involved, per tenant elastic search, per tenant redis, multiple relational stores etc .
- It feels like an implementation detail that the library shouldnt concern itself with.

```cs
    public interface ITenantInfo
    {
        string? Id { get; set; }
        string? Identifier { get; set;  }
        string? Name { get; set; }
        string? ConnectionString { get; set; } <--
    }
```

**Comment by natelaff** [comment]
I've brought this up before as well. #325

**Comment by AndrewTriesToCode** [comment]
Yep I agree with both of you. It's be a breaking change and I'm trying to group it in with some others for a major version bump.
