### ISSUE TITLE
_signInManager.PasswordSignInAsync() is throwing a NullReferenceException: Object reference not set to an instance of an object. 

### ISSUE THREAD

**Issue by hamedimbasher** [Finbuckle/Finbuckle.MultiTenant#642]
```
NullReferenceException: Object reference not set to an instance of an object.
lambda_method46(Closure , QueryContext )
Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync<TResult>(Expression query, CancellationToken cancellationToken)
Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync<TResult>(Expression expression, CancellationToken cancellationToken)
Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync<TSource, TResult>(MethodInfo operatorMethodInfo, IQueryable<TSource> source, Expression expression, CancellationToken cancellationToken)
Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync<TSource, TResult>(MethodInfo operatorMethodInfo, IQueryable<TSource> source, LambdaExpression expression, CancellationToken cancellationToken)
Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.FirstOrDefaultAsync<TSource>(IQueryable<TSource> source, Expression<Func<TSource, bool>> predicate, CancellationToken cancellationToken)
Microsoft.AspNetCore.Identity.EntityFrameworkCore.UserStore<TUser, TRole, TContext, TKey, TUserClaim, TUserRole, TUserLogin, TUserToken, TRoleClaim>.FindByNameAsync(string normalizedUserName, CancellationToken cancellationToken)
Microsoft.AspNetCore.Identity.UserManager<TUser>.FindByNameAsync(string userName)
Microsoft.AspNetCore.Identity.SignInManager<TUser>.PasswordSignInAsync(string userName, string password, bool isPersistent, bool lockoutOnFailure)
TherapyPlanner.OAuth.Pages.Login.Index.OnPost() in Index.cshtml.cs
+
                var result = await _signInManager.PasswordSignInAsync(Input.Username, Input.Password, Input.RememberLogin, lockoutOnFailure: true);
```

We have 2 projects in the same solution

1. IdentityContext : MultiTenantIdentityDbContext<User, Role, Guid, IdentityUserClaim<Guid>, UserRole, IdentityUserLogin<Guid>, IdentityRoleClaim<Guid>, IdentityUserToken<Guid>>
2. ExampleDbContext : DbContext

We're using the IdentityContext with Duende Server as an Identity Server with Code Grant with PKCE, and ExampleDbContext for our BusinessAPI, both as a multi tenant

I've added the migrations and updated the Identity Database, we can see the TenantId for the User,Role, etc..., when I click login after entering the username and password on the login page; the _signInManager.PasswordSignInAsync(Input.Username, Input.Password, Input.RememberLogin, lockoutOnFailure: true); is throwing a null exception

.NET 6, 
Duende Server V6

**Comment by AndrewTriesToCode** [comment]
Looks like the dbcontext isn't picking up the current tenant to use for the sign in request. What multitenant strategy are you using and do you know if the tenant for the request is being detected correctly? If you turn on debug logging the library will tell you if it has found the tenant or not as the middleware runs.

**Comment by hamedimbasher** [comment]
I'm using the `ClaimStrategy` 

**Below are the log for the middleware**

```
[01:51:48 Debug] Finbuckle.MultiTenant.Strategies.ClaimStrategy
GetIdentifierAsync: No identifier found

[01:51:48 Debug] Finbuckle.MultiTenant.Strategies.RemoteAuthenticationCallbackStrategy
GetIdentifierAsync: No identifier found
```

 **I've also added ConfigurePipeline as a screenshot**

![image](https://user-images.githubusercontent.com/81822466/219811310-72e8e84b-dba3-4d6f-b17d-6a49f767ac8f.png)

**Here is the ConfigureServices implementation,** 
```
 builder.Services.AddRazorPages();

            builder.Services.AddCors(opt =>
            {
                opt.AddDefaultPolicy(builder =>
                {
                    builder.AllowAnyOrigin()
                        .AllowAnyHeader()
                        .AllowAnyMethod();
                });
            });



            builder.Services.AddDbContext<IdentityContext>(options =>
                options.UseSqlServer(builder.Configuration.GetConnectionString("DefaultConnection")));


            builder.Services.AddMultiTenant<TenantInfo>()
            .WithClaimStrategy()
            .WithConfigurationStore()
            .WithPerTenantAuthentication();

            builder.Services.AddIdentity<User, Role>(options =>
            {
                options.User.RequireUniqueEmail = true;
            })
               .AddEntityFrameworkStores<IdentityContext>()
                .AddDefaultTokenProviders();

            builder.Services
                .AddIdentityServer(options =>
                {

                    options.Events.RaiseErrorEvents = true;
                    options.Events.RaiseInformationEvents = true;
                    options.Events.RaiseFailureEvents = true;
                    options.Events.RaiseSuccessEvents = true;

                    // see https://docs.duendesoftware.com/identityserver/v6/fundamentals/resources/
                    options.EmitStaticAudienceClaim = true;
                })
                .AddInMemoryIdentityResources(Config.IdentityResources)
                .AddInMemoryApiScopes(Config.ApiScopes)
                .AddInMemoryClients(Config.Clients)
                .AddAspNetIdentity<User>();
            //.AddProfileService<CustomProfileService>();


            return builder.Build();
```
I've also attached log file from running the Identity Server to logging in (Throwing the exception)

[log.txt](https://github.com/Finbuckle/Finbuckle.MultiTenant/files/10772184/log.txt)

**Comment by hamedimbasher** [comment]
Using the extentsion method `.WithStaticStrategy("acme")` in both APIs is working, but we want it to set the tenant id in the access token from the Identity Server when logging in based on the TenantId column in the Users table, and when requesting data from the Business API; we want to get the tenant id from the access token using the ClaimStrategy.

**Comment by hamedimbasher** [comment]
I figured it out, I was using the tenantId in the UserClaim instead of the tenant name, the ClaimStrategy is now picking up the tenant in the HttpContext

Thank you

**Comment by AndrewTriesToCode** [comment]
I'm glad you got it and sorry I couldn't be more helpful. I think you've got on a good point-- the I'd could also be a valid thing to check. I also think there are situations where a single tenant might have multiple identifiers.

**Comment by ava-vn** [comment]
I encountered the same situation
We better build a sample for the api.
@AndrewTriesToCode
