### ISSUE TITLE
DistributedCache Error

### ISSUE THREAD

**Issue by goforebroke** [Finbuckle/Finbuckle.MultiTenant#647]
Hello,

I am using multiple stores to resolve a tenant

1. WithDistributedCacheStore
2. WithHttpRemoteStore

If the 1st store does not resolve the tenant it moves to the 2nd store ([423](https://github.com/Finbuckle/Finbuckle.MultiTenant/issues/423))

The distributed cache store is backed with Redis and is registered per below

            services.AddStackExchangeRedisCache(options =>
            {
                options.Configuration = configuration["CacheServer:HostAddress"];
                options.InstanceName = configuration["CacheServer:InstanceName"];
            });

            return services;

The http remote store is just an API that does tenant resolution and tenant management backed with a database SQL Server.

Below is how the multitenant services are registered, stores and strategy...

            services.AddMultiTenant<Tenant>(options =>
            {
                options.Events = new MultiTenantEvents()
                {
                    OnTenantResolved = async (context) =>
                    {
                        var tenant = context.TenantInfo;
                        var sp = ((HttpContext)context.Context).RequestServices;
                        var distributedCacheStore = sp.GetService<IEnumerable<IMultiTenantStore<Tenant>>>()
                        .Where(s => s.GetType() == typeof(DistributedCacheStore<Tenant>)).FirstOrDefault();

                        await distributedCacheStore.TryAddAsync((Tenant)tenant);

                        await Task.FromResult(0);
                    }
                };
            })
            .WithHeaderStrategy()
            .WithDistributedCacheStore<Tenant>(TimeSpan.FromSeconds(300))
            .WithHttpRemoteStore<Tenant>(configuration["TenantRemoteStore:Url"])
            .WithPerTenantAuthentication()
            .WithPerTenantOptions<JwtBearerOptions>((o, tenantInfo) =>
            {
                o.Authority = tenantInfo.JwtAuthority;
                o.TokenValidationParameters = new TokenValidationParameters
                {
                    ValidateAudience = false
                };

                if(!isProduction) o.RequireHttpsMetadata = false;
            });

I keep getting the following error with the remote store. 

```
[14:16:07 ERR] Exception in TryGetByIdentifierAsync
System.ArgumentNullException: Value cannot be null. (Parameter 'configuration')
   at StackExchange.Redis.ConfigurationOptions.DoParse(String configuration, Boolean ignoreUnknown) in /_/src/StackExchange.Redis/ConfigurationOptions.cs:line 646
   at StackExchange.Redis.ConfigurationOptions.Parse(String configuration) in /_/src/StackExchange.Redis/ConfigurationOptions.cs:line 421
   at StackExchange.Redis.ConnectionMultiplexer.ConnectAsync(String configuration, TextWriter log) in /_/src/StackExchange.Redis/ConnectionMultiplexer.cs:line 843
   at Microsoft.Extensions.Caching.StackExchangeRedis.RedisCache.ConnectAsync(CancellationToken token)
   at Microsoft.Extensions.Caching.StackExchangeRedis.RedisCache.GetAndRefreshAsync(String key, Boolean getData, CancellationToken token)
   at Microsoft.Extensions.Caching.StackExchangeRedis.RedisCache.GetAsync(String key, CancellationToken token)
   at Microsoft.Extensions.Caching.Distributed.DistributedCacheExtensions.GetStringAsync(IDistributedCache cache, String key, CancellationToken token)
   at Finbuckle.MultiTenant.Stores.DistributedCacheStore`1.TryGetByIdentifierAsync(String identifier)
   at Finbuckle.MultiTenant.Stores.MultiTenantStoreWrapper`1.TryGetByIdentifierAsync(String identifier)
```

I have used Redis many times for response caching, and other things without issue. I have followed the example in the [documentation](https://www.finbuckle.com/MultiTenant/Docs/v6.10.0/Stores#distributed-cache-store) but I am still getting the error. Any help/guidance appreciated.

**Comment by AndrewTriesToCode** [comment]
Hello! Glad to hear from you. The error indicates that the identifier string is not getting passed to the IMultiTenantStore and instead is null. Most likely the strategy on the server is t getting the tenant if correctly. It logs to debug, I recommend turning that on and see what the middleware says about detecting the tenant identifier.

**Comment by goforebroke** [comment]
Hi Andrew! 

Thank you for responding so quickly. I looked at my code and checked that the header was set correctly and it is.

My HttpClient sets the header in a message handler

  ```
          var httpClientSettings = new HttpClientSettings();
            configuration.GetSection("HttpClient").Bind(httpClientSettings);

            services.AddTransient<AuthenticationDelegatingHandler>();
            services.AddTransient<LoggingDelegatingHandler>();

            services.AddHttpClient(API.HttpClientKeys.StripeDotNetClient, client =>
            {
                client.BaseAddress = new Uri(httpClientSettings.APIGatewayUrl); // API GATEWAY URL
                client.DefaultRequestHeaders.Clear();
                client.DefaultRequestHeaders.Add(HeaderNames.Accept, "application/json");
            })
           .AddHttpMessageHandler<AuthenticationDelegatingHandler>()
           .AddHttpMessageHandler<LoggingDelegatingHandler>(); 

            services.AddHttpContextAccessor();

            services.Configure<StripeCheckoutSettings>(options => 
            configuration.GetSection("StripeCheckout").Bind(options));

            return services;
```

Here is a snippet from the AuthenticatingDelegationHandler message handler

```
   protected override async Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, 
            CancellationToken cancellationToken)
        {
            if(_httpContextAccessor.HttpContext != null)
            {
               string? accessToken = await _httpContextAccessor
                    .HttpContext.GetTokenAsync(OpenIdConnectParameterNames.AccessToken);

                if (!string.IsNullOrWhiteSpace(accessToken))
                {
                    //_logger.LogInformation($"Token: {accessToken}");
                    request.SetBearerToken(accessToken);
                }
            }
            
            request.Headers.Add("__tenant__", _defaultTenant.Name);

            return await base.SendAsync(request, cancellationToken);
        }
```

I turned on debug in SeriLog in Ocelot Gateway, and TenantStore API

```
 "Serilog": {
    "MinimumLevel": {
      "Default": "Debug",
      "Override": {
        "Microsoft": "Information",
        "System": "Warning"
      }
    }
  }
```
And there is where I realized my errors. I had two issues

TenantRemoteStore url need to be updated from 

```
  "HttpRemoteStore": {
    "Url": "http://tenantstoreapi/api/v1/TenantStore/Identifier/__tenant__"
  },

```
to

```
  "TenantRemoteStore": {
    "Url": "http://tenantstoreapi/api/v1/TenantStore/Identifier/{__tenant__}"
  },
```

and I had not setup my values for Redis (Host & InstanceName) in appsettings.Development.json in tenantstore.api, which is why the configuration was null.. I had them setup in appsetting.Local.json for local debugging, but not in my dev profile which is used by docker.

Thank you for sending my the right direction.

Jaime

**Comment by AndrewTriesToCode** [comment]
Excellent. Let me know if there are any takeaways or suggestions for improvement.
