### ISSUE TITLE
API Sample

### ISSUE THREAD

**Issue by ctietgen** [Finbuckle/Finbuckle.MultiTenant#65]
Will there be a sample of implementing a MultiTenant API?

Specifically an example of a MultiTenant scenario where there's a tenant database for tenant lookup and a database per tenant?

**Comment by AndrewTriesToCode** [comment]
Hi @CMTietgen 

I'm working on more samples-- I hadn't thought of an API sample, but that is a good idea. Also I'm working on specific functionality for a database multitenant store (#26) so there will definitely will have a sample for that, hopefully soon.

**Comment by AndrewTriesToCode** [comment]
@CMTietgen Hi just wanted to let you know that I added a new sample project to the Dev branch -- it shows how to implement `IMultiTenantStore` to look up the tenant from a SQLite database. It could easily be adapted for any other database.

I still plan to include a formal store that integrates with EFCore in the future.

**Comment by ctietgen** [comment]
Awesome, thanks. Can't wait for the EFCore sample.
