### ISSUE TITLE
Integration with Serenity (using Dapper with Sqlconnections)

### ISSUE THREAD

**Issue by reach2rv** [Finbuckle/Finbuckle.MultiTenant#663]
Hi @AndrewTriesToCode ,

I am trying to integrate Finbuckle multitenant with [Serenity](https://github.com/serenity-is/Serenity), 

I have created instance of ISqlconncection to change default connectionstring with tenant conectionString. I am facing issues with tenant resolution as httpcontext in null in the following method. 

Can you please guide how it can be done

**Comment by AndrewTriesToCode** [comment]
Hi, sorry I didn't respond sooner. Did you figure it out?
