### ISSUE TITLE
MultiTenantContext is Null

### ISSUE THREAD

**Issue by reach2rv** [Finbuckle/Finbuckle.MultiTenant#665]
Hi @AndrewTriesToCode ,

Thank you for this wonderful library and work you have done!

I am trying to integrate this with [serenity](https://github.com/serenity-is/Serenity)

following is my class where I would like to override connectionstring as per tenant

```C#
public class TenantSqlConnections : ISqlConnections
    {
        private IMultiTenantContext<Tenant> _tenantContext;
        private IMultiTenantContextAccessor<Tenant> _tenantContextAccessor;
        private readonly IServiceProvider _serviceProvider;
        private IHttpContextAccessor _httpContextAccessor;
        /// <summary>Connection strings</summary>
        protected readonly IConnectionStrings connectionStrings;
        /// <summary>Profiler</summary>
        protected readonly IConnectionProfiler profiler;
        /// <summary>Logger factory</summary>
        protected readonly ILoggerFactory loggerFactory;


        public TenantSqlConnections(IServiceProvider serviceProvider,
            IHttpContextAccessor httpContextAccessor,
            IMultiTenantContextAccessor<Tenant> tenantContextAccessor,
            IConnectionStrings connectionStrings,
            IConnectionProfiler profiler = null,
            ILoggerFactory loggerFactory = null)
        {
            _serviceProvider = serviceProvider;
            _httpContextAccessor = httpContextAccessor;
            _tenantContextAccessor = tenantContextAccessor;
            this.connectionStrings = connectionStrings ?? throw new ArgumentNullException(nameof(connectionStrings));
            this.profiler = profiler;
            this.loggerFactory = loggerFactory;

        }

        public IEnumerable<IConnectionString> ListConnectionStrings()
        {
            return connectionStrings.ListConnectionStrings();
        }

        protected virtual IDbConnection CreateConnection(string connectionString, string providerName, ISqlDialect dialect)
        {
            if (providerName == null)
                throw new ArgumentNullException(nameof(providerName));

            if (connectionString == null)
                throw new ArgumentNullException(nameof(connectionString));

            var factory = DbProviderFactories.GetFactory(providerName);
            var connection = factory.CreateConnection();
            try
            {
                connection.ConnectionString = connectionString;
            }
            catch
            {
                connection.Dispose();
                return null;
            }

            return connection;
        }

        protected virtual IDbConnection WrapConnection(IDbConnection connection, string providerName, ISqlDialect dialect)
        {
            if (profiler != null)
                return new WrappedConnection(profiler.Profile(connection), dialect, loggerFactory?.CreateLogger<ISqlConnections>());

            return new WrappedConnection(connection, dialect, loggerFactory?.CreateLogger<ISqlConnections>());

        }

        public virtual IDbConnection New(string connectionString, string providerName, ISqlDialect dialect)
        {
            Tenant tenant = null;

            if (_httpContextAccessor.HttpContext != null)
            {
                _tenantContext = _httpContextAccessor.HttpContext.GetMultiTenantContext<Tenant>();

                if (_tenantContext == null)
                    _tenantContext = _serviceProvider.GetRequiredService<IMultiTenantContextAccessor<Tenant>>().MultiTenantContext;


                tenant = _tenantContext == null ? null : _tenantContext.TenantInfo;
            }

            if (tenant != null)
                connectionString = $"Server={tenant.DatabaseServer};Port=5432;Database={tenant.DatabaseName};User Id={tenant.Username};Password={tenant.Password};CommandTimeout=20;Timeout=15;";

            var connection = CreateConnection(connectionString, providerName, dialect);
            return WrapConnection(connection, providerName, dialect);
        }

        public virtual IDbConnection NewByKey(string connectionKey)
        {
            var info = connectionStrings.TryGetConnectionString(connectionKey);

            if (info == null)
                throw new InvalidOperationException(string.Format("No connection string with key {0} in configuration file!", connectionKey));

            return New(info.ConnectionString, info.ProviderName, info.Dialect);
        }

        public virtual IConnectionString TryGetConnectionString(string connectionKey)
        {
            return connectionStrings.TryGetConnectionString(connectionKey);
        }

    }

```

on first run everything works fine. but as soon as we refresh page mutiltenatcontex is null in New function, and it returns default connection string. 

As you can see I have tried  with 
` _tenantContext = _serviceProvider.GetRequiredService<IMultiTenantContextAccessor<Tenant>>().MultiTenantContext;`

value is still null. can you please help me resolve this to complete the integration.

I am changing implementation of ISQLconnection with
`services.AddSingleton<ISqlConnections, Common.TenantSqlConnections>(); ` in configure services.

Thank you!

**Comment by AndrewTriesToCode** [comment]
Hi I have a few questiosn:
- can you tell me on which line exactly you see the null tenant?
- how is this class registered in DI? Singleton, scoped, transient?
- In the cases where `New` is called is it always part of an Http request or could it be during app startup or in some background task?

**Comment by reach2rv** [comment]
@AndrewTriesToCode 

Following block I get null value for Multitentcontext 

```C#

if (_httpContextAccessor.HttpContext != null)
            {
                _tenantContext = _httpContextAccessor.HttpContext.GetMultiTenantContext<Tenant>();

                if (_tenantContext == null)
                    _tenantContext = _serviceProvider.GetRequiredService<IMultiTenantContextA ccessor<Tenant>>().MultiTenantContext;


```

This class is registered as singleton as rest dependent services required this class to be singleton.


New is called mostly during httprequest but It is also called during startup and sometimes by internal service.

Though multitenantcontext is null in above class if I try to call that in other IServiceCollection block to setup cookie i get tenant value. 

I get multitenant context as null in above block of class if I refresh page, but in IServiceCollection I get tenant value

**Comment by reach2rv** [comment]
@AndrewTriesToCode 

When I try to test it by creating host strategy based scenario on my development machine, if I try to test with 3 tabs of browser running 3 different host.

1. Tab get correct connection string
2. Tab gets correct connection string
3. As multitenent context return null it loads 2nd tab connection string.

If I refresh first tab again it loads with 2nd connection string as multitenent context is null.

**Comment by reach2rv** [comment]
@AndrewTriesToCode 

`New` is also called during tenant resolution to query database, I have handled that using 
`if(tenant==null) default connection string`

For the code I have shared I have using predefined tenant in store for testing.

**Comment by AndrewTriesToCode** [comment]
Hm, I don't see anything obvious. If you set the logging in appSettings.json to Debug you will see some more details from Finbuckle on why it is or isn't resolving the tenant.

Also HttpContext.GetMultiTenantContext internally called `IMultiTenantContextAccessor` so you don't really need to do that yourself in this case.

Also just to rule out anything with the resolving, I recommend setting the strategy to static and hardcode it to a specific tenant identifier. Do you still get nulls in that case?

**Comment by reach2rv** [comment]
@AndrewTriesToCode - I guess I am able to resolve it. My initial test in both development and production environment looks promising. 

Thank you for your support
