### ISSUE TITLE
DecorateService 

### ISSUE THREAD

**Issue by devalot76** [Finbuckle/Finbuckle.MultiTenant#668]
Hi,
this line of code does not compiler anymore after updating to the latest version 6.11.0:

`services.DecorateService<LinkGenerator, AmbientValueLinkGenerator>(new List<string> { "__tenant__" });`

Looking at your source, I can see that the extesion method `DecorateService` is now `internal `instead of `public`.

**Comment by AndrewTriesToCode** [comment]
Ah, good catch. I need to update my example projects so I catch things like this from outside dependents. I'll submit a patch release.
