### ISSUE TITLE
EFCore Store Sample missing?

### ISSUE THREAD

**Issue by HenrikHoyer** [Finbuckle/Finbuckle.MultiTenant#731]
The docs on the [website ](https://www.finbuckle.com/MultiTenant/Docs/v6.12.0/Stores#efcore-store) mentions this sample, but the [link ](https://github.com/Finbuckle/Finbuckle.MultiTenant/tree/master/samples/ASP.NET%20Core%203/EFCoreStoreSample) is broken, and I cannot find the sample anywhere (looks like is was removed?)

**Comment by AndrewTriesToCode** [comment]
Hi, I need to update the docs. The samples are in an older branch:

https://github.com/Finbuckle/Finbuckle.MultiTenant/tree/v6.3.1/samples/ASP.NET%20Core%203/EFCoreStoreSample

**Comment by AndrewTriesToCode** [comment]
And thank you for the sponsorship!

**Comment by HenrikHoyer** [comment]
Thanks!
