### ISSUE TITLE
Using ASP.Net Core, the sample didn't work, with SigninManager

### ISSUE THREAD

**Issue by AndreSteenbergen** [Finbuckle/Finbuckle.MultiTenant#75]
I am using the IdentityCore like following:
```
services.AddIdentityCore<ApplicationUser>()
                .AddUserStore()
                .AddSignInManager()
                .AddDefaultTokenProviders();
```

When I use the following code with it:
```
           services
                .AddAuthentication(CookieAuthenticationDefaults.AuthenticationScheme)
                .AddCookie(CookieAuthenticationDefaults.AuthenticationScheme);

            services.AddSingleton<IMultiTenantStore>((serviceProvider) =>
            {
                var cfg = serviceProvider.GetService<List<TenantConfiguration>>();
                return new TenantResolver(cfg.ToArray());
            });
            services.AddMultiTenant()
                .WithHostStrategy()
                .AddPerTenantCookieAuthentication();



public static MultiTenantBuilder AddPerTenantCookieAuthentication(this MultiTenantBuilder builder)
        {
            return builder.WithPerTenantOptions<CookieAuthenticationOptions>((options, tenantContext) =>
                {
                    // Set a unique cookie name for this tenant.         
                    options.Cookie.Name = tenantContext.Id + "-cookie";
                });
        }
```

I get the following error: InvalidOperationException: No sign-in authentication handler is registered for the scheme 'Identity.Application'. The registered sign-in schemes are: cookies. Did you forget to call AddAuthentication().AddCookies("Identity.Application",...)?
```

Microsoft.AspNetCore.Authentication.AuthenticationService.SignInAsync(HttpContext context, string scheme, ClaimsPrincipal principal, AuthenticationProperties properties)
Microsoft.AspNetCore.Identity.SignInManager<TUser>.SignInAsync(TUser user, AuthenticationProperties authenticationProperties, string authenticationMethod)
Profile.Controllers.AccountController.Registreer(RegisterViewModel model, string returnUrl) in AccountController.cs

                        await signInManager.SignInAsync(user, isPersistent: false);
```

If I change the scheme to this:
```
services
                .AddAuthentication("Identity.Application")
                .AddCookie("Identity.Application");
```
I can log in. Am I configuring something wrong? I would rather not hard code this value, to this one value I can't change.

**Comment by AndreSteenbergen** [comment]
Ok, it is is SignInManager (https://github.com/aspnet/Identity/blob/c7276ce2f76312ddd7fccad6e399da96b9f6fae1/src/Identity/SignInManager.cs#L194)

So basically if you want to use the SigninManager you will need to use scheme: 
```
services
                .AddAuthentication(IdentityConstants.ApplicationScheme)
                .AddCookie(IdentityConstants.ApplicationScheme);
```

**Comment by AndrewTriesToCode** [comment]
Hi @AndreSteenbergen 
Thanks for raising the issue. I'm glad you figured it out.

Looking back at my Identity sample I realized that I used [AddDefaultIdentity](https://github.com/aspnet/Identity/blob/c7276ce2f76312ddd7fccad6e399da96b9f6fae1/src/UI/IdentityServiceCollectionUIExtensions.cs) which internally sets the cookies for you with those constants so I hadn't run across this issue myself.

**Comment by AndreSteenbergen** [comment]
BTW I created some extension methods you might like. I'll attach some files. With these extensions it's a bit cleaner to get multitent authentication
```
services.AddMultiTenant()
                .WithStrategy<TenantStrategy>()
                .AddPerTenantCookieAuthentication()
                .AddPerTenantSocialLogins();
```

[LoginFiles.zip](https://github.com/Finbuckle/Finbuckle.MultiTenant/files/2464897/LoginFiles.zip)

**Comment by AndrewTriesToCode** [comment]
Hi @AndreSteenbergen, thanks for submitting these. Do you have them in a public github repo I can see? I did check the zip file--I saw you called a function called `AddSocialLoginTenantOptions` but I couldn't see where it was defined.

**Comment by AndreSteenbergen** [comment]
Sorry, yes here it is, the Project is in the Profile folder. https://github.com/AndreSteenbergen/Aspnet.Identity.Akka The Sociallogins providers now also get the ProfileImage url (google and fb at least)
