### ISSUE TITLE
Identity Sample App breaks 2FA

### ISSUE THREAD

**Issue by ChrisComply** [Finbuckle/Finbuckle.MultiTenant#759]
The sample https://github.com/Finbuckle/Finbuckle.MultiTenant/tree/main/samples/net6.0/IdentitySample uses IdentityUser and  to setup MFA,  like normal (https://localhost:7208/megacorp/Identity/Account/Manage/TwoFactorAuthentication).

However any logins after that don't prompt for the MFA code.

If you take a brandnew project with identity,  and scaffold out Login,  I found that Areas\Identity\Pages\Account\Login.cshtml.cs line 114 will return result.RequiresTwFactor True when MFA is setup,  but the sample Finbukle project always returns false.

**Comment by ChrisComply** [comment]
This was my issue using CheckPasswordSignInAsync thinking it returned the same two factor check as the other sign in methods.  It doesn't,  nothing wrong with Finbuckle...

**Comment by AndrewTriesToCode** [comment]
@ChrisComply no worries I appreciate your interest.
