### ISSUE TITLE
Using in a Worker Service

### ISSUE THREAD

**Issue by terencevs** [Finbuckle/Finbuckle.MultiTenant#761]
Thank you for a great package!

Is there any examples of how to setup to use the default TenantInfo implementation in a worker service? Using EntityFramework.

Program.CS
![image](https://github.com/Finbuckle/Finbuckle.MultiTenant/assets/1543193/c98fe189-d30d-4823-a235-521c040cb9b0)

I am using Quartz for job schduling:

![image](https://github.com/Finbuckle/Finbuckle.MultiTenant/assets/1543193/58dfcb4b-3799-404a-b8d8-51bc879fae65)

Tenant Details is null when we get into the job, am I missing something simple?

**Comment by AndrewTriesToCode** [comment]
Hi, sorry for the slow reply. Use DI to get an instance of `TenantResolver` which has a `"ResolveAasync` method which takes some sort of context (the middleware uses this and passes `HttpContext` for the context).

You can pass any contact and your strategy will see it and interpret as you need to. Most built in strategies are for the web but you can define your own or use delegate strategy which just takes the context as an `Object` a you can cast it as needed. Hope this help. I need to do a write up on this scenario.

**Comment by terencevs** [comment]
Hi @AndrewTriesToCode thank you for your feedback, It would be great if we could have an article on this as to see how you would recommend best practice in implementing this. Much appreciated!

**Comment by terencevs** [comment]
Just to expand on this a little, I have set it up and able to use var tenant = await tenantResolver.ResolveAsync(context); to get the tenant in my job.

The issue I am facing is that I am using DI to inject the DB context. TenantInfo is null on the context.
