### ISSUE TITLE
Problems with .NET 8 - Blazor Web App

### ISSUE THREAD

**Issue by eptgrant** [Finbuckle/Finbuckle.MultiTenant#771]
Hi there,

I'm having trouble integrating Finbuckle with my project, so I created a brand new Blazor project using the new template with these settings:

![image](https://github.com/Finbuckle/Finbuckle.MultiTenant/assets/2383857/46671d8e-4d6e-4475-b9c8-183ee2556e20)

Which includes provisioning for User registration / login etc.

After implementing the bare minimum for Finbuckle following the instructions at https://www.finbuckle.com/MultiTenant/Docs/v6.12.0/Identity#introduction, the result is the user registration works (including setting the tenantId against the user in the DB), however the "login" only half works.

There are no errors thrown, however the user isn't actually logged in. (Unable to access private pages etc)

I can see a cookie does get created.

Any help would be greatly appreciated,

Thanks

**Comment by AndrewTriesToCode** [comment]
HI! Sorry for the late reply!

Did you have any success resolving this? I’m not a Blazor expert and most of the guidance is for MVC style projects but should in theory work.

**Comment by eptgrant** [comment]
Hi, thats no problem.

No unfortunately I was unable to move past this.

Cheers

**Comment by eptgrant** [comment]
Resolved, my bad.

Didn't have:

            app.UseAuthentication();
            app.UseAuthorization();

Once added, works a treat, thanks!

**Comment by eptgrant** [comment]
Closed
