### ISSUE TITLE
Set tenant info inside hangfire job

### ISSUE THREAD

**Issue by jan-sramek** [Finbuckle/Finbuckle.MultiTenant#772]
Hi,
I'm using hangfire for some recuring background tasks. Inside of this task I need to implement logic for a specific tenant.

Problem is that hangfire has not HttpContext. I read here that it should be possible use IMultiTenantContextAccessor by injecting into the task.

Is it possible set tenant manually by something like "TrySetTenantInfo".
Problem is also that when injectiong "IMultiTenantContextAccessor" the "MultiTenantContext" is null.

Best regards
Jan

**Comment by jan-sramek** [comment]
I found this to be done:

```
 _scope.ServiceProvider.GetRequiredService<IMultiTenantContextAccessor>()
                    .MultiTenantContext = new MultiTenantContext<Multitenancy.Tenant>
                    {
                        TenantInfo = tenantInfo
                    };
```

**Comment by AndrewTriesToCode** [comment]
Hi! Sorry for my slow response— you figured it out without my help though. Your solution looks good and is what I would recommend.
