### ISSUE TITLE
 Request for Patch Release to Support .NET 8 LTS

### ISSUE THREAD

**Issue by aixasz** [Finbuckle/Finbuckle.MultiTenant#775]
Is there any plan to release a patch version? Due to some my project is in-process of upgrading to .NET 8 LTS, due to the this current version 6.12.0 still reference the preview version of dotnet dependency. 

I found this #770  already fixed this problem but not release into a patch version yet. 

It would be greatly appreciated if you could release a new version of your package that includes the fix for .NET 8 LTS #770.

Thank you for your work on this project and for considering this request.

Best regards

**Comment by AndrewTriesToCode** [comment]
Good timing -- just put out the release. Thanks!
