### ISSUE TITLE
Hierarchical Multitenancy

### ISSUE THREAD

**Issue by JonasDev17** [Finbuckle/Finbuckle.MultiTenant#780]
Hi @AndrewTriesToCode 

I have a requirement to add hierarchical multitenancy and I've been trying to do so but I can't figure out a good way.
Do you have any suggestions for how I should go about it?

I've seen two different answers from you regarding this:

`There is currently no built in support. You can implement your own IMultiTenantStore that has this functionality if you need it.`

and 

```
Hi, there is no support for this built in, but it should be possible. If you look at the MultiTenantDbContext code you should see where the logic for applying the tenant filter is -- you could easily modify that to also include a tenant's "servicer" tenant if that tenant was added as a property on the tenant.
```

What I tried so far:

I have copied the EntityTypeBuilderExtensions.IsMulitTenant  and updated the query filter in there which worked quite well and I got the entities of the current tenant and all its subtenants using a new property called TenantPath and the function StartsWith. Now the problem is I don't always want all of them. I only want them if a certain header is present. So I have written a scoped service that holds the subtenant id and a middleware that sets the subtenant id if the header is present. And this is where I got stuck. I couldn't figure out how to now access the value from the EntityTypeBuilderExtensions.IsMulitTenant Global Query Filter.

Any suggestions would be highly appreciated!

**Comment by AndrewTriesToCode** [comment]
hi @JonasDev17 
Your approach sounds good so far. Would it work to create a factory method that creates a new instance of your db context and if you choose to you can simply supply if with the subtenant as the tenant id for that instance so that dbcontext only know about the subtenant? Simply dispose of it when done or use `using`?

**Comment by JonasDev17** [comment]
I managed to make it work. What I did was inject the service through DI and create fields in the DbContext to access it. However, your method seems better, so I might consider that approach. I appreciate your help!
