### ISSUE TITLE
adjustindex api surface interaction with model class inheritance

### ISSUE THREAD

**Issue by vigouredelaruse** [Finbuckle/Finbuckle.MultiTenant#788]
howdy- i am unable to use the adjustindex apis when the model features inheritance
* when configuring table per concrete type in supported framework versions
* when permitting conventions

tested model scenario
`    public class RssBlog : Blog
    {
        public string RssUrl { get; set; }
    }`

`            IMutableIndex? origIndex = null;

            using var db = GetDbContext(builder =>
            {
                builder.Entity<Blog>()
                    .HasIndex(e => e.BlogId, "CustomIndexName")
                    .HasDatabaseName("CustomIndexDbName");

                origIndex = builder.Entity<Blog>().Metadata.GetIndexes().First();
                builder.Entity<Blog>().IsMultiTenant().AdjustIndex(origIndex);

                builder.Entity<RssBlog>()
                .HasIndex(e => e.BlogId, "RssCustomIndexName")
                .HasDatabaseName("RssCustomIndexDbName");

                var rssIndex = builder.Entity<RssBlog>().Metadata.GetIndexes().First();
                builder.Entity<RssBlog>().IsMultiTenant().AdjustIndex(rssIndex);
            });
            var index = db.Model.FindEntityType(typeof(Blog))?.GetIndexes().First();
            Assert.Equal("CustomIndexName", index!.Name);
            Assert.Equal("CustomIndexDbName", index.GetDatabaseName());`

i've tested this with the finbuckle unit tests as per this [commit ](https://github.com/Finbuckle/Finbuckle.MultiTenant/compare/main...vigouredelaruse:Finbuckle.MultiTenant:main)

perhaps i have misconfigured the indexes?
![image](https://github.com/Finbuckle/Finbuckle.MultiTenant/assets/31052867/29a603b1-4a07-4e9c-b84c-e41d40720ab8)

please advise

**Comment by AndrewTriesToCode** [comment]
Hi, I recommend that if you have explicit control of your entities that you set the index the normal way and include your tenant column. The helper methods are limited and intended to help when you inherit a model that you can’t directly alter. 

Edit: fixed typos

**Comment by vigouredelaruse** [comment]
thanks - i will explicitly configure the indexes to include tenantid column
