### ISSUE TITLE
Amateur question related to migration

### ISSUE THREAD

**Issue by joaquinniicolas** [Finbuckle/Finbuckle.MultiTenant#796]
Hi I'm new here. I love the bookstore, but I have a question. In NET 7 How can I create the database without running dotnet ef Database Update? Is there any equivalent to MigrateAsync() ?

**Comment by AndrewTriesToCode** [comment]
Hi, there is a way to do it with code. As described here:
https://learn.microsoft.com/en-us/ef/core/managing-schemas/migrations/applying?tabs=dotnet-core-cli#apply-migrations-at-runtime

However, you can do it from the command line with Finbuckle but you have to use a design time factory as discussed here:
https://www.finbuckle.com/MultiTenant/Docs/v6.13.1/EFCore#design-time-instantiation

**Comment by joaquinniicolas** [comment]
Thank you very much for your quick response. Those articles were very helpful.
