### ISSUE TITLE
Can't add migration after updating to dotnet 8

### ISSUE THREAD

**Issue by anasseb** [Finbuckle/Finbuckle.MultiTenant#799]
Hello,

I updated my API from dotnet 6 to dotnet 8, I updated also the Finbuckle references to the latest version.
I have no error when building or using the API, but when I want to create a new migration I have this error : 

Unable to create a 'DbContext' of type 'ApplicationDbContext'. The exception 'Unable to resolve service for type 'Finbuckle.MultiTenant.ITenantInfo' while attempting to activate 'WebApi.Infrastructure.Persistence.Context.ApplicationDbContext'.' was thrown while attempting to create an instance.

Before updating to dotnet 8 everything was fine.

I searched on the net but can't find any help.

**Comment by AndrewTriesToCode** [comment]
Hi, can you take a look at my response on #796 and try the design time solution mentioned there?

**Comment by anasseb** [comment]
Well, I was wrong the error has no link with Finbuckle but I don't know why the compiler say that.
Thanks.
