### ISSUE TITLE
Mocking StoreInfo?

### ISSUE THREAD

**Issue by charlieH1** [Finbuckle/Finbuckle.MultiTenant#800]
Hi Guys

Writing some unit tests for some stuff and I need to fake the store (I'm using nSubstitute and no we cant use Moq after the recent shenanigans over there) I was wondering if theres a way I can get the storeInfo but as a interface currently IMutlTenantContext provides it as a class so I cant mock it. I'm going down the route currently of injecting IMultiTenantContextAccessor using the DI and then navigating through MultiTenantContext to StoreInfo. Is thre a different and or better way which will allow me to mock or am scuppered and stuck with what I have. Below is a code snippet of what I'm trying to do and its the line that returnsnull that NSubstitute is unable to act on.

```
var mockGeneralHelper = Substitute.For<IGeneralHelper>();
var mockContextAccessor = Substitute.For<IMultiTenantContextAccessor<BasicTenantInfo>>();
var mockTenantContext = Substitute.For<IMultiTenantContext<BasicTenantInfo>>();
var mockStoreInfo = Substitute.For<StoreInfo<BasicTenantInfo>>();
var mockLogger = Substitute.For<MockLogger<TenantManagementController>>();
mockTenantContext.HasResolvedTenant.Returns(true);
mockStoreInfo.Store.ReturnsNull();
mockTenantContext.StoreInfo.Returns(mockStoreInfo);
mockContextAccessor.MultiTenantContext.Returns(mockTenantContext);
var sut = new TenantManagementController(mockContextAccessor, mockGeneralHelper, mockLogger);
```

**Comment by charlieH1** [comment]
Think I may have resolved this myself IMulitTenantStore (which is the layer below storeinfo) is [injected by the finbuckle DI](https://github.com/Finbuckle/Finbuckle.MultiTenant/blob/a916a2617d8a8cfc55cd5cf9917dec654961d558/src/Finbuckle.MultiTenant/DependencyInjection/MultiTenantBuilder.cs#L78) so I can pull it that way instead of trying to access it through the context accessor.
Do say though if you think there is a better solution otherwise I'll close

**Comment by charlieH1** [comment]
I did some further digging and think I might have the solution myself but please correct me if wrong or there is a better one

I can fetch the store (which is the endgame of the code anyway) by using the DI which is done by the following steps when using an Ef store:
1. [the withEfCoreStore calls here](https://github.com/Finbuckle/Finbuckle.MultiTenant/blob/a916a2617d8a8cfc55cd5cf9917dec654961d558/src/Finbuckle.MultiTenant.EntityFrameworkCore/Extensions/FinbuckleMultiTenantBuilderExtensions.cs#L20)
2. [which calls here](https://github.com/Finbuckle/Finbuckle.MultiTenant/blob/a916a2617d8a8cfc55cd5cf9917dec654961d558/src/Finbuckle.MultiTenant/DependencyInjection/MultiTenantBuilder.cs#L76) and adds it to the DI

so now in my code I will call something like:

```
 public TenantManagementController(IMultiTenantContextAccessor<BasicTenantInfo> multiTenantContextAccessor, IMultiTenantStore<BasicTenantInfo> tenantStore,IGeneralHelper generalHelper, ILogger<TenantManagementController> logger) {
     _generalHelper = generalHelper;
     _contextAccessor = multiTenantContextAccessor;
     _tenantStore = tenantStore;
     _logger = logger;
 }
```

**Comment by AndrewTriesToCode** [comment]
Looks like a solid approach to me. Cheers.
