### ISSUE TITLE
MultiTenantIdentityDbContext with EFCoreStore

### ISSUE THREAD

**Issue by Hameds** [Finbuckle/Finbuckle.MultiTenant#81]
Hi

I found this project when I was searching about multi-tenancy and it seems that `2.0.0` supports `EFCoreStore` but how can I use `EFCoreStore` with `MultiTenantIdentityDbContext`? even [sampe code](https://github.com/Finbuckle/Finbuckle.MultiTenant/tree/master/samples/IdentityDataIsolationSample) uses `InMemoryStore`

**Comment by clinically-au** [comment]
I find that you need two separate databases and DB contexts - one to store the tenant information, and the other for the actual data (including Identity). 

So, starting with the IdentityDataIsolationSample, you basically need to add the bits from the EFCoreStore sample.

            services.AddDbContext<TenantDbContext>(options => 
                options.UseSqlServer(Configuration.GetConnectionString("TenantDbConnection")));

            services.AddDbContext<DataDbContext>();

            services.AddIdentity<MultiTenantIdentityUser, MultiTenantIdentityRole>()
                .AddEntityFrameworkStores<DataDbContext>();

            services.AddMultiTenant()
                .WithHostStrategy()
                .WithEFCoreStore<TenantDbContext, AppTenantInfo>();

- AppTenantInfo implements IEFCoreStoreTenantInfo
- TenantDbContext inherits EFCoreStoreDbContext<AppTenantInfo>
- DataDbContext inherits MultiTenantIdentityDbContext

**Comment by AndrewTriesToCode** [comment]
Hi @Hameds, sorry for the late reply. @wojtj has the right idea (thanks for your reply!). Typically your multitenant store will be a separate database and context than your actual application data.

In the example you linked I am trying to focus only on the Identity data being multitenant, and so I used the simpler inmemory multitenant store. If you look at the [EFCoreStore Sample](https://github.com/Finbuckle/Finbuckle.MultiTenant/tree/master/samples/EFCoreStoreSample) you can see an example where I show using the EFCoreStore multitenant store (Note: this example does not use Identity at all).

It would be possible to share a single database and context for both the multitenant store and the app data by making sure the single database context **both** inherited from `MultiTenantIdentityDbContext` **and** had an entity implementing `IEFCoreStoreTenantInfo`. In my use cases this is extra complexity I try to avoid.

**Comment by Hameds** [comment]
Hi @wojtj and @achandlerwhite 
Thanks for the reply. I will check that

**Comment by ericsports** [comment]
@achandlerwhite Regarding your response and having it be in a single database, how would you go about setting up the services.AddMultiTenant part in the startup file? When attempting to add 'WithEFCoreStore' and adding the DbContext, I'm getting an error that there is no reference conversion.

Any help is much appreciated!
