### ISSUE TITLE
Identity Sample app, from Samples is not working

### ISSUE THREAD

**Issue by bojanivancev** [Finbuckle/Finbuckle.MultiTenant#812]
System.AggregateException: 'Some services are not able to be constructed (Error while validating the service descriptor 'ServiceType: IdentitySample.Data.ApplicationDbContext Lifetime: Scoped ImplementationType: IdentitySample.Data.ApplicationDbContext': No constructor for type 'IdentitySample.Data.ApplicationDbContext' can be instantiated using services from the service container and default values.) (Error while validating the service descriptor 'ServiceType: Microsoft.AspNetCore.Identity.IUserClaimsPrincipalFactory`1[Microsoft.AspNetCore.Identity.IdentityUser] Lifetime: Scoped ImplementationType: Microsoft.AspNetCore.Identity.UserClaimsPrincipalFactory`1[Microsoft.AspNetCore.Identity.IdentityUser]': No constructor for type 'IdentitySample.Data.ApplicationDbContext' can be instantiated using services from the service container and default values.) (Error while validating the service descriptor 'ServiceType: Microsoft.AspNetCore.Identity.UserManager`1[Microsoft.AspNetCore.Identity.IdentityUser] Lifetime: Scoped ImplementationType: Microsoft.AspNetCore.Identity.UserManager`1[Microsoft.AspNetCore.Identity.IdentityUser]': No constructor for type 'IdentitySample.Data.ApplicationDbContext' can be instantiated using services from the service container and default values.) (Error while validating the service descriptor 'ServiceType: Microsoft.AspNetCore.Identity.ISecurityStampValidator Lifetime: Scoped ImplementationType: Microsoft.AspNetCore.Identity.SecurityStampValidator`1[Microsoft.AspNetCore.Identity.IdentityUser]': No constructor for type 'IdentitySample.Data.ApplicationDbContext' can be instantiated using services from the service container and default values.) (Error while validating the service descriptor 'ServiceType: Microsoft.AspNetCore.Identity.ITwoFactorSecurityStampValidator Lifetime: Scoped ImplementationType: Microsoft.AspNetCore.Identity.TwoFactorSecurityStampValidator`1[Microsoft.AspNetCore.Identity.IdentityUser]': No constructor for type 'IdentitySample.Data.ApplicationDbContext' can be instantiated using services from the service container and default values.) (Error while validating the service descriptor 'ServiceType: Microsoft.AspNetCore.Identity.SignInManager`1[Microsoft.AspNetCore.Identity.IdentityUser] Lifetime: Scoped ImplementationType: Microsoft.AspNetCore.Identity.SignInManager`1[Microsoft.AspNetCore.Identity.IdentityUser]': No constructor for type 'IdentitySample.Data.ApplicationDbContext' can be instantiated using services from the service container and default values.) (Error while validating the service descriptor 'ServiceType: Microsoft.AspNetCore.Identity.IUserStore`1[Microsoft.AspNetCore.Identity.IdentityUser] Lifetime: Scoped ImplementationType: Microsoft.AspNetCore.Identity.EntityFrameworkCore.UserOnlyStore`6[Microsoft.AspNetCore.Identity.IdentityUser,IdentitySample.Data.ApplicationDbContext,System.String,Microsoft.AspNetCore.Identity.IdentityUserClaim`1[System.String],Microsoft.AspNetCore.Identity.IdentityUserLogin`1[System.String],Microsoft.AspNetCore.Identity.IdentityUserToken`1[System.String]]': No constructor for type 'IdentitySample.Data.ApplicationDbContext' can be instantiated using services from the service container and default values.)'

**Comment by AndrewTriesToCode** [comment]
Hi, this is a breaking change made in v7.0.0. You will need to add a constructor to your db context that accepts `IMultiTenantContextAccessor<TTenantInfo>` and  pass it to the base constructor.

**Comment by bojanivancev** [comment]
Thanks a lot!
