### ISSUE TITLE
The documentation still refers to the ConnectionString property

### ISSUE THREAD

**Issue by michaelhachen** [Finbuckle/Finbuckle.MultiTenant#813]
Since version 7.0.0, there is no longer a ConnectionString property in the `ITenantInfo` interface. However, the property is still mentioned in the [documentation](https://www.finbuckle.com/MultiTenant/Docs/v7.0.0/CoreConcepts#itenantinfo-and-tenantinfo) -> "These instances' type implements ITenantInfo which defines properties for Id, Identifier, Name, **_ConnectionString_**."

**Comment by AndrewTriesToCode** [comment]
Hi! Thanks for catching that. Feel free to submit a or if you’d like to be a contributor or I can correct it later today.

**Comment by AndrewTriesToCode** [comment]
Thanks!
