### ISSUE TITLE
MultiTenantDbContext now throws when saving non multitenant entities

### ISSUE THREAD

**Issue by LodewijkSioen** [Finbuckle/Finbuckle.MultiTenant#815]
In [this commit](https://github.com/Finbuckle/Finbuckle.MultiTenant/commit/70d27d79e0e7faa221bb83c6b3e42c26f2df437b#diff-c9a9e76f1c9dd849b1517fc946c8e1236e9eee65222d945f57297457a48e7f18L26-R28) the `EnforceMultiTenant` method was changed to always throw if `tenantInfo` is null. It used to be that it would only throw when the changeTracker contained multitenant entities.

Is there a reason for this change? Because now I need to split my DbContext in order to move to v7.0.

**Comment by AndrewTriesToCode** [comment]
It was done to to help with nullability static analysis but obviously that is not a good change so I will fix that this weekend.
