### ISSUE TITLE
IdentitySample Throwing Early Exception

### ISSUE THREAD

**Issue by benholtsclaw** [Finbuckle/Finbuckle.MultiTenant#824]
Trying to run the IdentitySample from the repository and getting a runtime exception. 

builder.Build() throws

`{"Error while validating the service descriptor 'ServiceType: IdentitySample.Data.ApplicationDbContext Lifetime: Scoped ImplementationType: IdentitySample.Data.ApplicationDbContext': No constructor for type 'IdentitySample.Data.ApplicationDbContext' can be instantiated using services from the service container and default values."}	System.Exception {System.InvalidOperationException}`

Is this because the ApplicationDbContext constructor is unable to resolve AppTenantInfo ?

**Comment by AndrewTriesToCode** [comment]
Thanks for letting me know. I need to add a constructor to the db context that accepts `IMultiTenantContexfAccessor` per the recent breaking change with v7. I will try to do so tonight.

**Comment by TimVerheul** [comment]
@AndrewTriesToCode I still have this issue.

**Comment by AndrewTriesToCode** [comment]
@TimVerheul is your issue specifically in the sample or are you getting the same error message from a different situation?

**Comment by TimVerheul** [comment]
> @TimVerheul is your issue specifically in the sample or are you getting the same error message from a different situation?

I already fixed this and I don't know how to reproduce it. Thank you for checking in though.
