### ISSUE TITLE
Multiple external logins cause PK error in AspNetUserLogins

### ISSUE THREAD

**Issue by matthewtamm** [Finbuckle/Finbuckle.MultiTenant#83]
Hi Andrew - great project!

I am just using to explore ideas at present, stumbled upon what I think is a minor issue (read: easy fix) with external logins .. consider 2 tenants, with one external user, a customer of both tenants

The **AspNetUserLogins** table has a primary key defined on **LoginProvider** and **ProviderKey** only - so this external user can only exist once, associated to the first tenant only

The **TenantId** column is added to **AspNetUserLogins** as expected, and the query to find an existing external login _does_ filter as expected `WHERE TenantId = ? AND LoginProvider = ? AND ProviderKey = ?`   ...so not finding the user for the 2nd tenant, then attempting the failing insert (a duplicate primary key thing)

So the fix for me was just to drop/create this PK but now as a combination of **LoginProvider**, **ProviderKey**, and **TenantId**  .. I just updated my database directly for now but will eventually add to a migration on the context

Thanks

**Comment by AndrewTriesToCode** [comment]
Hi @matthewtamm  good catch. I had to do a similar thing for the user and role entities in `OnModelCreating` [here](https://github.com/Finbuckle/Finbuckle.MultiTenant/blob/master/src/Finbuckle.MultiTenant.EntityFrameworkCore/MultiTenantIdentityDbContext.cs). I think I can also adjust the primary key for this entity too for the next release.
