### ISSUE TITLE
[Question] Integration/Subcutaneous testing with Finbuckle

### ISSUE THREAD

**Issue by Thijs153** [Finbuckle/Finbuckle.MultiTenant#830]
Hey @AndrewTriesToCode,

I'm trying to build Integration/subcutaneous tests for my API that uses Finbuckle for MultiTenancy.

I use the `WebApplicationFactory`, to configure some services, and a new DbContext that uses an in-memory Sqlite database, instead of my SqlServer database.

Now when running the tests I get a strange null reference exception and I see that the `TenantInfo` of my DbContext is null.
Do you have any idea how I could set this TenantInfo in my tests?

my WebAppFactory configure method:

```csharp
protected override void ConfigureWebHost(IWebHostBuilder builder)
    {
        TestDatabase = SqliteTestDatabase.CreateAndInitialize();

        builder.ConfigureTestServices(services =>
        {
            ...
            
            services
                .RemoveAll<DbContextOptions<AppDbContext>>()
                .AddDbContext<AppDbContext>((_, options) => options.UseSqlite(TestDatabase.Connection));
        });
    }
```

I'm testing my MediatR request handlers, so I'm not going through the full request pipeline. This is what my test looks like:

```csharp
[Collection(WebAppFactoryCollection.CollectionName)]
public class GetDatamodelTests
{
    private readonly WebAppFactory _factory;
    private readonly IMediator _mediator;
    
    public GetDatamodelTests(WebAppFactory webAppFactory)
    {
        _factory = webAppFactory;
        _mediator = webAppFactory.CreateMediator();
    }
    
    [Fact]
    public async Task GetDatamodel_WhenNoDatamodel_ShouldReturnNotFound()
    {
        // Arrange
        var query = DatamodelCommandFactory.GetDatamodelQuery();
        
        // Act
        var result = await _mediator.Send(query);

        // Assert
        result.IsError.Should().BeTrue();
    }
}
```

I get the null reference exception in this repository call:
_The error message is not very descriptive, it just says that there is a null reference in some closure_

```csharp
public sealed class ReadRepository<TEntity>(AppDbContext dbContext) : IReadRepository<TEntity>
    where TEntity : BaseEntity
{
    private readonly IQueryable<TEntity> _queryable = dbContext.Set<TEntity>().AsNoTracking();

    public Task<TEntity?> FindByIdAsync(Guid id, CancellationToken ct = default)
        => _queryable.FirstOrDefaultAsync(entity => entity.Id == id, ct);
}
```

Do you have any ideas/suggestions on how to implement this with Finbuckle?
Btw, could the TenantInfo being null even cause that null reference exception?

Thanks in advance :)

**Comment by Thijs153** [comment]
Already resolved it myself.

For anyone in the future, I resolved it by adding:

```charp
     services.RemoveAll<ITenantInfo>();
    services.AddScoped<ITenantInfo, TenantInfo>((_) => new TenantInfo
    {
        Id = TestConstants.User.Tenant,
        Identifier = TestConstants.User.Tenant,
    }); 
```

To the ConfigureWebHost method of the WebApplicationFactory.
(I only rely on the Tenant Identifier without any additional configuration, so this just works for me)

**Comment by AndrewTriesToCode** [comment]
Glad you got it working!
