### ISSUE TITLE
How to configure per tenant swagger implicit authentication options?

### ISSUE THREAD

**Issue by sivaji55** [Finbuckle/Finbuckle.MultiTenant#831]
Question : I am using host strategy to resolve tenants and my application uses jwt authentication using keycloak, we have swagger with implicit authentication flow, how can I configure swagger options per tenant using host strategy?

how can I add tenant specific settings during service registration with below code
Service Registrations: 

services.SwaggerDocument(s =>
{
    s.DocumentSettings = o =>
    {
        o.Title = commonConfig.ServiceName;
        o.Description = commonConfig.ServiceDesc;

        if (authConfig.Enabled)
        {
            var iamBaseUrl = new Uri(authConfig.GetIssuerUrl);
            var scheme = new OpenApiSecurityScheme
            {
                Type = OpenApiSecuritySchemeType.OAuth2,
                Flows = new OpenApiOAuthFlows()
                {
                    Implicit = new OpenApiOAuthFlow()
                    {
                        AuthorizationUrl = tenant.authorizationurl,
                        TokenUrl = tenant.tokenurl,
                        Scopes = authConfig.SwaggerScopes.ToDictionary(k => k, v => System.Globalization.CultureInfo.InvariantCulture.TextInfo.ToTitleCase(v)),
                        RefreshUrl = tenant.refreshurl,
                    }
                }
            };
            o.AddSecurity(DefaultScheme, scheme);
            o.AddAuth(DefaultScheme, scheme);
        }
    };

    s.AutoTagPathSegmentIndex = 2;
    s.EnableJWTBearerAuth = false;
});

how can I add tenant specific settings during middleware registration with below code
Middleware registration:

var tenantAccessor = application.ApplicationServices.GetRequiredService<IMultiTenantContextAccessor<BaseTenant>>();
var tenant = tenantAccessor?.MultiTenantContext?.TenantInfo;
application.UseSwaggerGen(null, s =>
{
    s.ConfigureDefaults();
    s.PersistAuthorization = false;
    s.OAuth2Client = new NSwag.AspNetCore.OAuth2ClientSettings()
    {
        ScopeSeparator = " ",
        ClientId = tenant?.ClientId,
        AppName = $"{System.Globalization.CultureInfo.InvariantCulture.TextInfo.ToTitleCase(commonConfig.ServiceName!)} Swagger UI"
    };
});

Note: I am using fastendpoints library so some of swagger options are different.

**Comment by AndrewTriesToCode** [comment]
Hi, unfortunately I haven't been able to get swagger to work with per-tenant settings because they pass options directly to the middleware "Use" method and bypass the Options pattern.

What type of swagger settings are you looking to customize?

**Comment by sivaji55** [comment]
Hi @AndrewTriesToCode I was looking to change issuer url and client id and client secret dynamically based on the tenant choosen, I was able to get it working by using below snippet

`public static IApplicationBuilder UseSwaggerUI3(this IApplicationBuilder application)
{
    var authConfig = application.ApplicationServices.GetRequiredService<IOptions<AuthConfig>>().Value;
    var commonConfig = application.ApplicationServices.GetRequiredService<IOptions<CommonConfig>>().Value;
    application.UseSwaggerGen(doc =>
    {
        application.Use(async (context, next) =>
        {
            var tenantAccessor = application.ApplicationServices.GetRequiredService<IMultiTenantContextAccessor<BaseTenant>>();
            var tenant = tenantAccessor?.MultiTenantContext?.TenantInfo;

            if (tenant != null)
            {
                doc.PostProcess = (d, req) =>
                {
                    var scheme = d.SecurityDefinitions[DefaultScheme];
                    scheme.AuthorizationUrl = tenant.AuthorizationUrl;
                    d.SecurityDefinitions[DefaultScheme] = scheme;
                };
            }
            await next();
        });
    }, s =>
    {
        s.ConfigureDefaults();
        s.PersistAuthorization = false;

        application.Use(async (context, next) =>
        {
            var tenantAccessor = application.ApplicationServices.GetRequiredService<IMultiTenantContextAccessor<BaseTenant>>();
            var tenant = tenantAccessor?.MultiTenantContext?.TenantInfo;

            if (tenant != null)
            {
                var authUrl = tenant.Authority;
                s.OAuth2Client = new NSwag.AspNetCore.OAuth2ClientSettings()
                {
                    ScopeSeparator = " ",
                    ClientId = tenant.ClientId,
                    AppName = "AppName Swagger UI"
                };
            }
            await next();
        });
    });
    return application;
}`

**Comment by AndrewTriesToCode** [comment]
Nice!
