### ISSUE TITLE
Supporting Database Type Conversion for Tenants in EF Core

### ISSUE THREAD

**Issue by wibu009** [Finbuckle/Finbuckle.MultiTenant#843]
Is it possible to enable database type conversion for different tenants in EF Core? Ideally, tenants could select their preferred database type. With EF Core, creating separate migration sets for each type seems achievable. I attempted adding a "database provider" field to tenant information and using it, but this conflicts with the CacheStore mechanism. I'm unsure how to resolve this issue. My project is using FullstackHero's Web API template and FullstackHero is using this package for multi tenant configuration

**Comment by AndrewTriesToCode** [comment]
Hi, there is no built in support for this but it might be possible. What did the code you tried look like in the `OnConfiguring` method?

edit: on second thought it would be in`OnModeling` instead of configuring…
