### ISSUE TITLE
Incorrect tenantId used after changing tenant

### ISSUE THREAD

**Issue by Leon99** [Finbuckle/Finbuckle.MultiTenant#850]
I can't figure out a way to make `UserManager` use the current tenant that was set earlier in the current request when saving data. `TenantInfo` is assigned in the constructor of `MultiTenantIdentityDbContext` and there's no setter, so the tenant that was active at the start of the request is used instead. Am I missing something? Any ideas much appreciated.

**Comment by AndrewTriesToCode** [comment]
Hi @Leon99 

Yeah there are a few options.

1. Register your identity db context as transient so it always gets recreated in DI. Not ideal.
2.  After setting a new tenant use the new scope to request the `UserManager` you need -- it will internally recreate `UserStore` and the scoped identity dbcontext with the correct tenant.

Something like:
```
_httpContextAccessor.HttpContext.TrySetTenantInfo(new Tenant(), true);
_serviceProvider = HttpContext.RequestService;
 var userManager = _serviceProvider.GetService<UserManager<AppUser>>()!;
```
Does that make sense? Give it a try and let me know.

**Comment by Leon99** [comment]
It's `SetTenantInfo()` nowadays and I was hoping for something more elegant but this works. Thanks Andrew!
