### ISSUE TITLE
Best way to ensure unique fields restricted to tenantId Only

### ISSUE THREAD

**Issue by japhethmutai** [Finbuckle/Finbuckle.MultiTenant#859]
I would like to seek a clarification on the use of AdjustUniqueIndexes. I have an entity that has a unique field, and I want to make sure that this unique field is only restricted to a given tenant, hence the unique field does not affect the other tenants. I tried defining it this way:

```
public class SettingConfig : IEntityTypeConfiguration<Setting>
{
    public void Configure(EntityTypeBuilder<Setting> builder)
    {
        builder.ToTable("Settings", SchemaNames.Settings).IsMultiTenant().AdjustUniqueIndexes();
        builder.HasIndex(s => s.Item).IsUnique();
        builder.Property(s => s.Item).IsRequired().HasMaxLength(255);
        builder.Property(m => m.Value).HasColumnType("text");
    }
}
```

However, the AdjustUniqueIndexes does not seem to have any impact since the unique field is enforced on all records regardless of it belong to different tenants. Could be I got this wrong? Any guidance on this is highly appreciated.

**Comment by japhethmutai** [comment]
Actually I resolved the issue by adding the function of AdjustUniqueIndexes at the end after configuring the field attributes, i.e.:

```
public class SettingConfig : IEntityTypeConfiguration<Setting>
{
    public void Configure(EntityTypeBuilder<Setting> builder)
    {
        builder.ToTable("Settings", SchemaNames.Settings);
        builder.Property(s => s.Item).IsRequired().HasMaxLength(255);
        builder.Property(m => m.Value).HasColumnType("text");
        builder.HasIndex(s => s.Item).IsUnique();
        builder.IsMultiTenant().AdjustUniqueIndexes();
    }
}
```

**Comment by AndrewTriesToCode** [comment]
Hello, The method simply looks at any existing unique indexes and rebuilds them with tenant id included in the set of properties for each index. That would allow you to have the other properties unique within the tenant but still allow other records to have that same value as long as the tenant is different.
