### ISSUE TITLE
ConfigurePerTenant<CookieAuthenticationOptions, TenantInfo> not working

### ISSUE THREAD

**Issue by malah-code** [Finbuckle/Finbuckle.MultiTenant#870]
When try the code below to make a difffernt cookie name per tenant , it never work, because the option name set to default which is string.empty.

from doc : https://www.finbuckle.com/MultiTenant/Docs/Authentication#other-authentication-options
code in https://github.com/Finbuckle/Finbuckle.MultiTenant/blob/3d3510e180ac9bc7f19e2ae7fec3c83dfcb3ba77/docs/Authentication.md

```c#
builder.Services.AddMultiTenant<TenantInfo>()
        .WithConfigurationStore()
        .WithRouteStrategy()
        .WithPerTenantAuthentication()

// WithPerTenantAuthentication, as shown above, is needed for this to work as intended
builder.Services.ConfigurePerTenant<CookieAuthenticationOptions, TenantInfo>((options, tenantInfo) =>
  {
    options.Cookie.Name = "SignInCookie-" + tenantInfo.Id;
  });
```

as a work around we use `ConfigureAllPerTenant` instead of `ConfigurePerTenant`. but not sure if this workaround is correct, and will that affect the concurrent requests from multiple tenants at the same time?

**Comment by AndrewTriesToCode** [comment]
Thanks @malah-code  I will take a look.

**Comment by AndrewTriesToCode** [comment]
You are right, I will update the docs. `ConfigureAllPerTenant` will not cause concurrency problems but will impact all cookie authentication schemes if you have multiple in use. For example Identity defines an external cookie scheme and an application cookie scheme.

If you want to target more closely then use ConfigurePerTenant with the names option set to your auth scheme name:

`builder.Services.ConfigurePerTenant<CookieAuthenticationOptions, TenantInfo>("auth_scheme_name", options => {...})`

Note that you can use `CookieAuthenticationDefaults.AuthenticationScheme` as the default cookie auth scheme name.

**Comment by malah-code** [comment]
Thank @AndrewTriesToCode , That was fast :) 👍
