### ISSUE TITLE
.NET 9 version expected release date

### ISSUE THREAD

**Issue by siriak** [Finbuckle/Finbuckle.MultiTenant#901]
When will .NET 9 version of this package be released? I saw in version policy that it's expected to be released at the same time as .NET 9 which is already available. In README it says that it's compatible with .NET 9, but I get an error when trying to use 9.x versions because this package requires 8.x versions of Microsoft's packages.
![image](https://github.com/user-attachments/assets/6dbda89b-219f-4217-a53b-5aad9eb8c33e)
Thank you for this library, it's awesome for multitenant applications.

**Comment by AndrewTriesToCode** [comment]
Hi, it’ll be this evening once I get home from work.

**Comment by siriak** [comment]
Awesome, thank you a lot!

**Comment by AndrewTriesToCode** [comment]
Glad you like the library. v9.0.0 is now out.
