### ISSUE TITLE
TenantInfo still with null values

### ISSUE THREAD

**Issue by aalexandre-cognivance** [Finbuckle/Finbuckle.MultiTenant#904]
Hi, 

I'm using the last version (9.0) and I don't understand why I don't get my Tenant Id.
TenantId id is in a user claims in the JWT.

Here is the Add Multitenants part in my Program.cs

`

builder.Services.AddMultiTenant<TenantInfo>()
	.WithDelegateStrategy(context =>
	{
		var httpContext = context as HttpContext;
		if (httpContext == null)
			return null;
		var tenantIdentifier = httpContext.User.Claims.FirstOrDefault(x=> x.Type == "tenantId");

		if (tenantIdentifier == null)
			return Task.FromResult<string?>(null);

		var tenantInfo = new TenantInfo
		{
			Id = tenantIdentifier.ToString()
		};
		httpContext.SetTenantInfo<TenantInfo>(tenantInfo,true);
		return Task.FromResult(tenantIdentifier.ToString());
        });
`

Why I debug it, I've got the good tenant Id.

But here, when it's called from DbContext
`
      builder.Services.AddDbContext<AppDbContext>((serviceProvider, options) =>
      {
	      var tenantInfo = serviceProvider.GetRequiredService<ITenantInfo>();
      
	      if (tenantInfo?.Id == null)
	      {
		      throw new InvalidOperationException("TenantId is not available.");
	      }
	      options.UseSqlServer(builder.Configuration.GetConnectionString("MyDatabase"));
      });
`

tenantInfo.Id is null :-(.

` 
          public class AppDbContext : DbContext
           {
		private readonly ITenantInfo _tenantInfo;

		public AppDbContext(DbContextOptions<AppDbContext> options, ITenantInfo tenantInfo) : base(options)
		{
                  _tenantInfo = tenantInfo ?? throw new ArgumentNullException(nameof(tenantInfo));
		}

                 public DbSet<WorkTask> WorkTask { get; set; }

		protected override void OnModelCreating(ModelBuilder modelBuilder)
		{
                    base.OnModelCreating(modelBuilder);
                    
                    var tenantId = _tenantInfo?.Id;
                    
                    if (!string.IsNullOrEmpty(tenantId))
                    {
	                    modelBuilder.Entity<WorkTask>().HasQueryFilter(w => w.TenantId == new Guid(tenantId));
                    }
		}
	}
`

I'm sure, I've forgotten something but what...

**Comment by AndrewTriesToCode** [comment]
Hi thanks for providing the details. I will take a closer look. Did this work in prior versions and break only in 9.0?

**Comment by aalexandre-cognivance** [comment]
It's the first time I use it, so I din't test with older version, I can try

[Edit], I've tried with 8.0, same problem

**Comment by AndrewTriesToCode** [comment]
Does your middleware setup have `UseAuthentication` before `UseMultiTenant`? If not the user claims will be empty.  

Also if you use the built in claims strategy it can handle this for you.

Similarly the EFCore support can do the tenant global query filter plus more checks if you are interested in using that part.

**Comment by aalexandre-cognivance** [comment]
UseAuthentication is before UseMultinenant.
I use "KeyCloak" for the Authent and the currently, all ASP.Net queries are authentified by this tenantId. I'm interested by the global query filter too but I've started to implement this part which is needed, right ?

**Comment by AndrewTriesToCode** [comment]
Oh ok the claims part in the strategy is working ok.

In the db context you are injecting `ITenantInfo` but this is not available via DI. Instead you’ll want to inject `IMultiTenantContextAccessor` from which you can get to the current tenant. 

The global query part will be ok. If you look at the Finbuckle docs you’ll see there is special support for EF Core that will do this for you.

**Comment by AndrewTriesToCode** [comment]
Also be aware of situations where there will not be a valid tenant. Such as during migrations or during app startup or outside of an http request or an http request where there no tenant.

**Comment by aalexandre-cognivance** [comment]
Thx for your answer @AndrewTriesToCode , I've tried to change ITenantInfo to IMultiTenantContextAccessor but there's no change.
But, even if we forget AppDbContext, I should have the tenantInfo Id in this lambda : 

```
builder.Services.AddDbContext<AppDbContext>((serviceProvider, options) =>
{
	var tenantInfo = serviceProvider.GetRequiredService<ITenantInfo>();

	if (tenantInfo?.Id == null)
	{
		throw new InvalidOperationException("TenantId is not available.");
	}
	options.UseSqlServer(builder.Configuration.GetConnectionString("MyDatabase"));
});

```
right ? But tenantInfo?.Id is still at "null" while WithDelegateStrategy return is ok... 

```
builder.Services.AddMultiTenant<TenantInfo>()
	.WithDelegateStrategy(context =>
	{
		var httpContext = context as HttpContext;
		if (httpContext == null)
			return null;

		var tenantIdentifier = httpContext.User.Claims.FirstOrDefault(x=> x.Type == "tenantId");

		if (tenantIdentifier == null)
			return Task.FromResult<string?>(null);

		var tenantInfo = new TenantInfo
		{
			Id = tenantIdentifier.ToString()
		};
		httpContext.SetTenantInfo<TenantInfo>(tenantInfo,true);
		return Task.FromResult(tenantIdentifier.ToString());

	});

```

I really don't understand

**Comment by aalexandre-cognivance** [comment]
Any idea @AndrewTriesToCode  ?

**Comment by AndrewTriesToCode** [comment]
Can you reproduce the issue is a basic sample project — I will run it myself and see what I can find.

**Comment by JonasDev17** [comment]
> Thx for your answer @AndrewTriesToCode , I've tried to change ITenantInfo to IMultiTenantContextAccessor but there's no change. But, even if we forget AppDbContext, I should have the tenantInfo Id in this lambda :
> 
> ```
> builder.Services.AddDbContext<AppDbContext>((serviceProvider, options) =>
> {
> 	var tenantInfo = serviceProvider.GetRequiredService<ITenantInfo>();
> 
> 	if (tenantInfo?.Id == null)
> 	{
> 		throw new InvalidOperationException("TenantId is not available.");
> 	}
> 	options.UseSqlServer(builder.Configuration.GetConnectionString("MyDatabase"));
> });
> ```
> 
> right ? But tenantInfo?.Id is still at "null" while WithDelegateStrategy return is ok...
> 
> ```
> builder.Services.AddMultiTenant<TenantInfo>()
> 	.WithDelegateStrategy(context =>
> 	{
> 		var httpContext = context as HttpContext;
> 		if (httpContext == null)
> 			return null;
> 
> 		var tenantIdentifier = httpContext.User.Claims.FirstOrDefault(x=> x.Type == "tenantId");
> 
> 		if (tenantIdentifier == null)
> 			return Task.FromResult<string?>(null);
> 
> 		var tenantInfo = new TenantInfo
> 		{
> 			Id = tenantIdentifier.ToString()
> 		};
> 		httpContext.SetTenantInfo<TenantInfo>(tenantInfo,true);
> 		return Task.FromResult(tenantIdentifier.ToString());
> 
> 	});
> ```
> 
> I really don't understand

<s>Sorry to interject but why do you expect TenantInfo to not be null when you configure your dbcontext? There is no http / or user context during the configuration of your dbcontext hence why the TenantInfo is null afaik. Why do you need the tenant there anyways? What are you trying to do?</s>

Nevermind, just realized the code you provide I assume is called every time the DbContext is created meaning it should have Http Context when called from a Route. Not sure what you have tried so far but I'd try debugging and see if your Delegate Strategy is called before your DbContext is instantiated because your TenantInfo would have to be set before your DbContext is created. And also try getting the Http Context in your Delegate where you're trying to get the TenantInfo.

**Comment by aalexandre-cognivance** [comment]
It was called but I've changed my code and it's solved right now.
I've used a provider and a filter : 

```
 
public class AppDbContext : DbContext, IMultiTenantDbContext
 {
	private readonly ITenantProvider _tenantProvider;

	public AppDbContext(DbContextOptions<AppDbContext> options, ITenantProvider tenantProvider)
		: base(options)
	{
		_tenantProvider = tenantProvider;
	}

	public Guid? CurrentTenantId
	{
		get
		{
			var tenantInfo = _tenantProvider.GetCurrentTenant();
			return tenantInfo != null && Guid.TryParse(tenantInfo.Id, out var guid) ? guid : (Guid?)null;
		}
	}

	public DbSet<Profession> Profession { get; set; }

	public ITenantInfo? TenantInfo { get; set; }
	public TenantMismatchMode TenantMismatchMode { get; set; } = TenantMismatchMode.Throw;
	public TenantNotSetMode TenantNotSetMode { get; set; } = TenantNotSetMode.Throw;

	protected override void OnModelCreating(ModelBuilder modelBuilder)
	{
		base.OnModelCreating(modelBuilder);
		
		modelBuilder.ConfigureMultiTenant();
		
		AddMultiTenantFilters(modelBuilder);
	}

	private void SaveAllChanges()
	{
		var tenantId = _tenantProvider.GetCurrentTenant()?.Id;

		if (!string.IsNullOrEmpty(tenantId))
		{
			foreach (var entry in ChangeTracker.Entries().Where(e => e.State == EntityState.Added))
			{
				if (entry.Entity is MultitenantEntity tenantEntity)
				{
					tenantEntity.TenantId = new Guid(tenantId);
				}
			}
		}
	}
	public override Task<int> SaveChangesAsync(bool acceptAllChangesOnSuccess, CancellationToken cancellationToken = default)
	{
		SaveAllChanges();

		return base.SaveChangesAsync(acceptAllChangesOnSuccess, cancellationToken);
	}


	public override int SaveChanges(bool acceptAllChangesOnSuccess)
	{
		SaveAllChanges();

		return base.SaveChanges(acceptAllChangesOnSuccess);
	}

	private void AddMultiTenantFilters(ModelBuilder modelBuilder)
	{
		foreach (var entityType in modelBuilder.Model.GetEntityTypes())
		{
			if (typeof(MultitenantEntity).IsAssignableFrom(entityType.ClrType))
			{
				var parameter = Expression.Parameter(entityType.ClrType, "e");
				var tenantIdProperty = Expression.Property(parameter, nameof(MultitenantEntity.TenantId));

				var currentTenantId = Expression.Property(Expression.Constant(this), nameof(CurrentTenantId));

				var tenantIdPropertyAsNullable = Expression.Convert(tenantIdProperty, typeof(Guid?));

				var body = Expression.Equal(tenantIdPropertyAsNullable, currentTenantId);
				var lambda = Expression.Lambda(body, parameter);

				modelBuilder.Entity(entityType.ClrType).HasQueryFilter(lambda);
			}
		}
	}
     }
```

```
	
public class TenantProvider : ITenantProvider
{
  private TenantInfo _tenantInfo;
  
  public TenantInfo GetCurrentTenant()
  {
	  return _tenantInfo;
  }
  
  public void SetCurrentTenant(TenantInfo tenantInfo)
  {
	  _tenantInfo = tenantInfo;
  }
}
```

And in my program.cs

```
        
builder.Services.AddMultiTenant<TenantInfo>()
.WithDelegateStrategy(context =>
{
  var httpContext = context as HttpContext;
  if (httpContext == null)
	  return null;
  
  var tenantIdentifier = httpContext.User.Claims.FirstOrDefault(x => x.Type == "tenantId");
  if (tenantIdentifier == null)
	  return Task.FromResult<string?>(null);
  
  var tenantInfo = new TenantInfo
  {
	  Id = tenantIdentifier.Value
  };
  
  var tenantProvider = httpContext.RequestServices.GetRequiredService<ITenantProvider>();
  tenantProvider.SetCurrentTenant(tenantInfo);
  
  return Task.FromResult(tenantIdentifier.Value);
});
```
Concerning EF, I've created a factory to skip tenant issues

```
    public class AppDbContextFactory : IDesignTimeDbContextFactory<AppDbContext>
```
