### ISSUE TITLE
MultiTenantException: 2 added entities with Tenant Id mismatch

### ISSUE THREAD

**Issue by MarcoGaribaldi** [Finbuckle/Finbuckle.MultiTenant#917]
I am working on a distributed application that implements .NET Aspire. The Aspire documentation suggests creating a background service for migration, so I made a separate project that verifies that a database exists, creates one when needed, applies migration, and seeds the database for each downstream service.

Each of these operations requires the initialization of the dbcontext, thus I have a DbContextFactory that creates the dbContext of the type I need. I use MultiTenantDbContext.Create<TContext, TenantInfo> to create the dbContext.

```
	public TContext CreateDbContext<TContext>(string dbName) where TContext : DbContext
	{
		ArgumentException.ThrowIfNullOrEmpty(dbName);
		ObjectDisposedException.ThrowIf(disposed, nameof(DbContextFactory));

		var cacheKey = $"{dbName}-{typeof(TContext).Name}";

		return (TContext)contextCache.GetOrAdd(cacheKey, static (key, state) =>
		{
			var (factory, dbName) = state;
			var connectionString = factory.GetConnectionString(dbName);

			var optionsBuilder = new DbContextOptionsBuilder<TContext>();
			factory.ConfigureOptions(optionsBuilder, connectionString);

			var tenantInfo = new DesignTimeTenantInfo().MapToTenantInfo();

			return MultiTenantDbContext.Create<TContext, TenantInfo>(
				tenantInfo,
				optionsBuilder.Options);
		}, (this, dbName));
	}
	
	/// <summary>
	/// Configures the DbContext options.
	/// </summary>
	/// <param name="optionsBuilder">The options builder to configure.</param>
	/// <param name="connectionString">The connection string to the database.</param>
	/// <param name="isDevelopment">Indicates if the environment is development.</param>
	public static void ConfigureWriteDbContextOptions(DbContextOptionsBuilder optionsBuilder, string connectionString, bool isDevelopment)
	{
		optionsBuilder.UseSqlServer(connectionString, sqlOptions =>
		{
			sqlOptions.MigrationsAssembly("Ginger.Migrations.Service");
		});

		optionsBuilder.UseExceptionProcessor();
		optionsBuilder.AddModelConfiguration(new DecimalPrecisionConfiguration());

		if (isDevelopment)
		{
			SetDevelopmentOptions(optionsBuilder);
		}
	}

	private static void SetDevelopmentOptions(DbContextOptionsBuilder optionsBuilder)
	{
		optionsBuilder.EnableSensitiveDataLogging();
		optionsBuilder.EnableDetailedErrors();
		optionsBuilder.LogTo(message => Debug.WriteLine(message), LogLevel.Information);
		optionsBuilder.LogTo(Console.WriteLine, LogLevel.Information);
	}

```
DesignTimeTenantInfo creates a class with some random data

```
/// <summary>
/// A design-time implementation of ITenantInfo for migrations.
/// </summary>
public class DesignTimeTenantInfo : ITenantInfo
{
	public string? Id { get; set; } = TenantId.Create().ToString();
	public string? Identifier { get; set; } = "DesignTimeTenant";
	public string? Name { get; set; } = "DesignTime Tenant";
	public string ConnectionString { get; set; } = string.Empty;
	public string AdminEmail { get; private set; } = "admin@designtime.com";
	public bool IsActive { get; private set; } = true;
	public DateTime ValidUpTo { get; private set; } = DateTime.MaxValue;
	public string? Issuer { get; set; } = "https://designtime.issuer.com";

	public void AddValidity(int months) => ValidUpTo = ValidUpTo.AddMonths(months);

	public TenantInfo MapToTenantInfo() =>
		new()
		{
			Id = Id,
			Identifier = Identifier,
			Name = Name,
			ConnectionString = ConnectionString,
			Issuer = Issuer
		};

	internal void SetValidity(in DateTime validTill)
	{
		ValidUpTo = ValidUpTo < validTill
			? validTill
			: throw new TenantException("Subscription cannot be backdated.");
	}

	internal void Activate()
	{
		if (Id == MultitenancyConstants.Root.Id)
			throw new TenantException("Invalid operation");

		IsActive = true;
	}

	internal void Deactivate()
	{
		if (Id == MultitenancyConstants.Root.Id)
			throw new TenantException("Invalid operation");

		IsActive = false;
	}
}
```

My problem is that I get the following error when the seeding process starts:

```
fail: Ginger.Migrations.Service.DataGenerators.TaskManagement.Seeding.TaskManagementSeeder[6]
2024-15-15T10:28:59 Event occurred in: TaskManagementSeeder: Failed to seed TaskManagement data
2024-15-15T10:28:59 Finbuckle.MultiTenant.MultiTenantException: 2 added entities with Tenant Id mismatch.
2024-15-15T10:28:59 at Finbuckle.MultiTenant.MultiTenantDbContextExtensions.EnforceMultiTenant[TContext](TContext context)
etc.
```

Any idea of what I am doing wrong?

**Comment by AndrewTriesToCode** [comment]
Hi, thanks for providing all the details. Most likely issue is in the seeding. As a quick check does it work ok without the seeding?

If that is the case then set the [TenantMismatchMode](https://www.finbuckle.com/MultiTenant/Docs/v9.0.0/EFCore#tenant-mismatch-mode) to `Ignore`.

In most normal cases the db context expects a single tenant at a time for data operations--obviously for seeding data you might want to bulk load a bunch of stuff for multiple tenants. Alternatively you could loop through each tenant and create a new tenant scoped db context and seed each one but that can be problematic depending on your schema and of course less performant.

**Comment by MarcoGaribaldi** [comment]
Hi Andrew,

thank you for your answer. I haven't found an easy way to set TenantMismatchMode to Ignore while dynamically creating a dbcontext with my setup. I have ended up making a design-time dbcontext just for migration. I haven't tested this solution yet, as I have got busy with other parts of the application, but I am confident this should work.

I read from another post that you are working on an integration of your library with .NET Aspire. I am very curious about this as I am heavily relying on Aspire in my project.

**Comment by AndrewTriesToCode** [comment]
Hi, the your `MultiTenantDbContext` derived db context should simply have a TenantMismatchMode property you can set in your design time instance. You might have to make the property public.

For Aspire I need to catch up on the latest. I have to admit I haven't dived in yet but it seems like a logical thing to focus on.
